.github/workflows/deploy.yml
1. Added Github deploy workflow
=> Github Deploy Workflow

devops/Makefile, devops/openshift/api-deploy.yml, sources/packages/api/src/app.service.ts
---------
1. Update api deploy config
2. Update api/app service
=> Test: Injecting version in api

sources/packages/web/serve.json
Restored the file serve.json that was deleted in the previous PR and it is causing the web-build to fail.
=> Restored the file serve.json that was deleted in previous PR.

.github/workflows/deploytest.yml
Testing some Github Actions for test deployment.
=> Testing Github Actions for test deployment.

.github/workflows/deploytest.yml
Enabling the deployment to test using the same image stream from dev (trying).
=> Enabling the deployment to test using the same image stream from dev.

.gitignore, sources/packages/web/src/App.vue, sources/packages/web/src/components/NavBar.vue, sources/packages/web/src/main.ts, sources/packages/web/src/router/index.ts, sources/packages/web/src/services/AppConfigService.ts, sources/packages/web/src/services/AuthService.ts, sources/packages/web/src/store/index.ts, sources/packages/web/src/store/modules/auth/actions.ts, sources/packages/web/src/store/modules/auth/auth.ts, sources/packages/web/src/store/modules/auth/getters.ts, sources/packages/web/src/store/modules/auth/mutations.ts, sources/packages/web/src/store/states.ts, sources/packages/web/src/views/Home.vue, sources/packages/web/src/views/Login.vue
--------
1. Add Home component
2. Use nav guard to control auth flow
=> SIM#17: Student Auth with BCSC

devops/Makefile, devops/openshift/api-deploy.yml
Adjusted the below variables on make "deploy-api" command
- KEYCLOAK_REALM
- KEYCLOAK_CLIENT
- KEYCLOAK_AUTH_URL
=> Adding missing variables to deploy-api make command.

sources/packages/web/package-lock.json, sources/packages/web/package.json, sources/packages/web/src/components/ValidatedInput.vue, sources/packages/web/src/main.ts, sources/packages/web/src/views/Student.vue, vetur.config.js
Added the contact information to the student profile and SIN number in preparation for #68.
The bellows validation frameworks were considered and the one on this PR is the VueValidate.
- https://vee-validate.logaretm.com/v4/
- https://vuelidate.js.org/
Veutify supports both frameworks as 3rd party validators, as shown here: https://vuetifyjs.com/en/components/forms/#vee-validate, but we may not need a 3rd party validator when we change to Veutify, as shown in the below image (copied from the above link).
Both seem to be well accepted in the community:
https://www.reddit.com/r/vuejs/comments/emcsoa/veevalidate_vs_vuelidate/
vee-validate has more contributors and more starts on GitHub.
The "Save" button is just displaying an alert with the data. This should be enough to unblock the #78 that …
=> SIMS #21 Student contact information

sources/packages/api/package.json
Update api run script to execute db migration
=> [api][SIM-78] Add migration script in OpenShift Deployment entry point 

sources/packages/web/src/main.ts, sources/packages/web/src/views/Student.vue
Add a link to the Student Profile page to redirect users to the BCSC site to update read-only information.
Please find below how the message looks like.
=> SIM #69 - Student WANTS to Update Read Only Services Card Information

sources/packages/api/src/route-controllers/student/student.controller.spec.ts, sources/packages/api/src/route-controllers/student/student.controller.ts, sources/packages/web/package-lock.json, sources/packages/web/package.json, sources/packages/web/src/main.ts, sources/packages/web/src/services/StudentService.ts, sources/packages/web/src/views/Student.vue
1. Calling create student api from student profile page
2. Handling error
3. Use browser alert for now
=> [frontend][api][SIM-78] Save/Create Student Account

.github/workflows/deploy.yml, .github/workflows/deploytest.yml, devops/Makefile
Adding KEYCLOAK_REALM, KEYCLOAK_CLIENT, and KEYCLOAK_AUTH_URL
=> Adding missing variables to git action test deploy workflow

sources/packages/api/src/route-controllers/student/student.controller.ts, sources/packages/web/src/views/Student.vue
=> [api][SIM-78]Fix user already exists issue in time of student creation

sources/packages/api/src/route-controllers/student/models/student.dto.ts, sources/packages/api/src/route-controllers/student/student.controller.ts, sources/packages/api/src/services/student/student.service.ts, sources/packages/api/src/types/contactInfo.ts, sources/packages/api/src/types/studentContact.ts, sources/packages/web/src/App.vue, sources/packages/web/src/components/NavBar.vue, sources/packages/web/src/main.ts, sources/packages/web/src/router/index.ts, sources/packages/web/src/services/StudentService.ts, sources/packages/web/src/services/http/StudentApi.ts, sources/packages/web/src/views/Student.vue
Reused the Student Profile page being used for the Student creation to also edit the same.
Added API endpoint to retrieve and update the student contact information.
Added toast notifications for creating an update. After a successful create or update the user will be redirected to the home page.
=> SIMS #44 Student update

sources/packages/web/src/App.vue, sources/packages/web/src/components/NavBar.vue, sources/packages/web/src/router/index.ts, sources/packages/web/src/views/Student.vue
Small adjustments in accordance with a chat with @2011sandeepraj.
It will also make it easier his merge due to some routes renaming.
=> SIMS #44 - Post Review Adjustments 

sources/packages/api/src/route-controllers/user/user.controller.ts, sources/packages/web/src/App.vue, sources/packages/web/src/router/index.ts, sources/packages/web/src/services/StudentService.ts, sources/packages/web/src/services/UserService.ts, sources/packages/web/src/services/http/ApiClient.ts, sources/packages/web/src/services/http/ConfigApi.ts, sources/packages/web/src/services/http/StudentApi.ts, sources/packages/web/src/services/http/UserApi.ts, sources/packages/web/src/services/http/common/HttpBaseClient.ts, sources/packages/web/src/services/http/common/User.ts, sources/packages/web/src/views/Home.vue, sources/packages/web/src/views/Student.vue
Check if User information exists in SABC Database. If it does, redirect to Home page. If it doesn't, then offer him the student -profile page where student can enter the information, save it to SABC DB and redirect back to Home Page.
=> Userstory45 studentloginto sabc accnt

sources/Makefile, sources/packages/api/.dockerignore, sources/packages/web/.dockerignore, sources/packages/web/src/router/index.ts, sources/packages/web/src/views/FAApplication.vue, sources/packages/web/src/views/Home.vue, sources/packages/web/src/views/PageNotFound.vue, sources/packages/web/tests/unit/Home.view.spec.ts
Add button for application start in Home View
Add placeholder for application page
Add page not found page
Include basic test
=> [web][SIM-104] Starting Application and page redirection

sources/packages/web/src/components/fa-application/WelcomePage.vue
Fix for a minor issue not allowing the web project to build properly introduced during the SIMS #144.
=> Fixing the issue causing the deploy to fail

devops/Makefile, devops/openshift/createdb-job.yml
1. Add job name tagging
2. Add dynamic db name
=> [devops] Update Create db job

sources/packages/web/src/main.ts, sources/packages/web/src/views/PersonalInfoQuestionnaire.vue
Added Highschool Graduation month/year, as shown below.
=> SIMS #130 - Added Highschool Graduation month/year.

sources/packages/web/src/views/PersonalInfoQuestionnaire.vue
=> [web][SIM-102][SIM-132] Update Personal Questionnaire

Developer.md
Added a general overview about the technologies being used for the frontend/backend and a list of suggested topics to do next.
=> Adding content to developer.md

docs/howto/db-migration.md, docs/howto/devops.md, docs/technologies-overview.md
Changed the structure of the docs in a live session with @abschwenker.
=> Changing the docs structure.

sources/packages/web/src/components/fa-application/InstituteList.vue, sources/packages/web/src/main.ts, sources/packages/web/src/services/InstituteService.ts, sources/packages/web/src/services/http/StudentApi.ts, sources/packages/web/src/views/SelectProgram.vue, sources/packages/web/tests/unit/ConfirmStudentAidBCProfileInfo.view.spec.ts, sources/packages/web/tests/unit/Home.view.spec.ts, sources/packages/web/tests/unit/InstituteList.spec.ts
1. Create basic layout of select-program page
2. Create Institute List view
3. Create Institute service
4. Fix lint issues
=> [web][SIM-167] Select Program Institute

sources/packages/web/src/components/fa-application/EducationProgramList.vue, sources/packages/web/src/services/InstituteService.ts, sources/packages/web/src/views/SelectProgram.vue
------------------------------------------------------
1. Add new EducationProgramList.vue component and integrate with SelectProgram page
2. Add some state management
3. Also added code for SIM - #169
=> [web][SIM-168] Add option to search education program

sources/packages/web/src/router/index.ts, sources/packages/web/src/views/FAApplication.vue, sources/packages/web/src/views/FinancialInfo.vue
Added the Personal Info page to the student be redirect from "Program Information Page"
=> SIMS #170 - Student Selects 'Next Page' on the Program Information Page

docs/howto/db-migration.md, sources/packages/api/src-sql/StudentPDVerified/Add-StudentPDVerified.sql, sources/packages/api/src-sql/StudentPDVerified/Remove-StudentPDVerified.sql, sources/packages/api/src/database/entities/student.model.ts, sources/packages/api/src/database/migrations/1614107103138-StudentPDVerified.ts
Added pd_verified to the database
=> 193AddedPD_VERIFIED column

sources/packages/web/src/components/NavBar.vue
Added the log-off button that will be displayed only when the user is authenticated.
=> SIMS #113 - Student Logs Off

devops/Makefile, devops/openshift/networkpolicy.yml
Changed to use KNP and changed NSP to be wide open, effectively disabling it. Changes made due to deprecation of Aporeto
=> Modified network policy config to use KNP

sources/packages/api/src/route-controllers/config/config.controller.ts, sources/packages/api/src/route-controllers/config/models/get-config.dto.ts, sources/packages/api/src/services/config/config.service.ts, sources/packages/api/src/types/config.ts, sources/packages/web/src/router/StudentRoutes.ts, sources/packages/web/src/services/AppConfigService.ts, sources/packages/web/src/services/AuthService.ts, sources/packages/web/src/types/contracts/ConfigContract.ts, sources/packages/web/src/views/student/AppStudent.vue, sources/packages/web/src/views/student/Student.vue
-------------------
1. Update API to fetch multiple KC Clients
2. Update web to init AuthService on StudentApp root
3. Update web app to manage multiple clients
4. Fix any student path load issue
=> [api][web][SIMS-#255] Change Student Auth Flow

sources/packages/web/src/components/partial-view/student/NavBar.vue, sources/packages/web/src/views/institution/AppInstitution.vue, sources/packages/web/src/views/student/AppStudent.vue
Added Navbar to Institution Portal, as shown below.
=> [web][SIMS #172]Navbar to Institution Portal

sources/packages/web/src/views/student/DynamicStudentApp.vue
Changed the page dynamic-application-form to invoke a workflow passing a shallow copy of all for data variables.
=> [web][SIM #270]Calling workflow will all form data variables

sources/packages/api/ormconfig.js, sources/packages/api/package.json, sources/packages/api/src/route-controllers/institution/institution.controller.ts, sources/packages/api/src/services/institution/institution.service.e2e-spec.ts, sources/packages/api/src/services/institution/institution.service.spec.ts, sources/packages/api/src/services/institution/institution.service.ts, sources/packages/api/test/jest-e2e.json, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/http/Institution.ts, sources/packages/web/src/views/institution/AppInstitution.vue
-------
1. Create new method to fetch institution using userName
2. Create sync flow
---
=> [api][web][SIMS-#233] Sync BCeID Account Info

sources/packages/api/Dockerfile
=> [api][SIMS-#233] Fix docker image file structure to build in OpenShift universal base images.

sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/views/institution/InstitutionDashboard.vue, sources/packages/web/src/views/institution/ManageLocations.vue
----
1. Add menu item in institution dashboard to invoke navigation
2. Add simple ManageLocations view with add new location button
3. Add new sub route under institution dashbaord
=> [web][SIMS-#122] Institution Manage Location Navigation

sources/packages/api/src-sql/InstitutionLocations/Create-InstitutionLocations.sql, sources/packages/api/src-sql/InstitutionLocations/Drop-InstitutionLocations.sql, sources/packages/api/src/app.module.ts, sources/packages/api/src/database/entities/institution-location.model.ts, sources/packages/api/src/database/migrations/1620073694961-CreateInstitutionLocations.ts, sources/packages/api/src/route-controllers/index.ts, sources/packages/api/src/route-controllers/institution-locations/institution-locations.controller.ts, sources/packages/api/src/route-controllers/institution-locations/models/institution-location.dto.ts, sources/packages/api/src/services/index.ts, sources/packages/api/src/services/institution-location/institution-location.service.e2e-spec.ts, sources/packages/api/src/services/institution-location/institution-location.service.ts, sources/packages/api/src/types/contactInfo.ts
---
1. Create sql for table creation and migration
2. Create entity and service
3. Create service e2e test
4. Created the GET endpoint "institution/location" to retrieve a location record by ID, currently returning a DTO as below.
```json
{
"id": 1,
"name": "New Dummy Location",
"data": {
"address": {
"city": "Victoria",
"country": "Canada",
"province": "BC",
"postalCode": "V9A 3AA",
"addressLine1": "Address Line 1",
"addressLine2": "Address Line 2"
}
}
}
```
=> [api][SIMS-#368] Create data model and service for Institution Location

sources/packages/api/src/main.ts
Enabling the CORS os SIMS Api to allow API calls from formsflow.ai.
Created the technical debit below to revisit the way as the CORS is enabled.
https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/419
=> [api][SIMS #368]Enable CORS to allow formsflow.ai requests

devops/openshift/api-deploy.yml
Fix missing variable FORMS_FLOW_API_URL on api-deploy.yml that is causing a deploy issue.
=> [CICD]Fix missing variable FORMS_FLOW_API_URL on api-deploy

sources/packages/api/src/route-controllers/institution-locations/institution-locations.controller.ts, sources/packages/api/src/route-controllers/institution-locations/models/institution-location.dto.ts, sources/packages/api/src/services/institution-location/institution-location.service.ts, sources/packages/api/src/types/institutionLocation.ts, sources/packages/web/package-lock.json, sources/packages/web/src/assets/css/institution.css, sources/packages/web/src/main.ts, sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/http/ApiClient.ts, sources/packages/web/src/services/http/InstitutionLocation.ts, sources/packages/web/src/types/contracts/institution/AddInstitutionLocation.ts, sources/packages/web/src/views/institution/AddInstitutionLocation.vue, sources/packages/web/src/views/institution/ManageLocations.vue
[web][api][sims-391]- Institution Location Summary page
Created API and Vue Component for Institution Summary Page  with Vuetify3.
TODO: when Vuetify 3 stable version is released.
1. I have used ` v-sheet` since `v-card` was not in vuetify3 alpha version. Once stable version is released `v-card` or veutify3 equivalent component can be used. 
2. I have used ` v-badge` with a dummy icon since `v-chip` was not in vuetify3 alpha version. Once stable version is released `v-chip` or veutify3 equivalent component can be used. 
TODO:
3. `DESIGNATED`  tag is static , in future need to make it dynamic.
Screenshot 3.1
4.  Screenshot 4.1 data are dummy values, need to make it dynamic.
Screenshot 4.1
=> [web][api][sims-391]- Institution Location Summary page

sources/packages/api/ormconfig.js, sources/packages/api/src-sql/AuthCodeTables/Create-initial-institution-user-types.sql, sources/packages/api/src-sql/AuthCodeTables/Create-institution-user-type.sql, sources/packages/api/src-sql/AuthCodeTables/Drop-institution-user-type.sql, sources/packages/api/src-sql/InstitutionAuth/Create-institution-auth.sql, sources/packages/api/src-sql/InstitutionAuth/Drop-institution-auth.sql, sources/packages/api/src-sql/InstitutionUsers/Create-institution-users.sql, sources/packages/api/src-sql/InstitutionUsers/Drop-institution-users.sql, sources/packages/api/src/database/__tests__/institution-user.e2e-spec.ts, sources/packages/api/src/database/entities/index.ts, sources/packages/api/src/database/entities/institution-user-auth.model.ts, sources/packages/api/src/database/entities/institution-user-type-role.model.ts, sources/packages/api/src/database/entities/institution-user.model.ts, sources/packages/api/src/database/entities/institution.model.ts, sources/packages/api/src/database/factories/index.ts, sources/packages/api/src/database/factories/institution-location.factory.ts, sources/packages/api/src/database/factories/institution-user-auth.factory.ts, sources/packages/api/src/database/factories/institution-user-type-role.factory.ts, sources/packages/api/src/database/factories/institution-user.factory.ts, sources/packages/api/src/database/factories/institution.factory.ts, sources/packages/api/src/database/factories/user.factory.ts, sources/packages/api/src/database/migrations/1621260402243-AuthCodeTables.ts, sources/packages/api/src/database/migrations/1621277444239-InstitutionUsers.ts, sources/packages/api/src/database/migrations/1621280592155-InstitutionAuth.ts, sources/packages/api/src/services/institution/institution.service.e2e-spec.ts, sources/packages/api/src/services/institution/institution.service.ts, sources/packages/api/src/types/index.ts, sources/packages/api/src/types/institutionAuth.ts
-----
1. Delete old pivot table institutions_users
2. Add new entity table institution_user
3. Add institution_user_auth table and entity model
3. Add code table for institution user types and roles
4. Create e2e tests to check all connection and relationship loading
----
N.B. This database setup for US #227
=> [api][SIMS-#227] Create ORM migration to setup institution auth table structure

sources/packages/api/src/database/entities/institution-user.model.ts, sources/packages/api/src/database/migrations/1621612824539-UpdateInstititionUserRemoveGuidCol.ts, sources/packages/api/src/route-controllers/institution/institution.controller.ts, sources/packages/api/src/route-controllers/institution/models/institution-user-auth.dto.ts, sources/packages/api/src/route-controllers/user/models/bceid-accounts.dto.ts, sources/packages/api/src/route-controllers/user/user.controller.ts, sources/packages/api/src/services/bceid/bceid.service.mock.ts, sources/packages/api/src/services/institution/institution.service.e2e-spec.ts, sources/packages/api/src/services/institution/institution.service.ts, sources/packages/api/test/institution.e2e-spec.ts
(#227 )
------
1. Add user info to payload
2. Adding actual user while creating IU
3. Update tests
--
=> [api][SIMS-#227] Update Creating of Institution User API

sources/packages/api/src/route-controllers/institution/institution.controller.ts, sources/packages/api/src/services/institution/institution.service.ts, sources/packages/web/src/services/AppConfigService.ts, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/http/Institution.ts, sources/packages/web/src/types/contracts/institution/InstitutionUser.ts, sources/packages/web/src/types/index.ts, sources/packages/web/src/views/institution/InstitutionUserDetails.vue
----
1. Create user table to display all users of institution
2. Create api to delete user from institution (Currently using hard delete)
--
=> [web][api][SIMS-#227] Crete User table and add remove user api

sources/packages/api/src/route-controllers/institution/institution.controller.ts, sources/packages/api/src/route-controllers/institution/models/institution-user-auth.dto.ts, sources/packages/api/src/services/institution/institution.service.e2e-spec.ts, sources/packages/api/src/services/institution/institution.service.ts, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/types/contracts/institution/AddInstitutionLocation.ts, sources/packages/web/src/views/institution/InstitutionUserDetails.vue
----
1. Fix api to accept multiple location
2. Fix UI table layout issue
--
=> [api][web][SIMS-#227] Fix API and UI table display issue

sources/packages/api/src/route-controllers/institution-locations/institution-locations.controller.ts, sources/packages/api/src/services/institution-location/institution-location.service.ts, sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/http/InstitutionLocation.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/views/institution/EditInstitutionLocation.vue, sources/packages/web/src/views/institution/ManageLocations.vue
1. Created Edit location screen in formsflow.ai
2. Integrated the vue component with the Edit location screen to load the data in formsflow.ai
2. Created API to get single location with locationId (This is used to fetch the particular location on click of 'Edit' in Manage Institutions location screen)
3. Created API to update the single location with locationId and the updated data in the table without forms submission in formsflow.ai database
4. Updated toast message in the Manage Institutions location screen on updating
5. Updated fields data in the Manage Institutions location screen
=> Update Institution Location as part of #392

sources/packages/api/src/cra-integration/cra-integration.service.ts, sources/packages/api/src/cra-integration/cra-personal-verification.service.ts, sources/packages/api/src/route-controllers/cra-integration/cra-integration.controller.ts, sources/packages/api/src/services/sequence-control/sequence-control.service.ts
Adding logs to SIN validation process to help troubleshooting an API call timeout issue that is happening only once the API is deployed to DEV env.
=> [api][SIMS #407]Adding logs to SIN validation process

sources/packages/api/src/cra-integration/cra-personal-verification.service.ts, sources/packages/api/src/services/student/student.service.ts
=> [appi][SIMS #407]SIN validation fix

sources/packages/api/src/cra-integration/cra-personal-verification.service.ts, sources/packages/api/src/services/sequence-control/sequence-control.service.ts, sources/packages/api/src/services/student/student.service.ts, sources/packages/api/src/utilities/database.ts
Found and fixed an issue on DB connections handling where the connection will remain open till the connection pool reaches the limit currently configured to 10.
=> [api][SIMS #407]CAR SIN Validation - closing DB connections properly

sources/packages/api/src/route-controllers/institution-locations/models/institution-location.dto.ts, sources/packages/api/src/route-controllers/user/user.controller.spec.ts, sources/packages/api/src/route-controllers/user/user.controller.ts, sources/packages/api/src/services/institution-location/institution-location.service.ts, sources/packages/api/src/services/user/user.service.spec.ts, sources/packages/web/src/components/layouts/Institution/sidebar/HomeSideBar.vue, sources/packages/web/src/components/layouts/Institution/sidebar/ManageInstitutionSideBar.vue, sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/services/UserService.ts, sources/packages/web/src/services/http/UserApi.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/types/contracts/UserContract.ts, sources/packages/web/src/views/institution/LocationPrograms.vue, sources/packages/web/src/views/institution/LocationStudents.vue, sources/packages/web/src/views/institution/LocationUsers.vue
**Front End Change**
- Given (Institution Location User), When (they are on the Account Dashboard), Then (They can see a button to Navigate to their location Dashboard)
-  Given (Institution Location User), When (They navigate to their location Dashboard), Then (they see a button to manage their "programs").
-  Given (Institution Location User), When (They navigate to their location Dashboard), Then (they see a button to manage their "student applications").
-  Given (Institution Location Manager), When (They navigate to their location Dashboard), Then (they see a button to manage their "location users").
**Tasks**
-  Retrieve list of locations that user has access to
-  Display on left menu that which you have access to
-  Add placeholder pages where necessary
=> [web][api][sims-#309] Institution Location User Navigates in a location

sources/packages/api/src-sql/EducationPrograms/Create-education-programs.sql, sources/packages/api/src-sql/EducationPrograms/Drop-education-programs.sql, sources/packages/api/src/app.module.ts, sources/packages/api/src/database/constant.ts, sources/packages/api/src/database/entities/education-program.model.ts, sources/packages/api/src/database/entities/index.ts, sources/packages/api/src/database/migrations/1623278887922-EducationPrograms.ts, sources/packages/api/src/route-controllers/education-program/education-program.controller.ts, sources/packages/api/src/route-controllers/education-program/models/create-education-program.dto.ts, sources/packages/api/src/route-controllers/index.ts, sources/packages/api/src/services/education-program/education-program.service.ts, sources/packages/api/src/services/form/constants.ts, sources/packages/api/src/services/form/form.service.ts, sources/packages/api/src/services/index.ts
Partial delivery of SIMS #279.
- Created migrations to create the table education_programs;
- Created the education programs controller with the method to create a new education program;
=> [api][SIMS #279] Create education porgrams

sources/packages/api/src-sql/EducationProgramsOfferings/Create-education-programs-offerings.sql, sources/packages/api/src-sql/EducationProgramsOfferings/Drop-education-programs-offerings.sql, sources/packages/api/src/app.module.ts, sources/packages/api/src/database/constant.ts, sources/packages/api/src/database/entities/education-program-offering.model.ts, sources/packages/api/src/database/entities/index.ts, sources/packages/api/src/database/migrations/1623359212222-EducationProgramsOfferings.ts, sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.controller.ts, sources/packages/api/src/route-controllers/education-program-offering/models/create-education-program-offering.dto.ts, sources/packages/api/src/route-controllers/index.ts, sources/packages/api/src/services/education-program-offering/education-program-offering.service.ts, sources/packages/api/src/services/index.ts
Education Program Offering
- Database Model
- API
=> [web][api][SIMS #421]Education Program Offering API

sources/packages/web/src/components/generic/formio.vue
Adding the form definitions into the session storage to avoid retrieve the same definition again during the same browser session.
In case of any failure during saving/retrieving from the session storage, the form will continue to be loaded from the server.
Sample storage consumption values based  on ours current forms.
Total Storage available: 5,242,880 bytes
Program Create/Edit: 53,727 bytes (1.02%)
Student Application: 129,522 bytes (2.47%)
Some browser storage capabilities.
Some browser storage capabilities.
Test the browser capability: http://dev-test.nemikor.com/web-storage/support-test/
=> [improvement]Caching form definition on session storage

sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/services/AuthService.ts, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/UserAuthorizationService.ts, sources/packages/web/src/services/http/Institution.ts, sources/packages/web/src/services/http/InstitutionLocation.ts, sources/packages/web/src/store/modules/institution/actions.ts, sources/packages/web/src/views/institution/AppInstitution.vue
1. Enabled guard to the dashboard, moved institution store initialization to authService.ts
2. Added try-catch to isUserTypeAllowed
=> [web][tasks-SIMS-#505] Route guard for Dashboard

sources/packages/api/src-sql/EducationProgramsOfferings/Create-education-programs-offerings.sql, sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.controller.ts, sources/packages/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts, sources/packages/api/src/services/education-program-offering/education-program-offering.service.models.ts, sources/packages/api/src/services/education-program-offering/education-program-offering.service.ts, sources/packages/web/src/services/EducationProgramOfferingService.ts, sources/packages/web/src/services/http/EducationProgramOfferingApi.ts, sources/packages/web/src/types/contracts/OfferingContact.ts, sources/packages/web/src/views/institution/locations/programs/LocationProgramOffering.vue
Institution User Views and edits Education offering details#471
Given (an Institution User), When (selecting edit offering), Then (they have the ability to view and edit all offering information)
Given (an Institution User), When (entering offering information), Then (they have to complete all mandatory fields)
Given (An Institution User), When (selects submit), Then (the offering information is saved)
All fields are mandatory
=> [web][SIMS #471]Institution User Views and edits Education offering details

devops/forms-flow-ai/forms-flow-forms/Dockerfile
Updating custom Dockerfile for FORMS-FLOW-FORMS build for openshift
=> FORMS_FLOW_FORMS initial Commit

sources/packages/web/src/views/institution/Login.vue
Changed the institution login labels from BCSC to BCeID.
=> [web][SIMS #371]Changed institution login button labels to BCeID

docs/howto/devops.md
Adding some documentation about how to execute the commands to create the structure of the backup.
=> [docs][SIMS #188]Implement backup strategy - documentation

devops/openshift/database-backup/backup.conf
Updating backup config map with new databases names.
=> [CICD]Updated backup database names

sources/packages/web/package-lock.json, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
added bootstrap class `w-100 ` to fix the flickering of the student application form when navigating from one tab to another
=> [web][SIMS #147] Flickering of  Student application form navigating from one tab to another

sources/packages/api/src/services/atbc/atbc.controller.e2e-spec.ts
Complementing the e2e test added by @ann-aot.
The test has a good example of an e2e test that:
1. prepares the database;
2. mock some dependent service (ATBC Api);
3. execute the test checking the controller output;
4. clean up the DB.
=> [api][SIMS #337]Adjust e2e ATBC test

sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.controller.ts, sources/packages/api/src/route-controllers/education-program/education-program.controller.ts, sources/packages/api/src/route-controllers/institution-locations/institution-locations.controller.ts, sources/packages/api/src/services/institution-location/institution-location.service.ts
1. Restrict institution Admin from accessing/ editing locations or location related features of other institutions
2.  Restrict institution Admin from accessing/ editing/ creating offerings, and programs related features of other institutions
=> [API][sims-#517]  restrict institution Admin from accessing/ editing locations or location related features of other institutions

sources/packages/api/src-sql/Applications/Add-col-assessment.sql, sources/packages/api/src-sql/Applications/Drop-col-assessment.sql, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/migrations/1626994719103-UpdateApplicationsAddAssessment.ts, sources/packages/api/src/route-controllers/application/application.controller.ts, sources/packages/api/src/route-controllers/application/application.system.controller.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/services/application/application.service.ts
- Determine table/Column for assessment
- Create Migration for "assessment" table/Column
- Create API for "assessment" table SAVE (for Camunda to save to SIMSDB)
- API call to get Assessment Details for Vue application
Only the Save and Get API for the assessment is created
=> Feature/#526 notice of assessment - API only

sources/packages/api/src-sql/ApplicationNumber/Create-application-number.sql, sources/packages/api/src-sql/ApplicationNumber/Drop-application-number.sql, sources/packages/api/src/app.module.ts, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/migrations/1627335003675-CreateApplicatioNumber.ts, sources/packages/api/src/route-controllers/application/application.controller.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/services/application/application.service.ts
When an application is submitted create a DB generated value (to ensure no duplicates are created)
1. Application number must 10 Characters
2. Application number must be in the format ((Program year/Program year) eg. 2122) YYYY######
3. Code Smell is due to TODO (for this ticket program year is static, we need to make it dynamic)
=> [api][sims-#530] Application Number added

sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/router/StudentRoutes.ts, sources/packages/web/src/services/ApplicationService.ts, sources/packages/web/src/services/http/ApplicationApi.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/views/student/NoticeOfAssessment.vue, sources/packages/web/src/views/student/financial-aid-application/Applications.vue
As discussed, I have hard coded 112 as application id to fetch and test the form from formsflow.ai in dev. 
This change integrated the vue routes with the form in formsflow.ai
=> Vue changes to import form

sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/web/src/services/ApplicationService.ts, sources/packages/web/src/services/http/ApplicationApi.ts, sources/packages/web/src/types/contracts/institution/ApplicationsDto.ts, sources/packages/web/src/views/institution/LocationApplications.vue
As an (Institution User) I want (View Students Application Summary) So That (I can manage the status of applications)
Given (Institution User), When (View Students Application Summary), Then (they can see the following )
-Students Name
-Program (we don't have this data now, so not showing as of now)
-Study Period
-Application Number
-PIR Status (completed and required)
-View button (placeholder)
=> [web][api][vue-sims#529]Institution User views Student Application Summary

sources/packages/web/src/views/institution/LocationApplications.vue
watch added to update the summary list
=> [web][vue-sims#529]Institution User views Student Application Summary- watch added

sources/packages/api/src-sql/Applications/Add-col-application-status.sql, sources/packages/api/src-sql/Applications/Drop-col-application-status.sql, sources/packages/api/src-sql/Types/Create-ApplicationStatus.sql, sources/packages/api/src-sql/Types/Drop-ApplicationStatus.sql, sources/packages/api/src/database/entities/application-status.type.ts, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/entities/index.ts, sources/packages/api/src/database/migrations/1628183925115-ApplicationStatusType.ts, sources/packages/api/src/database/migrations/1628186321954-UpdateApplicationsAddAppicationStatus.ts, sources/packages/api/src/services/application/application.service.ts
- Create a column for application_status and enum data type
- Save an application_status of Submitted when submitting an application
=> Created Application Status, Submitted updated

sources/packages/web/src/views/institution/locations/programs/LocationProgramView.vue
replaced <strong> with bootstrap class
=> [web][sims-#589] replaced strong tag with class

sources/packages/api/src-sql/EducationProgramsOfferings/Drop-education-programs-offerings.sql, sources/packages/api/src-sql/EducationProgramsOfferings/Remove-education-programs-offerings.sql, sources/packages/api/src/database/migrations/1628287630225-OfferingIntensity.ts, sources/packages/api/src/database/migrations/1628287835629-CreateOfferingIntensity.ts
=> [api][sims-#589] sql file name updated

sources/packages/api/src/route-controllers/application/application.system.controller.e2e-spec.ts
Fixed E2E tests failing after the last merge of #103 while Git Hub was facing issues and the PR went through without the proper validations.
=> [api][SIMS #103]Fix Complete PIR E2E tests 

sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/LocationCOESummary.vue, sources/packages/web/src/views/institution/locations/program-info-request/LocationProgramInfoRequestSummary.vue
Fixed links from PIR and COE pages that were not executing the navigation with the proper id.
=> Fixed PIR and COE Summary Lists

sources/packages/api/src-sql/Applications/Add-col-program-year-id.sql, sources/packages/api/src-sql/Applications/Drop-col-program-year-id.sql, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/entities/index.ts, sources/packages/api/src/database/migrations/1628891755473-UpdateApplicationsAddProgramYearId.ts, sources/packages/api/src/route-controllers/application/application.controller.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/route-controllers/program-year/models/program-year.dto.ts, sources/packages/api/src/route-controllers/program-year/program-year.controller.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/api/src/services/program-year/program-year.service.ts, sources/packages/api/src/testHelpers/fake-entities/application-fake.ts, sources/packages/api/src/testHelpers/fake-entities/program-year-fake.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/types/contracts/ProgramYearContract.ts, sources/packages/web/src/views/student/financial-aid-application/Applications.vue, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
- Save Program Year ID to the Application
- Along side with Application Submission send the Program Year ID
- Validate if PY is Actiive
- Validates if the program year is active, if not throw a BadRequestException or similar.
- Use the form definition to validate the Student Application submission instead of the hard-coded value.
=> #558 program year dynamic validation - Save Program Year ID to the ApplicationFeature -Form Integration

sources/packages/api/src/route-controllers/application/application.controller.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/web/src/services/ApplicationService.ts, sources/packages/web/src/services/StudentService.ts, sources/packages/web/src/services/http/ApplicationApi.ts, sources/packages/web/src/types/contracts/student/ApplicationContract.ts, sources/packages/web/src/views/student/StudentApplicationDetails.vue, sources/packages/web/src/views/student/StudentApplicationSummary.vue
1. corrected cancel action 
2. added edit application in summary and details page
=> [vue][api][sims-#605] Student can Cancel their FT/PT Application and add edit application

sources/packages/api/src/route-controllers/application/application.system.controller.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/services/application/application.service.ts
Updated getApplication API for camunda to get Program Year from the application
=> Updating getApplicationAPI for camunda

sources/packages/web/src/components/generic/formio.vue, sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/router/StudentRoutes.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/views/student/StudentApplicationDetails.vue, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
From the application details page. When a student clicks view. Show them a READ-ONLY version of the submitted application. This option will always be available
- Removed Save Draft and Submit Application Button
- Made all the fields in the application readonly
=> Feature/[SIMS-#613]-Student - View application (Read-Only)

sources/packages/api/src/services/application/application.service.ts
Added orderBy to make it easier to find applications on students applications summary.
=> [api]Added order by to students applications summary

devops/Makefile, devops/openshift/docker-build.yml
1. Added create for credential
2. Modified api and web builds to use artifactory
3. Modify docker-build to use credential
=> [devops]Fix for artifactory repo.

sources/packages/forms/src/form-definitions/educationprogram.json
#609 - [x] Average hours of study per week - 19 or less Weeks Add banner and add to pending program variable
=> [form][SIMS-#609]UPDATE_Program_and_Offering_Enhancements-Bug

sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts, sources/packages/api/src/route-controllers/institution-locations/institution-locations.controller.ts, sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/web/src/components/layouts/Institution/sidebar/HomeSideBar.vue, sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/UserAuthorizationService.ts, sources/packages/web/src/services/http/Institution.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/types/contracts/institution/ConfirmationOfEnrollment.ts, sources/packages/web/src/types/contracts/institution/ProgramInfoRequest.ts, sources/packages/web/src/types/contracts/student/ApplicationContract.ts, sources/packages/web/src/views/institution/locations/active-applications/ActiveApplicationReportAChange.vue, sources/packages/web/src/views/institution/locations/active-applications/LocationActiveApplicationSummary.vue, sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/LocationCOESummary.vue, sources/packages/web/src/views/institution/locations/program-info-request/LocationProgramInfoRequestSummary.vue
#652 - Active Applications Summary Page
Name | Study Period | Application # | Status
=> [API][Web][SIMS-#652] Active applications summary page creation

sources/packages/api/src/database/entities/student.model.ts, sources/packages/api/src/route-controllers/student/student.controller.ts, sources/packages/api/src/types/index.ts, sources/packages/api/src/types/pdStatus.ts, sources/packages/api/src/types/studentInfo.ts, sources/packages/api/src/utilities/student-utils.ts, sources/packages/web/src/types/contracts/StudentContract.ts, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
Student PD status Enum created with following values
Yes - When pd_verified is true in student table
No - When pd_verified is false 
Not Requested - When pd_date_sent and pd_date_updated is null
Pending - When pd_date_sent is NOT null pd_date_updated is null
=> [API][Web][SIMS #640] Import PD status into Student Readonly Application Details

sources/packages/api/src/route-controllers/application/application.controller.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/web/src/components/generic/formio.vue, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
Form.io wrapper component readOnly attribute type changed to boolean
isReadOnly variable added which decides to show the form in read-only mode or not
API check for status added for submit application
API check is not required to be added for save draft as it is already in place
=> [Api] [Vue] [SIMS #682] Hide Save-Draft and Submit button while viewing the application

sources/packages/api/src/services/student/student.service.ts
Bug, which does not search with application number now works
=> Updated query

sources/packages/web/src/views/aest/StudentDetails.vue
Typo fix on student detail page.
=> [SIMS #70]Typo Fix

sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.controller.ts, sources/packages/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts, sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts, sources/packages/api/src/services/education-program-offering/education-program-offering.service.ts, sources/packages/forms/src/form-definitions/educationprogramoffering.json, sources/packages/web/src/types/contracts/OfferingContact.ts, sources/packages/web/src/types/contracts/institution/EducationProgramOfferingDto.ts, sources/packages/web/src/views/institution/locations/programs/LocationProgramView.vue
The property name in offering changed to offeringName as it coincides with name in programDTO and hence the name gets overwritten from program.
=> [Api][Web][BUG #476] Offering Name on Offering Page not populating correctly

sources/packages/api/src-sql/DisbursementSchedules/Create-disbursement-schedules-table.sql, sources/packages/api/src-sql/DisbursementSchedules/Drop-disbursement-schedules-table.sql, sources/packages/api/src-sql/DisbursementValues/Create-disbursement-values-table.sql, sources/packages/api/src-sql/DisbursementValues/Drop-disbursement-values-table.sql, sources/packages/api/src-sql/Types/Create-disbursement-value-types.sql, sources/packages/api/src-sql/Types/Drop-disbursement-value-types.sql, sources/packages/api/src/app.module.ts, sources/packages/api/src/database/constant.ts, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/entities/disbursement-schedule.model.ts, sources/packages/api/src/database/entities/disbursement-value-type.ts, sources/packages/api/src/database/entities/disbursement-values.model.ts, sources/packages/api/src/database/entities/index.ts, sources/packages/api/src/database/migrations/1637004479449-CreateDisbursementValueTypes.ts, sources/packages/api/src/database/migrations/1637004487916-CreateDisbursementSchedulesTable.ts, sources/packages/api/src/database/migrations/1637004719088-CreateDisbursementValuesTable.ts, sources/packages/api/src/database/transformers/date-only.transformer.ts, sources/packages/api/src/route-controllers/application/application.system.controller.e2e-spec.ts, sources/packages/api/src/route-controllers/application/application.system.controller.ts, sources/packages/api/src/route-controllers/application/models/application.system.model.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule.models.ts, sources/packages/api/src/services/index.ts, sources/packages/api/src/services/sequence-control/sequence-control.service.ts
- Created the migrations for disbursements schedules and their values;
- Created an API endpoint to insert the disbursements with the payload as defined below.
=> [api][SIMS #753]Schedule Student Disbursement - API/Migrations

sources/packages/api/src-sql/EducationPrograms/Alter-education-programs.sql, sources/packages/api/src-sql/EducationPrograms/Rollback-alter-eduction-programs.sql, sources/packages/api/src/database/entities/education-program.model.ts, sources/packages/api/src/database/migrations/1637179568488-AlterEducationPrograms.ts, sources/packages/api/src/route-controllers/education-program/education-program.controller.ts, sources/packages/api/src/route-controllers/education-program/models/save-education-program.dto.ts, sources/packages/api/src/services/education-program/education-program.service.models.ts, sources/packages/api/src/services/education-program/education-program.service.ts, sources/packages/api/src/testHelpers/fake-entities/education-program-fake.ts, sources/packages/web/src/assets/css/formio-shared.scss, sources/packages/web/src/services/EducationProgramService.ts, sources/packages/web/src/types/contracts/institution/EducationProgramDto.ts
After the program is approved, you’ll get to add study periods and costs to it"
** Program Eligibility** (_This is a new heading)_
 A full-time program must have a course load of: 60% or greater or Between 40 and 60% for students with a permanent disability)__
institutions._
**Entrance Requirements**
- "Students to have graduated from grade 12 or equivalent.
- Students are 19 years old or older before the start of classes.
- This program has entrance requirements established by the institution that enables completion of the program study.
- This program is approved by the B.C. Industry Training Authority and students must meet the entrance requirements set by the B.C. ITA."
** Work-integrated Learning** (New Section) 
-  [ ]  If Yes- Provide the following question, " Is the WIL approved …
=> [Api][Web][SIMS #639] Program and Offering Enhancements - Part1

sources/packages/api/src/esdc-integration/e-cert-full-time-integration/e-cert-full-time-integration.service.ts, sources/packages/api/src/esdc-integration/e-cert-full-time-integration/e-cert-full-time-request.service.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/utilities/disbursements-utils.ts
- Changed the way that school amount and student amount are calculated;
- Consumed the new "years of study" from offerings.
=> [api][SIMS #645]Offering and calculations updated

sources/packages/forms/src/form-definitions/noticeofassessment.json
Added refresh on change and keeping disbursement total to 2 fixed decimal.
=> [SIMS #822] Minor form change

sources/packages/api/src/app.module.ts, sources/packages/api/src/route-controllers/index.ts, sources/packages/api/src/route-controllers/restriction/models/restriction.dto.ts, sources/packages/api/src/route-controllers/restriction/restriction.controller.ts, sources/packages/api/src/services/restriction/student-restriction.service.ts, sources/packages/web/src/assets/css/base.scss, sources/packages/web/src/components/common/notes/Notes.vue, sources/packages/web/src/components/generic/StatusBadge.vue, sources/packages/web/src/constants/routes/RouteConstants.ts, sources/packages/web/src/main.ts, sources/packages/web/src/router/AESTRoutes.ts, sources/packages/web/src/services/RestrictionService.ts, sources/packages/web/src/services/http/ApiClient.ts, sources/packages/web/src/services/http/RestrictionApi.ts, sources/packages/web/src/types/AppRoutes.ts, sources/packages/web/src/types/contracts/GeneralStatusForBadge.ts, sources/packages/web/src/types/contracts/RestrictionContract.ts, sources/packages/web/src/types/index.ts, sources/packages/web/src/views/aest/student/StudentRestrictions.vue
=> [Api][Web][SIMS #878] Ministry user views student restrictions

sources/packages/api/src/route-controllers/application/application.system.controller.ts, sources/packages/api/src/route-controllers/application/models/application.system.model.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/api/src/utilities/student-utils.ts
Fixing MSFAA number not populating
=> BUG[SIMS-#815]MSFAA number not populating

sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts, sources/packages/api/src/route-controllers/confirmation-of-enrollment/models/confirmation-of-enrollment.model.ts, sources/packages/api/src/route-controllers/education-program/education-program.controller.ts, sources/packages/api/src/route-controllers/program-info-request/models/program-info-request.dto.ts, sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/api/src/services/education-program/education-program.service.ts, sources/packages/web/src/components/aest/InstitutionUserSummary.vue, sources/packages/web/src/components/aest/StudentApplications.vue, sources/packages/web/src/components/common/LocationSummary.vue, sources/packages/web/src/components/common/notes/Notes.vue, sources/packages/web/src/components/generic/DesignationAndRestrictionStatusBadge.vue, sources/packages/web/src/components/generic/StatusBadge.vue, sources/packages/web/src/main.ts, sources/packages/web/src/types/contracts/institution/ConfirmationOfEnrollment.ts, sources/packages/web/src/types/contracts/institution/ProgramInfoRequest.ts, sources/packages/web/src/views/aest/student/StudentRestrictions.vue, sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/ApplicationDetailsForCOE.vue, sources/packages/web/src/views/institution/locations/program-info-request/LocationEditProgramInfoRequest.vue
- Hide "Edit Program Information" on COE when PIR=Not Required and block API
- When viewing a denied PIR, it should populate the deny reason, and deny reason other
- fixed router conflicts and fixed the dropdown issue in PIR form 
- refactored some codes
=> [Api][Web][SIMS #676 #326] View Denied Reason on Program Information Request View Page,  Edit Program info during CoE requirements

sources/packages/api/src/services/restriction/student-restriction.service.ts, sources/packages/forms/src/form-definitions/viewrestriction.json
The Federal restrictions are created by importing file. Hence as of now, it does not have creator. Changing the query from inner join to left join to accommodate these restrictions.
=> [API][SIMS #846] Minor fix to include restrictions without creator

sources/packages/api/src/auth/auth.module.ts, sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/services/student/student.service.ts, sources/packages/web/src/components/aest/StudentApplications.vue, sources/packages/web/src/views/student/StudentApplicationSummary.vue, sources/packages/web/src/views/student/financial-aid-application/Applications.vue
- I created a a new function called updateDisbursementSchedule in disbursement-schedule-service. This function invokes the logic generate a new document number.
- I removed the implementation that generates a new document number and assigns it to the document number in the createDisbursementSchedules function when a new disbursement is created.
- updateDisbursementSchedule is invoked in the confirmation-of-enrollment controller after the application status is completed.
- I implemented functionality in the front end web application to disable students from creating or editing/updating applications when their SIN status is not valid.
=> [Api][Web][SIMS#443]Document Number

sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/route-controllers/application/application.controller.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/web/src/types/contracts/student/ApplicationContract.ts
Added offering Intensity column for NOA calculations and structure for PartTime Assessment
This is a part of the PR, once the API is deployed, the formio changes will be updated as part of another PR.
=> [Api][Web][SIMS#562]Added Offering Intensity Value in NOA

sources/packages/api/src/database/entities/application.model.ts, sources/packages/forms/src/form-definitions/noticeofassessment.json, sources/packages/web/src/types/contracts/student/ApplicationContract.ts
NOA form changes
PartTime:
FullTime:
=> [SIMS#562][Forms]NOA formio changes for PartTime

sources/packages/api/src-sql/DisbursementSchedules/Add-coe-cols.sql, sources/packages/api/src-sql/DisbursementSchedules/Remove-coe-cols.sql, sources/packages/api/src/database/entities/coe-status.type.ts, sources/packages/api/src/database/entities/disbursement-schedule.model.ts, sources/packages/api/src/database/entities/student.model.ts, sources/packages/api/src/database/migrations/1643403892049-DisbursementAddCOECols.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule.models.ts, sources/packages/api/src/utilities/date-utils.ts, sources/packages/web/src/assets/css/base.scss, sources/packages/web/src/components/generic/COEStatusBadge.vue, sources/packages/web/src/components/generic/StatusBadge.vue, sources/packages/web/src/components/institutions/confirmation-of-enrollment/information.vue, sources/packages/web/src/constants/css-constants.ts, sources/packages/web/src/constants/index.ts, sources/packages/web/src/main.ts, sources/packages/web/src/services/ConfirmationOfEnrollmentService.ts, sources/packages/web/src/services/http/ConfirmationOfEnrollmentApi.ts, sources/packages/web/src/types/contracts/institution/ConfirmationOfEnrollment.ts, sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/COESummaryData.vue, sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/LocationCOESummary.vue
**Note -** **Search, Pagination and Sort** are not part of this PR.
=> [Api][Web][SIMS #792] Second COE PR Part 1

sources/packages/web/src/views/institution/designations/DesignationView.vue
Fix for Institution Name while viewing one designation agreement.
=> [web][SIMS #406]Fix Institution Name

sources/packages/web/src/components/generic/formio.vue, sources/packages/web/src/components/layouts/FullPageContainer.vue, sources/packages/web/src/views/institution/designations/DesignationRequest.vue, sources/packages/web/src/views/supporting-user/AppSupportingUser.vue
- moved custom class `ff-form-container` to `formio` component and removed the class from other files
=> moved class ff-form-container to formio component

devops/Makefile, docs/technologies-overview.md
Upgrading NodeJS to version 16.
=> [devops][SIMS #451] Node JS Upgrade to 16

sources/packages/api/package-lock.json, sources/packages/api/package.json, sources/packages/api/scripts/setupDB.ts, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/entities/disbursement-schedule.model.ts, sources/packages/api/src/database/entities/disbursement-values.model.ts, sources/packages/api/src/database/entities/education-program-offering.model.ts, sources/packages/api/src/database/entities/education-program.model.ts, sources/packages/api/src/database/entities/note.model.ts, sources/packages/api/src/database/entities/restriction.model.ts, sources/packages/api/src/database/entities/supporting-user.model.ts, sources/packages/api/src/logger/logger.service.ts, sources/packages/api/src/main.ts
Updated the following as per #761
=> [Api][SIMS #451] NEST Upgrade

sources/packages/api/src/database/database.service.spec.ts, sources/packages/api/src/database/database.service.ts
The following item has been mentioned in the PR 1036 (https://github.com/bcgov/SIMS/pull/1036) but the code snippet was missed to be pushed.
=> Set schema sql removed

sources/packages/api/src/route-controllers/supporting-user/supporting-user.controller.ts, sources/packages/api/src/services/supporting-user/supporting-user.service.ts
Updated await and error logging in missed places for supporting user
=> [SIMS-#900][Bug]Added missed await

sources/packages/forms/src/form-definitions/supportinguserspartner2022-2023.json
The Number of weeks should be enabled only when the above checkbox is yes.
Overall changes in the files are due to the formio changes, I will mark the only conditional change that I did
=> [Bug][SIMS-#900]Updated a bug in Partner Supporting user screen

sources/packages/forms/src/form-definitions/approvedenydesignation.json, sources/packages/web/src/components/generic/ModalDialogBase.vue, sources/packages/web/src/components/generic/formio.vue, sources/packages/web/src/views/aest/institution/ApproveDenyDesignation.vue
The property deep is set true for watch of readOnly in formio generic component.
Title moved into Vue component for the modals.
=> [Web][SIMS #467] Minor fix for Cached data and Modal heading.

sources/packages/api/src-sql/Student/Add-StudentValidSIN.sql, sources/packages/api/src-sql/Student/Remove-StudentValidSIN.sql, sources/packages/api/src/services/student/student.service.ts
Bug during the migration revert. Students does not contain schema appended to it.
=> Updated the student schema for the migrations

sources/packages/api/src/main.ts
=> [API][SIMS #355] Implement swagger bug fix

devops/openshift/api-deploy.yml
Add route configuration during api-deploy in openshift
=> [DEVOPS][SIMS-#355]Updated Route for swagger in api-deploy.yml

sources/packages/workflow/BPMN/assessment-gateway.bpmn
Fixes after tests executed on DEV.
=> [workflow][SIMS #28]Fixes on the assessment-gateway workflow

sources/packages/api/src/route-controllers/student/student.controller.ts, sources/packages/api/src/services/student/student.service.ts
- Given Names
- Last Name
- DOB change
=> [SIMS-#998][API]Revalidate SIN

sources/packages/api/src/route-controllers/application/application.controller.service.ts, sources/packages/api/src/route-controllers/institution-locations/models/institution-location.dto.ts, sources/packages/api/src/services/institution-location/institution-location.models.ts, sources/packages/api/src/services/institution-location/institution-location.service.ts
Designation query enhancement, added case, which will return true if location is designated and return false for else case
=> Create common component for student application - designation query enhancement

sources/packages/web/src/components/common/StudentApplication.vue
In order to maintain the reactiveness, removed the `v-if ` and added `watch`
=> form load happening before form component load

sources/packages/api/src-sql/Applications/Add-col-current-assessment-id.sql, sources/packages/api/src-sql/Applications/Drop-col-current-assessment-id.sql, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/migrations/1647894113762-ApplicationAddColCurrentAssessment.ts, sources/packages/api/src/esdc-integration/e-cert-full-time-integration/e-cert-full-time-request.service.ts, sources/packages/api/src/esdc-integration/msfaa-integration/msfaa-request.service.ts, sources/packages/api/src/route-controllers/application/application.controller.service.ts, sources/packages/api/src/route-controllers/application/application.students.controller.ts, sources/packages/api/src/route-controllers/application/application.system.controller.e2e-spec.ts, sources/packages/api/src/route-controllers/application/models/application.model.ts, sources/packages/api/src/route-controllers/assessment/assessment.system-access.controller.ts, sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts, sources/packages/api/src/route-controllers/institution-locations/institution-locations.controller.ts, sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts, sources/packages/api/src/services/application/application.service.e2e-spec.ts, sources/packages/api/src/services/application/application.service.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/services/msfaa-number/msfaa-number.service.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/api/src/testHelpers/fake-entities/application-fake.ts, sources/packages/api/src/utilities/application-utils.ts
- Move offering id from `sims.applications` to `sims.student_assessments`
- Created a new column  `sims.applications.current_assessment` to point to the active/current assessment.
- DB migrations to remove the legacy columns from `sims.applications` will be part of an upcoming PR.
=> [api][SIMS #28]Feature/reassessment offering

sources/packages/api/src/route-controllers/student-appeal/student-appeal.students.controller.ts, sources/packages/web/src/views/student/AppStudent.vue
Currently student nav component shows nav actions before login.
Bug fixed in the PR.
=> [Api][Vue] Minor bug on student nav component

devops/openshift/api-deploy.yml, devops/openshift/createdb-job.yml, devops/openshift/database-backup/backup-build.yaml, devops/openshift/database-backup/backup-deploy.yaml, devops/openshift/docker-build.yml, devops/openshift/forms-flow-ai/database/create-ffa-db.yml, devops/openshift/forms-flow-ai/database/mongo-ha.yml, devops/openshift/web-deploy.yml
Updated template version in yml
=> [SIMS-#383][YML]-Template Version Update

sources/packages/web/src/components/common/StudentApplication.vue
-previous and next nav button was not working in dev, as the `formInstance` used in vue template was not reactive
**bug**
**fix**
=> [bug fix][web] previous and next nav button issue fix

sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts, sources/packages/api/src/services/application/application.service.ts
- Fix an issue while completing a PIR that was preventing the offering id to be saved to the assessments table.
- Added audit while approving the PIR.
=> [api][SIMS #28]Fix Program Info Request

sources/packages/api/src/route-controllers/assessment/assessment.aest.controller.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts
- Request table -> sorting was not properly working in some scenario
- History table -> submitted data sort as default (i.e ASC, updated to DESC)
=> [bug fix][api] sorting issue fix

sources/packages/web/src/services/http/dto/SupportingUser.dto.ts
=> [bug fix][web] import error

sources/packages/workflow/BPMN/pt-disbursement-calculation.bpmn
Bug in updating valueCode in workflow
=> [SIMS-#891][Workflow]Bug in updating valueCode in workflow

sources/packages/api/src/route-controllers/student-appeal/student-appeal.aest.controller.ts, sources/packages/api/src/services/student-appeal/student-appeal.service.ts, sources/packages/web/src/services/http/StudentAppealApi.ts, sources/packages/web/src/services/http/common/HttpBaseClient.ts
Fix issues with the Student Appeal Approval and error message display on Vue.
=> [web][api][SIMS #1078]Fix Ministry approval

sources/packages/api/src/services/student-appeal/student-appeal.service.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/web/src/views/aest/StudentAppealRequestsApproval.vue
- Fix assessment validation;
- Fix the audit fields that were not displayed when the form was approved/declined. The form.io definition was already expecting it.
=> [web][api][SIMS #1078]Fix audit

sources/packages/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts
- dev saving the existing offering id instead of the new offering id, which is not happening in local, this PR to debug this issue
=> [bug-fix][Api][SIMS#1004] Institution Reports a change - offering id

sources/packages/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts
assigned saved object to a const and assigned id from the saved object
=> [bug-fix][Api][SIMS#1004] Institution Reports a change - offering id 

sources/packages/api/src/app.system-access.module.ts, sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/entities/supporting-user.model.ts, sources/packages/api/src/route-controllers/assessment/assessment.controller.service.ts, sources/packages/api/src/route-controllers/assessment/assessment.system-access.controller.ts, sources/packages/api/src/route-controllers/assessment/models/assessment.system-access.dto.ts, sources/packages/api/src/route-controllers/index.ts, sources/packages/api/src/route-controllers/models/common.dto.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/workflow/scripts/api-response-parser.js
- Included more data in the assessment request to allow the reassessment processing;
- Supporting users;
- CRA income;
- Appeal requests;
- Created a generic method to read the API JSON response;
Workflow changes are in progress and this PR will enable the continuation of the workflow work.
Not able to resolve the Sonarcloud issues.
=> [api][workflow][SIMS #1081]Return additional assessment data to workflow

sources/packages/api/src/database/entities/application.model.ts, sources/packages/api/src/database/entities/supporting-user.model.ts, sources/packages/api/src/route-controllers/assessment/assessment.controller.service.ts, sources/packages/api/src/route-controllers/assessment/assessment.system-access.controller.ts, sources/packages/api/src/route-controllers/assessment/models/assessment.system-access.dto.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/workflow/scripts/api-response-parser.js
- Fixed CRA data not being returned;
- Added more CRA data to the student;
- Fixes for `api-response-parser.js`.
=> [api][SIMS #1081]Added CRA data to get assessment API

sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-files/e-cert-file-record.ts, sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-record.ts, sources/packages/api/src/esdc-integration/esdc-file-handler.ts, sources/packages/api/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-file-detail.ts, sources/packages/api/src/esdc-integration/msfaa-integration/msfaa-request.service.ts, sources/packages/api/src/utilities/auth-utils.ts, sources/packages/web/src/services/AppConfigService.ts, sources/packages/web/src/services/InstitutionService.ts
- Resolve the following issues for MSFAA and ecert send files
=> [Bug][SIMS-#1179]MSFAA and ECerts File sent bugs

sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts
- Fix disbursement validation for reassessment;
- Fix incorrect query parameter.
=> [api][SIMS #1081]Fixes for reassessments

sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts
=> [api][SIMS #1081]Fix saving disbursement

sources/packages/forms/src/form-definitions/programinformationrequest.json, sources/packages/web/src/views/institution/locations/program-info-request/LocationEditProgramInfoRequest.vue
The missing functionalities listed below have been implemented:
1. Include header according to figma design.
2. Dropdowns should be readonly/disabled when the status is Completed or Declined.
3. When status is Declined, the "Create Program" section should not be displayed.
=> [API][Web][SIMS #979] Remove Create Offering PIR

sources/packages/forms/src/form-definitions/educationprogramoffering.json
Bug fix to 
- Use includes to compare the value "Full time and Part time" selected in programs with offering intensity in offering form.
- Added one additional level of brackets to make the logic right.
=> [SIMS #978] Minor bug fix in form javascript

sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-files/e-cert-file-record.ts, sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-full-time-integration.service.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts
- Added COE status as a constraint to consider the disbursement ready. So far, only after the COE is completed a document number will be generated and the disbursement should be considered ready;
- Filtered grants that have 0(zero) dollar amounts. These grants should be present on DB but should not be part of the e-Cert file;
- Improved the comments on the method to be clear the list of the current requirements for a disbursement happens.
=> [api][SIMS #1188]FT Ecert File Issue

sources/packages/api/src/esdc-integration/e-cert-integration/models/e-cert-integration-model.ts
Change "Title" in the header to "NEW ENTITLEMENT" (Was "ENTITLEMENT")
=> [api][SIMS #1188]

sources/packages/forms/src/form-definitions/educationprogramoffering.json, sources/packages/web/src/components/common/ProgramOfferingDetailHeader.vue, sources/packages/web/src/types/contracts/OfferingContact.ts, sources/packages/web/src/views/institution/locations/programs/LocationProgramOffering.vue
=> [SIMS #980] common header bug fix

sources/packages/api/src/route-controllers/institution-locations/institution-location.aest.controller.ts, sources/packages/api/src/route-controllers/institution-locations/institution-location.institutions.controller.ts, sources/packages/api/src/route-controllers/institution-locations/institution-location.students.controller.ts, sources/packages/api/src/route-controllers/institution/institution.aest.controller.ts, sources/packages/api/src/route-controllers/institution/institution.institutions.controller.ts, sources/packages/forms/src/form-definitions/institutionlocation.json, sources/packages/web/src/services/InstitutionService.ts, sources/packages/web/src/services/http/Institution.ts, sources/packages/web/src/services/http/InstitutionLocation.ts
Refactoring institution-location controller, due to route conflicts on locationId and institutionId get call.
Removed disabling inputs for institution user Add location.
=> [API][Web][SIMS-#696]-MInistry Edit Location - Institution Location controller refactor

sources/packages/api/src/route-controllers/utils/address-utils.ts
Keep the backward compatibility between old and new address formats.
=> [api][SIMS #1124]Fix possible nullable selectedCountry

sources/packages/api/src/route-controllers/assessment/assessment.system-access.controller.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts
=> [Bug][SIMS-#1181]-BUg in assessment data fetch

sources/packages/api/src/route-controllers/assessment/assessment.system-access.controller.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts
[Bug][SIMS-#1181]Bug on institution Location on Assessment
=> [Bug][SIMS-#1181]Bug on institution Location on Assessment

sources/packages/api/src/route-controllers/assessment/assessment.controller.service.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts
=> [BUG][SIMS-#1181]-NOA not populating

sources/packages/web/src/components/layouts/student/StudentPageContainer.vue, sources/packages/web/src/views/student/NoticeOfAssessment.vue, sources/packages/web/src/views/student/Notifications.vue, sources/packages/web/src/views/student/NotificationsSettings.vue, sources/packages/web/src/views/student/StudentAccountActivity.vue, sources/packages/web/src/views/student/StudentAppealRequest.vue, sources/packages/web/src/views/student/StudentApplicationDetails.vue, sources/packages/web/src/views/student/StudentApplicationSummary.vue, sources/packages/web/src/views/student/StudentDashboard.vue, sources/packages/web/src/views/student/StudentFileUploader.vue, sources/packages/web/src/views/student/StudentProfile.vue, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue, sources/packages/web/src/views/student/financial-aid-application/StudentApplication.vue
Changes to all student views to use student-page-container
=> [Vue][SIMS #1198] - Changes to all student views to use student-page-container

devops/openshift/api-deploy.yml
Changed environment variable to fix bug
=> change value to fix bug

sources/packages/workflow/BPMN/assessment-gateway/assessment-gateway.bpmn, sources/packages/workflow/BPMN/assessment-gateway/extract-dynamic-data-exceptions.js
- Fix exception duplication removal before submitting the API payload;
- Add checkpoints `assessment-gateway` to make the Ministry approval faster and also provide better troubleshooting.
=> [workflow]Fix Application Exception

sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-full-time-integration.service.ts, sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-integration.service.ts, sources/packages/api/src/esdc-integration/e-cert-integration/models/e-cert-integration-model.ts
Bug on Stop BC funding on Disbursement file, Updated the structure and added the restriction logic.
=> [Bug][SIMS-#1197] Restriction-Stop-Disbursements

sources/packages/api/src-sql/Reports/Create-disbursement-report.sql, sources/packages/api/src-sql/Reports/Drop-disbursement-report.sql, sources/packages/api/src/database/migrations/1655249778578-CreateDisbursementReport.ts, sources/packages/api/src/services/report/report.service.ts, sources/packages/forms/src/form-definitions/exportfinancialreports.json
**- Create Report**
- User must have the ability to generate “Individual Grant Disbursement Report” in SIMS
- Report DETAILS:
- Columns in CSV: 
- Criteria: Check for received amounts
CSV Example,
Disbursement Forecast Report - YYYYMMDD TT:TT
Date of Disbursement, SIN, Application Number, Certificate Number, Funding Code,Disbursement amount,
2020-AUG-01,123456789,2020000001,000000001,BCAG,16073.00,12
2020-AUG-01,123456789,2020000001,000000001,BGPD,5073.00,15
2020-AUG-01,123456789,2020000002,000000001,CSLF,1236073.00,206
2020-AUG-04,123456789,2020000003,000000001,BGPD,77073.00,88
2020-AUG-04,123456789,2020000003,000000001,BCAG,36073.00,71
2020-AUG-05,123456789,2020000004,000000001,BCSG,10415.00,88
=> [FORMS][DB][SIMS-#298]-Generate disbursement reports

sources/packages/api/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt-processing.service.ts, sources/packages/api/src/services/disbursement-receipt/disbursement-receipt.service.ts
Added process summary log on successful insertion and record ignored
=> [SIMS #1249] Added process summary log on successful insertion and record ignored

sources/packages/api/src-sql/Reports/Create-disbursement-report.sql
Application number in the disbursement report than the application ID.
=> [Bug][SIMS-#298]Generate Disbursements

sources/packages/api/src/services/student/student.service.ts, sources/packages/forms/src/form-definitions/studentinformation.json
- Fix the SIN content message (missing "refer") in the Student Profile.
- Fix the SIN validation guard that was not returning the proper "Forbidden resource" HTTP error when a draft application creation was invoked and the SIN was not valid.
=> [formio][api][SIMS #1063]Fix SIN management content

sources/packages/api/src/route-controllers/assessment/assessment.system-access.controller.ts, sources/packages/api/src/route-controllers/assessment/models/assessment.system-access.dto.ts, sources/packages/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/forms/src/form-definitions/educationprogramoffering.json
- assessment API update -> added `studyBreaks`
- form update -> removed null checks, since it was breaking the dry run
=> [FORMIO][API][SIMS-#1223] forms and worflow api

sources/packages/api/src/services/application/application.service.ts
While submitting an application that has been submitted, toast message is displaying "unexpected error".
=> [Bug][API][SIMS-#1241]Application Cyclic error bug

sources/packages/web/src/views/institution/Login.vue
Small changes to login UI texts as requested by @hellolynn-tbtb after the demo.
=> [web][SIMS #1018]Institution login text changes

sources/packages/api/scripts/setupDB.ts
=> [Bug][SIMS-#1134]Type orm upgrade

sources/packages/web/src/views/aest/AppAEST.vue, sources/packages/web/src/views/institution/Login.vue, sources/packages/web/src/views/supporting-user/AppSupportingUser.vue
=> [bug-fix] [vue][sims-#1311] Remove primevue per component and upgrade vuetify#1311 

sources/packages/api/src-sql/Types/Rename-offering-status-values.sql, sources/packages/api/src-sql/Types/Rollback-rename-offering-status-values.sql, sources/packages/api/src/database/entities/offering-status.type.ts, sources/packages/api/src/database/migrations/1659726181274-RenameOfferingStatus.ts, sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.aest.controller.ts, sources/packages/api/src/services/education-program-offering/education-program-offering.service.ts, sources/packages/forms/src/form-definitions/educationprogramoffering.json, sources/packages/web/src/assets/css/formio-shared.scss, sources/packages/web/src/assets/css/global-style-variables.scss, sources/packages/web/src/components/aest/institution/modals/AssessOfferingChangeModal.vue, sources/packages/web/src/components/common/ProgramOfferingDetailHeader.vue, sources/packages/web/src/composables/useOffering.ts, sources/packages/web/src/types/contracts/institution/EducationProgramOfferingDto.ts, sources/packages/web/src/views/aest/institution/ViewOffering.vue, sources/packages/web/src/views/aest/institution/ViewOfferingChangeRequest.vue, sources/packages/web/src/views/aest/institution/ViewOfferingChangeRequestComplete.vue, sources/packages/web/src/views/institution/locations/programs/LocationProgramOfferingEdit.vue
=> [Web][Form][SIMS #1345] Change offering status values

sources/packages/api/src/auth/guards/groups.guard.ts, sources/packages/api/src/auth/guards/roles.guard.ts, sources/packages/api/src/auth/jwt.strategy.ts, sources/packages/api/src/auth/roles.enum.ts, sources/packages/api/src/auth/userToken.interface.ts, sources/packages/api/src/route-controllers/application-exception/application-exception.aest.controller.ts, sources/packages/api/src/route-controllers/designation-agreement/designation-agreement.aest.controller.ts, sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.aest.controller.ts, sources/packages/api/src/route-controllers/education-program-offering/education-program-offering.controller.ts, sources/packages/api/src/route-controllers/education-program/education-program.aest.controller.ts, sources/packages/api/src/route-controllers/institution-locations/institution-location.aest.controller.ts, sources/packages/api/src/route-controllers/institution-user/institution-user.aest.controller.ts, sources/packages/api/src/route-controllers/institution/institution.aest.controller.ts, sources/packages/api/src/route-controllers/note/note.controller.ts, sources/packages/api/src/route-controllers/report/report.aest.controller.ts, sources/packages/api/src/route-controllers/restriction/restriction.controller.ts, sources/packages/api/src/route-controllers/student-appeal/student-appeal.aest.controller.ts, sources/packages/api/src/route-controllers/student/student.aest.controller.ts, sources/packages/api/src/route-controllers/student/student.students.controller.e2e-spec.ts, sources/packages/api/src/testHelpers/controllers/auth-test/auth-test.controller.ts, sources/packages/api/test/auth.e2e-spec.ts, sources/packages/web/src/views/aest/student/FileUploads.vue
- updates role enum and role decorator
- added AEST roles to the `post` and `patch` endpoints
- FIXED button alignment and variant AEST student file upload modal
=> [api][sims-#66] - Define Ministry User Access and Permissions (per IDIR)#66

docs/howto/db-migration.md, sources/packages/api/src-sql/StudentAccountApplication/Add-deleted-at-col.sql, sources/packages/api/src-sql/StudentAccountApplication/Remove-deleted-at-col.sql, sources/packages/api/src/constants/error-code.constants.ts, sources/packages/api/src/database/entities/student-account-application.model.ts, sources/packages/api/src/database/migrations/1660176482909-StudentAccountApplicationAddDeletedAt.ts, sources/packages/api/src/route-controllers/student-account-applications/student-account-application.aest.controller.ts, sources/packages/api/src/route-controllers/student-account-applications/student-account-application.students.controller.ts, sources/packages/api/src/services/student-account-applications/student-account-applications.service.ts, sources/packages/web/src/constants/error-code.constants.ts, sources/packages/web/src/services/http/StudentAccountApplicationApi.ts, sources/packages/web/src/views/student/StudentProfileCreate.vue
- Added the soft-delete while declining the student account application.
- Added a specific message when the user tries to create the student account application and the user is already present on DB.
=> [web][api][SIMS #1057]Added soft-delete and same user message.

sources/packages/api/src/services/application/application.service.ts
Minor bug fix for student id reference.
=> [bug][SIMS #1345]minor bug fix for student id reference

sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts, sources/packages/api/src/utilities/disbursements-utils.ts
- Replaced CIP Code with Field of Study Code in the query that is part of the process for generating full time e-cert file.
=> [API][SIMS #1222] Federal Field of Study Code Part 2

sources/packages/forms/src/form-definitions/educationprogram.json
- Fixed bug on CIP Code validation to ensure correct format is 2 digits followed by full stop then 4 digits.
- Removed code that was commented out from my previous PR.
Screenshot to show bug fix.
**Wrong format**
**Correct format**
=> [Forms][SIMS #1222] Federal Field of Study Code Bug fix

sources/packages/web/src/components/layouts/Institution/sidebar/HomeSideBar.vue, testing/src/cypress.config.ts, testing/src/cypress/custom-command/institution/InstitutionCustomCommand.ts, testing/src/cypress/e2e/02-institution/01-login-institution-page.cy.ts, testing/src/cypress/e2e/02-institution/02-dashboard-institution-page.cy.ts, testing/src/cypress/e2e/02-institution/03-institution-profile.cy.ts, testing/src/cypress/e2e/02-institution/04-manage-location.cy.ts, testing/src/cypress/e2e/02-institution/05-manage-designations.cy.ts, testing/src/cypress/e2e/02-institution/06-manage-users.cy.ts, testing/src/cypress/e2e/02-institution/07-location-programs.cy.ts, testing/src/cypress/e2e/02-institution/common-helper-functions.cy.ts, testing/src/cypress/e2e/04-api-institution/01-instition-dashboard.cy.ts, testing/src/cypress/page-objects/Institution-objects/DashboardInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/LoginInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageInstitutionObject.ts
- Had to change few base  functions for re-usability
- Adding a new config file for cypress only variables like expected results etc
- Adding the data-cy into the test case will be dealt later
=> [cypress][SIMS #1392] Adding Institution Dashboard UI and API tests 

sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/ApproveCOE.vue, sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementForm.vue, sources/packages/web/src/views/institution/designations/DesignationRequest.vue
1. I accidentally left a property in vue tag - removed it
2. added the "go back" feature for cancel btn in the designation agreement form.
=> [vue][sims-#1367] UI updates for Institution Account Part 2 of 2 - fixes

sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/ApproveCOE.vue
=> [vue][sims-#1367] UI updates for Institution Account Part 2 of 2 - bug fix

sources/packages/api/src/route-controllers/designation-agreement/designation-agreement.institutions.controller.ts
. Fixed Swagger API tag.
. Created documentation on naming standards in wiki. https://github.com/bcgov/SIMS/wiki/Development-Standards-and-Decisions
=> [API][SIMS-#1248] API Client Naming Convention

sources/packages/api/src/route-controllers/report/report.aest.controller.ts, sources/packages/api/src/route-controllers/student/student.aest.controller.ts, sources/packages/api/src/route-controllers/student/student.students.controller.ts, sources/packages/web/src/services/StudentService.ts, sources/packages/web/src/services/http/ApplicationApi.ts, sources/packages/web/src/services/http/ReportApi.ts, sources/packages/web/src/services/http/StudentApi.ts
- Changed API sub resource(s) from plural to singular.
- Updated affected files due to updated subresources in vue web application.
- Updated wiki documentation.
**Wiki Update**
https://github.com/bcgov/SIMS/wiki/Development-Standards-and-Decisions#controller-api-naming-convention
=> [API][SIMS-#1248] API Client Naming

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/uploadstudentdocuments.json
Updated file upload URLs on form io. This was missed in the last PR.
=> [Forms][SIMS-#1248] Client Name API

.github/workflows/deploy.yml
Fix Github actions deploy file.
=> [CI/CD][SIMS #1397]Fix jobs steps hierarchy

sources/packages/web/src/views/institution/Login.vue, testing/src/cypress/custom-command/institution/InstitutionCustomCommand.ts, testing/src/cypress/page-objects/Institution-objects/LoginInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageDesignationsObject.ts
- Adding data-cy id for login page 
- Fixing a typo from previous fix
=> [cypress][SIMS #1421] Manage Designation test cases - adding new data-cy ids 

.github/workflows/camunda-definitions-deploy.yml, devops/Makefile, sources/packages/workflow/package-lock.json, sources/packages/workflow/package.json, sources/packages/workflow/src/deploy.ts, sources/packages/workflow/tsconfig.json
- Allow local Camunda deployment automation to the developer machine;
- Allow deployment to DEV, TEST;
- Produce deployment log as shown below.
=> [CI/CD][SIMS #1442]Camunda deployment automation

sources/packages/backend/apps/workers/src/controllers/program-info-request/program-info-request.controller.ts, sources/packages/backend/apps/workers/src/controllers/supporting-user/supporting-user.controller.ts
Fixing the wrong enum name which caused a build error.
=> [workers][SIMS #1442]Fix build

sources/packages/web/src/components/aest/institution/modals/ApproveProgramModal.vue, sources/packages/web/src/components/aest/institution/modals/AssessOfferingChangeModal.vue, sources/packages/web/src/components/common/OfferingForm.vue, sources/packages/web/src/components/common/restriction/ViewRestriction.vue, sources/packages/web/src/components/common/sin/AddNewSIN.vue, sources/packages/web/src/components/generic/formio.vue, sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/ApproveCOE.vue, sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/DenyCOE.vue, sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementForm.models.ts, sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementForm.vue, sources/packages/web/src/views/aest/institution/DesignationAESTView.vue, sources/packages/web/src/views/institution/designations/DesignationRequest.vue, sources/packages/web/src/views/institution/designations/DesignationView.vue
1. Bug was caused due to the `deep: true` enabled in the watch for  `props.data`. and it was introduced as some of the form data were using vue `reactive`.
2. updated designation agreement as it was using  `reactive` to use `ref`
3. resolve `viewOnly` reactive issue of the designation agreement  form
=> [bug][vue][SIMS-#1302] formio datagrid bugs

.github/workflows/deploytest.yml, sources/packages/forms/src/deploy-forms.ts
Included the calls to deploy Camunda definitions and Form.io definitions in the TEST workflow.
=> [CI/CD][SIMS #1442]Added Camunda and forms deploy to TEST

sources/packages/web/src/components/aest/institution/modals/ApproveDenyDesignationModal.vue, sources/packages/web/src/components/aest/institution/modals/ApproveProgramModal.vue, sources/packages/web/src/components/aest/institution/modals/AssessOfferingModal.vue, sources/packages/web/src/components/aest/institution/modals/DeclineProgramModal.vue, sources/packages/web/src/components/common/notes/CreateNoteModal.vue, sources/packages/web/src/components/common/restriction/ViewRestriction.vue, sources/packages/web/src/components/common/sin/AddExpiryDate.vue, sources/packages/web/src/components/common/sin/AddNewSIN.vue, sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/ApproveCOE.vue, sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/DenyCOE.vue, sources/packages/web/src/components/students/modals/CancelApplication.vue, sources/packages/web/src/components/students/modals/ConfirmEditApplication.vue, sources/packages/web/src/components/students/modals/PDStatusApplicationModal.vue, sources/packages/web/src/views/aest/student/StudentAccountApplicationsApproval.vue, sources/packages/web/src/views/student/StudentProfileEdit.vue
Removed max-width and min-width as it is in common modal-dailog-base component
=> [Web][SIMS-#1435]-Removed max-width and min-width as it is in common component

sources/packages/web/src/composables/useRules.ts, sources/packages/web/src/services/http/SupportingUserApi.ts, sources/packages/web/src/views/supporting-user/SupportingInformation.vue
- used common rules for validations; 
- changed supportingUserApi to use postCall and handleAPICustomError;
- removed snackBar for field validation; 
- refactored catches for request reponses;
=> [Web][SIMS-#1110] UI updates for Supporting-Users - Search refactoring

.github/workflows/build-deploy-dev.yml, .github/workflows/deploy-all.yml
Fixes for reusable workflow names.
=> [CI/CD]Unified Deployments Fixes

.github/workflows/build-deploy-dev.yml, .github/workflows/deploy-all.yml
- Added Environment Variables for Complete DEV/TEST/QA Deployments
=> [CI/DC]Added Environment Variables for Complete DEV/TEST/QA Deployments

.github/workflows/build-deploy-dev.yml
Fix incorrect syntax for "uses".
=> [CI/CD]Fix "uses" on DEV deployment

testing/src/cypress/data/dataSetupInstitution.sql, testing/src/cypress/data/dataTearDownInstitution.sql
Creating the SQL scripts which will help on the data setup and teardown for institution test cases. The SQL Scripts will help creating  
- new institutions 
- new institution locations
- new institution users
- new designation agreements for institutions
=> [cypress][SIMS #1443] Adding SQL scripts for setup and teardown of test data

sources/packages/web/src/services/http/SupportingUserApi.ts, sources/packages/web/src/types/formio.ts, sources/packages/web/src/views/supporting-user/SupportingInformation.vue
Fixes for the navigation through the formio breadcrumbs and for the submission. 
- added emits for proper navigation
- refactored updateSupportingInformation to use patchCall and handleAPICustomError
- raised an error for unknown errors
=> [Web][SIMS-#1110] UI updates for Supporting-Users - Navigation fix

sources/packages/backend/libs/sims-db/src/entities/federal-restriction.model.ts
=> [SIMS #1466]unused import

sources/packages/web/src/components/common/InstitutionUserSummary.vue, sources/packages/web/src/components/institutions/modals/AddInstitutionUserModal.vue, sources/packages/web/src/components/institutions/modals/EditInstitutionUserModal.vue, sources/packages/web/src/components/institutions/modals/InstitutionUserManagement.vue, testing/src/cypress/e2e/02-institution/06-manage-users.cy.ts, testing/src/cypress/page-objects/Institution-objects/LoginInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageDesignationsObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageUsersObject.ts
- Managing the users inside the institutions 
- With Supporting data-cy ids
=> [cypress][SIMS #1521] Adding Institution Users  UI TestCases  

sources/packages/web/src/components/institutions/modals/AddInstitutionUserModal.vue, testing/src/cypress/data/dataSetupInstitution.sql, testing/src/cypress/data/dataTearDownInstitution.sql, testing/src/cypress/e2e/02-institution/06-manage-users.cy.ts, testing/src/cypress/page-objects/Institution-objects/ManageUsersObject.ts
Fixing the test cases to match the cy-ids and some modification to the methods
=> [cypress][SIMS #1521] Fixing Institution Test Cases - I 

sources/packages/backend/apps/api/src/institution-integration/ier-integration/ier12-file.service.ts, sources/packages/backend/apps/api/src/route-controllers/institution-integration/ier-integration-system-access.controller.ts, sources/packages/backend/apps/api/src/route-controllers/institution-integration/models/ier.dto.ts, sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts
=> [API][SIMS-#1347]Bug fix on query param

sources/packages/workflow/BPMN/camunda-8/assessment-2021-2022.bpmn, sources/packages/workflow/BPMN/camunda-8/assessment-2022-2023.bpmn, sources/packages/workflow/BPMN/camunda-8/assessment-2023-2024.bpmn, sources/packages/workflow/BPMN/camunda-8/assessment-decisions.dmn, sources/packages/workflow/BPMN/camunda-8/assessment-gateway.bpmn, sources/packages/workflow/BPMN/camunda-8/configure-disbursement.bpmn, sources/packages/workflow/BPMN/camunda-8/load-assessment-consolidated-data.bpmn
1. Add assessment selector based off ProgramYear
2. Add assessment-2021-2022 workflow for Camunda 8 (Assessed need and Award Configuration)
3. Added and converted previous DMNs into a DRD for all assessment DMNs for Camunda 8
4. Added disbursement schedule BPMN to prepare payload for saving disbursement
5. Removed hardcoded variables from "Save assessment output"
=> [camunda][SIMS#577] Adding Full Time Assessment 20212022

sources/packages/forms/src/form-definitions/educationprogram.json
=> [form][SIMS #1394]"Which regulatory body does this program belong to?" Missing in create new program form

sources/packages/backend/apps/test-db-seeding/src/main.ts, sources/packages/backend/libs/utilities/src/config/config.models.ts, sources/packages/backend/libs/utilities/src/config/config.service.ts
1. Added a method in the config service to retrieve the process env variable for test-db-seeding
=> [backend] config update

sources/packages/backend/apps/test-db-seeding/src/test-db-seeding.module.ts
=> [backend] config import error fix 

sources/packages/backend/apps/api/src/services/education-program/education-program.service.ts
I just changed from `program` to `educationProgram` to use the right sabcCode to update. It was wrongly changed in the latest updates for the previous PR.
=> [Api][SIMS #1488] Cannot create institution program - sabc unique code constraint violation - Small fix

devops/Makefile
Deployment bug during Hostprefix change
=> [DEVOPS][SIMS-#1493]Implement Formio - bug

devops/Makefile, devops/openshift/queue-consumers-deploy.yml
Fixed missed environment variables for queue consumers.
=> [Bug][DEVOPS][SIMS-#1550]Move Modules to Shared Library Part 1 of 3 

sources/packages/web/src/router/InstitutionRoutes.ts, sources/packages/web/src/views/institution/Login.vue
- Removed switch/case
- Removed props
- Removed route props
=> [web][SIMS #1465] Remove not possible error message

sources/packages/web/src/components/common/LocationSummary.vue, sources/packages/web/src/components/layouts/Institution/sidebar/ManageInstitutionSideBar.vue, sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementSummary.vue, sources/packages/web/src/views/institution/EditInstitutionLocation.vue, sources/packages/web/src/views/institution/InstitutionUserProfile.vue, sources/packages/web/src/views/institution/designations/ManageDesignations.vue, testing/src/cypress/e2e/02-institution/01-login-institution-page.cy.ts, testing/src/cypress/e2e/02-institution/02-dashboard-institution-page.cy.ts, testing/src/cypress/e2e/02-institution/04-manage-location.cy.ts, testing/src/cypress/e2e/02-institution/05-manage-designations.cy.ts, testing/src/cypress/e2e/02-institution/06-manage-users.cy.ts, testing/src/cypress/e2e/data/institution/manage-location.json, testing/src/cypress/page-objects/Institution-objects/BaseMethods.ts, testing/src/cypress/page-objects/Institution-objects/DashboardInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/LoginInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageDesignationsObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageLocationObject.ts
- Adding more data cy ids 
- Adjusting the hierarchy to match the test cases for the TestQuality
=> [cypress][SIMS #1541] Adding Institution data-cy ids - 2

sources/packages/web/src/components/common/restriction/ViewRestriction.vue
Fixed some layout issues to match the updated figma prototype:
- Added headers for all cases;
- Changed 'Close' button to be primary
Provincial unresolved:
Provincial resolved:
Federal unresolved:
Federa resolved:
=> [web][SIMS #1562] AEST Resolve Federal Restriction 

sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12-file-detail.ts
Bug regarding rounding of awards and invalid date in date sent.
=> [Bug][SIMS#1602]-IER12_Bug

sources/packages/web/src/components/common/OfferingSummary.vue, sources/packages/web/src/components/common/ProgramDetails.vue, sources/packages/web/src/views/institution/locations/programs/LocationProgramView.vue, sources/packages/web/src/views/institution/locations/programs/LocationPrograms.vue, testing/src/cypress/e2e/02-institution/05-manage-designations.cy.ts, testing/src/cypress/e2e/02-institution/07-location-programs.cy.ts, testing/src/cypress/e2e/data/institution/manage-location.json, testing/src/cypress/page-objects/Institution-objects/BaseMethods.ts, testing/src/cypress/page-objects/Institution-objects/DashboardInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ManageInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/ProgramDetailViewObject.ts
- Updating/Adding institution program tests 
- Adding respective cy-ids to support the above tests
=> [cypress][SIMS #1549] Institution Programs

devops/openshift/api-deploy.yml
Remove sfas env variable SFAS_RECEIVE_FOLDER from api deploy yml
=> #1606 - Remove sfas env variable from api

testing/src/cypress/e2e/02-institution/03-institution-profile.cy.ts, testing/src/cypress/e2e/02-institution/04-manage-location.cy.ts, testing/src/cypress/e2e/02-institution/06-manage-users.cy.ts, testing/src/cypress/e2e/02-institution/07-location-programs.cy.ts, testing/src/cypress/page-objects/Institution-objects/BaseMethods.ts, testing/src/cypress/page-objects/Institution-objects/DashboardInstitutionObject.ts, testing/src/cypress/page-objects/Institution-objects/LocationProgramObject.ts
=> [cypress][SIMS #1549] Institution Programs - Adding Test Cases

testing/src/cypress/e2e/02-institution/07-location-programs.cy.ts, testing/src/cypress/page-objects/Institution-objects/DashboardInstitutionObject.ts
- Adding program creation test cases
=> [cypress][SIMS #1549] Institution Programs - Adding more tests

sources/packages/forms/src/form-definitions/studentprofile.json
=> #1390 - Bug Remove the test dropdown added in form

devops/openshift/queue-consumers-deploy.yml
=> #1548 - deployment bug fix

sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/backend/libs/integrations/src/services/msfaa-number/msfaa-number.service.ts
1. #1548 - bug fix in MSFSS and E-Cert
=> #1548 - bug fix in MSFSS and E-Cert

sources/packages/backend/apps/workers/src/workers.module.ts
Bug in importing module for workers
=> Bug in importing module for workers

sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece.processing.service.ts
Uploaded records bug for institution file upload
=> #486 - Bug Uploaded records for institution file upload

sources/packages/forms/src/form-definitions/uploadstudentdocuments.json, sources/packages/web/src/assets/css/formio-shared.scss
1. remove the formio button.
2. formio file uploader misalignment issue style fix  - actually it was happening for all files. formio file uploader.
=> #1614 - Student File Upload - UI

devops/Makefile
Fixing deploy-api and deploy-queue-consumers Makefile commands
=> #1638 - Makefile bug fix

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json
Created a new hidden variable `showParentInformation` which uses the current logic of determining  dependant status.
Form.io Javascript in VS Code
=> #1587 Get dependent status excluding parents if both parents estranged or passed away

.github/workflows/test.yml
Review Dependabot, adding env variable for test.yml
=> #1666-Review dependabot

.github/workflows/test.yml
=> #1666- Reverting the dependabot change

devops/Makefile, sources/packages/forms/Dockerfile
Updated version of fomio with 2.5.4 and install libraries using package-lock.json
=> Updated version of fomio with 2.5.4 and install libraries using package-lock.json

sources/packages/forms/Dockerfile
=> Updated Dockerfile for formio

sources/packages/web/src/components/students/applicationTracker/ApplicationProgressBar.vue, sources/packages/web/src/components/students/applicationTracker/Completed.vue, sources/packages/web/src/components/students/applicationTracker/DisbursementBanner.vue, sources/packages/web/src/components/students/applicationTracker/MultipleDisbursementBanner.vue, sources/packages/web/src/views/student/StudentApplicationDetails.vue
=> #1665 - Application tracker for completed status

sources/packages/backend/apps/api/src/services/application/application.service.ts, sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts, sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts, sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts, sources/packages/backend/apps/api/src/services/student/student.service.ts, sources/packages/backend/apps/api/src/testHelpers/fake-entities/application-fake.ts, sources/packages/backend/apps/db-migrations/src/migrations/1675373000032-RenameApplicationStatusEnrolment.ts, sources/packages/backend/apps/db-migrations/src/sql/Types/Rename-application-status-enrolment.sql, sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-rename-application-status-enrolment.sql, sources/packages/backend/apps/queue-consumers/src/processors/assessment/cancel-application-assessment.processor.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/tests/ecert-full-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/services/application/application.service.ts, sources/packages/backend/apps/workers/src/controllers/disbursement/tests/disbursement.controller.e2e-spec.ts, sources/packages/backend/apps/workers/src/services/application/application.service.e2e.skip-spec.ts, sources/packages/backend/apps/workers/src/services/application/application.service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts, sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule.service.ts, sources/packages/backend/libs/sims-db/src/entities/application-status.type.ts, sources/packages/backend/libs/test-utils/src/factories/application.ts, sources/packages/web/src/components/aest/StudentApplications.vue, sources/packages/web/src/components/common/ConfirmEnrolment.vue, sources/packages/web/src/components/students/applicationTracker/ApplicationProgressBar.vue, sources/packages/web/src/composables/useApplication.ts, sources/packages/web/src/types/contracts/student/ApplicationContract.ts, sources/packages/web/src/views/student/NoticeOfAssessment.vue, sources/packages/web/src/views/student/StudentApplicationDetails.vue, sources/packages/web/src/views/student/StudentApplicationSummary.vue, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
=> #1696 - Rename application status enrolment and fix the enum

sources/packages/backend/apps/api/src/route-controllers/program-info-request/program-info-request.institutions.controller.ts
- added optional chaining to avoid exceptions when undefined;
- tested other all the situations  where the user can't find the program, period;
=> #1676 - PIR Data not showing up in institutions

sources/packages/forms/src/form-definitions/programinformationrequest.json
- added condition to display course details when offering equals to Part Time.
=> #1676 - Condition to display course only with Part Time

sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts, sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts, sources/packages/forms/src/form-definitions/programinformationrequest.json, sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json
While deriving the valid confirmation period of a COE to be approved by the institution, the valid confirmation period end date has been modified to be offering end date.
=> #1669 - Modify the confirmation period end date for COE

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/studentexceptions.json
=> #1669 - Fix the student exception to use updated hidden variables and texts

sources/packages/backend/package-lock.json, sources/packages/web/package-lock.json
Executed `npm audit fix` to remove detected vulnerabilities and remove warnings.
=> npm audit fix

sources/packages/web/src/components/common/OverawardDetails.vue, sources/packages/web/src/components/common/StudentOverawardDetails.vue
=> #1692 - Fix for the toggle content with right constant

sources/packages/backend/apps/api/src/services/student/student.service.ts
Just fixing an issue for the last PR. It was not checking if sfasIndividual was null.
=> #1677 - Bug when there is no sfasIndividual

sources/packages/forms/src/form-definitions/designationagreementdetails.json
- Move text underneath heading
- Content change on bullet points
- https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=9474%3A97285&t=jEspGEbtvSsanZjp-0
=> #1543 - Update designation form content

.github/workflows/build-deploy-dev.yml
Possible fix to fix the failing deployment
=> #1719 - Create Release Strategy

.github/workflows/build-deploy-dev.yml, .github/workflows/build-deploy-forms.yml, .github/workflows/deploy-all.yml, .github/workflows/deploy-secrets.yml
- added `gitRef` for all checkouts
- removed default  `main` from all workflow dispatch input for  `gitRef/buildRef`
=> #1719 - Create Release Strategy 

sources/packages/backend/apps/api/src/route-controllers/overaward/_tests_/e2e/overaward.students.controller.getOverawardBalance.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/overaward/_tests_/e2e/overaward.students.controller.getOverawardsByStudent.e2e-spec.ts
=> #1712 - Students over awards UI - E2E Test cases

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-part-time-process-integration.scheduler.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-part-time-process-response-integration.scheduler.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/models/msfaa-integration.model.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-file-detail.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-file-footer.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-file-header.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-response-cancelled-record.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-response-received-record.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-files/msfaa-response-record-identification.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-request.processing.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-response.processing.service.ts, sources/packages/backend/libs/integrations/src/services/msfaa-number/msfaa-number.service.ts
- MSFAA sent/received schedulers were named incorrectly (the request was a response and vice-versa). There are no actual changes on files `msfaa-integration/msfaa-part-time-process-integration.scheduler.ts` and `msfaa-part-time-process-response-integration.scheduler.ts` other than the file renaming.
- Replaced some deprecated `substr` by `substring`.
- Added a condition `cancelledDate is null` to pending MSFAA generation to avoid generating an MSFAA to canceled records.
=> #1864 - PT Integration Files Review - MSFAA Send/Request Files

sources/packages/forms/src/form-definitions/noticeofassessment.json
Removing extra "," that was causing a form.io deploying issue.
=> #1759 - MSFAA UI Changes for NOA - Fix form.io definition

.github/workflows/build-deploy-dev.yml, .github/workflows/deploy-all.yml
Bug in deployment on github actions.
=> #1717 - Bug-02/Segregate db migrations deployment - Part 1 

.github/workflows/build-deploy-dev.yml
=> #1717-Bug-04/Segregate DB Migrations Deployment

.github/workflows/build-deploy-dev.yml
=> #1717-Bug-05/Segregate DB Migration deployment

sources/packages/backend/apps/api/Dockerfile, sources/packages/backend/apps/db-migrations/Dockerfile, sources/packages/backend/apps/queue-consumers/Dockerfile, sources/packages/backend/apps/workers/Dockerfile
In this PR, updated user to nonroot user 1001 for queue-consumer, api, workers and db-migration
=> #1966 - Update user to nonroot user 1001

sources/packages/backend/apps/api/Dockerfile, sources/packages/backend/apps/db-migrations/Dockerfile, sources/packages/backend/apps/queue-consumers/Dockerfile, sources/packages/backend/apps/workers/Dockerfile
As a part of this PR, removed the redundant nonroot user from the Dockerfiles.
=> #1867 - Fix SonarCloud security hotspots

devops/Makefile
Updating deploy namespace in db migrations
Bug from this story, not able to connect as the story is closed.
https://github.com/bcgov/SIMS/issues/1717
=> #1717 - Bug/Updating deploy namespace in db migrations

sources/packages/forms/src/form-definitions/educationprogram.json
- Update the Education Program NOC code to accept 5 digits.
- No DB updates are required for the existing ones as per agreed by @JasonCTang.
=> #2024 - Changed NOC to 5 digits

sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.getCompletedApplications.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.getEligibleApplications.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.getInProgressApplications.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/application-offering-change-request.institutions.controller.ts, sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/models/application-offering-change-request.institutions.dto.ts, sources/packages/backend/apps/api/src/route-controllers/models/pagination.dto.ts, sources/packages/backend/libs/test-utils/src/data-source/e2e-data-source.ts, sources/packages/backend/libs/test-utils/src/factories/application-offering-change-request.ts, sources/packages/backend/libs/test-utils/src/index.ts
- Created E2E test cases for `available`, `in-progress`, and `completed` endpoints.
- Added 2 TCs each one with page, page limit, and sort and 2nd with page, page limit, and search
- Screenshots
- `available`
- `in progress`
- `completed`
=> #1953 - Request an Offering Change - Part 4

sources/packages/web/src/views/institution/locations/programs/LocationPrograms.vue
- Program table search fix
_screenshots_
=> #2036 - Fix search issue in the program data table that is using v-data-table search

sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/ApplicationDetailsForCOE.vue
- Error while approving COE due to previous WAVA fixes.
=> #2020 - WAVA Changes - Fix for the COE Approval

sources/packages/forms/src/form-definitions/educationprogram.json
The regulatory body question was repeating
=> #2086 - Fix question repetition

sources/packages/web/src/services/http/dto/StudentAccountApplication.dto.ts
Added missing property `identityProvider`
=> #2126 - Add missing property on student account creation

devops/openshift/sysdig-team.yml
Sysdig monitoring team creation yml is created to run the agent in our namespace in openshift.
=> #1874-Sysdig Monitoring Team creation

sources/packages/backend/apps/api/src/app.aest.module.ts, sources/packages/backend/apps/api/src/app.students.module.ts, sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts, sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.students.controller.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/models/assessment.dto.ts, sources/packages/backend/apps/api/src/services/application-offering-change-request/application-offering-change-request.service.ts, sources/packages/backend/libs/sims-db/src/entities/assessment-trigger.type.ts, sources/packages/web/src/components/aest/students/assessment/History.vue, sources/packages/web/src/components/generic/StatusChipRequestedAssessment.vue, sources/packages/web/src/components/students/StudentAssessmentDetails.vue, sources/packages/web/src/components/students/applicationTracker/ApplicationProgressBar.vue, sources/packages/web/src/components/students/applicationTracker/Completed.vue, sources/packages/web/src/composables/useAssessment.ts, sources/packages/web/src/services/StudentAssessmentsService.ts, sources/packages/web/src/services/http/dto/Application.dto.ts, sources/packages/web/src/services/http/dto/Assessment.dto.ts, sources/packages/web/src/types/contracts/AssessmentTrigger.ts, sources/packages/web/src/types/contracts/StatusChip.ts
**1.** On app tracker, in completed status:
- added a warning card with button "Review changes" when status is in progress with student.
- added a warning card showing the request is pending SABC approval if the student approves the change request.
- added a student declined card if the student declines the change request. 
- added a ministry approved card if the ministry approves the change request. 
- added a ministry declined card if the ministry declines the change request.
Note: All the statuses are based on the most recent submitted request for change (Same logic from student appeal).
**2.** Added logic to display the offering change requests in the "assessment" table.
**3.** Modified the logic to show amber color in the application tracker when there is atleast one of the following …
=> #1977 - Request Offering Change: Student Application Tracker - Part 2

sources/packages/backend/apps/db-migrations/src/migrations/1690490545372-AlterColOperatingAndLegalOperatingName.ts, sources/packages/backend/apps/db-migrations/src/sql/Institution/Alter-col-operating-and-legal-operating-name.sql, sources/packages/backend/apps/db-migrations/src/sql/Institution/Rollback-alter-col-operating-and-legal-operating-name.sql, sources/packages/backend/libs/sims-db/src/entities/institution.model.ts, sources/packages/forms/src/form-definitions/institutionprofile.json, sources/packages/forms/src/form-definitions/institutionprofilecreation.json, sources/packages/web/src/views/aest/SearchInstitutions.vue
Merge hotfix v1.1.1 to main
Hotfix branch `hotfix/v1.1.1` was created for Releasev1.1.1 (https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTQwNDc)
=> Merge hotfix v1.1.1 to main

sources/packages/backend/workflow/BPMN/camunda-8/fulltime-assessment-2021-2022.bpmn, sources/packages/backend/workflow/BPMN/camunda-8/fulltime-assessment-2022-2023.bpmn, sources/packages/backend/workflow/BPMN/camunda-8/fulltime-assessment-2023-2024.bpmn, sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json
- Changed conditions to accept Separated / Divorced / Widowed as "independant" from form.io;
- Changed gateway assessment workflow condition;
- Married student application:
- Change Separated / Divorced / Widowed Student application:
- Single student application:
=> #2165 - Student application - Change Separated / Divorced / Widowed Students to 'Independent' Status

devops/openshift/api-deploy.yml, devops/openshift/database/mongo-ha.yml, devops/openshift/queue-consumers-deploy.yml, devops/openshift/web-deploy.yml, devops/openshift/workers-deploy.yml
Attaching PDB to the statefulset and deploymentconfig
=> #1875 - PodDisruptionBudget Bug

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json
- Hid the questions for part-time applications;
- Tested Part-time and Full-time application.
=> #2172 - Remove Part-Time Questions from Application

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json
The conditional is not applied in the panel rather applied in the question below, so fixed it right now.
=> #2137 - Full Time Work Question - Bug

sources/packages/forms/src/form-definitions/designationagreementdetails.json, sources/packages/web/src/views/institution/Login.vue
=> #2300 - Update institution hyperlinks

sources/packages/forms/src/form-definitions/designationagreementdetails.json, sources/packages/web/src/views/institution/Login.vue
Cherry pick commit from main branch
=> #2300 - Update institution hyperlinks (#2400)

sources/packages/forms/src/form-definitions/educationprogram.json
-  Adjusted one of the options within the 'entrance requirements' question
> **from** “This program has entrance requirements established by the institution that enable completion of the program [of] study”
> **to** “For post-secondary level academic credit-based programs: This program has entrance requirements established by the institution that enable completion of the program of study.”
-  Adjusted one of the options within the 'entrance requirements' question
> **from** BC Industry Training Authority
> **to** SkilledTradesBC
**_Screenshots_**
=> #2402 - Content Changes for Program Form in Institution Portal (Program Entrance Requirements)

sources/packages/backend/apps/db-migrations/src/migrations/1702080750384-DataInventoryReport.ts, sources/packages/backend/apps/db-migrations/src/sql/Reports/Create-data-inventory-report.sql, sources/packages/backend/apps/db-migrations/src/sql/Reports/Drop-data-inventory-report.sql, sources/packages/forms/src/form-definitions/exportfinancialreports.json
- Created a query for the new report (120 columns were implemented of 216 in total) and added to the report form;
- Updated the spreadsheet;
- Created a new ticket for the missing columns.
[CSV Sample](https://github.com/bcgov/SIMS/files/13639769/Data_Inventory_Report_2023-12-11_10.40.12.csv)
- Column names need to have max 63 characters. So some column names will be truncated to 63 characters when they are longer.
- Country column for address is missing, so I added that column to the report.
- "Home Address" column won't be added because we have already all the address data separated and that can be easily achieved through Excel.
- For the column  "Marital Status (or 'category')" we can have the student dependency status in one column and the relationship status in another column …
=> #2525 - Data Inventory Report Analysis

sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts, sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.models.ts, sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/libs/sims-db/src/database-utils.ts, sources/packages/web/src/components/generic/StatusChipAssessmentHistory.vue, sources/packages/web/src/composables/useAssessment.ts, sources/packages/web/src/types/contracts/AssessmentStatus.ts
- Adjusted the assessment history query and I didn't change the existing query to TypeORM, only adjusted the query.
- Mapped the status and chip color as per the ticket
=> #2188 - Queued Assessments - Assessment Status Review

sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/validate-disbursement-base.ts
Added COE declined constraint to e-Cert eligibility criteria to ensure that disbursements with declined COEs will not be considered for e-Cert generations.
=> #2510 - e-Cert Implementation for Individual Student Processing - Added COE Declined Constraint

package-lock.json, sources/packages/backend/package-lock.json, sources/packages/backend/package.json, sources/packages/forms/package-lock.json, sources/packages/forms/package.json, sources/packages/web/package-lock.json, sources/packages/web/package.json, sources/packages/web/src/services/EducationProgramOfferingService.ts, sources/packages/web/src/services/ScholasticStandingService.ts, sources/packages/web/src/services/http/EducationProgramOfferingApi.ts, sources/packages/web/src/services/http/ScholasticStandingApi.ts, sources/packages/web/src/services/http/common/FileUploadProgressEvent.ts, sources/packages/web/src/services/http/common/HttpBaseClient.ts, sources/packages/web/src/views/institution/OfferingsUpload.vue, sources/packages/web/src/views/institution/WithdrawalUpload.vue, testing/package-lock.json, testing/src/package-lock.json, testing/src/package.json
- Upgraded Axios to 1.6.2 version;
- Replaced FileUploadProgressEventArgs by AxiosProgressEvent;
- Tested the application modules to see if any issued with the upgrade;
- Waiting for the merge to check that the security issues related will be resolved.
=> #2505 - Upgrade Axios Package

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json
If 'loans and grants' is selected, the info text should be revised to read: "I am required to start making payments on the first day of the seventh month after leaving studies; my payments are made up of principal and any accrued interest, if applicable".
- Change the content as described above.
Please see the image below for the adjusted content (taken from student portal)
=> #2324 Update PT Grant-Only Text

sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-decisions.dmn
- Updated values as per ACs;
- No test needed to change.
=> #2301 - Input new 2023/2024 Program Year Amounts - PT

sources/packages/backend/apps/api/Dockerfile, sources/packages/backend/apps/db-migrations/Dockerfile
API failure in PROD due to NPM access issue
This is related to https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2535
So cherry picking the changes that went through as part of this ticket into the new HOTFIX branch v1.2.1
Please note: NOT upgrading NPM or changing any other apps dockerfile like workers, queue-consumers or load-test-gateway. As they are not deployed and used in PROD env.
=> #2648 - Prod NPM Access fix

devops/openshift/database/patroni-deploy.yml
Merging Hotfix/v1.2.1 to main
https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTg1OTI
=> Hotfix v1.2.1 to main branch

sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.controller.service.ts, sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts, sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts, sources/packages/web/src/components/common/OfferingSummary.vue, sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts, sources/packages/web/src/types/contracts/DataTableContract.ts
- Added a column to the offering listing:
=> #2484 - Add year of study column to offering listing

sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn, sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn, sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn, sources/packages/backend/workflow/test/2021-2022/parttime-assessment/eligibility/parttime-assessment-2021-2022-eligibility-BCAG.e2e-spec.ts, sources/packages/backend/workflow/test/2022-2023/parttime-assessment/eligibility/parttime-assessment-2022-2023-eligibility-BCAG.e2e-spec.ts, sources/packages/backend/workflow/test/2023-2024/parttime-assessment/eligibility/parttime-assessment-2023-2024-eligibility-BCAG.e2e-spec.ts
- Updated awardEligibilityBCAG in parttime assessments for all program years
- Adjusted E2E tests
Camunda Screenshot
=> #2614 - PT Award Eligibility - BCAG

devops/openshift/api-deploy.yml
**This PR is the fix for the change in the formatting of the `api-deploy.yml` file caused due to the previous PR.**
=> #2524 - Hide FT Programs for PT Release - File Formatting Fix

sources/packages/web/src/composables/useFormatters.ts
COE Disability Application Status description: 
- "Assessment Includes disability funding types." (corresponds to option 1 in the student form)
- "No disability funding types included on assessment." (corresponds to option 2 or 3 in the student form)
=> #2522 - COE Disability Application Status description

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/load-test/src/_tests_/form-io/form-io-application-submission/models.ts
**As a part of this PR, formio definitions were updated to include the additional transport cost related questions for all program years.**
Please note: There is no field validation currently in place for the 1st question (as per the story requirements) - "Please estimate your weekly transportation costs."
=> #1707 - Application Form: Additional Transportation Costs (FT & PT)

.github/workflows/prune-images.yml
Fixes the time the action is triggered at 6am Pacific is 2pm UTC
Maps the inputs or default values into GH Environment variables
Quotes were changed
=> #1989 - prune images

sources/packages/backend/apps/api/src/route-controllers/education-program/_tests_/e2e/education-program.institutions.controller.createEducationProgram.e2e-spec.ts, sources/packages/backend/apps/db-migrations/src/migrations/1708121940221-UpdateProgramLength.ts, sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Rollback-update-program-length.sql, sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Update-program-length.sql, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/_tests_/unit/e-cert-part-time-integration.service.spec.ts, sources/packages/backend/libs/utilities/src/integration-utils.ts, sources/packages/backend/workflow/BPMN/camunda-8/fulltime-assessment-2021-2022.bpmn, sources/packages/backend/workflow/BPMN/camunda-8/fulltime-assessment-2022-2023.bpmn, sources/packages/backend/workflow/BPMN/camunda-8/fulltime-assessment-2023-2024.bpmn, sources/packages/backend/workflow/test/2021-2022/fulltime-assessment/eligibility/fulltime-assessment-2021-2022-eligibility-BCAG.e2e-spec.ts, sources/packages/backend/workflow/test/2022-2023/fulltime-assessment/eligibility/fulltime-assessment-2022-2023-eligibility-BCAG.e2e-spec.ts, sources/packages/backend/workflow/test/2023-2024/fulltime-assessment/eligibility/fulltime-assessment-2023-2024-eligibility-BCAG.e2e-spec.ts, sources/packages/backend/workflow/test/models/assessment.model.ts, sources/packages/forms/src/form-definitions/educationprogram.json, testing/src/cypress/e2e/02-institution/07-location-programs.cy.ts, testing/src/cypress/page-objects/Institution-objects/DashboardInstitutionObject.ts
- Updated the form labels for Education Program
- Updated workflow
- Updated integration-utils
- Updated E2E
=> #2820 - Program length form and label changes

sources/packages/backend/apps/load-test-gateway/src/constants/application.constants.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/_tests_/unit/e-cert-full-time-integration.service.spec.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-files/e-cert-file-record.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-full-time.integration.service.ts
PT eCert PD/PPD flag populating based on application selection
FT eCert PD/PPD flag populating based on application selection
=> #2734 - Ecert File Revisions

.editorconfig, sims.code-workspace
Creates an editor config which sets defaults for the entire project (lf, 2 space tab, etc)
Created a multi-root workspace with extension recommendations, default search excludes, format on save etc.
=> Create VS Code Workspace and Editor Config files

sources/packages/web/src/components/common/ProgramOfferingDetailHeader.vue
Only follow the second route for the institution link if the first does not apply.
=> #2948 - Add conditional to institution link routing

sims.code-workspace, sources/packages/forms/src/form-definitions/exportfinancialreports.json, sources/packages/forms/src/form-definitions/reportscholasticstandingchange.json, sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/studentdependantsappeal.json, sources/packages/forms/src/form-definitions/studentdisabilityappeal.json, sources/packages/forms/src/form-definitions/studentfinancialinformationappeal.json, sources/packages/forms/src/form-definitions/supportingusersparent2022-2023.json, sources/packages/forms/src/form-definitions/supportingusersparent2024-2025.json, sources/packages/forms/src/form-definitions/supportinguserspartner2022-2023.json, sources/packages/forms/src/form-definitions/supportinguserspartner2024-2025.json
Make the defined options the only ones available for any multi-choice that has defined options.
=> #2813 - form security update

sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.getApplicationAssessmentStatusDetails.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.aest.controller.manualReassessment.e2e-spec.ts, sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/libs/test-utils/src/factories/application.ts
Added tests for: 
- ApplicationAESTController(e2e)-getApplicationAssessmentStatusDetails
- AssessmentAESTController(e2e)-manualReassessment
=> #2272 - Ministry Trigger Manual Reassessment E2E tests

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
Add a warning message to the disability section of applications, conditional on disability status already being approved and the user selecting 'no' to disability funding.
=> Add a warning message to the disability section of applications.

devops/Makefile, devops/openshift/database/redis-ha-deploy.yml
- Change to remove `RoleBinding` from `make delete-redis` command as we don't need that in our environments and it causes an error:
After the change:
- Changed spacing of `storageClassName` to make it be under `spec`. That issue cause an error when testing on TEST env:
=> 3027 - Investigate Queue-Consumers error in Prod

sources/packages/forms/src/form-definitions/sfaa2021-22.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Remove the 'not required' option and make the situation description question required when additional transportation is selected. Update the wording around document upload and remove the unused field after the upload.
=> #2806 - Additional Transportation Form Change

sources/packages/forms/src/form-definitions/educationprogram.json
Update SABC codes, and confirm other study codes.
Example:
=> #2841 - Fix Study Codes

sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentAwardDetails.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts, sources/packages/backend/libs/test-utils/src/factories/application.ts, sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts, sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts, sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts, sources/packages/backend/workflow/test/models/assessment.model.ts, sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts
E2E test cases for PT Lifetime maximum CSLP
- Workers
- Queue Cosumers
- Workflow - Only the test related to the Lifetime maximum is covered as part of this PR.
Updated one API test case to assert its value rightly with the offering intensity.
=> #2872 - PT Lifetime maximum CSLP - E2E Tests

sources/packages/web/src/components/students/applicationTracker/DisbursementBanner.vue
Fix "have/has" content issue for a single disbursement.
=> #2650 - Cancel Future Disbursements if COE is declined (Bug) - Content Fix

.github/workflows/prune-images.yml, devops/scripts/fetchOldJobTags.sh, devops/scripts/pruneImages.sh
Enhanced PruneImages by adding a new type and dynamically calling fetch script.
Created new fetchOldJobTags script which looks at the job isntead of the DC.
Updated the GH Action to run both types of prunes.
=> #3237 - Enhance prune images to support either DCs or Jobs

sources/packages/forms/src/form-definitions/educationprogram.json
- Changed field name;
- Changed text below input field;
- Added tooltip with the text and link requested.
The json file had 2 tabs instead of one for some reason. That's why it shows as entirely changed:
=> #3185 - Content: Institution: Create program: “SABC program code” text box label Fixes

sources/packages/backend/libs/services/src/notifications/notification/gc-notify.service.ts
Remove the api key prefix from the gc-notify section.
=> #3055 - Remove api key prefix

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/parsers/full-time-e-cert-record-parser.ts
This PR is just to fix the E2E. I notice an issue with the test case I created:
=> #3026 - Ecert File Creation - PT & FT - E2E fix

sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.models.ts, sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- Removed properties "hasAssessmentData", "workflowName", "assessmentWorkflowId" from select.
- Removed property "assessmentAppealId" but keep "studentAppeal.id" from select.
- Removed class "ApplicationAssessmentSummary" and method returns Application array.
- Added `studentAppeal` property to `application.currentAssessment` if applicationStatus is Completed.
=> #3263 - Refactor Code for Mass Offering Change Request

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Make the number of weeks of additional transport costs a required field.
=> #3216 - Make transport weeks a required field

sources/packages/forms/src/form-definitions/studentrequestchange.json, sources/packages/web/src/views/institution/Login.vue, sources/packages/web/src/views/student/Login.vue, sources/packages/web/src/views/supporting-user/Login.vue
Update a selection of second level headings from to h2.
=> #3113 - Update second level headings to h2 from h3

.github/workflows/prune-images.yml
The new jobs pruning portion of the script was failing as the variable was not being initialized properly.
I renamed the variable jobs as it is valid yaml syntax and I wanted to be sure we had no conflicts.
=> Rename variable and initialize properly

sources/packages/backend/apps/db-migrations/src/migrations/1715796993998-UpdateOfferingStatusForOfferingDetailsReport.ts, sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-update-offering-status-offering-details-report.sql, sources/packages/backend/apps/db-migrations/src/sql/Reports/Update-offering-status-offering-details-report.sql
- Updated the **offering statuses** to include the statuses: **Creation pending, Approved, Change under review** in the Offering Details SQL.
=> #3062 - Enable Reports for BC Public Institutions (Part 5)

sources/packages/forms/src/form-definitions/studentrequestchange.json, sources/packages/web/src/views/aest/AppAEST.vue, sources/packages/web/src/views/institution/Login.vue, sources/packages/web/src/views/student/AppStudent.vue, sources/packages/web/src/views/student/Login.vue, sources/packages/web/src/views/supporting-user/AppSupportingUser.vue, sources/packages/web/src/views/supporting-user/Login.vue
Add accessible text labels to account buttons.
=> #3111 - Add label to account button

sims.code-workspace, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-integration.module.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.models.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-pre-validation-service-models.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-pre-validation-service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/full-time-calculation-process.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/index.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/part-time-calculation-process.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/validate-disbursement-base.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/validate-disbursement-full-time-step.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/validate-disbursement-part-time-step.ts
Created a new service to execute e-Cert validations in a centralized manner.
The service allows validations to be executed before the e-Cert disbursement time reusing the same checks and query used during the e-Cert generation.
If more validating are added, they should be seamlessly consumed using the `ECertPreValidationService`.
Service it to be injected as below.
```ts
private readonly eCertPreValidationService: ECertPreValidationService,
```
Validations to be executed based in the application ID, where a list of failed validations will be returned.
```ts
const failedValidations = await this.eCertPreValidationService.executePreValidations(applicationId);
// Sample result: [ 'NonCompletedCOE', 'MSFAANotSigned', 'DisabilityStatusNotConfirmed' ]
```
A list of possible errors as below. …
=> #2798 - e-Cert Validations for Blocked Disbursement Service

sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentNOA.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.confirmAssessmentNOA.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.getAssessmentNOA.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.students.controller.ts, sources/packages/backend/apps/api/src/route-controllers/assessment/models/assessment.dto.ts, sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts, sources/packages/backend/apps/workers/src/controllers/assessment/assessment.dto.ts, sources/packages/backend/apps/workers/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/libs/test-utils/src/factories/application.ts, sources/packages/backend/libs/test-utils/src/factories/disbursement-schedule.ts, sources/packages/backend/workflow/src/workflow-definitions/assessment-gateway.bpmn, sources/packages/backend/workflow/src/workflow-definitions/load-assessment-consolidated-data.bpmn, sources/packages/backend/workflow/test/2022-2023/assessment-gateway/assessment-gateway.originalAssessment.e2e-spec.ts, sources/packages/backend/workflow/test/2022-2023/assessment-gateway/assessment-gateway.studentAppeal.e2e-spec.ts, sources/packages/backend/workflow/test/2023-2024/assessment-gateway/assessment-gateway.originalAssessment.e2e-spec.ts, sources/packages/backend/workflow/test/2023-2024/assessment-gateway/assessment-gateway.studentAppeal.e2e-spec.ts, sources/packages/backend/workflow/test/2024-2025/assessment-gateway/assessment-gateway.originalAssessment.e2e-spec.ts, sources/packages/backend/workflow/test/2024-2025/assessment-gateway/assessment-gateway.studentAppeal.e2e-spec.ts, sources/packages/backend/workflow/test/models/assessment.model.ts, sources/packages/backend/workflow/test/test-utils/constants/workflow-variables-constants.ts, sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts, sources/packages/web/src/components/common/NoticeOfAssessmentFormView.vue, sources/packages/web/src/services/http/dto/Assessment.dto.ts, sources/packages/web/src/views/student/NoticeOfAssessment.vue, sources/packages/web/src/views/student/StudentAssessmentAward.vue
Students will need to accept at least one assessment, and be unable to accept outdated assessments.
=> #2807 - Revise student accepting assessments logic

sources/packages/web/src/components/common/NoticeOfAssessmentFormView.vue, sources/packages/web/src/router/StudentRoutes.ts, sources/packages/web/src/views/student/NoticeOfAssessment.vue
Follow up to #2807 to add parsing the number for the id.
=> #2807 - Cast to int in router for assessment page

sources/packages/forms/src/form-definitions/exportfinancialreports.json
- Conditionally showing `Intensity` filter for Ecert Errors Report.
=> #3132 - Bug fix: Ecert Errors Report

sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-decisions.dmn, sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
Update the parttime-assessment-decisions logic, and associated tests.
=> #2572 - 2024 2025 Award Configuration

sources/packages/backend/libs/integrations/src/esdc-integration/fed-restriction-integration/fed-restriction.processing.service.ts
Set the max parallel to 4 instead of the previous OS cores (usually 32 in Openshift).
The current configuration was making the POD unresponsive, leading to Health check fails, and causing the queue job to be stalled.
=> #3283 - Adjusted Federal Restrictions Import Parallelism

sources/packages/backend/apps/db-migrations/src/migrations/1717182261632-AddFileDateAndSequenceNumberColumnsToDisbursementReceipts.ts, sources/packages/backend/apps/db-migrations/src/sql/DisbursementReceipts/Add-file-date-and-sequence-number-cols.sql, sources/packages/backend/apps/db-migrations/src/sql/DisbursementReceipts/Drop-add-file-date-and-sequence-number-cols.sql, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/full-time-disbursement-receipts-integration.scheduler.e2e-spec.ts, sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt-files/disbursement-receipt-file-header.ts, sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt.processing.service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-receipt/disbursement-receipt.service.ts, sources/packages/backend/libs/sims-db/src/entities/disbursement-receipts.model.ts, sources/packages/backend/libs/test-utils/src/factories/disbursement-receipt.ts
- Added migration for the new fields;
- Saved the new fields;
- Changed E2Es to test new fields in DB;
- Validated fields are saved:
- DISB-TOT-DISB-AMT (pos. 45 - 52)  mapped as totalDisbursedAmount
- DISB-TOT-GRANT-DISB (pos. 102 - 109) mapped as totalDisbursedGrantAmount
=> #2869 - Updates to Provincial Daily Disbursement - Import Data Changes

sources/packages/web/src/views/student/Login.vue
Update the wording on the student log in screen.
=> #3301 - Student login page content updates

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Update text on the get started on your application page.
=> #3160 - Get started on your application page

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Update the content of the financial section of applications.
=> #3311 - Student financial information content

sources/packages/web/src/views/student/StudentAppealRequest.vue
Add change request instructions.
=> #2846 - add change request instructions

sources/packages/web/src/components/common/students/StudentProfile.vue, sources/packages/web/src/composables/useFormatters.ts, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
Add a display formatter for the ministry view of student gender.
=> #2831 - Add a display formatter for the ministry view of student gender

sources/packages/forms/src/form-definitions/studentprofile.json
Reorder gender options on the student profile.
=> #2831 - Reorder gender options

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Update the personal info section of applications.
=> #3310 - Update personal info content

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Update the Family Information section of student applications.
=> #3309 - Family Information Updates

sources/packages/backend/apps/db-migrations/src/migrations/1719252081303-UpdateSINValidationStudentUnmetNeedReport.ts, sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-update-sin-validation-student-unmet-need-report.sql, sources/packages/backend/apps/db-migrations/src/sql/Reports/Update-sin-validation-student-unmet-need-report.sql
**Bug:**  Multiple application records were being selected because of an incorrect `WHERE` condition in the `SQL` query for the `sin_validations` and `students` tables.
**Fix:** The `WHERE` condition of the `SQL` query has been fixed.
**Part of the query fixed**
---------------------------------------------------------------
**SQL**
```sql
SELECT
users.first_name AS "Student First Name",
users.last_name AS "Student Last Name",
sin_validations.sin AS "SIN",
applications.student_number AS "Student Number",
users.email AS "Student Email Address",
students.contact_info ->> 'phone' AS "Student Phone Number",
institution_locations.institution_code AS "Institution Location Code",
institution_locations.name AS "Institution Location Name",
applications.application_number AS "Application Number", …
```
=> #3133 - Student Unmet Need Report: BC Public Institution (Bug Fix)

sources/packages/forms/src/form-definitions/studentdependantsappeal.json
Applied the changes as described on the ticket:
=> #3441 - Content: Student: Request a Change - Add/Remove Dependant

sources/packages/web/src/views/student/AppStudent.vue
Make the overawards section visibility dependent on fulltime being allowed.
=> #3031 - Overawards menu item

sources/packages/backend/apps/db-migrations/src/migrations/1719531876964-CreateSupplierStatusType.ts, sources/packages/backend/apps/db-migrations/src/migrations/1719533191327-CreateCASSuppliersTable.ts, sources/packages/backend/apps/db-migrations/src/migrations/1719597653676-AddCASSupplierIdColumnToStudentsTable.ts, sources/packages/backend/apps/db-migrations/src/sql/CASSuppliers/Create-cas-suppliers.sql, sources/packages/backend/apps/db-migrations/src/sql/CASSuppliers/Rollback-create-cas-suppliers.sql, sources/packages/backend/apps/db-migrations/src/sql/Student/Add-cas-supplier-id.sql, sources/packages/backend/apps/db-migrations/src/sql/Student/Rollback-add-cas-supplier-id.sql, sources/packages/backend/apps/db-migrations/src/sql/Types/Create-supplier-status-type.sql, sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-create-supplier-status-type.sql, sources/packages/backend/libs/sims-db/src/constant.ts, sources/packages/backend/libs/sims-db/src/data-source.ts, sources/packages/backend/libs/sims-db/src/entities/cas-supplier.model.ts, sources/packages/backend/libs/sims-db/src/entities/index.ts, sources/packages/backend/libs/sims-db/src/entities/student.model.ts, sources/packages/backend/libs/sims-db/src/entities/supplier-status.type.ts
First PR. This includes:
- Created supplier status type;
- Created CAS Supplier table;
- Added cas supplier id to students table;
- Created models.
=> #3255 - CAS Integration - Add CAS Supplier Info to Student Profile - Part 1

sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.getApplicationWarnings.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-pre-validation-service.ts, sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts, sources/packages/web/src/services/StudentAssessmentsService.ts, sources/packages/web/src/services/http/StudentAssessmentApi.ts, sources/packages/web/src/views/student/NoticeOfAssessment.vue
Add a warning and disable the assessment acceptance button if the application has validation failures.
=> #2706 - Block Assessment Acceptance

sources/packages/web/src/views/supporting-user/SupportingInformation.vue
Change when supporting user footer is hidden (keep the footer visible on repeat searches).
=> #2990 - Supporting User Footer

sources/packages/web/src/components/generic/Banner.vue, sources/packages/web/src/views/student/NoticeOfAssessment.vue
Extend banner components to display a list of content.
=> #2706 - add a list form for banners

sources/packages/backend/apps/api/src/route-controllers/designation-agreement/_tests_/e2e/designation-agreement.institutions.controller.submitDesignationAgreement.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/designation-agreement/designation-agreement.institutions.controller.ts, sources/packages/backend/libs/test-utils/src/factories/designation-agreement.ts, sources/packages/web/src/views/institution/designations/ManageDesignations.vue
Change the error for multiple designation requests and add an e2e test case.
=> #2903 - multiple designation requests

sources/packages/web/src/views/student/StudentAppealRequest.vue
Update to the second part of the request a change form page.
=> #3469 - Request a change update

sources/packages/forms/src/form-definitions/studentrequestchange.json
Update the request a change form page.
=> #3307 - Request a change update

sources/packages/web/src/views/aest/student/StudentAccountApplicationsApproval.vue
Update ministry student account creation wording.
=> #3491 - Ministry student account creation

devops/Makefile
- Readded params to init-secrets.
=> #3255 - CAS - deploy error fix - 3

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Update the select program section of the student application.
=> #3306 - Select program content updates

sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- Changed to return `data` prop from CAS logon response.
=> #3255 - CAS logon bugfix

sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.models.ts
Make validation for offeringCostExceedMaximum conditional on all of the costs being entered.
=> #2919 - Institution offering warning message

devops/openshift/workers-deploy.yml
Previous PR fixes parameters (require vs required) properties causing some issues.
=> #3502 - Removed ATBC_LOGIN_ENDPOINT

devops/openshift/workers-deploy.yml
Removing "required" when value is provided which was causing a deploy error.
=> #3502 - Removing "required" when value is provided.

devops/Makefile, devops/openshift/workers-deploy.yml
Added missing ENV variable mapping from the previous PR.
=> #3502 - Mapped missing DISABLE_ORM_CACHE

sources/packages/web/src/services/StudentAssessmentsService.ts, sources/packages/web/src/services/http/StudentAssessmentApi.ts, sources/packages/web/src/views/institution/designations/ManageDesignations.vue, sources/packages/web/src/views/student/NoticeOfAssessment.vue, sources/packages/web/src/views/student/StudentAppealRequest.vue
Code formatting in few of the files were not in sync with the common settings that we have been following. Fixed those files listed here.
=> #3561 - Fix code formatting

sources/packages/web/src/composables/useFileUtils.ts, sources/packages/web/src/services/FormUploadService.ts
**Bug:** The text of the file was not displaying properly. Instead, it was displaying [Object object]
**Fix:** Updated the `FormUploadService` `downloadFile` method to use the `fileUtils.downloadStudentDocument` method which ensures the proper download of the `blob` type response.
=> #2973 - File Uploader Bug

sims.code-workspace, sources/packages/backend/apps/api/src/route-controllers/student/student.aest.controller.searchStudents.e2e-spec.ts, sources/packages/web/src/components/common/SearchStudents.vue
Student search now contains a SIN column. E2E tests are covered in student.institutions.controller.searchStudents.e2e-spec
=> #3291 - Student search

sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.models.ts, sources/packages/web/src/components/common/OfferingForm.vue, sources/packages/web/src/components/common/OfferingFormSubmit.vue
Add blocking for institution offering costs warning when a field is empty.
=> #2919 - Institution offering warning

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/studentadditionaltransportationappeal.json
- Updated the application forms with the additional transportation question
- Updated the additional transportation appeals form with the additional transportation question
- Updated the formio for the updated variable as per the table and removed the prefix `studentData` as the variable given is in camunda format in both the forms - Application and Change Requests
**Note:** I have confirmed with @Joshua-Lakusta and the red banner as shown in the image is as expected.
**Application Screenshots:**
----------------------------------------------------------------
----------------------------------------------------------------
**Appeal Screenshots:**
-----------------------------------------------------------------
=> #3351 - Form Additional Transportation Question (FT/PT)

sources/packages/forms/src/form-definitions/designationagreementdetails.json
Add a warning when a request contains duplicate officers.
=> #2742 - Designation request role validation

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
Update the indigenous questions section of student applications.
=> #3350 - Update indigenous questions

sources/packages/forms/src/form-definitions/studentwelcomepage.json
Update the content on the student landing page.
=> #3452 - Student landing page

sources/Makefile, sources/packages/web/src/components/students/modals/ConfirmEditApplication.vue, sources/packages/web/src/views/student/StudentApplicationDetails.vue, sources/packages/web/src/views/student/StudentApplicationSummary.vue, sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue, sources/tests/Makefile
Update the warning modal for application edits.
=> #3495 - Edit application

sources/packages/forms/src/form-definitions/studentrequestchange.json
- Case  change for request a change options
=> #3399 - Content: Student: Request a Change: Options

.github/workflows/release-build-all.yml, .github/workflows/release-deploy-camunda-definitions.yml, .github/workflows/release-deploy-formio-definitions.yml, .github/workflows/repo-checks-tests.yml
- Upgraded actions/github-script to v7 - https://github.com/actions/github-script?tab=readme-ov-file#breaking-changes
- Upgraded actions/setup-node to v4 and node-version to "18.x"
=> #3061 - Upgraded actions/github-script to v7

sources/packages/web/src/components/aest/students/assessment/History.vue, sources/packages/web/src/components/aest/students/assessment/Request.vue, sources/packages/web/src/components/layouts/aest/AESTApplicationSideBar.vue, sources/packages/web/src/views/aest/student/applicationDetails/AssessmentsSummary.vue
Update the content on the ministry assessments page.
=> #3316 - Update ministry assessment content

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-feedback-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-feedback-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-full-time-process-response-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-part-time-process-response-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/student-loan-balances/_tests_/student-loan-balances-part-time-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ece-response/_tests_/ece-response-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sfas-integration.scheduler.e2e-spec.ts, sources/packages/backend/libs/integrations/src/constants/system-configurations-constants.ts, sources/packages/backend/libs/integrations/src/cra-integration/cra-income-verification.processing.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt.processing.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/backend/libs/integrations/src/esdc-integration/fed-restriction-integration/fed-restriction.processing.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-response.processing.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa.integration.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/sin-validation/sin-validation.processing.service.ts, sources/packages/backend/libs/integrations/src/esdc-integration/student-loan-balances/student-loan-balances.processing.service.ts, sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece-response.processing.service.ts, sources/packages/backend/libs/integrations/src/services/ssh/sftp-integration-base.ts, sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.processing.service.ts, sources/packages/backend/libs/utilities/src/system-configurations-constants.ts
- Replaced method `deleteFile` for  `archiveFile`;
- Updated comments about file deletions;
- Updated the list of schedulers with "Sequential" and "Archiving on error" columns.
List of Schedulers and behaviour to process sequentially and archiving:
| Scheduler Name                                         | Description                                                 | Cron expression       | UTC                                       | PDT      | SFTP Folder                            | Sequential | Archiving on error |
| ------------------------------------------------------ | ----------------------------------------------------------- | --------------------- | ----------------------------------------- | -------- | -------------------------------------- |------------|--------------------| …
=> 2801 - Archive SFTP files

sources/packages/forms/src/form-definitions/studentprofile.json, sources/packages/web/src/views/student/NoticeOfAssessment.vue
=> #3464 - Disability status info

devops/helm/clam-av/main/Makefile, devops/helm/crunchy-postgres/Makefile, sources/Makefile
=> #3268 - Local connection to the openshift DB - Makefile command change

sources/packages/backend/apps/db-migrations/src/migrations/1725052431315-CreateRestrictionBypassBehaviorsType.ts, sources/packages/backend/apps/db-migrations/src/migrations/1725052532471-CreateApplicationRestrictionBypassesTable.ts, sources/packages/backend/apps/db-migrations/src/sql/ApplicationRestrictionBypasses/Create-application-restriction-bypasses.sql, sources/packages/backend/apps/db-migrations/src/sql/ApplicationRestrictionBypasses/Rollback-create-application-restriction-bypasses.sql, sources/packages/backend/apps/db-migrations/src/sql/Types/Create-restriction-bypass-behaviors.sql, sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-create-restriction-bypass-behaviors.sql, sources/packages/backend/libs/sims-db/src/constant.ts, sources/packages/backend/libs/sims-db/src/data-source.ts, sources/packages/backend/libs/sims-db/src/entities/application-restriction-bypass.model.ts, sources/packages/backend/libs/sims-db/src/entities/application.model.ts, sources/packages/backend/libs/sims-db/src/entities/index.ts, sources/packages/backend/libs/sims-db/src/entities/restriction-bypass-behaviors.type.ts
- Created new DB migrations for the type `sims.restriction_bypass_behaviors`.
- Created new DB migrations for the new table `sims.application_restriction_bypasses`.
=> #1815 - Ignore restrictions - DB Migrations

sims.code-workspace, sources/packages/backend/apps/api/src/route-controllers/report/_tests_/e2e/report.institutions.controller.exportReport.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/report/models/report.dto.ts, sources/packages/backend/apps/api/src/route-controllers/report/report.controller.service.ts, sources/packages/backend/apps/api/src/services/index.ts, sources/packages/backend/apps/api/src/testHelpers/auth/index.ts, sources/packages/backend/apps/api/src/testHelpers/auth/institution-user-helpers.ts, sources/packages/backend/apps/db-migrations/src/migrations/1725898775531-CreateCOERequestsReport.ts, sources/packages/backend/apps/db-migrations/src/sql/Reports/Create-coe-requests-report.sql, sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-create-coe-requests-report.sql, sources/packages/backend/libs/services/src/report/report.service.ts, sources/packages/backend/libs/test-utils/src/factories/institution.ts, sources/packages/backend/package.json, sources/packages/forms/src/form-definitions/exportfinancialreports.json, sources/packages/web/src/constants/index.ts, sources/packages/web/src/constants/report-constants.ts, sources/packages/web/src/views/aest/Reports.vue, sources/packages/web/src/views/institution/Reports.vue
Note: This format can be potentially an agreement that we can follow to display date and time columns.
```sql
SELECT
student_user.first_name AS "Student First Name",
student_user.last_name AS "Student Last Name",
sin_validation.sin AS "SIN",
application.data ->> ''studentNumber'' AS "Student Number",
student_user.email AS "Student Email Address",
student.contact_info ->> ''phone'' AS "Student Phone Number",
application.application_number AS "Application Number",
TO_CHAR((assessment.assessment_date AT TIME ZONE ''America/Vancouver''), ''YYYY-MM-DD HH24:MI:SS'') AS "Assessment Date",
program.program_name AS "Program Name",
offering.offering_name AS "Offering Name",
offering.offering_intensity AS "Study Intensity",
student.disability_status AS "Profile Disability Status", …
```
=> #3131 - COE Requests Report

sources/packages/forms/src/form-definitions/programinformationrequest.json
- Reverted file `programinformationrequest.json` and used the `isGivenDateBeforeToday` validation for the PIR process in institution portal
=> #2997 - 6 Week Deadline - Policy (Quick Fix)

sources/packages/forms/src/form-definitions/designationagreementdetails.json, sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementForm.models.ts, sources/packages/web/src/views/aest/institution/DesignationAESTView.vue
- **Sentence wordings below the `Designated Locations` heading for both the ministry and the institution have been updated [checked with @CarlyCotton on the wording for both]. The updated wordings are shown in the below screenshots.**
- **Ministry View: Removed the link completely.**
----------------------------------------------------------------------------------------------------------------------
- **Institution View: The link remains as it is.**
=> #3589 - Ministry views designation agreement: 403 error on link

sources/packages/backend/apps/db-migrations/src/migrations/1726604196628-UpdateRestrictionsNotificationTypes.ts, sources/packages/backend/apps/db-migrations/src/sql/Restrictions/Rollback-update-restrictions-notification-types.sql, sources/packages/backend/apps/db-migrations/src/sql/Restrictions/Update-restrictions-notification-types.sql
- Updated notification_type for the restriction code '12', 'O' and 'PTWTHD'
=> #3512 - Review Impact of All Restrictions (Quick Fix)

sources/packages/forms/src/form-definitions/studentaccountactivity.json
=> #3634 - Change student account restriction content

sources/packages/forms/src/form-definitions/studentexceptions.json, sources/packages/web/src/components/common/students/applicationDetails/ApplicationExceptionsApproval.vue
=> #3496 - Content: Ministry: Exception request approve/deny

sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/_tests_/e2e/student-scholastic-standings.institutions.controller.saveScholasticStanding.e2e-spec.ts, sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts, sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts, sources/packages/backend/libs/services/src/restriction/model/restriction.model.ts, sources/packages/backend/libs/test-utils/src/models/common.model.ts
When an withdrawal of an application is requested from the institution user, now PTWTHD restriction is also added with PTSSR.
=> #3511 - Revise PT Scholastic Standing

sources/packages/web/package-lock.json, sources/packages/web/package.json, sources/packages/web/src/assets/css/base.scss, sources/packages/web/src/components/generic/SnackBar.vue, sources/packages/web/src/types/contracts/DataTableContract.ts, sources/packages/web/src/views/aest/institution/ViewPendingOfferingChangeRequests.vue, sources/packages/web/src/views/aest/student/CASSupplierInformation.vue, sources/packages/web/src/views/institution/WithdrawalUpload.vue, sources/packages/web/src/views/institution/locations/programs/LocationPrograms.vue, sources/packages/web/src/views/institution/locations/request-a-change/request-a-change/AvailableToChange.vue, sources/packages/web/src/views/institution/locations/request-a-change/request-a-change/Completed.vue, sources/packages/web/src/views/institution/locations/request-a-change/request-a-change/InProgress.vue
- **Upgraded Vuetify to the most recent version: 3.7.2**
- **Following issue came up during the upgrade and was fixed:**
**This issue was fixed by fixing the width of the Vuetify toolbar.**
- **Also the below issue was investigated as a part of the task:**
**The reason why the above arrows do not show up when the screen width is  decreased is because of the following CSS class changes are automatically applied by the framework on adjusting the browser window size:**
- **Thoroughly checked almost all the functionality for all the client types: student, institution and ministry. Major functionalities tested include:**
1. Student portal:  application submission (in its entirety till completion), file uploader and request a change section.
2. Ministry portal: search students, search …
=> #3198 - Upgrade Vuetify and fix UI issues

sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.controller.getApplicationDetails.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.institutions.controller.getApplicationDetails.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/application.aest.controller.ts, sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts, sources/packages/backend/apps/api/src/route-controllers/application/application.institutions.controller.ts, sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts, sources/packages/backend/apps/api/src/services/application/application.service.ts, sources/packages/web/src/components/aest/students/ApplicationHeaderTitle.vue, sources/packages/web/src/components/generic/DetailHeader.vue, sources/packages/web/src/services/ApplicationService.ts, sources/packages/web/src/services/http/ApplicationApi.ts, sources/packages/web/src/services/http/dto/Application.dto.ts, sources/packages/web/src/views/aest/student/applicationDetails/AssessmentAward.vue, sources/packages/web/src/views/aest/student/applicationDetails/AssessmentsSummary.vue, sources/packages/web/src/views/aest/student/applicationDetails/NoticeOfAssessment.vue
If there is no offering attached:
=> #3287 - Add header to minsitry assessment pages

sources/packages/web/src/components/aest/students/bypassedRestrictions/HistoryBypassedRestrictions.vue, sources/packages/web/src/components/generic/StatusChipBypass.vue, sources/packages/web/src/composables/useRestrictionBypass.ts, sources/packages/web/src/types/contracts/DataTableContract.ts
- Included "Restriction status" to reflect the current status of any restriction in the table.
- Included "Bypass status" column to reflect the status of the bypass: Active / Removed
=> #1862 - UX/UI for Ignore Restriction - Bypass List (Adjustment)

sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json
Fixed duplicates of the markup content in the Upload Document panel in the Form.io file.
Screenshot of the markup content before the fix
Screenshot of the markup content after the fix
=> #3620 - Change Request - Partner Current Year Income (financial information) option (Fix Duplicate Markup)

sources/packages/web/src/views/institution/WithdrawalUpload.vue
Same fix done for the bulk upload in https://github.com/bcgov/SIMS/pull/3860.
=> #3840 - Hotfix: Fix for withdraw upload

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-scheduler.ts
**As a part of this PR, the scheduler `DisbursementReceiptsFileIntegration` is being enabled for Parttime.**
=> #3912 - Allow Disbursement Receipts File Integration Scheduler For Parttime

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json
**Updated the blurb for self-declare partner financial information.**
=> #3615 - Minor FormIO content update

sources/packages/web/src/views/aest/student/StudentApplicationExceptions.vue
-  Updated the number to show the **total records** and not the number of records being displayed.
=> #3744 - Bug - Exception Dashboard Count is Incorrect

sources/packages/backend/apps/api/src/services/application-restriction-bypass/application-restriction-bypass.service.ts
Fix for when the student doesn't have any student restrictions in the API.
=> #3691 - UX/UI for Ignore Restriction - API bugfix

sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/_tests_/e2e/application-restriction-bypass.aest.controller.getAvailableRestricitionsToBypass.e2e-spec.ts, sources/packages/backend/apps/api/src/services/application-restriction-bypass/application-restriction-bypass.service.ts
- Added StopPartTimeBCFunding restriction action type to the query that gets the available student restrictions to be bypassed.
=> #3691 - UX/UI for Ignore Restriction - Bypass Add/Remove - Added  "Stop part time BC funding" action type

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-scheduler.ts, sources/packages/backend/package-lock.json, sources/packages/backend/package.json
To proceed with the investigation about the intermittent ioredis issue on DEV, the package was updated and more logs were added to try to narrow down the root cause of the issue.
=> #3667 - Bull Scheduler - Updated ioredis and Added Logs

sources/packages/web/src/views/institution/OfferingsUpload.vue
=> #3187 - Content: Institution: Offerings Upload: Add bullets and links Fixes

sources/packages/backend/apps/api/src/services/student/student.service.ts
- Added conditions to query only applications with an applicationNumber;
- Added order clause,
=> #3981 - Model SDPR API - Query improvement

sources/packages/forms/src/form-definitions/supportingusersdashboard.json
Deploy problem:
- Made button key unique.
=> #3645 - Content: Support Portal: Welcome Page- Formio issue

sources/packages/backend/apps/db-migrations/src/migrations/1734984637510-AddApplicationCancelDateSFASPartTimeApplications.ts, sources/packages/backend/apps/db-migrations/src/sql/SFASPartTimeApplications/Add-application-cancel-date.sql, sources/packages/backend/apps/db-migrations/src/sql/SFASPartTimeApplications/Rollback-add-application-cancel-date.sql
- Migration to add `application_date_column` to `sims.sfas_part_time_applications`
=> #4133 - SFAS to SIMS Bridge - PT App Cancellation Date & MSFAA (FT/PT) Change - Part 1

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/sfaa2025-26.json
- Removed subtitle;
- Changed text to "Documents required:"
- Formatted to bold: "Valid Confirmation of SIN document; and"
=> #4060 - Content: Protected Person Update

sources/packages/backend/apps/db-migrations/src/migrations/1735859368020-AddInstitutionReadOnlyUserType.ts, sources/packages/backend/apps/db-migrations/src/sql/AuthCodeTables/Add-institution-read-only-user-type.sql, sources/packages/backend/apps/db-migrations/src/sql/AuthCodeTables/Rollback-add-institution-read-only-user-type.sql
- Added `read-only-user` to the table `sims.institution_user_type_roles`
Migration revert:
=> #2370 - Institution Read-Only User Type

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/full-time-e-cert-file-handler.ts, sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/part-time-e-cert-file-handler.ts
**As a part of this PR, release v2.3.0 is merged to main. This PR contains the changes that were directly made into the release branch 2.2 and were updated to the release branch 2.3 when the release branch 2.2 was merged to 2.3**
=> #274 - Merge release v2.3.0 to Main Branch

sources/packages/web/src/router/InstitutionRoutes.ts
- Added access to read-only user to institution routes
=> #2370 - Institution Read-Only User Type - PR 3

devops/Makefile, devops/openshift/api-deploy.yml, devops/openshift/load-test-gateway-deploy.yml, devops/openshift/queue-consumers-deploy.yml, devops/openshift/workers-deploy.yml
=> #3685 - Convert to Deployment - Part 2

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/student-application-notifications/_tests_/student-application-notifications.scheduler.e2e-spec.ts
As the final part of the story, this PR has the following changes:
- Added E2E tests for the second disbursement reminder notification.
- Should generate a second disbursement reminder notification for a student when the application is Completed and the second disbursement with Required COE status is still pending when its disbursement date has passed. 
- Should not generate a second disbursement reminder notification for a student when a notification is already sent for the second disbursement still pending.
- Should not generate a second disbursement reminder notification for a student when an application has two disbursements with both COEs completed but the second disbursement is still pending.
=> #3594 - Email to Student - 2nd Disbursement has passed, still pending (Part 3)

sources/packages/backend/apps/db-migrations/src/sql/Applications/Add-application-versioning-columns.sql, sources/packages/backend/apps/db-migrations/src/sql/Applications/Rollback-add-application-versioning-columns.sql
- Added Indexes for the `parent_application_id` and `preceding_application_id` columns.
=> #4247 - Create Application Versioning (Part 2)

sources/packages/web/package-lock.json, sources/packages/web/package.json, sources/packages/web/src/shims-vue.d.ts, sources/packages/web/src/views/student/NoticeOfAssessment.vue, sources/packages/web/tsconfig.json
**Technical**
Updates added to remove non used packages and add `npm run format` as per existing prettier config.
2 files detected with prettier.
=> #3060 - Migrate Vue CLI to Vite Part-2

sources/packages/backend/apps/db-migrations/src/sql/Queue/Add-cas-send-invoices.sql
CAS Send Invoice Scheduler Update to 3AM, 3PM and 12Noon PST.
=> #4330 - CAS Send Invoice Scheduler Update

sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.controller.getApplicationDetails.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.institutions.controller.getApplicationDetails.e2e-spec.ts
- ApplicationAESTController(e2e)-getApplicationDetails
√ Should get the latest student application details when the optional query parameter isParentApplication is set to true.
- ApplicationInstitutionsController(e2e)-getApplicationDetails
√ Should get the latest student application details when the optional query parameter isParentApplication is set to true.
------------------------------------------------------------------------------------------------
=> #4247 - Create Application Versioning (e2e tests)

sources/packages/web/src/components/generic/StatusChipRequestedAssessment.vue, sources/packages/web/src/composables/useAssessment.ts, sources/packages/web/src/types/contracts/ApplicationOfferingChangeRequestStatus.ts
- Corrected the status icon to be outlined in black, with a black circle and text "Change awaiting approval"
- Added item `ChangeAwaitingApproval = "Change awaiting approval"` to enum `ApplicationOfferingChangeRequestStatus`.
Screenshot
=> #3949 - BUG: Ministry and Institution: Change awaiting approval status icon only has a black dot and no words... expecting Change awaiting approval

bcgovpubcode.yml
=> #4433 - Update BC Gov Pub Code yml file

sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2022-2023.bpmn, sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2023-2024.bpmn, sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2024-2025.bpmn, sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2025-2026.bpmn, sources/packages/backend/workflow/src/workflow-definitions/load-assessment-consolidated-data.bpmn, sources/packages/backend/workflow/test/2022-2023/fulltime-assessment/fulltime-assessment.e2e-spec.ts, sources/packages/backend/workflow/test/2023-2024/fulltime-assessment/fulltime-assessment.e2e-spec.ts, sources/packages/backend/workflow/test/2024-2025/fulltime-assessment/fulltime-assessment.e2e-spec.ts, sources/packages/backend/workflow/test/2025-2026/fulltime-assessment/fulltime-assessment.e2e-spec.ts, sources/packages/backend/workflow/test/models/assessment.model.ts, sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/sfaa2025-26.json
- Fixed form variables:
- Fixed/added them in Load assessment consolidated:
- Checked the values in the workflow context:
=> #4362 - FT Application - Values not coming into consolidated data

sources/packages/backend/libs/utilities/src/integration-utils.ts
Fix the PD Status Declined translation to `PDDL` from `PDDC`
=> #4427 - Fix the translation for disability status declined.

sources/packages/web/package-lock.json, sources/packages/web/package.json
=> #3201 - Vue Upgrade

sources/packages/forms/src/form-definitions/noticeofassessment.json
Typo fix: "Canada Student Grant for Persons with Dependants (CSG-FTDEP)"
=> #3961 - NOA Layout: Typo fix

sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.students.controller.getOfferingSummaryDetails.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.controller.service.ts, sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts, sources/packages/web/src/components/common/OfferingView.vue, sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts, sources/packages/web/src/views/institution/locations/programs/LocationPrograms.vue
- Changed the 2 pages to display the friendly version;
- Reviewed the other pages;
- Checked the match between Formio's and DB credential types;
=> #2081 - Update Institution Program Credential Formatting

.github/workflows/release-build-all.yml, devops/openshift/api-deploy.yml, devops/openshift/workers-deploy.yml, sources/packages/backend/apps/api/src/app.module.ts, sources/packages/backend/apps/api/src/route-controllers/health-check/health.controller.spec.ts, sources/packages/backend/apps/api/src/route-controllers/health-check/health.controller.ts
- Updated the health check of API to check for the sims-db database ping.
- The public expose of the health check https://github.com/bcgov/SIMS/blob/dddb903701e8dda6c761ef74a5f8bda328c10d78/sources/packages/backend/apps/api/src/main.ts#L31 is already done, so no changes required in this PR.
=> #2822 - API Readiness Liveliness

sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/cancel-application-assessment.processor.e2e-spec.ts, sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts, sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-workflowWrapUp.e2e-spec.ts, sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
=> #4510 - Cherry Pick from Hotfix - Sequential assessment and PY totals bug fix

sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/sfaa2025-26.json
Fixes missed content to clarify income as gross.
=> #4578 - Update Content - Gross Income

sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.createApplicationOfferingChangeRequest.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.submitApplication.e2e-spec.ts, sources/packages/backend/apps/api/src/utilities/application-utils.ts
- updates content on study period overlap error
- updates e2e
=> #4412 - Update study period overlap content

sources/packages/web/src/views/aest/institution/PendingDesignation.vue
Fixes grammar in pending designation page.
=> #4585 - Update content

sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.createApplicationOfferingChangeRequest.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.submitApplication.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts, sources/packages/backend/apps/api/src/route-controllers/program-info-request/program-info-request.institutions.controller.ts, sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.supporting-users.controller.ts, sources/packages/backend/apps/api/src/services/application/application.service.ts, sources/packages/backend/apps/db-migrations/src/sql/Applications/Add-offering-intensity-column.sql, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sims-to-sfas-integration.scheduler.e2e-spec.ts, sources/packages/backend/libs/integrations/src/services/sfas/sims-to-sfas.service.ts, sources/packages/backend/libs/sims-db/src/entities/application.model.ts, sources/packages/backend/libs/test-utils/src/factories/application.ts, sources/packages/web/src/composables/useApplication.ts
- Removed the `howWillYouBeAttendingTheProgram` from the backend code where it is not needed anymore.
=> #4489 - Formio Changes: Split FT/PT within form - Clean Backend Code 

sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.supporting-users.controller.ts, sources/packages/backend/apps/api/src/services/application/application.service.ts, sources/packages/forms/src/form-definitions/studentrequestchange.json
An error in the SQL query (missing parentheses) was causing the incorrect data to be retrieved.
_Note:_ removed some unnecessary data from the `select` that was no longer required.
- Fixed form.io content duplication due to the known issue of rendering HTML inside a `p` tag. Applied the know fix, replacing the `p` with a `div`.
- Minor content adjustment for the third bullet in the instructions.
=> #4431 - Student View change request revamp - Fix Partner Submission

sources/packages/web/src/views/institution/locations/program-info-request/LocationProgramInfoRequestSummary.vue
=> #3394 - Enable Search & Filter on Institution PIR queue

sources/packages/forms/src/form-definitions/educationprogram.json
- `Education Program` form was updated to include the logic to show the program as `Pending` status when a BC Private Institution selects Online Only as their Program Delivery mode.
**Screenshots:**
=> #4516 - Moratorium on BC Private Programs with Online Program Delivery

sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-loadAssessmentConsolidatedData.e2e-spec.ts, sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/load-assessment-consolidated-data-factory.ts, sources/packages/backend/apps/workers/src/controllers/cra-integration/cra-integration.controller.ts, sources/packages/backend/apps/workers/src/services/cra-income-verification/cra-income-verification.service.ts, sources/packages/backend/apps/workers/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/libs/test-utils/src/factories/cra-income-verification.ts
https://github.com/bcgov/SIMS/commit/b9885924b705e3f0ebde5114f66ee967a8d3f10d
=> #4619 - Cherry pick from Release2.7.1 - Student CRA reported income fix

sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-loadAssessmentConsolidatedData.e2e-spec.ts, sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/load-assessment-consolidated-data-factory.ts, sources/packages/backend/apps/workers/src/controllers/cra-integration/cra-integration.controller.ts, sources/packages/backend/apps/workers/src/services/cra-income-verification/cra-income-verification.service.ts, sources/packages/backend/apps/workers/src/services/student-assessment/student-assessment.service.ts, sources/packages/backend/libs/test-utils/src/factories/cra-income-verification.ts
https://github.com/bcgov/SIMS/commit/6a659a103eeb4e1715d985e20a320a5c66ec42a5
=> #4619 - Cherry pick from main - Student CRA reported income fix

sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/sfaa2025-26.json, sources/packages/web/src/views/institution/designations/ManageDesignations.vue
- Updates to punctuation in student application and institution designation agreement
=> #4631 - Content: Punctuation Updates 

sources/packages/forms/src/form-definitions/studentprofile.json
Minor update to content in create profile.
=> #4244 - Content: Update Create Profile Declaration 

sources/packages/web/src/views/aest/institution/PendingDesignation.vue
Updates title and subtitle on Ministry designation requests page.
=> #3317 - Update designation request page titles

.github/workflows/prune-images.yml
- changes min tags to keep as default
- changes default environment for automated job
=> #4648 - Update Prune GH Action

sources/packages/forms/src/form-definitions/studentprofile.json
- Minor updates to create profile page in alignment with casing standard.
=> #4244 - Update create profile declarations

sources/packages/web/src/components/layouts/aest/AESTHomeSideBar.vue, sources/packages/web/src/views/aest/institution/ViewPendingOfferingChangeRequests.vue
- updates to Ministry account for institution change request titles and content.
=> #3319 - Update content for institution change request

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/parsers/full-time-e-cert-record-parser.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/parsers/part-time-e-cert-record-parser.ts, sources/packages/backend/libs/test-utils/src/factories/application.ts, sources/packages/backend/libs/utilities/src/_tests_/unit/esdc-utils.getMaritalStatusCode.spec.ts, sources/packages/backend/libs/utilities/src/_tests_/unit/esdc-utils.getPartTimeMaritalStatusCode.spec.ts
- Update e-cert E2E tests to validate marital status.
- Added some basic unit tests to validate the outputs of the conversions.
=> #4517 - Bypass partner declaration exception (DV) - E2E/Unit Tests

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json, sources/packages/forms/src/form-definitions/sfaa2025-26-pt.json
=> #4520 - Remove dynamic logic from SFAA2025-26 FT

.github/workflows/release-deploy-all.yml
Possible fix for the below issue.
=> #4690 - Update Deploy-All to use tag gitreference - Added the env to the new job step

sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2024-2025.bpmn, sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts, sources/packages/backend/workflow/test/2024-2025/parttime-assessment/eligibility/parttime-assessment-eligibility-CSGD.e2e-spec.ts
- Cherry pick 2.8.1 hotfix commit into release 2.9
=> #4707 - Cherry Pick to 2.9 

sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2024-2025.bpmn, sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts, sources/packages/backend/workflow/test/2024-2025/parttime-assessment/eligibility/parttime-assessment-eligibility-CSGD.e2e-spec.ts
- cherry pick hotfix 2.8.1 commit to main
=> #4707 - Cherry Pick to main

.github/workflows/release-deploy-all.yml
=> #4715 - Update Deploy-All Workflow

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json, sources/packages/forms/src/form-definitions/sfaa2025-26-pt.json
- fixes link in PT and FT form 
- updates double quotes for consistency
=> #4722 - Fix JSON for SFAA 25/26 Forms 

sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json, sources/packages/forms/src/form-definitions/sfaa2022-23.json, sources/packages/forms/src/form-definitions/sfaa2023-24.json, sources/packages/forms/src/form-definitions/sfaa2024-25.json, sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json, sources/packages/forms/src/form-definitions/sfaa2025-26-pt.json, sources/packages/forms/src/form-definitions/studentfinancialinformationappeal.json, sources/packages/forms/src/form-definitions/supportingusersdashboard.json, sources/packages/web/src/views/aest/institution/OfferingChangeRequests.vue, sources/packages/web/src/views/aest/student/ApplicationChangeRequests.vue, sources/packages/web/src/views/aest/student/StudentApplicationAppeals.vue
Fixes the following findings from content hodge podge review. 
- Removes colon from uploader labels for consistency
- Fixes styling on Transportation header
- Fixes common-law header and adds description on Supporting User dashboard
- Fixes casing on Ministry account - "Change Request" and "Offering Change Request" sub-titles
=> #4579 - Content Hodge Podge

sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2025-2026.bpmn, sources/packages/backend/workflow/test/2025-2026/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
- Made some small changes to the labels on different award eligibility flows
- Updated the flow on the CSGD calculation to choose the correct path based on new eligibility for dependants
- Updated E2E for pt csgd assessment award amounts with new dependant creator
=> #4708 - PT Assessment Fix - Workflow and E2E Tests Updated

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json, sources/packages/forms/src/form-definitions/studentexceptions.json
**Demo Student**
**Demo Ministry**
=> #3870 - Student: FT: Parent Residency Exception 

sources/packages/web/src/assets/css/formio-shared.scss
- fixes style for formio href to remove bottom border
=> #4765 - Fixes styling on formio href

sources/packages/backend/apps/workers/src/controllers/supporting-user/supporting-user.controller.ts, sources/packages/backend/apps/workers/src/controllers/supporting-user/supporting-user.dto.ts, sources/packages/backend/apps/workers/src/zeebe/zeebe-transport-strategy.ts, sources/packages/backend/libs/services/src/workflow/variables/supporting-user-information-request.ts
Create a placeholder for the new worker to fix the issue with the OpenShift health check.
Created a log for Worker initialization
=> #4740 - Parent update first effort - Workers Fix

sources/packages/backend/workflow/src/workflow-definitions/load-assessment-consolidated-data.bpmn, sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
=> #4610 - Room and Board Application Questions

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ece-request/_tests_/ece-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece.processing.service.ts
**Acceptance Criteria Part 1** 
Demo
File Over write:
Overwritten
=> #4664 - PSI Integration Changes - Filename and Folders - Part 1

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
Updates to content on modified independent questions on SFAA25/26 FT, including: 
- Update to header content for description of situation and supporting document uploader. 
- Adds panel for "Which of the following best describes your situation" question.
=> #4842 - Update modified independent content and layout

sims.code-workspace, sources/packages/backend/apps/api/src/app.students.module.ts, sources/packages/backend/apps/api/src/route-controllers/index.ts, sources/packages/backend/apps/api/src/route-controllers/supporting-user/_tests_/e2e/supporting-user.students.controller.getIdentifiableSupportingUser.e2e-spec.ts, sources/packages/backend/apps/api/src/route-controllers/supporting-user/models/supporting-user.dto.ts, sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.students.controller.ts, sources/packages/backend/apps/api/src/services/supporting-user/supporting-user.service.ts
=> #4819 - Student declare parent information - Get supporting user API

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- This PR adds dashes and spacing for the bulleted list.
=> #4850 - Add bullets and spacing to self-contained suite question

devops/helm/crunchy-postgres/values-0c27fb-dev.yaml, devops/helm/crunchy-postgres/values-0c27fb-prod.yaml, devops/helm/crunchy-postgres/values-0c27fb-test.yaml, devops/helm/crunchy-postgres/values-a6ef19-test.yaml, devops/helm/crunchy-postgres/values.yaml
As a part of this PR, updated the s3 bucket name in the values.yaml file.
=> #3732 - Update s3 bucket name

.github/dependabot.yml
Created the configuration to allow Dependabot to create PRs for version updates.
The intention is to have an initial configuration to be tested and improved from here.
_Note:_ The referenced labels were reused when possible, keeping the existing cases.
- [About Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)
- [Configuring Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)
- [Optimizing the creation of pull requests for Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates)
=> #3059 - Software Package Updates (dependabot version-updates)

devops/helm/crunchy-postgres/Chart.yaml, devops/helm/crunchy-postgres/values-a6ef19-test.yaml
As a part of this PR, the postgres version in the staging config file has been updated to 17 and the chart version incremented for semantic versioning.
=> #4884 - Update postgres version in staging config file

devops/helm/crunchy-postgres/values-0c27fb-prod.yaml
**As a part of this PR, the postgres version is updated to version 17 for PROD.**
=> #4884 - Database version update in PROD config file

sources/packages/web/package-lock.json, sources/packages/web/package.json, sources/packages/web/src/components/generic/formio.vue, sources/packages/web/src/router/index.ts, sources/packages/web/src/services/http/common/HttpClient.ts, sources/packages/web/src/types/vuetify.ts, sources/packages/web/vite.config.ts
- Removed packages and test-related packages from the Web App that are not used right now. If they are required, they can be added later.
- Did a change to remove the below warning message. _Note:_ The web app uses only the NODE_ENV and no other env variable was defined in the deployment.
=> #3059 - Software Package Updates (packages cleanup)

sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-full-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-part-time-process-integration.scheduler.e2e-spec.ts, sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-request.processing.service.ts
- PT/FT MSFAA File - Create 0 record file
- Full time MSFAA
---
- Part Time MSFAA
=> #4918 - PT/FT MSFAA File - Create 0 record file

sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2025-2026.bpmn, sources/packages/backend/workflow/test/2025-2026/fulltime-assessment/costs/fulltime-assessment-costs-interface-policy.e2e-spec.ts, sources/packages/backend/workflow/test/models/assessment.model.ts, sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts
- Converted the interface policy path into a "flag" calculated variable to support reporting out to IER/EDW
- Variables to support reporting now it contains:
- `calculatedDataInterfaceEducationCosts`
- `calculatedDataInterfaceChildCareCosts`
- `calculatedDataInterfaceTransportationAmount`
- `calculatedDataInterfaceAdditionalTransportationAmount`
- `calculatedDataInterfaceNeed`
- Test Cases added for Interface Policy being applied:
- Student >$1500 (positive flag)
- Student <$1500 (negative flag)
- Student: nothing declared (negative)
- Married: Student <$1500 + Partner >$1500 (positive)
- Married: Student <$1500 + Partner <$1500 (negative)
=> #4934 - FT Assessment: Interface Policy

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json, sources/packages/forms/src/form-definitions/supportinguserspartner2025-2026.json
- adds tooltips to supporting-user partner and FT25/26 questions regarding partner caring for dependants
=> #4922 - Add tooltips to supporting partner questions 

sources/packages/forms/src/form-definitions/supportingusersdashboard.json
- updates supporting user dashboard to have clear instructions for parents and partners. Previously, the content was directed towards partners.
=> #4802 - Update supporting user dashboard

sources/packages/backend/apps/api/src/route-controllers/student-appeal/_tests_/e2e/student-appeal.aest.controller.getAppeals.e2e-spec.ts
**StudentAppealAESTController(e2e)-getAppeals**
**Technical Details:**
- Creates a program year with start date >= "2025-08-01" to match `AppealType.Appeal` filter criteria
- ✅ *Should return result count as 1 when there is one pending appeal for student application with appeal type 'appeal'*
**Demo:**
=> #4885 - Room and board appeal part 2 (ministry) E2E

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- Created a specific file uploader for permanent residency.
- Adjusted the API keys as
- citizenshipVerificationPermanentResident
- citizenshipVerificationProtectedPerson
- Adjusted the dir names to
- Proof of Citizenship - Permanent resident
- Proof of Citizenship - Protected person
=> #4941 - Approved exception does not repeat - Missing Citizenship Uploader

sources/packages/backend/apps/api/src/route-controllers/student/student.external.controller.ts
Work Done:
- Implemented logging for all API calls to the external `sdpr controller`.
- Captured the student ID (sims_student_id or sfas_individual_id) used in each request.
- Logged the student ID returned in the API response to confirm data retrieval.
=> #4591 - Log Person ID - External API

sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2025-2026.bpmn, sources/packages/backend/workflow/test/2025-2026/fulltime-assessment/costs/fulltime-assessment-costs-living-allowance.e2e-spec.ts, sources/packages/backend/workflow/test/models/assessment.model.ts
- New variable to calculate the MSOL province for both student and dependant paths for MSOL.
- Added conditions to the MSOL calculation for students & dependants to half the value in a specific situation.
=> #5081 - FT Assessment - MSOL for Married Student Spouse FT Student

sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- adds a hidden field to enforce exception validation on modified independent questions if changed
=> #5116 - Fix to compare modified independent questions

sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule-shared.service.ts
See #5125 for more details on the bug fix. 
This is to sync the branch fix on #5125 that was applied to 2.14 branch with main.
=> #5124 - Student debit subtraction bug 

sources/packages/web/src/constants/award-constants.ts
- Updates the display for FT awards in the award summary table.
=> #5220 - Updates Award Summary Display

sources/packages/forms/package-lock.json, sources/packages/load-test/package-lock.json
Audit fixes for forms and load-test packages.
=> #4964 - Upgrade Packages - Audit Fixes

.github/dependabot.yml
Fix the filter used for @formio packages and the invalid Docker configuration.
=> #4964 - Upgrade Packages - Formio filter and Docker
