bcgov/SIMS

- sources/Makefile
- sources/packages/web/package-lock.json
The "make local" was failing with the below error due to the missing POSTGRES_USER env variable.
"no PostgreSQL user name specified in startup packet"
"[TypeOrmModule] Unable to connect to the database. Retrying (4)... +3006ms"
> Added missing POSTGRES_USER env variable to local build.

- sources/packages/api/src/route-controllers/application/application.controller.ts
- sources/packages/api/src/services/form/form.service.ts
- sources/packages/api/src/types/form.ts
- sources/packages/api/src/types/index.ts
Added server validation to formio using "dry run" option during the submission.
As per the below references, the dryrun works as follow: "You can hit any of the submission API's with a special dryrun=1 query parameter. This does both a permission and data validation, but does not execute the actions."
Some references for "dry run" option:
https://github.com/formio/formio/issues/244
https://gitter.im/formio/formio?at=58de963508c00c092a363688
When the validation is successful, the method returns a data object as a result of the formio processing result. For instance, the returned object will take into consideration configurations like the below one.
> [web][api][SIMS #138 ]Added server validation with dry run option from formio

- docs/bceid-webservice-integration.md
- sources/packages/api/package.json
- sources/packages/api/src/app.module.ts
- sources/packages/api/src/route-controllers/user/models/bceid-accounts.dto.ts
- sources/packages/api/src/route-controllers/user/user.controller.ts
- sources/packages/api/src/route-controllers/user/user.e2e-spec.ts
- sources/packages/api/src/services/bceid/bceid.models.ts
- sources/packages/api/src/services/bceid/bceid.service.mock.ts
- sources/packages/api/src/services/bceid/bceid.service.provider.ts
- sources/packages/api/src/services/bceid/bceid.service.ts
- sources/packages/api/src/services/bceid/mockups/getAccountDetails.mock.ts
- sources/packages/api/src/services/bceid/mockups/searchBCeIDAccounts.mock.ts
- sources/packages/api/src/services/bceid/search-bceid.model.ts
- sources/packages/api/src/services/index.ts
- Created SOAP request to retrieve all the BCeID accounts that belong to a particular institution. The implementation is retrieving a maximum of 500 records. With the help of @abschwenker, we were able to check that the max amount of records currently on production is around 270 accounts. So far the decision is to retrieve the first page (500 maximum).
- Create a mocked version of BCeIDService to be used when "DUMMY_BCeID_ACCOUNT_RESPONSE=yes";
- Created mocked files with the full content from BCeID Web Service on "Teams>Files>BCeID Web Service Mockups" to allow the development without the Gov VPN enabled. IMPORTANT: the mocked classes will not be part of the production runtime code.
- Documentation updated
> [api][SIMS #226]Enable Search for BCeID webservices

- devops/openshift/api-deploy.yml
- devops/openshift/web-deploy.yml
1. Increase initial delay
2. Increase Failure threshold
> [devops][SIMS-#227][Hotfix] Increase readiness-probe delay/failure threshold for api deployment

- sources/packages/api/src/route-controllers/institution/institution.controller.ts
- sources/packages/api/src/route-controllers/institution/models/institution-user-auth.dto.ts
- sources/packages/api/src/services/institution/institution.service.ts
- sources/packages/web/src/services/InstitutionService.ts
- sources/packages/web/src/types/contracts/institution/AddInstitutionLocation.ts
- Refactor the add location logic on API to allow the creations of one user with multiple permissions with only one API call.
- Kept the validation logic on the controller and moved the main logic to a service (Institution service for now), but I think that this logic should be in an "institution-user" service. Also, I think that we should consider moving the API methods from the institution controller to a specific controller.
> [web][api][SIMS #227]Adding multiple locations

- sources/packages/web/src/components/generic/formio.vue
While loading data into the Form.IO there was a race condition between the method loading the form definition and the method loading the form data to be displayed. The race condition was already in place but became evident when the form was cache and started to be always ready before the data loading to populate the form.
> Fix Form.IO cached form load data

- sources/packages/web/src/router/StudentRoutes.ts
- sources/packages/web/src/router/index.ts
`meta: {
clientType: ClientIdType.STUDENT,
},` added for student routes and fixed  `https://dev-aest-sims.apps.silver.devops.gov.bc.ca/student` redirecting to institution login.
> [web] [improvement]Basic student route guard added

- sources/packages/api/src-sql/Types/alter-application-status.sql
- sources/packages/api/src-sql/Types/rollback-alter-application-status.sql
- sources/packages/api/src/database/entities/application-status.type.ts
- sources/packages/api/src/database/entities/application-student-file.model.ts
- sources/packages/api/src/database/entities/application.model.ts
- sources/packages/api/src/database/migrations/1629400247363-AddOverwrittenToApplicationStatus.ts
- sources/packages/api/src/route-controllers/application/application.controller.ts
- sources/packages/api/src/route-controllers/application/application.system.controller.e2e-spec.ts
- sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts
- sources/packages/api/src/route-controllers/student/student.controller.spec.ts
- sources/packages/api/src/services/application/application.models.ts
- sources/packages/api/src/services/application/application.service.ts
- sources/packages/api/src/services/atbc/atbc.controller.e2e-spec.ts
- sources/packages/api/src/testHelpers/mocked-providers/jwt-service-mock.ts
- sources/packages/web/src/types/contracts/students/ApplicationContract.ts
- Partial delivery for ticket #532 ;
- No Vue changes included;
- Created the new enum value for application status called "Overwritten";
- Added @RelationId properties to application entity to allow the retrieval of many foreign keys without the need to create a join to satisfy Typeorm requirements. In this way, we can have easy access to foreign keys;
- Create a centralized method to start the application workflow and assign the workflow id to the application. This method is being shared between the submit application method (already existent) and the new one added to COE;
- Create a new API endpoint to:
- Clone the Student Application;
- Delete the current workflow;
- Start a new workflow.
This API endpoint was created as a **POST** because it is creating a new resource and because …
> [api][SIMS #532]Institution User Edits Student Enrolment (CoE)

- sources/packages/web/src/assets/css/formio-shared.css
- `alert` is a common class, because of that  all alerts were hidden, updated CSS only to hide success alert
formio is using bootstrap and it accepts bootstrap class if we want to add bootstrap alter-success class to any form component, it won't work. but we can override it by adding an extra class to show the alert-success or we can create a custom alert-success  equivalent to bootstrap success-alert
> [vue-css][sims-#339] hide only success formio alert, show danger alerts

- sources/packages/api/src/route-controllers/application/application.system.controller.ts
- sources/packages/api/src/route-controllers/application/models/application.system.model.ts
- sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts
- sources/packages/api/src/services/application/application.service.ts
- sources/packages/api/src/services/workflow/workflow-actions.service.ts
#555 
**Tasks**
Application status update to in_progress and workflowId update has been taken care in a single method call, even though there is no business requirement, this creates a sync between the application status update and workflowid population
> [api][SIMS #555]Workflow approach fix's

- sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts
- sources/packages/api/src/route-controllers/program-info-request/program-info-request.controller.ts
- sources/packages/api/src/services/application/application.service.ts
#668 
**Additional Context**
- When a COE or PIR is declined, the workflow in Camunda sits at the message waiting. This ticket is to stop the workflow when a COE or PIR and declined.
- Once a COE or PIR is declined the student will either edit their application and resubmit or cancel it and restart
**Tasks**
> [SIMS #668][API]Workflow for Decline Confirmation of Enrolment (COE) and Program Information Request (PIR)

- sources/packages/forms/src/form-definitions/educationprogram.json
#764 
When creating a program the below field is not being saved to SIMSDB, saving as null
Added the missed hidden field isBCPrivate
The bug was happening, during the dry run submission of the saveEducationProgram call. The isBCPrivate variable which is used to manipulate regulatoryBody field in the conditional logic was not present in the form definition, so after the dry run submission, the value for regulatory body was undefined.
> [SIMS#764][Form]Program Regulatory not saving 

- sources/packages/api/src-sql/ProgramYear/Add-col-program-year-prefix.sql
- sources/packages/api/src-sql/ProgramYear/Drop-col-program-year-prefix.sql
- sources/packages/api/src/database/entities/program-year.model.ts
- sources/packages/api/src/database/migrations/1637263467635-AddColProgramYearPrefixToProgramYear.ts
- sources/packages/api/src/services/application/application.service.ts
> [API][SIMS-#647]PY_Prefix_ApplicationNumber

- sources/packages/api/Dockerfile
- sources/packages/api/Dockerfile.dev
- sources/packages/api/package-lock.json
- sources/packages/api/package.json
- sources/packages/api/src/services/config/config.service.ts
- sources/packages/web/Dockerfile
- sources/packages/web/Dockerfile.dev
- Updated Nodejs from 12 to 16. There were issues while migration from 12 to 16(slim) with some messages related to "missing python" (found [this discussion](https://github.com/nodejs/docker-node/issues/1385) about it also). So the version for DEV was changed to be the same used for Openshift. Please let me know if there is any concern or suggestions about it.
- There were also some issues related to reading the SFTP private key that has line breaks in the configuration ".env" file. This issue should not affect the application once deployed to Openshift because of the way it is being read from the secret file. It was affecting only local dev env while executing the API on docker. Please let me know if there is any concern or suggestions about it.
- Update ssh2 client from 6.0.1 to 7.1.0. …
> [web][api][OpenShift]Update Nodejs to version 16 and ssh2-sftp-client to 7.1.0

- sources/packages/api/src/database/entities/application.model.ts
- sources/packages/api/src/route-controllers/application/application.controller.ts
- sources/packages/api/src/route-controllers/application/models/application.model.ts
- sources/packages/api/src/services/application/application.service.ts
- sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts
- sources/packages/forms/src/form-definitions/noticeofassessment.json
- sources/packages/web/src/services/ApplicationService.ts
- sources/packages/web/src/services/http/ApplicationApi.ts
- sources/packages/web/src/types/contracts/student/ApplicationContract.ts
- Application Query for NOA enhanced with disbursement and the disbursement data is converted to json with dynamic key(s).
- Dynamic keys are to make the data compatible with Award Breakdown in form. 
- The pattern of the dynamic key is disbursement{disbursement no i.e 1|2}{value code eg: csgd} -> disbursement1csgd.
- Camunda updated with all required inputs to for assessment payload. Also the all the amounts are rounded to 2 decimal places.
> [Api][Web][SIMS #822] Populate NOA with all Assessment Values

- sources/packages/api/tsconfig.json
This configuration was changed on the previous PR and it seems that it is impacting the build.
> Reverting typescript target changed on the previous PR

- sources/packages/api/src/esdc-integration/e-cert-full-time-integration/e-cert-files/e-cert-response-record.ts
Updated error code indexes. Index of the first error code is 731, not 641 because `Grant Award Code` and `Grant Award Amount` will be repeated 10 times, which is not mentioned in the doc 'CSLP-AppendixF2AsReviewed2016-FileLayouts BC Files V3(HAJ-CB EDITS) In ESDC Folder'.
> [api][SIMS - #File/sims-#646] Receive BC E-Cert Feedback File - updated error code indexes

- sources/packages/api/src-sql/SFASPartTimeApplications/Create-part-time-sfas-application-records.sql
- sources/packages/api/src-sql/SFASPartTimeApplications/Drop-part-time-sfas-application-records.sql
- sources/packages/api/src/database/constant.ts
- sources/packages/api/src/database/entities/index.ts
- sources/packages/api/src/database/entities/sfas-application.model.ts
- sources/packages/api/src/database/entities/sfas-part-time-application.model.ts
- sources/packages/api/src/database/migrations/1642195310361-CreatePartTimeSAILApplicationRecords.ts
- sources/packages/api/src/services/index.ts
- sources/packages/api/src/services/sfas/sfas-part-time-application.service.ts
- sources/packages/api/src/sfas-integration/sfas-files/sfas-application-record.ts
- sources/packages/api/src/sfas-integration/sfas-files/sfas-part-time-application-record.ts
- sources/packages/api/src/sfas-integration/sfas-integration-processing.service.ts
- sources/packages/api/src/sfas-integration/sfas-integration.models.ts
- sources/packages/api/src/sfas-integration/sfas-integration.module.ts
-  Created table and insert records for SAIL APPLICATION DATA RECORDS
-  since  `substr` is deprecated i have used `substring`
- primary id is varchar because we are saving the application id coming from the file as the primary key and in part-time case its like `2019P40086`
> [Api][Web][SIMS #378] Update SFAS file integration#378

- sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts
I fixed a bug by renaming applicationId to application.id  in updateDisbursementScheduleDocumentNumber function. This was causing a column not found error when I did end to end testing in dev.
> [Api][Web][SIMS#443]Document Number

- sources/packages/api/src/route-controllers/application/models/application.model.ts
- sources/packages/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.controller.ts
API Call to COE Summary using getISODateOnlyString  for disbursement date to ignore timestamp and timezone getting appended.
> Date formatting using getISODateOnlyString  for disbursement list.

- sources/packages/web/src/components/generic/formio.vue
- sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementForm.vue
While executing the association of the hyperlinks with the form.io during the load event, after the form call a redraw due to a binding changing, the association with the hyperlinks was lost.
Exposed the event from form.io called render that will happen after a redraw, allowing us to attach the hyperlink events every time that the hyperlink is recreated due to a redraw.
> [web][SIMS #406]Fix for Designation Agreement Links

- sources/packages/forms/src/form-definitions/sfaa2021-22.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- Relationship status for marriedCommonLaw is renamed to married and otherSingle is renamed to other in all the workflow and the student application forms for the 3 years. This has been done to be in consistent with our code relationshipstatus.
- dependantStatus hidden variable event trigger has been updated to AnyChange to hide and show the partnerInformation tab, which was inconsistent. Also moved to the appropriate screen.
> [SIMS-#900][Forms]Relationship-status rename

- sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/ApplicationDetailsForCOE.vue
I implemented functionality to hide the Application Actions button when CoE is completed or Declined.
I also changed the navigation label to "Confirmation of enrolment".
Fixed a typo.
> [Web][SIMS #397] Remove actions on completed and declined CoE

- sources/packages/web/src/views/aest/institution/DesignationAESTView.vue
- sources/packages/web/src/views/institution/designations/DesignationView.vue
Form.io is not reactively binding the property readOnly. If the readOnly value change after DOM(form) is mounted, form does not respond to it.
Hence, the modelLoaded variable ensures that API is called and data is initialized before form is loaded.
> [Web][SIMS #467] Work around to fix the non-reactive nature of form.io readOnly property.

- sources/packages/api/src/database/entities/application.model.ts
- sources/packages/api/src/route-controllers/application/application.system.controller.ts
- sources/packages/api/src/services/application/application.service.e2e-spec.ts
- sources/packages/api/src/services/application/application.service.ts
- sources/packages/api/src/services/disbursement-schedule-service/disbursement-schedule-service.ts
- sources/packages/api/src/services/msfaa-number/msfaa-number.service.spec.ts
- sources/packages/api/src/services/msfaa-number/msfaa-number.service.ts
- sources/packages/api/src/services/student-assessment/student-assessment.service.ts
- sources/packages/api/src/testHelpers/fake-entities/application-fake.ts
- sources/packages/api/src/testHelpers/fake-entities/index.ts
- sources/packages/api/src/testHelpers/fake-entities/student-assessment-fake.ts
- sources/packages/api/src/utilities/system-configurations-constants.ts
- Reintroduce the missing trigger type that was preventing the application to move to "In Progress" after submission;
- Fixed MSFAA that was still relying on the offering from the _sims.applications_ table;
- Adjusted the MSFAA endpoint removing the offering intensity that is now retrieved from the application itself;
- Fixed the MSFAA query that was not considering the offering intensity type;
- Refactor a typo on the constant MAX_MSFAA_VALID_DAYS.
- Small change is needed (not critical) in the assessment_gateway workflow but it will be part of an upcoming PR.
> [api][SIM #28]Fixes after reassessments changes

- sources/packages/api/src/route-controllers/institution/institution.institutions.controller.ts
- sources/packages/api/src/route-controllers/institution/models/institution-user.dto.ts
getUserFullName() formatting has been added back to API which was missing while doing the re-organize API story.
> [API]Bug - Re-organizeAPI

- sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/api/src/esdc-integration/msfaa-integration/msfaa-integration.service.ts
- sources/packages/api/src/utilities/system-configurations-constants.ts
> [Bug][SIMS-#1184]Bugs in MSFAA and ECert Receive and File generation

- sources/packages/api/src/auth/auth.module.ts
- sources/packages/api/src/auth/decorators/index.ts
- sources/packages/api/src/auth/decorators/requires-student-account.decorator.ts
- sources/packages/api/src/auth/guards/authorized-parties.guard.ts
- sources/packages/api/src/auth/guards/index.ts
- sources/packages/api/src/auth/guards/requires-student-account.guard.ts
- sources/packages/api/src/auth/identity-providers.enum.ts
- sources/packages/api/src/auth/jwt.strategy.ts
- sources/packages/api/src/auth/userToken.interface.ts
- sources/packages/api/src/route-controllers/application/application.students.controller.ts
- sources/packages/api/src/route-controllers/assessment/assessment.students.controller.ts
- sources/packages/api/src/route-controllers/institution-locations/institution-location.students.controller.ts
- sources/packages/api/src/route-controllers/program-year/program-year.controller.ts
- sources/packages/api/src/route-controllers/student-appeal/student-appeal.students.controller.ts
- sources/packages/api/src/route-controllers/student/student.students.controller.ts
- sources/packages/api/src/services/student-assessment/student-assessment.service.ts
- sources/packages/api/src/services/user/user.model.ts
- sources/packages/api/src/services/user/user.service.ts
- sources/packages/api/src/utilities/system-configurations-constants.ts
- Created a new user (when not already created) for the `forms-flow-bpm` that will allow saving the audit user also during workflow operations on the SIMS API.
- Added validation for the IDP used for authorization based on the authorized party. It will basically enforce that a user logged in to the Institution was authenticated using BCeID, a student was authenticated using BCSC, and so on. **THE SAME VALIDATION ALREADY EXISTS ON THE VUE APPLICATION BUT IS WAS MISSING ON THE API.**
- Created a new decorator `@RequiresStudentAccount()` that will ensure that there is a student account created and associated with the current user. The decorator can also be used as `@RequiresStudentAccount(false)` in methods that the student must access but the student account is not created yet, for …
> [api][SIMS #612]New decorator and new service account user

- sources/packages/api/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-files/e-cert-file-record.ts
- provinceState and postalCode as nullable as per e-Cert file requirements.
> [api][SIMS #1205]provinceState/postalCode optionals

- sources/packages/web/src/components/generic/Banner.vue
- Removed div with left padding css class that was causing UI defect on the button in the banner.
- Removed redundant css float-left class from summary in the banner.
Screen shot of what the defect is.
Screen shot of output after fixing defect.
> [Api][Web][sims-#1156] institution edits program bug fix

- sources/packages/api/src/route-controllers/student/models/student.dto.ts
- sources/packages/api/src/route-controllers/student/student.aest.controller.ts
- sources/packages/api/src/route-controllers/student/student.students.controller.ts
- sources/packages/api/src/services/restriction/student-restriction.service.ts
- sources/packages/web/src/services/StudentService.ts
- sources/packages/web/src/services/http/StudentApi.ts
- sources/packages/web/src/services/http/dto/Student.dto.ts
- sources/packages/web/src/types/contracts/StudentContract.ts
- sources/packages/web/src/views/aest/student/StudentDetails.vue
1. Fixed - When the ministry user views a student, the restriction badge was not working properly
2. Fixed - The new restriction API was retrieving all active and nonactive restriction
> [vue][api][SIMS #948] Student Restriction update - AEST Student badge fix

- sources/packages/api/src/database/entities/student-scholastic-standing.model.ts
Remove unused fields (approvedData, assessedDate, assessedBy) from Student Scholastic Standing Model. These fields were causing error when I tried to test report a change functionality.
> [api][SIMS #1200]End application (Soft Archive)

- sources/packages/workflow/BPMN/disbursement-schedule-gateway.bpmn
- sources/packages/workflow/BPMN/ft-disbursement-calculation.bpmn
- sources/packages/workflow/BPMN/pt-disbursement-calculation.bpmn
While executing the workflow there were some errors like below when a JavaScript object was assigned to a Camunda variable.
The error was usually intermittent and even sometimes was resolved just by restarting the Openshift POD (what is not ideal).
The solution was to serialize the object to JSON and parse it back where it is consumed.
The workflow was tested for Full-time and Part-time and both worked as expected.
> [workflow][SIMS #1007]Using JSON.stringify to pass set variables

- sources/packages/api/src/route-controllers/institution/institution.institutions.controller.ts
- The API endpoint to get the application details was restricted only for admin users but it is also needed during the login process for non-admin-users which leads to a wrong _Forbidden User_ error.
> [api]Removed IsInstitutionAdmin decorator

- sources/packages/web/package-lock.json
- sources/packages/web/package.json
- sources/packages/web/src/assets/css/base.scss
- sources/packages/web/src/assets/css/global-style-variables.scss
- sources/packages/web/src/assets/css/vuetify.scss
- sources/packages/web/src/components/generic/StatusChip.vue
- sources/packages/web/src/components/layouts/Institution/sidebar/HomeSideBar.vue
- sources/packages/web/src/components/layouts/Institution/sidebar/ManageInstitutionSideBar.vue
- sources/packages/web/src/components/layouts/aest/AESTApplicationSideBar.vue
- sources/packages/web/src/components/layouts/aest/AESTHomeSideBar.vue
- sources/packages/web/src/plugins/vuetify.ts
- sources/packages/web/src/views/aest/AppAEST.vue
- sources/packages/web/src/views/aest/Login.vue
- sources/packages/web/src/views/institution/Login.vue
- sources/packages/web/src/views/student/Login.vue
- Changed icon library to use mdi (Material Design Icons) as default to cause less impact during the transition to use `v-icon` that now supports Font Awesome and Material Design Icons.
- StatuChip component changed to stop using `v-badge` and use `v-chip`.
- Login pages adjusted.
- Left menus adjusted to use the properties instead of the contents
Before
After
- Buttons have now the `prepend-icon` working, so we can use the property instead of setting the icon using the v-icon. Please notice also that the below icons are set using the Font Awesome `fa:` prefix.
- There is a known issue with the alerts that cause the font to be different as shown below.
The above issue affects the alerts when the body text is not defined between a span, like the below one that is working as expected.
Since …
> [vuetify]Upgrade beta 4

- sources/packages/api/src/app.institutions.module.ts
- sources/packages/api/src/app.module.ts
- sources/packages/api/src/constants/error-code.constants.ts
- sources/packages/api/src/route-controllers/application/models/application.model.ts
- sources/packages/api/src/route-controllers/index.ts
- sources/packages/api/src/route-controllers/program-info-request/models/program-info-request.dto.ts
- sources/packages/api/src/route-controllers/program-info-request/program-info-request.institutions.controller.ts
- sources/packages/api/src/services/application/application.service.ts
- sources/packages/web/src/services/ProgramInfoRequestService.ts
- sources/packages/web/src/services/http/ProgramInfoRequestApi.ts
- sources/packages/web/src/services/http/dto/ProgramInfoRequest.dto.ts
- sources/packages/web/src/services/http/dto/index.ts
- sources/packages/web/src/types/contracts/institution/EducationProgramOfferingDto.ts
- sources/packages/web/src/types/contracts/institution/ProgramInfoRequest.ts
- sources/packages/web/src/views/institution/locations/program-info-request/LocationEditProgramInfoRequest.vue
- sources/packages/web/src/views/institution/locations/program-info-request/LocationProgramInfoRequestSummary.vue
- Program information request related methods moved to a specific institution client controller.
- Changed PIR get data to rely always on the original assessment instead of the current assessment to ensure that every time that the PIR UI is shown the data will be coming from the original assessment record.
> [web][api][SIMS #1300]PIR moved to institutions API client

- sources/packages/api/src/route-controllers/institution-user/institution-user.aest.controller.ts
- sources/packages/api/src/route-controllers/institution-user/institution-user.controller.service.ts
- sources/packages/api/src/route-controllers/institution-user/institution-user.institutions.controller.ts
Fix the authorization to prevent a basic BCeID user to create a basic BCeID user under the institution.
The UI is hiding the option but the API would accept the request if called directly.
> [api][SIMS #1353]Basic BCeID Institution Authorization

- sources/packages/api/src/main.ts
- sources/packages/api/src/utilities/system-configurations-constants.ts
Defined a variable to allow cors request based on environment variable NODE_ENV.
> [API][SIMS #419] - Restrict CORS on all non-local-development environment

- sources/packages/api/src/services/education-program-offering/education-program-offering-import-csv.service.ts
- sources/packages/api/src/services/education-program-offering/education-program-offering-validation.models.ts
- sources/packages/api/src/utilities/class-validation/custom-validators/is-date-after.ts
- sources/packages/api/src/utilities/class-validation/custom-validators/period-max-length.ts
- sources/packages/api/src/utilities/class-validation/custom-validators/period-min-length.ts
- sources/packages/api/src/utilities/class-validation/custom-validators/periods-are-between-limits.ts
- sources/packages/api/src/utilities/class-validation/index.ts
- sources/packages/api/src/utilities/date-utils.ts
Fixes for offering bulk upload validation.
- A new validator was created to generate an error when the end date is not greater than the start state. It was not possible to reuse the period validation.
- Avoid creating study breaks when the property "has study breaks" is not set as `yes`.
- Changed the date format displayed to the user in the validation messages.
> [api][SIMS #1341]Validation fixes.

- sources/packages/web/src/components/common/AssessmentAwardDetails.vue
- sources/packages/web/src/components/generic/TooltipIcon.vue
> [Web][UI Fix]Align tooltip icons to start slightly over the text

- sources/packages/web/src/views/institution/Login.vue
1. Updated content for institution login
2. Updated error messages - note one of the error message has not been updated as it is flagged for removal (future ticket)
3. Removed columns in card
4. Removed custom style
[Figma reference](https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=3651%3A95326)
> [UX][Web][SIMS #1450] UI Content for Institution - Login

- sources/packages/backend/apps/workers/src/controllers/cra-integration/cra-integration.dto.ts
- sources/packages/backend/apps/workers/src/controllers/program-info-request/program-info-request.controller.ts
- sources/packages/backend/apps/workers/src/controllers/program-info-request/program-info-request.dto.ts
- sources/packages/backend/libs/services/src/workflow/variables/assessment-gateway.ts
- sources/packages/backend/libs/services/src/workflow/variables/cra-integration-income-verification.ts
- sources/packages/workflow/BPMN/camunda-8/assessment-gateway.bpmn
- sources/packages/workflow/BPMN/camunda-8/load-assessment-consolidated-data.bpmn
- Renamed variables in the `load-assessment-consolidated-data` that also affects the `assessment-gateway` and the workers.
- The motivation was to bring more clarity on the source of the variable, for instance, the "Student Dynamic Data" has many variables that are also part of the workflow. When looking at the BPMN they are more "grouped", as shown below.
> [workflow][SIMS #577]Variables renaming

- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.institutions.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.models.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.service.ts
- sources/packages/backend/apps/api/src/utilities/class-validation/custom-validators/period-max-length.ts
- sources/packages/forms/src/form-definitions/educationprogramoffering.json
- sources/packages/web/src/components/common/OfferingFormSubmit.vue
- sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts
- sources/packages/web/src/views/institution/OfferingsUpload.vue
- sources/packages/web/src/views/institution/locations/offerings/OfferingEdit.vue
- sources/packages/web/src/views/institution/locations/offerings/OfferingRequestChange.vue
- Converted the 10% warning message to an information banner only that will no longer make the offering to be pending.
- Executing the validations on the server during the "on change" of specific form.io components marked with the tag "execute-validation" or "execute-calculation".
- The calculation happen always that one component tagged with "execute-calculation" changed.
- The validation "on change" started to happen only the first manual validation is triggered and for components marked with the tag "execute-validation".
- Added info also to the bulk upload.
> [form][web][api][SIMS #1499]Convert 10% warning to info

- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.models.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/forms/src/form-definitions/educationprogramoffering.json
- sources/packages/web/src/components/common/OfferingFormSubmit.vue
- Converted the 21 days waning banner to info banner.
- Allow the info banners to be displayed even when the validation was not triggered yet.
> [web][api][SIMS #1546]Changed warning to info

- sources/packages/web/src/components/generic/Banner.vue
- Fixed overlapping button on text
- Changed col to accommodate longer button text
- Checked UI for other banners (e.g. restrictions and CRA)
- [Figma mockups (for reference only)](https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=3651%3A95172)
Larger resolution
Smaller resolution
Without button
> [UX][Web][SIMS #1451] UI Content for Institution - Profile page (banner fix)

- .github/workflows/deploy-all.yml
- .github/workflows/deploy-camunda-definitions.yml
- sources/packages/workflow/src/deploy.models.ts
- sources/packages/workflow/src/deploy.ts
- Camunda deployment changed to support also DMNs deployment.
- Removed `Camunda Folder` input from GitHub actions (it was not actually being used).
The method `deployProcess` is deprecated and the recommended method `deployResource` supports BPMN and DMN deployments, as per[ Zeebe documentation](https://github.com/camunda-community-hub/zeebe-client-node-js#deploy-process-models-and-decision-tables).
Please note that the new method `deployResource` supports BPMN/DMN but the method has different overloads that produce different outputs. This causes additional changes to the code and BPMN/DMN are handled in different ways.
Log summary including DMNs.
> [workflow][CI/CD][SIMS #577]Deploy DMNs

- sources/packages/backend/apps/api/src/services/student/student.service.ts
- sources/packages/backend/apps/workers/src/utilities/jsonpath/jsonpath-utils.ts
- Changed worker filter object to ensure that when a value is `undefined` it will be converted to `null` to allow the variable to always be created on Camunda.
- Found an issue in the Student User Sync that would prevent the Student to see the top menu navigation and also from having his data revalidated when his name or DOB is changed on BCSC.
> [workers][api][SIMS #577]Workers ad Student Login Sync Fixes

- sources/packages/backend/apps/api/src-sql/federal-restrictions/Bulk-insert-new-restrictions.sql
- sources/packages/backend/apps/api/src-sql/federal-restrictions/Bulk-update-students-foreign-key.sql
- sources/packages/backend/apps/api/src/app.system-access.module.ts
- sources/packages/backend/apps/api/src/auth/auth.module.ts
- sources/packages/backend/apps/api/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt-integration.module.ts
- sources/packages/backend/apps/api/src/esdc-integration/e-cert-integration/e-cert-integration.module.ts
- sources/packages/backend/apps/api/src/esdc-integration/fed-restriction-integration/fed-restriction-integration.module.ts
- sources/packages/backend/apps/api/src/esdc-integration/fed-restriction-integration/fed-restriction-processing.service.ts
- sources/packages/backend/apps/api/src/route-controllers/esdc-integration/fed-restrictions-integration.system-access.controller.ts
- sources/packages/backend/apps/api/src/services/notification/gc-notify-actions.service.ts
- sources/packages/backend/apps/api/src/services/notification/gc-notify.model.ts
- sources/packages/backend/apps/api/src/services/notification/notification.model.ts
- sources/packages/backend/apps/api/src/services/notification/notification.service.ts
- sources/packages/backend/apps/api/src/services/restriction/federal-restriction.service.ts
- sources/packages/backend/apps/api/src/services/restriction/models/federal-restriction.model.ts
- sources/packages/backend/apps/api/src/services/restriction/restriction.service.ts
- sources/packages/backend/apps/api/src/services/restriction/student-restriction.service.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts
- sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1668746601780-InsertStudentRestrictionMessage.ts
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Delete-student-restriction-message.sql
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Insert-student-restriction-message.sql
- sources/packages/backend/libs/sims-db/src/entities/notification.model.ts
- Changed the federal restrictions insert script to return the inserted IDs to be used to generate the notifications to students;
- Fixed an error in the federal restrictions queries that were not considering the SIN change from the `students` table to the `sin_vallidations` table.
- Created a unified method to get the student data needed to send the notification and create the notifications.
Todo
- Add transactions to the existing notifications;
- Move notifications to the shared library.
- Sonarcloud issues mostly about a method to be removed in the upcoming PR.
> [api][SIMS #1453]Notifications for Student Restrictions - Part 1

- sources/packages/backend/libs/services/src/notifications/notification/notification.service.ts
The date_sent column was not updated after the notifications were changed to be created in a DB transaction.
> [API][SIMS #1453]Notifications - date sent not saved

- devops/openshift/queue-consumers-deploy.yml
Removing readiness and liveness probe for queue consumers as it does not have a non-authenticated end point to respond.
> [Devops] Removing readiness and liveness probe for queue consumers

- sources/packages/backend/libs/services/src/system-users/index.ts
- Circular dependency fix caused by the wrong index.tx export order.
> [wrokers][SIMS $1346]Circular dependency fix

- sources/packages/web/src/components/common/IdleTimeChecker.vue
- sources/packages/web/src/components/common/modals/ConfirmExtendTime.vue
- sources/packages/web/src/composables/useAuth.ts
- sources/packages/web/src/composables/useModalDialog.ts
- sources/packages/web/src/constants/system-constants.ts
If the computer hibernates or the tab/window is inactive, the setInterval does not work but when it gets back to "active" state it should count the time the user session is idle and then:
- if it is already expired, logout;
- it is not expired but there's less than COUNT_DOWN_TIMER_FOR_LOGOUT (in seconds) left, it should show the correct seconds that are left in the modal;
- otherwise the timer should count the same time independent when it got in the active state.
Also, every tab should check if the user extended their time or if they logged out. 
Some of the main changes:
- removed logic from modal; 
- created logic to use the right remaining time in IdleTimeChecker.vue; 
- logout when the other tab has logged out; 
- close modal when requested more time in other tab/window; 
- shared …
> [web][SIMS #990] Logout timer bug

- sources/Makefile
Added shortcuts to connect to Openshif Patroni DEV/TEST/QA databases.
> Openshift Patroni Shortcuts for Local DEV Environment

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/tests/ecert-full-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/disbursement/tests/disbursement.controller.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt-files/disbursement-receipt-file-detail.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt-files/disbursement-receipt-file-record.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-receipt/disbursement-receipt.model.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts
- sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule.service.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-overaward.model.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-receipt-values.model.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-receipts.model.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-values.model.ts
- sources/packages/backend/libs/sims-db/src/transformers/numeric.transformer.ts
- sources/packages/backend/libs/test-utils/src/factories/disbursement-overaward.ts
- sources/packages/backend/libs/test-utils/src/factories/disbursement-value.ts
- sources/packages/backend/libs/utilities/src/disbursements-utils.ts
Changed the DB entity models mapped to "numeric" and typed as `string` to `number` with a Typeorm transformer.
Dealing with all the numbers mapped as `string` was proving to be more error-prone and they were causing the code to be more complex than needed.
> #1346 - Converted DB numeric string to number

- sources/packages/backend/apps/api/src/route-controllers/student-account-applications/student-account-application.students.controller.ts
- sources/packages/backend/apps/api/src/services/student-account-applications/student-account-applications.service.ts
TypeOrm has a [bug](https://github.com/typeorm/typeorm/issues/9316) that returns a record when the param is `null` or `undefined`! 😲 
The issue happened because userId is `undefined` in `studentUserToken` in the request to check if the student has pending account application.  Then used `userName` instead of `userId`.
> #1649 - Request Basic BCeID account creation limited to one at a time

- sources/packages/backend/package-lock.json
Resolved the dependency which the @nestjs/mapped-types version that did not update, once they implement the class-validator in their version, the package-lock will be updated automatically.
FYI: Similar reference of error in build in Stackoverflow
https://stackoverflow.com/questions/75139457/error-or-breaking-changes-in-nest-class-validator0-13-2
> #1666-Dependabot dependency error

- sources/packages/forms/Dockerfile
As forms image was deleted and the formio was not supporting the latest version of node artifactory, changed the supported version of node and build the dockerfile.
> Formio dockerfile update

- .github/workflows/tests.yml
- sources/packages/backend/apps/api/test/auth.e2e-spec.ts
When GitHub `dependabot` is creating the PR it does not have access to the env and an error happens "Error: Resource not accessible by integration". For instance: https://github.com/bcgov/SIMS/actions/runs/4130521677/jobs/7137296569
Using the closed ticket #1693 for reference only.
This workflow is executed during pull requests triggered by a user or by the GitHub `dependabot`.
When created by the `dependabot` the access to the env variables is restricted, please see https://github.com/dependabot/dependabot-core/issues/3253 and
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
To allow access to the secrets in both cases, the test users' passwords (or any other secret) are defined at the repository
level and also at the …
> #1693 - Removing env from tests workflow

- sources/packages/backend/apps/api/src/route-controllers/overaward/models/overaward.dto.ts
- sources/packages/backend/libs/services/src/disbursement-overaward/disbursement-overaward.service.ts
- sources/packages/web/src/components/aest/students/modals/AddManualOverawardDeduction.vue
- sources/packages/web/src/components/common/AwardTable.vue
- sources/packages/web/src/components/common/OverawardDetails.vue
- sources/packages/web/src/components/common/StudentOverawardDetails.vue
- sources/packages/web/src/components/generic/TitleValue.vue
- sources/packages/web/src/composables/useFormatters.ts
- sources/packages/web/src/constants/award-constants.ts
- sources/packages/web/src/constants/routes/RouteConstants.ts
- sources/packages/web/src/constants/system-constants.ts
- sources/packages/web/src/router/AESTRoutes.ts
- sources/packages/web/src/types/AppRoutes.ts
- sources/packages/web/src/types/contracts/aest/roles.ts
- sources/packages/web/src/views/aest/student/Overawards.vue
- sources/packages/web/src/views/aest/student/StudentDetails.vue
> #1692 - Ministry overaward part 2

- sources/packages/web/src/components/aest/students/modals/AddManualOverawardDeduction.vue
- sources/packages/web/src/components/common/OverawardDetails.vue
- sources/packages/web/src/constants/award-constants.ts
> #1692 - UI label fix and Ordering awards in Federal and BC order

- sources/packages/backend/apps/api/src/route-controllers/models/pagination.dto.ts
- sources/packages/backend/apps/api/src/services/education-program/education-program.service.ts
- sources/packages/web/package-lock.json
- sources/packages/web/package.json
- sources/packages/web/src/assets/css/base.scss
- sources/packages/web/src/helpers/helpers/uri.ts
- sources/packages/web/src/plugins/vuetify.ts
- sources/packages/web/src/services/http/EducationProgramApi.ts
- sources/packages/web/src/types/contracts/DataTableContract.ts
- sources/packages/web/src/views/institution/locations/programs/LocationPrograms.vue
- Upgrade Vuetify to 3.1.5.
- Imported `VDataTableServer` from "vuetify/labs/VDataTable".
- Replaced Location program datatate with <v-data-table-server
- Implemented <v-data-table-server default sort and pagination
- Search feature is not in the <v-data-table-server 
- There was a bug in the existing API, for page 0, it was returning the entire values,- fixed
> #1730 Upgrade Vuetify to Release Version#1730

- sources/packages/backend/apps/api/src/services/disbursement-schedule/_tests_/unit/disbursement-schedule.getCOEApprovalPeriodStatus.spec.ts
- sources/packages/backend/apps/api/src/services/disbursement-schedule/_tests_/unit/disbursement-schedule.getMaxTuitionRemittance.spec.ts
- Added unit test for the method `getCOEApprovalPeriodStatus`. 
-  DisbursementScheduleService-getCOEApprovalPeriodStatus - Tests covered
✓ Should throw an error when the disbursement date is undefined. (16 ms)
✓ Should throw an error when both the disbursement date and study end date are undefined. (1 ms)
✓ Should return "Within approval period" when enrolment now is the first day of (within) the allowed approval period. (4 ms)
✓ Should return "Within approval period" when enrolment now is the last day of (within) the allowed approval period. (2 ms)
✓ Should return "Before approval period" when enrolment now is before the eligible approval period. (3 ms)
✓ Should return "After approval period" when enrolment now is after the eligible approval period. (1 ms)
> #1726 - E2E/Units Tests - Add Units Tests to Helpers (COEApprovalPeriodStatus)

- sources/packages/backend/apps/db-migrations/src/migrations/1677801820875-AddManualOverawardNoteIdToDisbursementOverawards.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1677801820875-AddNoteIdAddedByAddedDateToDisbursementOverawards.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1677805984987-AddNoteTypeOveraward.ts
- sources/packages/backend/apps/db-migrations/src/sql/DisbursementOverawards/Add-note-id-added-by-added-date.sql
- sources/packages/backend/apps/db-migrations/src/sql/DisbursementOverawards/Remove-note-id-added-by-added-date.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Add-note-type-overaward.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Drop-note-type-overaward.sql
- DB changes for the ticket #1753:
- added note_id, added_by and added_date to sims. disbursement_overawards table.
> #1753 - Add student notes during add manual overaward deduction - part 1

- sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts
- sources/packages/backend/apps/api/src/services/student-appeal/student-appeal.service.ts
- sources/packages/backend/libs/sims-db/src/entities/student-appeal.model.ts
- sources/packages/web/src/components/common/notes/Notes.vue
- sources/packages/web/src/components/students/applicationTracker/ApplicationProgressBar.vue
- sources/packages/web/src/components/students/applicationTracker/Completed.vue
- sources/packages/web/src/components/students/applicationTracker/Enrolment.vue
- sources/packages/web/src/services/ApplicationService.ts
- sources/packages/web/src/services/http/ApplicationApi.ts
- sources/packages/web/src/services/http/dto/Application.dto.ts
- sources/packages/web/src/types/contracts/NoteContract.ts
- Renamed `ApplicationCOEDetailsAPIOutDTO` (and related) to EnrolmentApplicationDetailsAPIOutDTO. This is an attempt to leave "In Progress", "Enrolment" and "Completed" statuses more aligned, respectively using `InProgressApplicationDetailsAPIOutDTO`, `EnrolmentApplicationDetailsAPIOutDTO`, and `CompletedApplicationDetailsAPIOutDTO`.
- Student appeal assessment record was not updated on the application `current_assessment_id`.
- COE records were displayed multiple times when the application had multiple assessments associated.
- COE confirmation sometimes failed when the application had multiple assessments associated.
- Added missing note categories to filters and adjusted timeline "bullets" alignment.
- New cards for scholastic standing.
- E2E tests
> #1683 - Application Completed Status - Progress Tracker (Part 1 of 2)

- sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/models/student-scholastic-standings.dto.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/constants.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.model.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts
- sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1678757112924-CreateStudentScholasticStandingChangeTypes.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1678757977330-AddStudentScholasticStandingChangeTypeColumn.ts
- sources/packages/backend/apps/db-migrations/src/sql/StudentScholasticStandings/Add-change-type.sql
- sources/packages/backend/apps/db-migrations/src/sql/StudentScholasticStandings/Remove-change-type.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Create-student-scholastic-standing-change-types.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Drop-student-scholastic-standing-change-types.sql
- sources/packages/backend/libs/sims-db/src/entities/application.model.ts
- sources/packages/backend/libs/sims-db/src/entities/index.ts
- sources/packages/backend/libs/sims-db/src/entities/student-scholastic-standing.model.ts
- sources/packages/backend/libs/sims-db/src/entities/student-scholastic-standing.type.ts
- sources/packages/forms/src/form-definitions/reportscholasticstandingchange.json
- sources/packages/web/src/components/students/applicationTracker/ApplicationProgressBar.vue
- sources/packages/web/src/components/students/applicationTracker/Completed.vue
- sources/packages/web/src/services/http/dto/Application.dto.ts
- sources/packages/web/src/types/contracts/StudentScholasticStanding.ts
- sources/packages/web/src/types/index.ts
- Extracted the scholastic standing change type from the dynamic data and persisted as a separate column using a DB enum.
- Created an error card to display the scholastic standing as an error when the change type is `Student did not complete program`.
_Right now there is no further information about what must happen with the disbursement/COE cards nor what should actually happen with the assessment. `Student did not complete program` is the only scholastic standing change type that does not generates a new student assessment._
> #1683 - Application Tracker Scholastic Change (Part 2)

- sources/packages/web/src/components/common/InstitutionUserSummary.vue
- sources/packages/web/src/components/common/LocationSummary.vue
- sources/packages/web/src/views/aest/institution/Designation.vue
- sources/packages/web/src/views/aest/institution/InstitutionNotes.vue
- sources/packages/web/src/views/aest/institution/Locations.vue
- sources/packages/web/src/views/aest/institution/Profile.vue
- sources/packages/web/src/views/aest/institution/Programs.vue
- sources/packages/web/src/views/aest/institution/Restrictions.vue
- sources/packages/web/src/views/aest/institution/Users.vue
Used the common containers `TabContainer` and the `BodyHeaderContainer` for the institution tabs in the ministry portal. This ensures that there is no jumping effect when the ministry user clicks from one tab to the other ensuring a smooth UI transition. 
Below are the screenshots for the change:
Profile:
Programs:
Locations:
Users:
Designations:
Restrictions:
Notes:
I updated the styling in the `LocationSummary` component. This also affected the below view in the institution portal for the better. It basically fixed the left alignment of the Locations table with the Heading.
> #1757 - Create common container for content in tab (Institution) - Part 2

- sources/packages/forms/src/form-definitions/institutionlocation.json
- sources/packages/web/src/assets/css/base.scss
- sources/packages/web/src/assets/css/formio-shared.scss
- sources/packages/web/src/assets/css/vuetify.scss
- sources/packages/web/src/components/common/LocationSummary.vue
- sources/packages/web/src/views/institution/EditInstitutionLocation.vue
- Updated content on location form and summary
- Added banner on location edit
- Aligned tooltips styles
Forms.io tooltips
Forms.io tooltips - custom (within content like NOA)
Vuetify tooltips
> #1737 - Update institution location content (new)

- sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/web/src/components/students/applicationTracker/ApplicationProgressBar.vue
- sources/packages/web/src/components/students/applicationTracker/MultipleDisbursementBanner.vue
- sources/packages/web/src/services/http/dto/Application.dto.ts
The success icon was not displayed for a reassessment because the check relied on the COE confirmation.
Change the check to be based on the application status.
> #1683 - Show success icon when application is completed

- .github/workflows/tests.yml
Ignore the test coverage when the pull requests are initiated by the dependabot.
> #1806 - Ignoring test coverage for dependabot

- sources/packages/backend/libs/test-utils/src/models/common.model.ts
- sources/packages/backend/workflow/BPMN/camunda-8/assessment-gateway.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/load-assessment-consolidated-data.bpmn
- sources/packages/backend/workflow/test/2022-2023/assessment-gateway/assessment-gateway.originalAssessment.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/assessment-gateway/assessment-gateway.studentAppeal.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/assessment-gateway/assessment-gateway.originalAssessment.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/assessment-gateway/assessment-gateway.studentAppeal.e2e-spec.ts
- sources/packages/backend/workflow/test/test-utils/constants/mock-constants.ts
- sources/packages/backend/workflow/test/test-utils/constants/workflow-variables-constants.ts
- sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts
- sources/packages/backend/workflow/test/test-utils/mock/assessment-gateway/create-supporting-users-parents-task-mock.ts
- sources/packages/backend/workflow/test/test-utils/mock/assessment-gateway/load-assessment-consolidated-data-mock.ts
- sources/packages/backend/workflow/test/test-utils/mock/assessment-gateway/verify-application-exceptions-task-mock.ts
- sources/packages/backend/workflow/test/test-utils/mock/cra-integration-income-verification/check-income-request-task-mock.ts
- sources/packages/backend/workflow/test/test-utils/mock/cra-integration-income-verification/create-income-request-task-mock.ts
- sources/packages/backend/workflow/test/test-utils/mock/mock.utils.ts
- sources/packages/backend/workflow/test/test-utils/mock/supporting-user-information-request/check-supporting-user-response-task-mock.ts
- sources/packages/backend/workflow/test/test-utils/mock/zeebe-worker-mock.ts
- sources/packages/backend/workflow/test/test-utils/validation/workflow-validation.utils.ts
The service task ids are now the root of the mocked objects. When the same service task id exists for multiple subprocesses, these subprocesses are added as a child of the root service task id object. In the below sample, `create_supporting_users_for_parents_task` is not invoked by any subprocess, so the mocked objects for `result` and `messageResult` are direct properties of the root service task id. On the other hand, `create_income_request_task` is invoked by multiple subprocesses, and `result` and `messageResult` are associated with each one of them.
The `load-assessment-data-?` subprocess, which is potentially invoked twice, is now treated as a regular subprocess where we should provide mocked data for both subprocesses (the same data can be provided twice).
Please that some `null` …
> #1834 - Hierarchical mocks for workflow E2E tests

- sources/packages/backend/apps/api/src/app.supporting-users.module.ts
- sources/packages/backend/apps/api/src/constants/error-code.constants.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.institutions.controller.searchStudents.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.institutions.controller.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/backend/apps/api/src/services/student/student.service.ts
- sources/packages/backend/apps/api/src/testHelpers/auth/institution-auth-helpers.ts
- sources/packages/backend/apps/api/src/testHelpers/auth/institution-token-helpers.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1681162016660-UpdateLocationIdComment.ts
- sources/packages/backend/apps/db-migrations/src/sql/Applications/Rollback-update-comment-location-id.sql
- sources/packages/backend/apps/db-migrations/src/sql/Applications/Update-comment-location-id.sql
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/institution/basic-seeding/create-institutions-and-authentication-users.model.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/institution/basic-seeding/create-institutions-and-authentication-users.ts
- sources/packages/backend/apps/workers/src/controllers/program-info-request/program-info-request.controller.ts
- sources/packages/backend/apps/workers/src/controllers/program-info-request/program-info-request.dto.ts
- sources/packages/backend/apps/workers/src/services/application/application.service.ts
- sources/packages/backend/libs/services/src/workflow/variables/assessment-gateway.ts
- sources/packages/backend/libs/test-utils/src/constants/institution.constants.ts
- sources/packages/backend/libs/test-utils/src/factories/application.ts
- sources/packages/backend/libs/test-utils/src/factories/student.ts
- sources/packages/web/src/assets/css/base.scss
- sources/packages/web/src/components/common/SearchStudents.vue
- Added BC Public institution (COLLF) to test seed data;
- Added COLLF users to test-utils;
- Adjusted query to not get either Cancelled applications that weren't assessed or Draft applications;
- Persisted institution location at the submit time;
- Removed application update for institution location from PIR process;
- Updated comment on sims.applications.location_id;
- Added E2E testes for the search student API.
- Fixed responsiveness for the form:
> #1786 - Enable Search Student for Institutions part 2

- sources/packages/web/src/composables/institution/useInstitutionAuth.ts
- sources/packages/web/src/router/InstitutionRouteHelper.ts
- sources/packages/web/src/router/InstitutionRoutes.ts
Based on the route meta property `allowOnlyBCPublic` block access for non BC Public Institution users from accessing routes which are for BCPublic institutions.
> #582 - Restrict non BC Public Institutions from accessing Routes for BC Public institutions

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-part-time-feedback-integration.scheduler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-full-time.integration.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-footer.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-header.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-record.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-response-record.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-part-time.integration.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert.integration.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/models/e-cert-integration-model.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule-errors/disbursement-schedule-errors.service.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.service.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts
- sources/packages/backend/libs/sims-db/src/error-handler.ts
- sources/packages/backend/libs/test-utils/src/factories/disbursement-schedule.ts
- sources/packages/backend/libs/utilities/src/disbursements-utils.ts
- sources/packages/backend/libs/utilities/src/esdc-utils.ts
- Adjusted new header/record/footer record types from 3 to 2 characters.
- Changed the "sent title" using a new const `ECERT_PT_SENT_TITLE`.
- Added a new field for PD/PDD. Currently reading from the student profile. Later it should be determined from where it will be actually read.
- Reading country, province, and postal code in the same way as it is for full-time. This is still pending business answers about how it will properly work.
- Header record now includes the file sequence.
- Fixes for all the positions that were shifted by 1.
- Fix for the total "number of records" calculation.
- Replace the obsolete method `onConflict`.
- Removed no longer needed different codes for the feedback file.
- Fix an error preventing the e-Cert from being generated when some awards were not present.
> #1864 - PT Integration Files Review - e-Cert and Feedback Files

- sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule-shared.service.ts
- `totalDisbursedBCSLAmount` was calculating `valueAmount` sum instead of `effectiveAmount`., which was causing the issue
> #1761 - Handling full time BCSL lifetime and federal maximums -  fix

- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.institutions.controller.getStudentProfile.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.institutions.controller.searchStudents.e2e-spec.ts
Fixing the test case failure by having the right institution in place and removing the test cases which are not valid anymore with decorators in place.
> #1830 - Test case fix

- sources/packages/web/src/router/InstitutionRoutes.ts
- replaced getting the first item by using route.params.locationId as string.
> 1866 - Bug fix for issue when accessing some locationIds from Institutions portal

- .github/workflows/build-deploy-dev.yml
- devops/Makefile
Bug in deployment on github actions.
Added wait for db migration, as the job is not waiting until its completed.
Added delete db migration, as the job name is unique and cannot be recreated until deleted.
> #1717 - Bug-03/Segregate db migrations deployment - Part 1

- sources/packages/backend/apps/api/src/services/bceid/bceid.service.ts
- sources/packages/backend/libs/integrations/src/services/ssh/sftp-integration-base.ts
- sources/packages/backend/workflow/BPMN/assessment-gateway/extract-dynamic-data-exceptions.js
- sources/packages/backend/workflow/scripts/api-response-parser.js
- testing/src/uploadResult.ts
This PR addresses the following sonarcloud critical issues:
- Change `var` to use `const` or `let`.
- Provide a comparator as an argument to the sort function.
> #1966 - Fix sonarcloud critical and major issues (part 1)

- sources/packages/backend/apps/api/src/route-controllers/designation-agreement/designation-agreement.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/institution/institution.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/note/note.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.aest.controller.ts
- sources/packages/backend/apps/db-migrations/src/main.ts
- sources/packages/backend/apps/queue-consumers/src/main.ts
- sources/packages/backend/apps/queue-consumers/src/processors/assessment/cancel-application-assessment.processor.ts
- sources/packages/backend/apps/test-db-seeding/src/main.ts
- sources/packages/backend/apps/workers/src/main.ts
- sources/packages/backend/libs/integrations/src/cra-integration/cra-income-verification.processing.service.ts
- sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule-shared.service.ts
- sources/packages/web/src/components/common/IdleTimeChecker.vue
- sources/packages/web/src/components/common/LocationSummary.vue
- sources/packages/web/src/components/common/StudentApplication.vue
- sources/packages/web/src/components/students/StudentDocumentList.vue
- sources/packages/web/src/main.ts
- sources/packages/web/src/router/index.ts
- sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/ApplicationDetailsForCOE.vue
- sources/packages/web/src/views/student/StudentApplicationDetails.vue
- sources/packages/web/src/views/student/StudentApplicationSummary.vue
- sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
- testing/src/cypress/e2e/04-api-institution/02-instition-create-update-location.cy.ts
- testing/src/uploadResult.ts
As a part of this PR, fixed the major issues (bugs) reported by SonarCloud.
> #1966 - Fix sonarcloud critical and major issues (part 2)

- sources/packages/backend/apps/api/src/services/education-program-offering/_tests_/unit/education-program-offering.service-getCalculatedStudyBreaksAndWeeks.spec.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/backend/libs/utilities/src/date-utils.ts
- sources/packages/forms/src/form-definitions/educationprogramoffering.json
- Added 1 day to the calculation of `dateDifference` as all date periods will be calculated with start and end dates inclusive;
- Changed education program offering form to add 1 day in the calculated value for study break days;
- Added unit tests to check the calculation results for `getCalculatedStudyBreaksAndWeeks` method:
√ Should calculate funded study period and total days when study start and end study dates are available. (4 ms)                                                                      
√ Should not calculate funded study period days and total days when study start date is not available.                                                                                
√ Should not calculate funded study period days and total days when study end date is not available. (1 …
> #1929 - Current days of study/studybreaks count is 1 short of total

- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getRequestedAssessmentSummary.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.institutions.controller.ts
- sources/packages/backend/libs/test-utils/src/factories/disbursement-receipt-value.ts
- sources/packages/backend/libs/test-utils/src/factories/offering-change-request.ts
- sources/packages/web/src/views/institution/student/applicationDetails/InstitutionAssessmentsSummary.vue
1 - Offering change and scholastic change related changes and related e2e
2 -  @andrewsignori-aot comment from my previous is addressed, https://github.com/bcgov/SIMS/pull/1952#discussion_r1207267373\
Screenshots:
1. Ministry view with offering change,
Institutions view with offering change
2-  Ministry view with scholastic standing.
Institutions view scholastic standing, 
3- new TC,
Next PR:
1. I will be addressing @dheepak-aot comment added in my last PR, https://github.com/bcgov/SIMS/pull/1952#discussion_r1207444962
> #1791 - Enable Assessments tab view and NOA view for Public Institution Users - Part 4 

- sources/packages/backend/apps/api/src/auth/roles.enum.ts
- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.reissueMSFAA.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.aest.controller.ts
- sources/packages/backend/apps/api/src/testHelpers/auth/_tests_/e2e/aest-token-helpers.getAESTToken.e2e-spec.ts
- sources/packages/backend/apps/api/test/auth.aest.e2e-spec.ts
- sources/packages/web/src/types/contracts/aest/roles.ts
- sources/packages/web/src/views/aest/student/applicationDetails/NoticeOfAssessment.vue
- Added role to aest-business-administrators group on DEV and TEST;
- Added role to enums;
- Added decorator on the api call to restrict only to business administrator role;
- Passed value to hide button when user has not business administrator role;
- Updated User profile matrix spreadsheet;
- Added the following tests:
Auth Ministry
√ Should have specific roles when ministry user is a business administrator. (400 ms)
ApplicationAESTController(e2e)-reissueMSFAA
√ Should not reissue an MSFAA when user is not a business administrator.
> #1964 - Added role to restrict MSFAA reissue

- sources/packages/backend/libs/sims-db/src/data-source.ts
While using the standalone mode (local development only) the configuration used was meant to be used by `ioredis` client but it was configured to use `redis` client. For reference only, this is the method on the Typeorm source code where the initialization of the specific client happens: https://github.com/typeorm/typeorm/blob/master/src/cache/RedisQueryResultCache.ts#L50
This is the Typeorm documention that states that the connection can happen using `redis` or `ioredis` client: https://orkhan.gitbook.io/typeorm/docs/caching
As shown below, the `redis` client requires a `socket` configuration. because the information about the host/port was not properly provided to `redis` client the connectivity was established on localhost:6379 by default, which explains why it was working from our …
> #1983 - Changed Redis client to ioredis for local development

- sources/packages/forms/Dockerfile
Formio permission change in the dockerfile while build. 
The tried combinations are 640, 644, 650, 654, 750, 754, 770, 774 and 777. So with the least permission level of 770, 774 and 777 which worked. Selected 770.
> #1959 - Staging sims prod environment formio

- .github/workflows/env-setup-build-forms-server.yml
- .github/workflows/env-setup-deploy-forms-server.yml
Split the github action workflow which currently builds and deploys simultaneously in a single action into seperate build and deploy github action.
> #1959 - Staging sims prod environment : formio GitHub action build deploy split

- sources/packages/backend/apps/api/src/route-controllers/confirmation-of-enrollment/_tests_/e2e/confirmation-of-enrollment.institutions.getCOESummary.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/models/pagination.dto.ts
- Added a max value to the page number that is globally used for all API endpoints that have pagination enabled. This fix the 45 issues on Wava identified in the category `Integer Overflow`.
- Added an E2E test to one of the endpoints mentioned on the Wava scan: `confirmation-of-enrollment/enrollmentPeriod/current?page=99999999999999999999&pageLimit=10`. This E2E test case file was used because it already has tests created and it was easier to have this one added.
- The issues on the category `API Mass Assignment` are not part of this PR. Further details on the associated ticket.
> #2006 - Remediate high risk vulnerabilities from WAVA report

- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- sources/packages/backend/workflow/test/models/assessment.model.ts
Initial effort was to upgrade to Zeebe 8.2.4 latest version of zeebe node (https://www.npmjs.com/package/zeebe-node?activeTab=versions) but upgrading to latest version brought back the GRPC resource exhausted error logs. 
Hence upgrading with second latest/penultimate version 8.2.3.
> #1997 - Upgrade Zeebe node version

- sources/packages/backend/workflow/src/deploy.ts
We have an ongoing issue on camunda definition deployments when deploying to camunda SaaS not in local.
The deployment gets executed but the command does not terminate(happens in local and github actions as well). 
`zeebeClient.close()` has been added to code and tested that it fixes the issue.
> #1997 - Fix camunda deployments

- sources/packages/backend/apps/api/src/services/education-program-offering/custom-validators/has-valid-offering-period-for-funded-days.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.models.ts
- sources/packages/backend/apps/api/src/utilities/class-validation/custom-validators/period-min-length.ts
- sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts
- sources/packages/forms/src/form-definitions/educationprogramoffering.json
When the same decorator is used for offering validation, the function `studyPeriodMinLength` is assigned to minAllowedDays which calculates minAllowedDays based on offering intensity.
Full Time
Part Time
> #2033 - Validating FT and PT offering minimum length

- sources/packages/backend/apps/api/src/services/institution/institution.service.ts
Currently `getInstitutionTypeById()` in the institution.service.ts is cached at ORM level. 
Due to this, if the cache provider(Redis) is not working properly this method could wait indefinitely for a response and eventually it causes issues which currently could affect the areas of release testing.
Hence as a temporary measure, the cache is being disabled to not affect the release.
Once #1927 is completed, the cache will be enabled again.
> #2043 - Remove cache for institution type

- sources/packages/web/src/composables/institution/useInstitutionAuth.ts
- sources/packages/web/src/composables/institution/useInstitutionState.ts
- sources/packages/web/src/store/modules/institution/actions.ts
- sources/packages/web/src/views/institution/InstitutionCreate.vue
- sources/packages/web/src/views/institution/InstitutionProfile.vue
When a Business BCeID creates the institution the main applications menus are not displayed to allow the user to navigate in the application. 
The way the store was previously being accessed was apparently interrupting the reactivity, so even when the store was updated the computed properties were not broadcasting the changes.
The way it is right now is working and was the quick way to have it fixed for the upcoming release.
From Vue documentation (https://vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue)
_When you assign or destructure a reactive object's property to a local variable, accessing or assigning to that variable is non-reactive because it no longer triggers the get/set proxy traps on the source object. Note this "disconnect" only affects the …
> #2055 - Institution menus not displayed after creation (Business BCeID only)

- sources/packages/forms/src/form-definitions/educationprogram.json
- Added new entry to the program's regulatory options.
- Label: Senate, Academic Council, Education Council, and/or Program Council and Board of Governors
- Value: senateOrEducationCouncil
> #2058 - Add new program regulatory option

- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.getCompletedApplications.e2e-spec.ts
- In the completed search test case, there are multiple search results with the default order of application number. Did a fix to set the application number in order to predict the order while asserting.
> #1953 - Request an Offering Change - Fix

- sources/packages/backend/apps/db-migrations/src/migrations/1688016799148-InsertMSFAACancellationMessage.ts
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Delete-msfaa-cancellation-message.sql
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Insert-msfaa-cancellation-message.sql
- sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-response.processing.service.ts
- sources/packages/backend/libs/integrations/src/services/msfaa-number/msfaa-number.service.ts
- sources/packages/backend/libs/services/src/notifications/notification/notification-actions.service.ts
- sources/packages/backend/libs/services/src/notifications/notification/notification.model.ts
- sources/packages/backend/libs/sims-db/src/entities/notification.model.ts
**As a part of this PR:**
- Created a GC Notify template to send emails when a MSFAA record is cancelled.
- Updated msfaa-number service to save notifications on MSFAA cancellation.
- MSFAA reactivation template is not required as the federal government will send them notification. 
Screenshot of the sent notification email:
**To be done in a separate PR:**
- E2E tests for MSFAA Cancellation Notification.
**NOTE:** There is an update in the Acceptance Criteria (point 2) - MSFAA reactivation template is not required as the federal government will send them notification. Only MSFAA cancellation notification needs to be sent.
> #1777 - Process MSFAA Cancellation and Reactivation Notification

- sources/packages/backend/apps/api/src/services/institution-location/institution-location.service.ts
- sources/packages/web/src/components/common/LocationSummary.vue
- sources/packages/web/src/composables/useFormatters.ts
- Institution locations address formatted as below. The same component is shared between Mnistry and Institutions so the change affects both places.
- Removed column for address line 2.
- Added `orderBy` to the query returning locations because every time that one item was edited they kept switching orders.
> #1658 - Address fields display for institutions and ministry users

- sources/packages/web/src/composables/institution/useInstitutionAuth.ts
The store reference was wrong at this part of the code and due to the same, useInstitutionAuth was always returning undefined for isBCPublic.
It has been fixed and it is working now.
> #2074 - Fix the store reference

- configs/env-example
- sources/packages/backend/apps/api/src/route-controllers/config/config.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/config/models/config.dto.ts
- sources/packages/backend/libs/utilities/src/config/config.service.ts
- sources/packages/web/src/components/generic/formio.vue
- sources/packages/web/src/services/AppConfigService.ts
- sources/packages/web/src/services/http/ConfigApi.ts
- sources/packages/web/src/services/http/dto/Config.dto.ts
- sources/packages/web/src/types/contracts/ConfigContract.ts
- version added to form name
_screenshots_
> #2022 - Form.io definitions cache update for releases

- sources/packages/forms/src/form-definitions/educationprogram.json
- sources/packages/forms/src/form-definitions/institutionprofile.json
- sources/packages/forms/src/form-definitions/institutionprofilecreation.json
- sources/packages/web/src/views/aest/institution/Profile.vue
> #2086 - Enhance regulatory body dropdown

- devops/Makefile
- devops/openshift/database-backup/patroni-simsdb-backup.conf
- devops/openshift/database/patroni-pre-req.yml
- Patroni creds change from Superuser to Databaseuser in DB Backup
- The scripts to assign the privileges for the Databaseuser is updated in wiki 
https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#assign-privileges-for-database-user-for-backup-and-restore
https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#revoke-privileges-for-database-user-for-backup-and-restore
> #2067 - Patroni creds change from Superuser to Databaseuser in DB Backup

- devops/Makefile
As per rocketchat, the docket image atifactory cache `redhat-docker-remote` is pointing to `registry.connect.redhat.com` and not the `registry.access.redhat.com`.
Hence updated the cache to `redhat-access-docker-remote`
> #2001 - Updating the cache name of redhat docker image artifactory

- sources/packages/backend/libs/sims-db/src/data-source.ts
- sources/packages/backend/libs/utilities/src/system-configurations-constants.ts
When `ignoreErrors: true` is set, errors are ignored and the typeorm works normally but the redis client(ioredis and ioredis/cluster) does retry every 2 seconds to connect again to redis server and creates log for every retry.
This is due to the default implementation of `retryStrategy` and `clusterRetryStrategy`.
> #2044 Add Ignore errors and timeout for ORM Cache

- sources/packages/backend/apps/db-migrations/src/migrations/1690490545372-AlterColOperatingAndLegalOperatingName.ts
- sources/packages/backend/apps/db-migrations/src/sql/Institution/Alter-col-operating-and-legal-operating-name.sql
- sources/packages/backend/apps/db-migrations/src/sql/Institution/Rollback-alter-col-operating-and-legal-operating-name.sql
- sources/packages/forms/src/form-definitions/institutionprofile.json
- sources/packages/forms/src/form-definitions/institutionprofilecreation.json
> #2134 - Increase the max length of operating and legal operating name to 250

- sources/packages/backend/libs/sims-db/src/entities/institution.model.ts
- sources/packages/web/src/views/aest/SearchInstitutions.vue
> #2134 - Institution Search Fix

- sources/packages/web/src/services/http/dto/SupportingUser.dto.ts
- sources/packages/web/src/views/supporting-user/SupportingInformation.vue
- Partner and partner When searching for the student application, I couldn't find any issue in my local, As discussed in the call, look like the loading issue mentioned in the ticket was due to point 4.
- Supporting partner data submission was failing - fixed
- Did an overall smoke test in the supporting user portal - everything looks fine.
- Supporting user form was not correct in TEST db, updated it
- Fixed a small UI issue - Once you search for an existing application and then try to search for a nonexisting application the form's Next step  and back btn was still visible
**Issue**
**Fix**
**Screenshots**
> #2150 - TESTING BUG - Unable to search student in the Support user portal (Parent/partner declaration portal)

- sources/packages/web/package-lock.json
Update the package lock file which was missing BC sans and causing error on local build in docker for web.
> #2175 - Update package lock for web

- sources/packages/backend/apps/db-migrations/src/migrations/1693355224679-CreateTypeStudentAssessmentStatus.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1693355238484-StudentAssessmentsAddStudentAssessmentStatusColumns.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1693355247384-ApplicationsAddCurrentProcessingAssessmentId.ts
- sources/packages/backend/apps/db-migrations/src/sql/Applications/Add-col-current-processing-assessment-id.sql
- sources/packages/backend/apps/db-migrations/src/sql/Applications/Drop-col-current-processing-assessment-id.sql
- sources/packages/backend/apps/db-migrations/src/sql/StudentAssessments/Add-student-assessment-status-cols.sql
- sources/packages/backend/apps/db-migrations/src/sql/StudentAssessments/Drop-student-assessment-status-cols.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Create-student-assessment-status.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Drop-student-assessment-status.sql
- sources/packages/backend/libs/sims-db/src/entities/application.model.ts
- sources/packages/backend/libs/sims-db/src/entities/student-assessment-status.type.ts
- sources/packages/backend/libs/sims-db/src/entities/student-assessment.model.ts
- sources/packages/web/src/types/contracts/AssessmentStatus.ts
- Created new columns on `sims.student_assessments`.
- Created new column on `sims.applications`.
- The enum for the new type (`StudentAssessmentStatus`) was already present. The new enum items were added, and the `Submitted` type was kept for backward compatibility, ticket #2188 will be responsible for having it removed.
> #2179 - Queued Assessments - Create DB migrations

- sources/packages/backend/apps/workers/src/controllers/application/application.controller.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts
- sources/packages/backend/apps/workers/src/controllers/cra-integration/cra-integration.controller.ts
- sources/packages/backend/apps/workers/src/controllers/disbursement/disbursement.controller.ts
- sources/packages/backend/apps/workers/src/controllers/program-info-request/program-info-request.controller.ts
- sources/packages/backend/apps/workers/src/controllers/supporting-user/supporting-user.controller.ts
- sources/packages/backend/apps/workers/src/utilities/error-handler.ts
- sources/packages/backend/apps/workers/src/utilities/index.ts
- sources/packages/backend/apps/workers/src/zeebe/zeebe-transport-strategy.ts
- sources/packages/backend/libs/utilities/src/index.ts
- sources/packages/backend/libs/utilities/src/parse-json.ts
- The issue was able to replicate in one of the workers when we submitted an application with a long income, which was an error in the worker logic during the assessment. However, the worker is not getting any acknowledgment from the code and it is waiting
- So, the next time a new assessment comes, it gets stuck in the same worker for an infinite time.
- checked our worker global error handle in https://vscode.dev/github/bcgov/SIMS/blob/fix/sims-%232207/sources/packages/backend/apps/workers/src/zeebe/zeebe-transport-strategy.ts#L57
and found that, the `return await jobHandler(job);` is not throwing any error, when there is an error, as a result, the `catch` is not invoked and the worker is not getting the acknowledgment. 
- fixed the global handler, the jobhandler is returning an …
> #2207 - Investigate Root Cause of Camunda Workers Getting Stuck

- sources/packages/web/src/components/students/modals/ApproveApplicationOfferingChangeRequestModal.vue
- sources/packages/web/src/views/student/application-offering-change-request/tabs/RequestedApplicationOfferingDetails.vue
The following two scenarios are fixed:
-  **Problem:** Application Offering Change Request Status was not sent in payload. 
**Fix:** Application Offering Change Request Status is being set to `InProgressWithSABC` in the payload.
- **Problem:** Text under the Application Details and Request Details headings was only omitted when the application offering change request was approved by the ministry. 
**Fix** As per the requirement, text under the Application Details and Request Details headings is only displayed when "In progress with student." They are omitted after the student approves or declines.
> #1978 - Request Offering Change - Student View Request (Bug fix)

- sources/packages/backend/apps/db-migrations/src/sql/StudentAssessments/Update-student-assessment-status.sql
A missing CASE condition was causing an attempt to set null the student assessment status: "QueryFailedError: null value in column "student_assessment_status" violates not-null constraint".
> #2180 - Assessment Workflow Enqueuer Scheduler - Start Assessment (Part 1) - DB migration fix

- sources/Makefile
- sources/packages/web/Dockerfile
- sources/packages/web/Dockerfile.dev
- sources/packages/web/default.conf.template
- sources/packages/web/nginx.conf
- sources/packages/web/package.json
- sources/packages/web/serve.json
Using npm `serve` package or vue-cli to host a Vue.js app in a production environment is generally not recommended for several important reasons like limited performance, security concerns, lack of Load Balancing, low customization, inefficient static file serving, bad redundancy and scalability and lack of features for monitoring and logging.
According to w3techs and Netcraft websites Nginx is the most used web server at the moment:
Among the benefits of adopting Nginx for the project the items below can be highlighted:
- High Performance: Nginx is renowned for its high-performance capabilities. It is designed to handle a large number of concurrent connections efficiently and can serve static content quickly. This makes it well-suited for websites with high traffic and performance …
> #88 - Analysis to Migrate the Vue Server

- devops/Makefile
- devops/openshift/docker-build.yml
- sources/packages/backend/apps/api/Dockerfile
- sources/packages/backend/apps/db-migrations/Dockerfile
- sources/packages/backend/apps/queue-consumers/Dockerfile
- sources/packages/backend/apps/workers/Dockerfile
- sources/packages/web/Dockerfile
- Modified docker-build.yml to allow multi stage builds. docker-build.yml was forcing the base images to be the one passed as argument to the oc command. Now, the image used will be the one in the Dockerfiles.
- Modified Dockerfiles to use artifacts.developer.gov.bc.ca images.
> #88 - Change to allow multi staged builds and continue using artifacts repo

- sources/packages/backend/apps/queue-consumers/src/processors/models/processors.models.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-enqueuer.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/services/workflow/workflow-enqueuer.service.ts
- sources/packages/backend/libs/utilities/src/logger/index.ts
- sources/packages/backend/libs/utilities/src/logger/logger.service.ts
- sources/packages/backend/libs/utilities/src/logger/process-summary.ts
- sources/packages/backend/libs/utilities/src/parse-json.ts
Created the class `ProcessSummary` (based on the existing one) at the generic library to allow the capture of logs alongside processes like integrations and schedulers services. The goal is to allow the capture of a set of logs to allow them to be logged at the same time for convenience. For instance, the below logs are better interpreted if read altogether.
This effort does not have the intention of removing the `QueueProcessSummary` but it improves the logs one step further.
All new schedulers and integrations can use the new `ProcessSummary` in the same way the old ones can be refactored to use it.
- Bull dashboard job log.
- Equivalent console log.
- Bull dashboard is also able to identify the different types of logs and add some colors to them.
- Equivalent console log.
> #2180 - Log improvements

- sources/packages/web/default.conf.template
- sources/packages/web/nginx.conf
- Configured error_log and access_log to be redirected only to stdout. Kibana should be responsible for capturing the logs output on stdout.
Notice that error_log is now configured to "info" log level which means that all the higher [log levels](https://www.keycdn.com/support/nginx-error-log#nginx-error-log-severity-levels) will be also logged.
> #2305 - Nginx - change configuration to output logs to stdout

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/_tests_/assessment-workflow-enqueuer.scheduler.e2e-spec.ts
- sources/packages/backend/libs/test-utils/src/mocks/queue-module-mock.ts
- Create a  few E2E tests for the new schedler.
- Should queue an assessment when an active application has only the original assessment and it is in 'Submitted' state. (119 ms)
- Should queue the oldest pending reassessment when an active application has one completed original assessment and multiple submitted reassessments queued. (145 ms)                          
- Should not queue a 'Submitted' assessment if the another assessment has its status as 'Queued' (99 ms)
- Should not queue a 'Submitted' assessment if the another assessment has its status as 'In progress' (101 ms)
- Should not queue a 'Submitted' assessment if currentAssessment and currentProcessingAssessment are the same already. (96 ms)
- Created a method to centralize the mock name creation and allow retrieve the mock to …
> #2180 - Assessment Workflow Enqueuer Scheduler - Start Assessment - E2E tests

- sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/start-application-assessment.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/assessment/start-application-assessment.processor.ts
- sources/packages/backend/apps/queue-consumers/src/processors/models/processors.models.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-enqueuer.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/services/application/application.service.ts
- sources/packages/backend/apps/queue-consumers/src/services/workflow/workflow-enqueuer.service.ts
- sources/packages/backend/apps/queue-consumers/src/utilities/index.ts
- sources/packages/backend/apps/queue-consumers/src/utilities/log-utils.ts
- sources/packages/backend/libs/services/src/restriction/student-restriction-shared.service.ts
- sources/packages/backend/libs/utilities/src/logger/process-summary.ts
- The date and time are now prepended in the job logger.
- Added a visual hierarchy to identify better the child logs.
- Changed the hierarchy organization to allow child process to be chronologically added, as seen in the image below (before the green ones, for instance, would be displayed altogether).
Created a new method to inspect the summary message to indicate if there is something that needs attention in the logs.
The query was not filtering by application status and I thought that it would be better to ensure that only `Submitted` and `Completed` applications would be considered to have a workflow queued.
Adjusted the logs for the `assessment-workflow-enqueuer` and `start-application-assessment` to exclusively use the new `ProcessSummary` class instead of the …
> #2180 - Additional log improvement

- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.aest.controller.getApplicationOfferingChangeRequest.e2e-spec.ts
As a part of this PR, the following task was completed:
√ Should return the application offering change request details when provided with the application offering change request id.
√ Should throw a HttpStatus Not Found (404) when an incorrect application offering change request is retrieved.
> #1980 - Request Offering Change: Ministry View Request (e2e tests)

- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts
- sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts
- sources/packages/web/src/types/contracts/EducationProgram.ts
- sources/packages/web/src/views/aest/institution/ProgramDetails.vue
- sources/packages/web/src/views/aest/institution/ViewOffering.vue
- sources/packages/web/src/views/aest/institution/ViewOfferingChangeRequest.vue
- sources/packages/web/src/views/aest/institution/ViewOfferingChangeRequestComplete.vue
- sources/packages/web/src/views/institution/locations/offerings/OfferingEdit.vue
- sources/packages/web/src/views/institution/locations/offerings/OfferingRequestChange.vue
- sources/packages/web/src/views/institution/locations/programs/LocationProgramView.vue
As a part of this PR, the following bug was fixed:
**Issue:** The institution id was not being returned by the API and therefore clicking on the Institution Name did not navigate to the Institution Profile
**Fix:** The institution id was added to the `EducationProgramAPIOutDTO` and the web was adjusted to fix the issue.
Screenshot:
Clicking on the above highlighted Institution Name link takes to the below shown Institution Profile view.
> #2349 - Clicking institution name in offering change request view should navigate to institution profile

- sources/packages/backend/apps/api/src/route-controllers/restriction/_tests_/e2e/restriction.aest.controller.addStudentProvincialRestriction.e2e-spec.ts
- sources/packages/backend/libs/services/src/restriction/student-restriction-shared.service.ts
Fixed the query used by `createNotifications` that was throwing an error due to the incorrect object-query syntax.
This was impacting multiple restriction notifications such as:
- Add Provincial Restriction
- Temporary SIN
- Scholastic Standing
- Federal Restrictions
The application submission is now working as expected, validating and generating the error message.
Error on Add Provincial Restriction also fixed
> #2323 - Create notifications query error

- sources/packages/forms/src/form-definitions/sfaa2021-22.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
-  [x] If ‘yes’ selected to question 2, then trigger exception path, document upload tool, etc.. (Same as current behaviour)
> #2167 - Change how Students Report Dependants

- sources/packages/web/src/assets/css/base.scss
- sources/packages/web/src/components/aest/institution/ApplicationOfferingChangeDetailsHeader.vue
- sources/packages/web/src/components/common/ProgramOfferingDetailHeader.vue
- sources/packages/web/src/components/generic/Separator.vue
- sources/packages/web/src/main.ts
As a part of this PR, the following tasks were completed:
**Screenshots:**
> #2357 - Replace separator component and vertical-divider class with v-divider component

- sources/packages/web/src/components/aest/institution/modals/ApproveDenyDesignationModal.vue
- sources/packages/web/src/components/common/restriction/ViewRestriction.vue
- sources/packages/web/src/components/generic/ModalDialogBase.vue
- sources/packages/web/src/views/aest/institution/Profile.vue
- sources/packages/web/src/views/institution/OfferingsUpload.vue
- sources/packages/web/src/views/institution/WithdrawalUpload.vue
- sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/ApplicationDetailsForCOE.vue
- sources/packages/web/src/views/institution/locations/offerings/OfferingEdit.vue
- sources/packages/web/src/views/student/AppStudent.vue
- sources/packages/web/src/views/student/StudentApplicationDetails.vue
- There were some new properties and classes for v-divider in Vuetify 3, added those properties for all `v-divider` for the fix. 
- The default opacity of the divider is `--v-border-opacity: 0.12;` updated it to `--v-border-opacity: 1 `
- Tried to make it as close to Figma
https://vuetifyjs.com/en/components/dividers/
**Screenshots**
> #1807 - Fix css style for dividers (<hr />)

- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.students.controller.getStudentProfile.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/models/student.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.institutions.controller.ts
- sources/packages/web/src/components/common/students/StudentProfile.vue
- sources/packages/web/src/services/http/StudentApi.ts
- sources/packages/web/src/services/http/dto/Student.dto.ts
- sources/packages/web/src/types/contracts/StudentContract.ts
- sources/packages/web/src/views/aest/student/StudentDetails.vue
- Added a new DTO to contain sensitive data and changed the logic to make the student api to not bring the SIN data.
- Removed the SIN property from the student profile retrieved by the student.
> #1910 - Student profile returns SIN

- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/application-offering-change-request.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/models/application-offering-change-request.dto.ts
- sources/packages/backend/libs/sims-db/src/entities/application-offering-change-request.model.ts
- sources/packages/web/src/components/aest/AssessApplicationOfferingChangeRequestModal.vue
- sources/packages/web/src/components/generic/ModalDialogBase.vue
- sources/packages/web/src/services/ApplicationOfferingChangeRequestService.ts
- sources/packages/web/src/services/http/ApplicationOfferingChangeRequestApi.ts
- sources/packages/web/src/services/http/dto/ApplicationOfferingChangeRequest.dto.ts
- sources/packages/web/src/views/aest/institution/ApplicationOfferingChangeRequestForm.vue
Reason for modifying the base component (ModalDialogBase.vue): `<hr>` tag was changed to `<v-divider>` component. This v-divider component by default adds a significant amount of vertical whitespace. As a result, the margin for `v-divider` in this component is changed to reduce the whitespace.
Please note: Placeholder added for the API endpoint.
> #1981 - Request Offering Change: Ministry View/Approve/Deny (UI only) - Part 1

- sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12.integration.service.ts
> #2373 - IER fix allow zero grants

- sources/packages/web/src/views/institution/locations/programs/LocationProgramAddEdit.vue
> #2376 - Edit Program Banner Message Change

- sources/packages/web/nginx.conf
> add_header 'X-Content-Type-Options'  "nosniff";
> add_header 'Content-Security-Policy' "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'";
> add_header 'Strict-Transport-Security' "max-age=31536000; includeSubDomains; preload";
> add_header 'Referrer-Policy' "same-origin";
As we are not setting any cookie our application, we are not fixing the "Cookie with Insecure or Improper or Missing SameSite attribute" issue.
> #2307 - WAVA scan headers update

- sources/packages/backend/libs/utilities/src/math-utils.ts
https://stackoverflow.com/questions/45221535/javascript-floating-point-multiply-by-100-still-has-errors
Certain decimal numbers when multiplied by 100 may not return precise mathematical result as we expect
`Math.round()` seems to be one of the solutions to handle this issue.
But in the `combineDecimalPlaces` method we are dividing and then multiplying by 100 again, which re-creates the same issue which was fixed by `Math.round()`
Hence: Divide and multiply of the rounded value by multiplier is removed.
> #2379 - Fix computer multiplication in combine decimal places

- devops/openshift/forms-deploy.yml
- Added missing label to be aligned with the other template items.
- Changed the apiVersion that was failing. `apps/v1` is for `kind: Deployment` while `apps.openshift.io/v1` is for `DeploymentConfig` (the one that we use).
> #2287 - Fix forms PodHorizontalAutoscaler

- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.aest.controller.assessApplicationOfferingChangeRequest.e2e-spec.ts
- sources/packages/backend/apps/api/src/services/application-offering-change-request/application-offering-change-request.service.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1697055771725-InsertApplicationOfferingChangeRequestCompletedByMinistryMessage.ts
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Delete-application-offering-change-request-completed-by-ministry-message.sql
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Insert-application-offering-change-request-completed-by-ministry-message.sql
- sources/packages/backend/libs/services/src/notifications/notification/notification-actions.service.ts
- sources/packages/backend/libs/services/src/notifications/notification/notification.model.ts
- sources/packages/backend/libs/sims-db/src/entities/notification.model.ts
Screenshot:
ApplicationOfferingChangeRequestAESTController(e2e)-assessApplicationOfferingChangeRequest
√ Should assess the application offering change request for the provided application offering change request id.
√ Should not create a new assessment when the application offering change request has been declined by the ministry user.
√ Should throw a HttpStatus Not Found (404) error when an application offering change is not in a valid status to be assessed.
√ Should throw a HttpStatus Bad Request (400) error when an invalid application offering change request status is provided.
√ Should throw a HttpStatus Forbidden (403) error when an unauthorized AEST user tries to assess the application offering change request.
> #1981 - Request Offering Change: Ministry View [Approve / Deny Request] - Part 3

- sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12.integration.service.ts
- There was a logic missing for application event code and date, due to which both fields were not showing in the file content
**_Sample file screenshot_**
> #2289 - Implement logic for Application Event Code in IER12 - code and date assignment (Part 5)

- devops/Makefile
- sources/packages/backend/apps/api/Dockerfile
- sources/packages/backend/apps/api/Dockerfile.dev
- sources/packages/backend/apps/db-migrations/Dockerfile
- sources/packages/backend/apps/queue-consumers/Dockerfile
- sources/packages/backend/apps/queue-consumers/Dockerfile.dev
- sources/packages/backend/apps/workers/Dockerfile
- sources/packages/backend/apps/workers/Dockerfile.dev
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- sources/packages/backend/workflow/Dockerfile.dev
- sources/packages/web/Dockerfile
- sources/packages/web/Dockerfile.dev
- Upgraded Dockerfile base images to [nodejs-18:1-71.1697652955](https://catalog.redhat.com/software/containers/ubi8/nodejs-18/6278e5c078709f5277f26998?image=65302e01ec5935b621691d22&architecture=amd64&container-tabs=overview). 
- Upgraded Dockerfile.dev base images to [node:18.17.1-alpine3.18](https://hub.docker.com/layers/library/node/18.17.1-alpine3.18/images/sha256-982b5b6f07cd9241c9ebb163829067deac8eaefc57cfa8f31927f4b18943d971).
- Upgraded [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client/v/9.1.0) to the latest version.
- Did some smoke tests locally to check any incompatibility.
Please upgrade your local NodeJS version from https://nodejs.org/en/download and check if you are really using the new version:
```bash
$ node -v
```
Just for reference, you can check …
> #2089 - Upgrade node version on all environments

- sources/packages/backend/apps/api/src/services/application/application.service.ts
Checked if application has a currentAssessment when cancelling the student assessment. Draft applications don't have a current assessment.
> #2456 - Cancelling a draft application fails

- .github/workflows/env-setup-deploy-secrets.yml
- .github/workflows/env-setup-redis-recovery.yml
- .github/workflows/redis-recovery.yml
- devops/Makefile
Created a make command from the below recommendation from the Redis channel in rocket chat and it seems to recover our Redis without deleting it completely in the environment and creating them again.
Note: This command had to be run every time, when we put down the Redis manually or any disruptions that restart the Redis pods. Parallel to this, if we have a Sysdig alert which checks the health of the Redis pods in the environment, would help us in any delays to the application queues processing.
Also wiki has been appropriately updated
https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#redis-cluster-failing-to-recover
> #2382 - Redis recovery command

- sources/packages/web/src/views/aest/institution/InstitutionNotes.vue
-  `Create new note` button was missing in the institution note, fixed the issue.
> #2087 - Ministry Add New Note for Institution Account 

- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/_tests_/unit/e-cert-part-time-integration.service.spec.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-header.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-record.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-part-time.integration.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/models/e-cert-integration-model.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts
- sources/packages/backend/libs/services/src/constants/system-configurations-constants.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-value-type.ts
- sources/packages/backend/libs/utilities/src/disbursements-utils.ts
- e-Cert tuition remittance should be the minimum value between `tuition_remittance_requested_amount` and `max calculated tuition remittance`:
https://github.com/bcgov/SIMS/blob/0aea33c42854e25ebf4a5afba8621ae3e0aa3997/sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts#L623-L636
- File name change
- Moved to another ticket: https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2479
- Fixed file max line length;
- Changed field of study to be string with trailing spaces;
- Grants
- Renamed CSGPT to CSPT;
- Renamed some variables removing the "total" in the name because they don't represent a total value.
- Fixed grant types (order);
- Confirmed that CSGP Total Amount is …
> #1934 - Finastra Part-time File Review Changes

- sources/packages/web/src/views/institution/WithdrawalUpload.vue
**Bug:** UI shows success message in the snackbar when there are validation errors for one or more application bulk withdrawal errors. 
**Fix:** This is fixed to show no success message when there are one or more validation errors.
> #2112 - Business Validations: Application Bulk Withdrawal: Bug Fix

- sources/packages/backend/apps/api/src/services/application-bulk-withdrawal/application-bulk-withdrawal-import-text.service.ts
- sources/packages/backend/apps/api/src/services/application-bulk-withdrawal/application-bulk-withdrawal-validation.models.ts
**Bug:** When an application record in the bulk withdrawal file where the student has previously withdrawn from the program (scholastic standing) is processed and the same record in the file also has an incorrect value of SIN:
> #2112 - Application Bulk Withdrawal: Business Validations - Bug Fix

- sources/packages/backend/apps/api/src/services/application-bulk-withdrawal/application-bulk-withdrawal-validation.models.ts
**Bug:** If the application is withdrawn due to the **student withdrew from program (this very specific type of scholastic standing only)**, then the error message resulting from the application getting archived shows up.
**[Bug Screenshot]**
**Fix:** If the application is withdrawn due to student withdrew from program, then the error message resulting from the application getting archived shouldn't be shown. Only the warning message: "This application is already withdrawn and going to be skipped." is shown.
As per the new message request in the story, the withdrawal date is also not shown in the UI.
**[Fix Screenshot]**
The application in the below screenshot has scholastic standing: Student withdrew from program.  Hence, only the warning message "This application is already withdrawn …
> #2112 - Application Bulk Withdrawal: Business Validation - Bug Fix

- devops/openshift/api-deploy.yml
- devops/openshift/forms-deploy.yml
- devops/openshift/queue-consumers-deploy.yml
- devops/openshift/web-deploy.yml
- devops/openshift/workers-deploy.yml
Horizonatal Autoscaler value change from average value to CPU utilization
> #2383 - Horizonatal Autoscaler value change

- sources/packages/backend/apps/api/src/main.ts
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
The SIMS API needs to have security HTTP headers set for the endpoint responses to satisfy some security issues raised by the WAVA scans. Among the alternatives to achieve that, two of them can be highlighted as most common: 
1. Configure and set headers through the API itself;
2. Configure a reverse proxy to receive the client requests, redirect to the API and change the response headers to the client.
Helmet.js is the middleware module recommended by [Nest.js](https://docs.nestjs.com/security/helmet) and [Express.js](https://expressjs.com/en/advanced/best-practice-security.html#use-helmet). As its documentation mentions, we can achieve something similar [without Helmet.js](https://helmetjs.github.io/faq/you-might-not-need-helmet/). The middleware will set some headers by default and …
> 2283 - HTTP server for nest

- sources/packages/backend/apps/load-test-gateway/src/constants/system-configurations-constants.ts
- sources/packages/backend/apps/workers/src/controllers/application/application.controller.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts
- sources/packages/backend/apps/workers/src/controllers/cra-integration/cra-integration.controller.ts
- sources/packages/backend/apps/workers/src/controllers/disbursement/disbursement.controller.ts
- sources/packages/backend/libs/utilities/src/system-configurations-constants.ts
**Background:** 
While load testing the workers with a chunk of 5000 assessments with different worker configuration scenarios, It has been observed that, when the pods are auto-scaling and going at and beyond 6 pods for workers, an immense load has been put on the patroni db and the patroni db was going to recovery state for few seconds and then became functional without any issues. 
As a side effect of patroni db going to recovery state, the inference proves that  the worker `associate-workflow-instance` was executed twice for the same assessment, during such an occurrence it is expected that second workflow instance must be cancelled and it must not raise an incident. The workflow instance was getting cancelled but the code to cancel workflow was not terminating/conveying the terminal …
> #2489 - Worker and ORM changes based on load test results

- devops/openshift/api-deploy.yml
- devops/openshift/queue-consumers-deploy.yml
- devops/openshift/web-deploy.yml
- devops/openshift/workers-deploy.yml
Tested the scenarios with the setting mentioned in the PR for Workers and queue consumers in dev by manually setting the liveliness and readiness probe. Tested by making redis and/or postgres down, both the pods restarted after the recovery successfully.
> #2546 - Readiness and Liveliness Probe for workers and Queue consumers

- sources/packages/backend/apps/api/src/services/education-program-offering/_tests_/unit/education-program-offering.service-adjustStudyBreaks.spec.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/_tests_/unit/student-scholastic-standings.service.adjustStudyBreaks.spec.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts
- `study_breaks` column will be updated using the `EducationProgramOfferingService.getCalculatedStudyBreaksAndWeeks`
-  If the change in study end date overlaps/crosses any study breaks, the below logics are followed:
> If new study end date =< break start date, ignore study break
> If new study end date => break end date, include study break as is.
> If break start date < new study end date < break end date, update break end date with new study end date
- During an offering creation when the break period is less than 6 days, offering is not allowed to create, In Scholastic standing, we do the above 3 steps and ignore all the validations(even if the new study break period is less than 6 days, we don't care, we still clone the offering with above-mentioned logic)
- created unit test for …
> #1824 - Scholastic Standing Cloning Offering 

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-full-time-feedback-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-full-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-part-time-feedback-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-part-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-process-integration-base.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-enqueuer.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-queue-retry.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/utilities/log-utils.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-integration.module.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/full-time-e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/part-time-e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/index.ts
- Created the new based class `ECertProcessIntegrationBaseScheduler` to be shared by the full-time and part-time e-Cert schedulers.
- Created also the base class `ECertFileHandler` to support the above-mentioned change.
- Changed the e-Cert file generation to also use the `ProcessSummary` logs.
_Please note that refactors for the e-Cert feedback are out of the scope of this effort._
> #2510 - Full-time and Part-Time Schedulers Centralization Refactor

- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-full-time-integration/e-cert-files/e-cert-file-record.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-part-time-integration/e-cert-files/e-cert-file-record.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/assert-life-time-maximum-full-time-step.ts
- sources/packages/backend/tsconfig.json
- Fixed an issue for the BC `assert-life-time-maximum-full-time-step` that would fail during the log due to a null exception while accessing `bcLoan.valueCode`.
- Added `cause` to the errors generated during e-Cert record generation for further investigation. The `cause` is present in `es2022` but only `es2022.error` was updated right now because extra changes are needed to completely update the backend to use `es2022`.
> #2510 - e-Cert Implementation for Individual Student Processing - Fix and Investigation

- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.models.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-calculation-process.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-generation.service.ts
Adding the application number to e-Cert logs to make it easier to find application-related issues.
The log entry would be changing from:
```
Processing disbursement id 56209 scheduled for 2023-12-17.
```
To
```
Processing application number 1077887860, disbursement id 56209 scheduled for 2023-12-17.
```
> #2510 - e-Cert Implementation for Individual Student Processing - Added application number to logs

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ier12-integration/_tests_/e2e/models/data-inputs/programs-inputs.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ier12-integration/_tests_/e2e/models/data-inputs/students-inputs.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12-file-detail.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12.integration.service.ts
- sources/packages/backend/libs/utilities/src/_tests_/unit/string-utils.replaceLineBreaks.spec.ts
- sources/packages/backend/libs/utilities/src/index.ts
- sources/packages/backend/libs/utilities/src/integration-utils.ts
- sources/packages/backend/libs/utilities/src/string-utils.ts
- sources/packages/backend/package.json
> #2452 - IER12 File Adjustments

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/services/src/constants/system-configurations-constants.ts
- Change the PT eCert SEND file naming convention to: TPBC.EDU.NEW.PTCERTS.Dyyyyjjj.001
> #2479 - Finastra - File name change

- sources/packages/web/src/types/contracts/EducationProgram.ts
There was a build failure, because of the below issue,
`ProgramOfferingHeader` is a shared interface, the certain components don't need the `parentofferingid`, so, I made the `parentofferingid` as optional,
> #2488 - Ensure offering parent id is always present- build fix

- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn
Update calculatedDataExceptionalExpenses = offeringExceptionalExpenses - is not done as calculatedDataExceptionalExpenses is removed as a part of #2229.
Update any affected E2E tests - No test cases are affected, so no change.
> #2557 - Remove course load calculation from PT

- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn
> #2582 - PT Remove child care cost spilt in half 

- sources/packages/backend/apps/api/src/route-controllers/confirmation-of-enrollment/_tests_/e2e/confirmation-of-enrollment.institutions.confirmEnrollment.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.institutions.controller.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.models.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/_tests_/unit/confirmation-of-enrollment.getMaxTuitionRemittance.spec.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/confirmation-of-enrollment.service.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/models/confirmation-of-enrollment.models.ts
As a part of this PR, the following was done:
- Mandatory fees is incorporated into the allowable maximum (i.e. tuition+books and supplies+mandatory fees.)
- Unit tests were updated
> #2299 - Adjust Maximum Allowable Tuition Remittance

- devops/openshift/database/patroni-deploy.yml
More on the failure on Rocketchat - https://chat.developer.gov.bc.ca/channel/patroni?msg=64A8yQr3KeMthqsWn
The solution:
1. Take the current DB backup in patroni backup pod
2.  Change the image from image-registry.openshift-image-registry.svc:5000/bcgov/12.4-latest to artifacts.developer.gov.bc.ca/bcgov-docker-local/patroni-postgres:2.0.1-12.4-latest
> #2646 - Patroni Prod issue

- .vscode/launch.json
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-2021-2022-awards-amount-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-2022-2023-awards-amount-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-2023-2024-awards-amount-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/models/assessment.model.ts
Current
```
if (awardEligibilityCSPT = true)
then
if (calculatedDataTotalRemainingNeed1 > federalAwardCSPTAmount)
then federalAwardCSPTAmount
else calculatedDataTotalRemainingNeed1
else
0
```
Expected
```
if (awardEligibilityCSPT = true && calculatedDataTotalRemainingNeed1 >= 100)
then
min(
calculatedDataTotalRemainingNeed1,
min(dmnPartTimeAwardAllowableLimits.limitAwardCSPTAmount, federalAwardCSPTAmount)
)
else
0
```
> #2632 - PT CSPT Awards Update

- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-2021-2022-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-2022-2023-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-2023-2024-awards-amount-BCAG.e2e-spec.ts
- removed console.log(calculatedAssessment.variables); from test files
> #2641 - Award Configurations - PT BCAG (Net) Quick Fix

- sources/packages/backend/apps/api/src/route-controllers/student/student.controller.service.ts
-  Allow Ministry users to open files embedded within Student App
-  Allow students to view uploaded files
> #2233 - Unable to view files Uploaded within App (Through Exception Path)

- devops/openshift/api-deploy.yml
- devops/openshift/load-test-gateway-deploy.yml
- devops/openshift/queue-consumers-deploy.yml
- devops/openshift/workers-deploy.yml
Analysis and troubleshooting on patroni going to recovery mode on load test
Tested the simple workflow in our application after changing the database user to non super user with the minimal permissions and it seems to work well.
Also the release notes will be updated to grant the non super user permissions to do application operations.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sims TO "app_database_user";
> #2544 - Patroni Recovery mode resolution

- sources/packages/backend/apps/db-migrations/src/sql/StudentAssessments/Rollback-add-calculation-start-date.sql
- The file `Rollback-add-calculation-start-date.sql` updated to have the table name `sims.student_assessments`. Issue found by @sh16011993
> #2664 - Fix the DB migration revert script

- sources/packages/forms/src/form-definitions/sfaa2021-22.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/supportingusersparent2022-2023.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2022-2023.json
**As a part of this PR, validations (for negative and very large [> $100 million] inputs) have been added for total income reported in the application forms for all the 3 program years along with parent and partner supporting documents. Also, ability for the user to enter a decimal number has been disabled.**
> #2688 - Bug in submitting application when total income has non integer values

- sources/packages/backend/apps/queue-consumers/src/services/application/application.service.ts
Added the missing `ApplicationStatus.Assessment` to allow the queue processing before the student even accepts the assessment.
> #2665 - Added Missing Assessment for Queue Processing

- sources/packages/backend/apps/api/src/route-controllers/education-program/education-program.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/models/education-program.dto.ts
- sources/packages/forms/src/form-definitions/educationprogram.json
- sources/packages/web/src/services/http/dto/EducationProgram.dto.ts
- sources/packages/web/src/views/institution/locations/programs/LocationProgramAddEdit.vue
-  Remove prompts for additional questions when "Online" program delivery is selected when being created by BC Public or BC Private institutions.
- Keep prompts when creating an "Online" program (or Online and On site) for all other institution types.
- No production adjustment is needed.
Screenshot of selection behaviors for non-BC institutions
Screenshot of selection behaviors for BC private institutions
> #2623 - Program Validation - Online - BC Public/BC Private

- sources/packages/backend/workflow/BPMN/camunda-8/assessment-gateway.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn
> #2633 - Assessment gateway related changes on child care cost

- sources/packages/forms/src/form-definitions/sfaa2021-22.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
**As a part of this PR, the following were fixed:**
The below two fixes are for the story: [Application Form - Additional Transportation Costs (FT and PT)](https://github.com/bcgov/SIMS/issues/1707)
- Added the missing `$` prefix to the weekly transportation costs to the forms for all the program years.
- Added the missing `km` suffix to the weekly transportation costs to the form for program year: 2021-22.
The below fix is for the story: [Bug in submitting application when the Total income has integers](https://github.com/bcgov/SIMS/issues/2688)
- Added the missing validation for the field: **Supporting user income, when reported by the student for all program years.**
> #1707 - Application Form: Additional Transportation Cost (Bug Fix)

- .github/workflows/prune-images.yml
- devops/scripts/fetchOldTags.sh
Created a new script to determine ImageStream tags that can be safely removed for a given environment.  The intended usage would be to run the script against prod and set min_tags to a number like 3 for rollback.  This would list all tags newer than prod + include 3 tags that are older than prod.
After speaking with Guru, I added the ability to prefix a branch which then only targets those tags.
The script itself only dumps a list which then must be used by a command to do something.  For this, I've created a new GitHub Action which calls the fetchOldTags.sh against dev with a min_tags to set at 10.  This is the behaviour that has been run manually.  Ideally in the future we could target Prod but this requires timely releases.  
NOTE:  Currently the script simply echo's the OC commands …
> #1989 -  Prune images

- sources/packages/forms/src/form-definitions/sfaa2021-22.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2022-2023.json
Remove the following questions from supporting users form and student form 'self-report' feature
- "Will you be employed full-time or part-time during your partner's study period"
- "Will you be at home caring for eligible dependent children on a full-time basis during your partner's entire study period?"
- "Will you be living with your partner during the study period"
- "Will you be a full-time post-secondary student for some or all of your partner's study period (remove the follow-up questions capturing weeks of study as well)"
- "Will you be paying a Canada Student Loan.."
- "Will you be paying for Child support and/or spousal support during your Partner's study period"
- "Will you be taking care of eligible dependents during your Partner's study period"
- Add to the ticket comments …
> #2348 - Removal of Part-Time Application Questions For Partner Supporting Users

- .github/workflows/prune-images.yml
- devops/scripts/fetchOldTags.sh
- devops/scripts/pruneImages.sh
These ideal method for this script would be that it would be called against the Production project and without a branch specifier and would remove all but N older images from the associated tools imagestreams.  This is not currently the practice as the deployments don't occur frequently enough to prevent a build up of old tags.
As such, the script runs against the dev environment and removing tags that are older than N versions in dev and only tagged against main.
In an even more ideal world we would use environment tags like: dev, test, staging, production which with a minor modification would allow the script to only look at the image stream tags and not have to review the deployment configs.  
1. pruneImages.sh \
⚠️ This script is **destructive** and iterates over a comma seperated …
> #1989 - Prune images

- sources/packages/web/src/components/generic/BodyHeader.vue
- sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/COESummaryData.vue
- sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/LocationCOESummary.vue
1. Revised the tab name from "Upcoming Enrolment" to: "Upcoming and Previous Enrolments"
2. Within the 'upcoming and previous enrolment' tab, added wording beneath the header which reads: "This page contains two types of records:
- disbursements requests which are upcoming and will be required at a later date. These are indicated by a 'Required' status.
- previously actioned Confirmation of Enrolment Requests which can no longer be actioned. These are indicated by a 'Completed' status.
> #2530 - Rename Upcoming Enrollment Tab Within Institution Account

- sources/packages/backend/libs/src-sql/sfas-restrictions/Bulk-insert-sfas-mapped-restrictions.sql
- sources/packages/web/src/components/common/students/StudentRestrictions.vue
-----------------------------------------------------------------------
- **Bug:** The Resolved Column was not showing the date for Resolved restrictions and was instead showing a Date for the Active Restrictions.
**Fix:** It has been fixed to show the resolved date for the Resolved restrictions and not show a date under the Resolved column for the currently active restrictions.
---------------------------------------------------------------------
- **Bug:** The `Bulk-insert-sfas-mapped-restrictions.sql` query was not checking for the scenario when a specific restriction for a student mapped from SFAS is inactive is SIMS and at the same time, the same restriction has entries as an active restriction. If this situation was there, the query was still allowing for this restriction to be …
> #2685 - Import Provincial Restrictions from SFAS into SIMS [Bug Fix 2]

- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-2021-2022-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-2022-2023-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-2023-2024-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts
Updated part time assessment bpmn's on the calculate BCAG Event to consider programYearTotalPartTimeBCAG
e2e Test cases updated
parttime-assessment-2021-2022-awards-amount-BCAG.e2e-spec.ts
parttime-assessment-2022-2023-awards-amount-BCAG.e2e-spec.ts
parttime-assessment-2023-2024-awards-amount-BCAG.e2e-spec.ts
> #2880 - PT Award Configuration BCAG

- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/BPMN/camunda-8/parttime-assessment-2023-2024.bpmn
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-2021-2022-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-2021-2022-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-2021-2022-awards-amount-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGP.e2e-spec.ts
- sources/packages/backend/workflow/test/2021-2022/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-SBSD.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-2022-2023-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-2022-2023-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-2022-2023-awards-amount-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGP.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-SBSD.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-2023-2024-awards-amount-BCAG.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-2023-2024-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-2023-2024-awards-amount-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGP.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-SBSD.e2e-spec.ts
- sources/packages/backend/workflow/test/models/assessment.model.ts
- sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts
PT award configuration CSPT updated to consider the program year totals of CSPT already given to the student.
Bug resolved in this PR:
PT award configuration variables 
- federalAwardNetCSGPAmount
- federalAwardNetCSGDAmount
- provincialAwardNetBCAGAmount
- provincialAwardNetSBSDAmount
all became null when they do not find the below values for the student in the particular year (or if its the first application for a student in a PY) so it will return as null
- programYearTotalFullTimeSBSD
- programYearTotalPartTimeSBSD
- programYearTotalFullTimeCSGP
- programYearTotalPartTimeCSGP
- programYearTotalPartTimeCSGD
- programYearTotalPartTimeSBSD
So fixed it by checking a null for the above values and return 0 if they are null.
E2E Test cases  updated
> #2639 - Award Configuration PT - CSPT

- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.aest.controller.assessApplicationOfferingChangeRequest.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.aest.controller.assessOfferingChangeRequest.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/_tests_/e2e/student-scholastic-standings.institutions.controller.saveScholasticStanding.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/student-scholastic-standings.institutions.controller.ts
- sources/packages/backend/apps/api/src/services/application-offering-change-request/application-offering-change-request.service.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.models.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-workflowWrapUp.e2e-spec.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.models.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
- sources/packages/backend/libs/test-utils/src/factories/student-assessment.ts
**Rephrase of the AC**
Update any student appeal record (Request a Change) for the current student re-assessment for an application when the re-assessment takes place in offering change, scholastic standing, automatic re-assessment, etc.. That is, modify places where re-assessments occur for all assessment trigger type other than the "original assessment". This story will be a preparation story for a later story, where application data used for Camunda reassessment calculation will be updated with student appeal data.
- Updated one place for `AssessmentTriggerType.ScholasticStandingChange`.
- Updated one place for `AssessmentTriggerType.ApplicationOfferingChange`.
- Updated one place for `AssessmentTriggerType.RelatedApplicationChanged`.
- Updated one place for …
> #2847 - Ensure Re-assessments Recognize Request a Change Assessments as the Relevant Baseline

- sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.models.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.processing.service.ts
- sources/packages/backend/libs/services/src/sfas/sfas-individual.service.ts
**Bug:** After student account creation, when the `sfas-integration` scheduler runs, it calls the `insertStudentRestrictions` method which ensures that the restrictions imported for the newly created student, if any, from SFAS are inserted into the SIMS student restrictions. However, as per the current code, the `insertStudentRestrictions` method is only called when there is atleast one SFAS file to process.
**Fix:** Code has been refactored to ensure that this block of code runs even when there are no SFAS file imports to be processed.
**Note:** There is some additional code cleanup in the file `sfas-individual.service.ts`.
> #2685 - Import Provincial Restrictions from SFAS to SIMS (Bug Fix)

- sims.code-workspace
- sources/packages/backend/apps/db-migrations/src/migrations/1710462853532-CreateProgramDeactivationColumns.ts
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Add-deactivation-columns.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Rollback-add-deactivation-columns.sql
- sources/packages/backend/libs/sims-db/src/entities/education-program.model.ts
Created the new columns related to the education program deactivation. Used one of the suggested name combinations in the ticket technical discussion.
- isActive
- isActiveUpdatedBy
- isActiveUpdatedOn
_Minor comment, we did not plan to add a specific note id associated with the is_active column. The note requested will be created without it and it was my understanding that it would not be required. Please let me know if it need to be discussed._
_Minor update in the shared workspace `cSpell.words`._
> #2645 - Program Deactivation - DB migrations

- sims.code-workspace
- sources/packages/backend/.vscode/settings.json
- sources/packages/backend/apps/api/src/app.students.module.ts
- sources/packages/backend/apps/api/src/auth/roles.enum.ts
- sources/packages/backend/apps/api/src/constants/error-code.constants.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/_tests_/e2e/education-program.aest.controller.deactivateProgram.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/_tests_/e2e/education-program.institutions.controller.deactivateProgram.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/education-program.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/education-program.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/education-program.institutions.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/models/education-program.dto.ts
- sources/packages/backend/apps/api/src/services/education-program/education-program.service.ts
- sources/packages/backend/apps/api/src/services/institution/institution.service.ts
- sources/packages/backend/apps/api/src/testHelpers/fake-entities/education-program-fake.ts
- Created new API endpoints to deactivate the program available for Institutions and the Ministry. The controller was created to specifically deactivate the program and the service was created to be generic to also allow the reactivation in case we need to work in the requirement in the future.
- Created a new role `institution-deactivate-education-program`.
- Created E2E tests for the new endpoints.
- Ministry
- Should allow an education program to be deactivated when the program is active.
- Should return an unprocessable entity HTTP status when the program is already deactivated.
- Should return a not found HTTP status when the program id does not exists.
- Should return a bad request HTTP status when payload is invalid.
- Institutions
- Should allow an education program to be …
> #2645 - Program Deactivation - API Changes

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-calculation-process.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-notification/e-cert-notification.service.ts
- sources/packages/backend/libs/sims-db/src/database.module.ts
- sources/packages/backend/libs/test-utils/src/factories/notification.ts
- sources/packages/backend/libs/test-utils/src/factories/sin-validation.ts
- sources/packages/backend/libs/test-utils/src/factories/student.ts
- sources/packages/backend/libs/test-utils/src/index.ts
- Scheduler queue processor for part-time-e-cert-integration.
√ Should create a notification for the ministry and student for a blocked disbursement when there are no previously existing notifications for the disbursement.
√ Should not create a notification for the student for a disbursement when there are already 3 notifications created.
√ Should not create a notification for the student for a disbursement when an attempt is made to create the 2nd notification before 7 days from the first notification.
√ Should create a notification for the student for a disbursement when an attempt is made to create the 2nd notification on or after 7 days from the first notification.
> #2536 - Notify Student About Blocked Disbursements (e2e tests)

- sources/packages/backend/apps/api/src/app.aest.module.ts
- sources/packages/backend/apps/api/src/route-controllers/student-loan-balance/_tests_/e2e/student-loan-balance.aest.controller.getStudentLoanBalance.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-loan-balance/models/student-loan-balance.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/student-loan-balance/student-loan-balance.aest.controller.ts
- sources/packages/backend/apps/api/src/services/index.ts
- sources/packages/backend/apps/api/src/services/student-loan-balance/student-loan-balance.service.ts
- sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1711342815738-CreateStudentLoanBalances.ts
- sources/packages/backend/apps/db-migrations/src/sql/StudentLoanBalances/Create-student-loan-balances.sql
- sources/packages/backend/apps/db-migrations/src/sql/StudentLoanBalances/Rollback-create-student-loan-balances.sql
- sources/packages/backend/libs/sims-db/src/constant.ts
- sources/packages/backend/libs/sims-db/src/data-source.ts
- sources/packages/backend/libs/sims-db/src/entities/index.ts
- sources/packages/backend/libs/sims-db/src/entities/student-loan-balances.model.ts
- sources/packages/backend/libs/test-utils/src/data-source/e2e-data-source.ts
- sources/packages/backend/libs/test-utils/src/factories/student-loan-balance.ts
- sources/packages/backend/libs/test-utils/src/index.ts
- sources/packages/web/src/services/StudentLoanBalanceService.ts
- sources/packages/web/src/services/http/StudentLoanBalanceApi.ts
Following files are copied from the PR #3036  as this story has dependency on #3018 
```
sources/packages/backend/apps/db-migrations/src/migrations/1711342815738-CreateStudentLoanBalances.ts
sources/packages/backend/apps/db-migrations/src/sql/StudentLoanBalances/Create-student-loan-balances.sql
sources/packages/backend/apps/db-migrations/src/sql/StudentLoanBalances/Rollback-create-student-loan-balances.sql
sources/packages/backend/libs/sims-db/src/constant.ts
sources/packages/backend/libs/sims-db/src/entities/student-loan-balances.model.ts
```
> #2694 - PT life time maximum part 2

- sources/packages/backend/apps/api/src/services/student/student.service.ts
Add a system note upon student creation when there is a legacy system match. 
The note is further down in the code than suggested in the ticket so that the student has been created and has an id to use for the note.
> #2852 - SFAS SAIL Student Data Match Import Note

- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2021-2022.bpmn
- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2023-2024.bpmn
- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2024-2025.bpmn
> #2875 - Exclude student dependents born after study end date

- sources/packages/backend/apps/api/src/route-controllers/application-exception/_tests_/e2e/application-exception.aest.approveException.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-exception/application-exception.aest.controller.ts
- sources/packages/backend/libs/services/src/workflow/workflow-client.service.ts
When application exception is verified by ministry (Approved or Declined), message is sent to workflow with correlation id, so that the workflow can proceed for further processing.
The workflow expects a message with name `application-exception-verified` and correlation id `${applicationId}` but it was receiving a message with correlation id `${applicationExceptionId}` and hence the message was not accepted and processed by workflow.
Updated the code to send `applicationId` as correlation id for the message.
> #3076 - Application exception bug fix

- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/costs/parttime-assessment-costs-child-care-cost.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/eligibility/parttime-assessment-eligibility-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/costs/parttime-assessment-costs-child-care-cost.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/eligibility/parttime-assessment-eligibility-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/costs/parttime-assessment-costs-child-care-cost.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/eligibility/parttime-assessment-eligibility-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/test-utils/factories/student-dependent.ts
**Motive of tests:** To workflow E2E tests that validate outputs based on student dependents (e.g CSGD award eligibility, child care cost calculation), add tests with dependant born after study end date and ensure that dependant is not included as eligible dependant for any calculations.
> #2875 - Newborn dependant born after study end date E2E

- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.aest.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts
- sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts
- sources/packages/web/src/components/common/AssessmentAwardDetails.vue
- sources/packages/web/src/components/common/AwardTable.vue
- sources/packages/web/src/components/common/students/applicationDetails/AssessmentAward.vue
- sources/packages/web/src/services/http/dto/Assessment.dto.ts
- sources/packages/web/src/views/aest/student/applicationDetails/AssessmentAward.vue
- The UI page has some components and some duplicated logic already when the application has two disbursements. This behavior has not changed. Some refactors in the future can improve this page.
- Two minor bugs were found from the previous PR, a missing assessment ID in a SQL query and `null` values returned for a second disbursement (the expectation was to not return null awards.)
- Disbursement pending: "The final award can't be calculated at this time." (previously COE Required)
- Disbursement sent: no message expected since we will display the values.
- COE Declined: "The final award is no longer applicable due to a change. Any scheduled disbursements will be canceled." (Same as before)
- Disbursement pending: "The final award can't be calculated at this time." (previously COE …
> #2958 - Part-time Final Award From e-Certs - UI

- sources/packages/backend/apps/api/src/services/institution-location/institution-location.service.ts
Due to a missing institution ID Typeorm was trying to create an institution because the modal is also defined with `cascade: true`.
This is blocking the demo of the other sprint ticket and **the fix is intended to allow the Student Application to be submitted**.
API Error:
```console
[Nest] 17 - 04/23/2024, 9:35:27 PM LOG [SequenceControlService] Persisting new sequence number to database...
query failed: INSERT INTO "sims"."institutions"("created_at", "updated_at", "business_guid", "legal_operating_name", "operating_name", "primary_phone", "primary_email", "website", "regulating_body", "other_regulating_body", "established_date", "primary_contact", "institution_address", "creator", "modifier", "institution_type_id") VALUES (DEFAULT, DEFAULT, DEFAULT, $1, $2, DEFAULT, $3, DEFAULT, …
```
> #2369 - Added missing institution id to prevent institution creation from Typeorm

- .vscode/launch.json
- sources/packages/backend/webpack.config.js
Over the past weeks, the debug was not working properly due to the `devtool` configuration (that is the assumption). The configuration we have right now is the [right one for production](https://webpack.js.org/configuration/devtool/#devtool) and to produce the correct stack trace for errors but it was preventing the debugging from properly working. 
A further investigation was not done and the current change is not supposed to affect production, hence it is intended only to quickly bring back the debug functionality.
Besides that, new configurations were added to allow the debugging of the backend applications. Below are the benefits.
- Start the application with the debugger attached.
- Allow application modification keeping the debugger attached.
- Allow the debugging of multiple …
> Fix Webpack Config and Enable Multiple Debug

- sims.code-workspace
- sources/packages/backend/libs/services/src/report/report.service.ts
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
The backend is currently using the [papaparse ](https://www.npmjs.com/package/papaparse) lib to read CSVs from the bulk file uploads and the same library has a method to convert objects to CSV ([unparse](https://www.papaparse.com/docs)).
Used the `Data Inventory Report` as a POC, changing a user first name to a string with characters that would break the CSV generation.
- Input string: `Testing "quotes" and comma, and more; characters, and values $45.123,21!`
- Escaped string: `"Testing ""quotes"" and comma, and more; characters, and values $45.123,21!"`
Typeorm will produce an object as below. The property names are enclosed in single or double quotes depending on their content. Please see the difference between `'Application Number'`, `'First Name with quotes " in the name and ,coma'`, …
> #2589 - Use a CSV parser library for the report service

- sources/packages/backend/package.json
- sources/packages/backend/webpack.config.js
The PR #3188 introduced an issue where the SQL files expected to be copied by the `copy-webpack-plugin` during the `webpack` build are no longer copied.
The current check was failing because the ENV variable was not present at "build time" and new syntax was also affecting the `plugins` configuration.
A new env variable (`DEBUG`) was introduced only to allow the `webpack` to be aware of the `devtools` expected value.
> Queue-consumers Fail to Start 

- sources/packages/backend/apps/api/src/route-controllers/confirmation-of-enrollment/_tests_/e2e/confirmation-of-enrollment.institutions.denyConfirmationOfEnrollment.e2e-spec.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/confirmation-of-enrollment.service.ts
- sources/packages/web/src/components/students/applicationTracker/DisbursementBanner.vue
- sources/packages/web/src/components/students/applicationTracker/MultipleDisbursementBanner.vue
> #2650 - Cancel Future Disbursements if COE is declined (Bug)

- sources/packages/backend/apps/api/src/app.institutions.module.ts
- sources/packages/backend/apps/api/src/route-controllers/report/models/report.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/report/report.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/report/report.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/report/report.institutions.controller.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1715153766792-OfferingDetailsReport.ts
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Create-offering-details-report.sql
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-create-offering-details-report.sql
- SQL query for **Offering Details Report**.
**Query:**
```sql
SELECT
institution_locations.institution_code AS "Institution Location Code",
education_programs.program_name AS "Program",
education_programs.sabc_code AS "SABC Program Code",
education_programs_offerings.offering_name AS "Offering Name",
education_programs_offerings.year_of_study AS "Year of Study",
education_programs_offerings.offering_intensity AS "Offering Intensity",
education_programs_offerings.course_load AS "Course Load",
education_programs_offerings.offering_delivered AS "Delivery Type",
education_programs_offerings.has_offering_wil_component AS "WIL Component",
education_programs_offerings.offering_wil_type AS "WIL Component Type",
education_programs_offerings.study_start_date AS "Start Date", …
```
> #3062 - Enable Reports for BC Public Institutions (Part 3)

- sources/packages/web/src/views/student/StudentApplicationDetails.vue
- Checked how to change the current dropdown menu to allow tab navigation across all its subitems.
- Implemented the solution in the application tracker landing page present in the image above.
Screenshot of the button for the Completed tracker card
Screenshot of the button for the Assessment tracker card
> #3141 - 2.4.3 Menu- Student- Accessibility Fixes - Level A - Focus Order

- sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/web/src/components/students/applicationTracker/Completed.vue
- sources/packages/web/src/components/students/applicationTracker/DisbursementBanner.vue
- sources/packages/web/src/components/students/applicationTracker/MultipleDisbursementBanner.vue
- sources/packages/web/src/services/http/dto/Application.dto.ts
Reassessments were not displaying a card while the assessment was `In progress` because there was an expectation that at least the first disbursement would always be present, which is true only when the assessment workflow is completed.
The UI was already completely ready expecting the `first disbursement` not to be present, but the API was throwing an error every time.
> #3040 - Allow the first disbursement to be not present

- sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts
- sources/packages/backend/apps/workers/src/services/student-assessment/student-assessment.service.ts
- `workflow-wrap-up` worker was updated to populate the new column `previous_date_changed_reported_assessment_id` for an application in `Completed` state. The following were considered when updating the worker:
**Scenario 1**
Checked if there is a previously reported assessment for the application (ordered by assessment_date desc, limit 1), immediately before the assessment being processed right now.
**Scenario 2**
If no assessment was ever reported, checked if an e-Cert was generated for this application.
**If Scenario 1 or Scenario 2 produced an assessment:**
Checked if the offering dates changed,
If yes, saved the assessment in the `previous_date_changed_reported_assessment_id`.
If no, then left the column as is.
**Generated Queries for reference:**
```sql
-- SELECT 1st
SELECT …
```
> #3282 - Detect Assessment Offering Dates Change (Part 2)

- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-workflowWrapUp.e2e-spec.ts
- sources/packages/backend/libs/test-utils/src/factories/education-program-offering.ts
- sources/packages/backend/libs/test-utils/src/factories/education-program.ts
- sources/packages/backend/libs/test-utils/src/factories/student-assessment.ts
AssessmentController(e2e)-workflowWrapUp
√ Should populate the previousDateChangedReportedAssessment when the e-Cert was generated for the 'Original Assessment' and offering dates changed as a result of the reassessment. 
√ Should not populate the previousDateChangedReportedAssessment when the e-Cert was generated for the 'Original Assessment' and offering dates didn't change as a result of the reassessment.
√ Should not populate the previousDateChangedReportedAssessment when the e-Cert is not generated for the 'Original Assessment' and offering dates changed as a result of the reassessment.   
√ Should populate the previousDateChangedReportedAssessment with the most recent reported reassessment when there are previously reported reassessments.
√ Should not populate the …
> #3282 - Detect Assessment Offering Dates Change - Part 3 (e2e tests)

- sources/packages/web/src/views/student/AppStudent.vue
- Update student portal menu so that all items can be tabbed through. Currently, after the menu is opened, tabbing closes the menu.
- Reuse the same solution from the ticket
> #3096 - 2.1.1 Menu Navigation- Student- Accessibility Fixes - Level A - Keyboard

- sources/packages/backend/apps/api/src/route-controllers/institution/institution.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/institution/institution.controller.service.ts
- sources/packages/backend/apps/api/src/services/institution/institution.service.ts
- sources/packages/forms/src/form-definitions/exportfinancialreports.json
- sources/packages/web/src/components/common/Reports.vue
- sources/packages/web/src/composables/useFormioDropdownLoader.ts
- sources/packages/web/src/services/InstitutionService.ts
- sources/packages/web/src/services/http/InstitutionApi.ts
- sources/packages/web/src/types/formio.ts
- sources/packages/web/src/views/aest/Reports.vue
As part of this story, the frontend UI/UX and partial backend have been completed in this PR
- Added Form.io changes for the report. Update form for the filter logic specific to the report. Also related Vue changes.
- Added new options API to get the institution name dropdown values.
- Added report filters:
- Institution operating name dropdown
- SABC program code - Free text input restricted to 4 characters max. (Optional)
Screenshot of the Ministry Reports with new elements
Screenshot of the Institution Name dropdown content
> #3140 - Build Ministry-Specific Reports - Programs and Offering Status (Part 1)

- sources/packages/backend/workflow/src/deploy.ts
Changed the Zeebe healthy check to wait till some partition is healthy instead of using `every`.
`every` returns true when the array is empty, which is not desirable in this situation.
Using `some` will ensure that at least one partition is available to accept the deploy commands.
```json
{
"brokers": [
{
"partitions": [
{
"partitionId": 1,
"role": "LEADER",
"health": "HEALTHY"
}
],
"nodeId": 0,
"host": "172.18.0.2",
"port": 26501,
"version": "8.5.0"
}
],
"clusterSize": 1,
"partitionsCount": 1,
"replicationFactor": 1,
"gatewayVersion": "8.5.0"
}
```
```json
{
"brokers": [],
"clusterSize": 1,
"partitionsCount": 1,
"replicationFactor": 1,
"gatewayVersion": "8.5.0"
}
```
```json
{
"brokers": [
{
"partitions": [],
"nodeId": 0,
"host": "172.18.0.2",
"port": 26501,
"version": "8.5.0"
}
], …
```
> #3105 - Camunda Definitions Deployment Healthy Check

- sources/packages/backend/apps/db-migrations/src/migrations/1718842224620-UpdateProgramAndOfferingStatusReport.ts
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Create-program-and-offering-status-report.sql
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-update-program-and-offering-status-report.sql
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Update-program-and-offering-status-report.sql
The following issues have been fixed in the `Update-program-and-offering-status-report.sql` file.
- Dates displaying timestamp on "Program Expiry Date" 
```sql
CAST(
education_programs.effective_end_date AS varchar
) AS "Program Expiry Date",
```
> #3140 - Build Ministry-Specific Reports - Programs and Offering Status (Quick Fix)

- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
Updating Camunda8 SDK to resolve the below security issue in its dependency (https://github.com/bcgov/SIMS/pull/3437).
> #3105 - Camunda8 SDK Updated

- devops/openshift/queue-consumers-deploy.yml
- Since the ClamAV port is passed from the Makefile, it should be set to `required: true` in the queue-consumers-deploy.yml
> #3377- Virus Scanning bug Fix

- sources/Makefile
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- Upgraded Camunda SDK to the latest version.
- Upgraded local Camunda versions to the latest available from https://github.com/camunda/camunda-platform/blob/main/.env
> Camunda SDK and Camunda Localhost Upgrade

- devops/Makefile
- devops/openshift/queue-consumers-deploy.yml
- Removed the params in the Makefile for queue-consumers deploy;
- Renamed params in queue-consumers-deploy.yml to end with "_NAME_KEY" instead of "_KEY".
> #3255 - CAS - deploy error fix

- devops/Makefile
- Removed params from the command that calls the deploy.
> #3255 - CAS - deploy error fix - 2

- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/backend/libs/sims-db/src/entities/application-student-file.model.ts
As per the analysis, student files are never deleted, only the relationship between an application and its files is deleted while the application is in draft. Once the application is summited the file relations are no longer deleted.
According to the confirmation from @CarlyCotton and @Joshua-Lakusta, there are no concerns about keeping the current behavior since the application only starts to matter when submitted.
Student application files were never updated from their `Temporary` status because the status was added later.
This PR is now updating the file origin when an application is saved.
> #1366 - Set FileOriginType for Student Application Files

- sources/packages/backend/apps/db-migrations/src/sql/Queue/Rollback-drop-fin-process-provincial-daily-disbursements-integration.sql
**Bug:** Migration revert for `Rollback-drop-fin-process-provincial-daily-disbursements-integration.sql` was failing on staging environment because of the missing `sims` schema name and the `queue_settings` not nullable column.
**Fix:** Fixed the query.
**Note:** Tested the migration reverts till the v1.9.0 release to ensure that all the migration reverts are happening properly.
> #3560 - Migration revert bug fix

- sources/packages/web/src/services/FormUploadService.ts
**Bug:** The text of the file was not displaying properly. Instead, it was displaying `[Object object]`
**Fix:** Updated the `FormUploadService` `downloadFile` method return object.
> #2973 - File Uploader UI Bug Fix

- sources/packages/backend/apps/db-migrations/src/sql/Queue/Rollback-drop-fin-process-provincial-daily-disbursements-integration.sql
**Bug:** Migration revert for
`Rollback-drop-fin-process-provincial-daily-disbursements-integration.sql` was failing on staging environment because of the missing `sims` schema name and the `queue_settings` not nullable column.
**Fix:** Fixed the query.
**Note:** Tested the migration reverts till the v1.9.0 release to ensure that all the migration reverts are happening properly.
> #3560 - Migration revert bug fix (#3559)

- sources/packages/backend/apps/api/src/constants/error-code.constants.ts
- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.aest.controller.getUploadedFile.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.aest.controller.searchStudents.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.students.controller.getUploadedFile.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.students.controller.ts
- sources/packages/backend/apps/api/src/services/student-file/student-file.service.ts
- sources/packages/backend/apps/queue-consumers/src/processors/virus-scan/_tests_/virus-scan.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/virus-scan/virus-scan.processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/student-file/student-file.service.ts
- sources/packages/backend/apps/queue-consumers/test/helpers/testing-modules/testing-modules-helper.ts
- sources/packages/backend/libs/services/src/queue/index.ts
- sources/packages/backend/libs/sims-db/src/entities/index.ts
- sources/packages/backend/libs/test-utils/src/factories/student-file-uploads.ts
- sources/packages/web/src/composables/useFileUtils.ts
- sources/packages/web/src/constants/error-code.constants.ts
- sources/packages/web/src/services/FormUploadService.ts
- sources/packages/web/src/services/StudentService.ts
- sources/packages/web/src/services/http/common/HttpBaseClient.ts
- Added [a logic](https://github.com/bcgov/SIMS/blob/8f38efe285b71f1d3ccac08a4a63691da972c9ac/sources/packages/backend/apps/api/src/services/student-file/student-file.service.ts#L123) to block any `fileContent` to be downloaded if the file is infected;
-  Added [a logic](https://github.com/bcgov/SIMS/blob/8f38efe285b71f1d3ccac08a4a63691da972c9ac/sources/packages/backend/apps/queue-consumers/src/services/student-file/student-file.service.ts#L55) to update the name of the file along with the status for infected files;
- Created [centralized logic](https://github.com/bcgov/SIMS/blob/8f38efe285b71f1d3ccac08a4a63691da972c9ac/sources/packages/web/src/composables/useFileUtils.ts#L69) to handle file scan process errors;
- Added [clamAVServiceMock](https://github.com/bcgov/SIMS/blob/8f38efe285b71f1 …
> #3297 - Virus Scanning - Ministry User File Interactions

- sources/packages/backend/workflow/test/models/assessment.model.ts
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
Label and tooltip
Part time:
Full time:
- `youthInCare` is only compared to "yes" in the workflow and it's just displayed as it is in the reports, so there's no impact adding a new value to this radio set.
- Some of the changes are regarding putting SFAA* files in sync (issue from a previous PR not related to this ticket)
> #2826 - Update to Youth in Care Question (content & radio option) 

- sources/packages/backend/apps/db-migrations/src/migrations/1723651012387-AddApplicationChangesReportIntegration.ts
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Add-application-changes-report-integration.sql
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Rollback-add-application-changes-report-integration.sql
- sources/packages/backend/apps/queue-consumers/src/processors/index.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/application-changes-report-integration/application-changes-report-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/queue-consumers.module.ts
- sources/packages/backend/libs/utilities/src/queue.constant.ts
> #2499 - Application changes report scheduler setup

- sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.supporting-users.controller.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723231015871-CreateHistoryEntryFunction.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723231119349-CreateUsersHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723239334876-CreateStudentsHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723494302501-CreateSupportingUsersHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723494314291-CreateInstitutionsHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723494323451-CreateInstitutionLocationsHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723494334204-CreateEducationProgramsHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1723494349958-CreateEducationProgramsOfferingsHistoryTable.ts
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Create-education-programs-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Rollback-create-education-programs-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationProgramsOfferings/Create-education-programs-offerings-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationProgramsOfferings/Rollback-create-education-programs-offerings-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/Functions/Create-function-create-history-entry.sql
- sources/packages/backend/apps/db-migrations/src/sql/Functions/Rollback-create-function-create-history-entry.sql
- sources/packages/backend/apps/db-migrations/src/sql/Institution/Create-institutions-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/Institution/Rollback-create-institutions-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/InstitutionLocations/Create-institution-locations-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/InstitutionLocations/Rollback-create-institution-locations-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/Student/Create-student-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/Student/Rollback-create-student-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/SupportingUsers/Create-supporting-users-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/SupportingUsers/Rollback-create-supporting-users-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/User/Create-user-history-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/User/Rollback-create-user-history-table.sql
- sources/packages/backend/apps/workers/src/services/supporting-user/supporting-user.service.ts
This PR is the result a cherry-pick from reverted PRs #3618 and #3627. These PRs were reverted by #3631 to allow the history tables to be created following exactly the same column orders from the DB it is being deployed.
The only real change not reviewed previously is the below. All other files were kept as they were. The description below is also a combination from the previous reverted PRs (the rollback evidences are new).
```sql
CREATE TABLE sims.supporting_users_history AS
SELECT
CURRENT_TIMESTAMP AS history_timestamp,
'' :: varchar(50) AS history_operation,
*
FROM
sims.supporting_users
WHERE
false;
```
- Created a generic function `create_history_entry` to be associated with every table that would need a history.
- Created the history tables for the required tables.
- Tables were …
> #3223 - Create history/journal tables for auditing purposes

- devops/helm/crunchy-postgres/Makefile
- devops/helm/crunchy-postgres/value-0c27fb-prod.yaml
- devops/helm/crunchy-postgres/values-0c27fb-dev.yaml
- devops/helm/crunchy-postgres/values-0c27fb-test.yaml
- devops/helm/crunchy-postgres/values-a6ef19-dev.yaml
- devops/helm/crunchy-postgres/values-a6ef19-prod.yaml
- devops/helm/crunchy-postgres/values-a6ef19-test.yaml
- Crunchy PVC DB size changed to 5Gi as initial size.
- -f values are removed in the makefile, as it was going always to the default values.yml and it was not needed. I found while testing so changed it now.
> #3268- Crunchy DB PVC size change

- sources/packages/web/public/index.html
- sources/packages/web/src/main.ts
- Added the `integraty` and `crossorigin` following the WAVA scan recommendation.
Checked the BC Gov for other projects using the same `.css` ([see search results](https://github.com/search?q=org%3Abcgov%20formio.full.min.css&type=code)).
No other projects are using the `integrity` property. Please see below com of the CDNs used.
- https://cdn.jsdelivr.net/npm/formiojs@4.13.1/dist/formio.full.min.css
- https://cdn.form.io/formiojs/4.13.1/formio.full.min.css
- https://cdn.form.io/formiojs/formio.full.min.css
We can use the CSS directly imported from the package in the web app. Right now the decision was to have it imported in the `main.ts` following the same from other packages dependent on styles.
```ts
import "formiojs/dist/formio.full.min.css";
```
Or we can use a CDN as below.
```html …
```
> #3610 - Missing check for SRI (Subresource Integrity) support

- sources/packages/backend/apps/api/src/route-controllers/report/report.controller.service.ts
- sources/packages/backend/libs/utilities/src/system-configurations-constants.ts
Currently, in reports controller we set the `Content-Length` header value as length of the csv string.  
Due to this, we have an issue when the string involves special characters as the size of these characters are more than one byte.
e.g. When a string of length 100 characters has one special character like `â` in it, then string length is `100` but the byte length is `101`. Hence when this is set in API response it eliminates any characters which is more than set content length. 
Like this
Set `content-length` header with byte length.
> #3131 - Fix content length to be based on byte lenth

- sources/packages/backend/apps/api/src/route-controllers/student-appeal/_tests_/e2e/student-appeal.aest.controller.getAppeals.e2e-spec.ts
- sources/packages/backend/apps/api/src/services/student-appeal/student-appeal.service.ts
- sources/packages/backend/libs/test-utils/src/factories/student-appeal-request.ts
- sources/packages/web/src/views/aest/student/StudentApplicationAppeals.vue
Appeals Tab as a Ministry User is not displaying the number of appeals properly.
Fix is done on the query returned on the appeals, removed the unwanted join on the appealRequests table.
The count that is passed on the header to show the total appeals, is fixed.
> #3595 - Ministry Login - Appeals dashboard bug

- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- Uploader is now shown for all the 4 radio options when either of them is selected as shown below:
Likewise, the uploader will show for the other radio buttons as well.
- Fixed the radio option text as below:
`You will have completed 4 years of full-time post-secondary study in B.C. before the first day of your study period.`
> #3500 - Upload supporting documents bug fix

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/disbursement/_tests_/e2e/disbursement.controller.saveDisbursementSchedules.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/disbursement/_tests_/e2e/save-disbursement-schedules-payloads.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/part-time-calculation-process.ts
- Removed the `applyOverawardsDeductionsStep` from part-time e-Cert process.
- Created the below E2E tests.
- `queue-consumers`: Should create an e-Cert with no overaward deductions when the student has overawards.
- `workers`: Should generate an overaward and deduct grants already paid for a part-time application when a reassessment happens and the student is entitled to less money.
> #3525 - Remove Overawards Deductions from PT e-Cert

- sources/packages/backend/apps/db-migrations/src/migrations/1726275056327-AddStopPartTimeBCFundingRestrictionActionType.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1726275219662-UpdateRestrictionsReviewImpact.ts
- sources/packages/backend/apps/db-migrations/src/sql/Restrictions/Rollback-update-restrictions-review-impact.sql
- sources/packages/backend/apps/db-migrations/src/sql/Restrictions/Update-restrictions-review-impact.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Add-stop-part-time-bc-funding-restriction-action-type.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-add-stop-part-time-bc-funding-restriction-action-type.sql
- sources/packages/backend/libs/sims-db/src/entities/restriction-action-type.type.ts
- Created a DB migration to update the `sims.restriction_action_types` enum to include "Stop part time BC funding".
- Used "part time" without capitalized letters for "Stop part time BC funding" to be consistent with existing convention across FT/PT restrictions.
- Created a DB migration to update the `sims.restrictions`. Updated restrictions per the spreadsheet to ensure all behaviors and names are updated. ALL CHANGES ARE IN HIGHLIGHTED CELLS
- Updated `action_type` for the restriction code _5_, _7_ and _9_.
- Updated `action_type` for the restriction code _12_, _O_ and _PTWTHD_.
- Updated `restriction_code`, `action_type` for the restriction code _APPC_.
- Updated `restriction_type`, `description`, `restriction_category` for the restriction code _B6_.
- Updated `description`, …
> #3512 - Review Impact of All Restrictions

- .github/workflows/env-setup-build-forms-server.yml
- .github/workflows/env-setup-deploy-forms-server.yml
- devops/Makefile
- sources/Makefile
- sources/packages/forms/Dockerfile
- sources/packages/forms/Dockerfile.dev
- sources/packages/forms/package-lock.json
- sources/packages/forms/package.json
- sources/packages/web/package-lock.json
- sources/packages/web/package.json
- Upgraded form.io server to [v4.2.4](https://github.com/formio/formio/releases/tag/v4.2.4).
- Updated nodejs version as required by the new form.io version (there is a check and it requires at least Nodejs 20).
- The current redirect in the PROD docker using `NPM_PACKAGES` caused issues to a form.io package `@formio/vm`. The redirect of the `NPM_PACKAGES` was removed.
- Upgraded Vue client lib to `4.21.4`.
- Smoke test
- New student prole;
- New institution;
- New location;
- New designation agreement;
- New program and program approval;
- New offering and offering approval;
- New student application.
- Form.io build and deploy were always happening from the main branch. They are now happening from the GitHub action target branch as the others.
- `define FORMIO_SOURCE_REPO_TAG` was …
> #2509 - Update formio server and js

- sources/packages/forms/src/form-definitions/studentdependantsappeal.json
- sources/packages/forms/src/form-definitions/supportingusersparent2022-2023.json
- sources/packages/forms/src/form-definitions/supportingusersparent2024-2025.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2022-2023.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2024-2025.json
- sources/packages/forms/src/form-definitions/uploadstudentdocuments.json
Removed the `<strong>` tags from labels content.
The change does not impact the form.io layout. As shown below the labels are still bold.
> #2509 - Update formio server and js - Labels adjustment

- sources/packages/web/src/services/AuthService.ts
The BCSC user needs to be redirected to keycloak's logout url while BCeID users do a `executeSiteminderLogoff()`.
> #3668 - Fix for logout BCSC user bug

- sources/packages/web/src/services/AuthService.ts
The invalid beta user was being sent to the dashboard before being redirected to the login page with an invalid beta user message.
> #3668 - Send the invalid beta user immediately to login page

- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2022-2023.bpmn
- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2023-2024.bpmn
- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2024-2025.bpmn
- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-decisions.dmn
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/costs/parttime-assessment-costs-program-related-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/costs/parttime-assessment-transportation-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/costs/parttime-assessment-costs-program-related-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/costs/parttime-assessment-transportation-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/costs/parttime-assessment-costs-program-related-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/costs/parttime-assessment-transportation-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/models/assessment.model.ts
- sources/packages/forms/Dockerfile.dev
- Added `limitWeeklyBooksAndSupplies` to `dmnPartTimeProgramYearMaximums`:
- Changed calculatedDataProgramRelatedCosts to check the minimum between `offeringProgramRelatedCosts` and `dmnPartTimeProgramYearMaximums.limitWeeklyBooksAndSupplies * offeringWeeks`:
- Added offering delivery "blended" to allow  `calculatedDataWeeklyMinTransport` to receive `dmnPartTimeProgramYearMaximums.limitTransportationAllowance`:
- Added offering delivery "blended" to allow  `inputDataRemainingTransportWeeks` to receive the value of `offeringWeeks - calculatedDataAdditionalTransportWeeks`
- Added offering delivery "blended" to allow  `calculatedDataTotalTransportationAllowance` to receive the value of `offeringWeeks * dmnPartTimeProgramYearMaximums.limitTransportationAllowance`
- Added tests to check …
> #3721 - PT Assessment - Books and Supplies Limit

- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.aest.controller.updateProfileInformation.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/models/student.dto.ts
- sources/packages/backend/apps/api/src/services/student/student.service.ts
`StudentAESTController(e2e)-updateProfileInformation`
√ Should allow the student profile update when the student is a Basic BCeID user. (5472 ms)
√ Should throw an HTTP Unprocessable Entity (422) error when the student is not a Basic BCeID user. (2619 ms)
√ Should throw an HTTP Forbidden (403) error when the ministry user performing the profile update does not have the associated role. (497 ms)
√ Should throw an HTTP Unprocessable Entity (422) error when the student is a Basic BCeID user but none of the user profile information that needs to be updated has changed. (3076 ms)
√ Should throw an HTTP Not Found (404) error when the student does not exist. (514 ms)
√ Should throw an HTTP Bad Request error when some mandatory profile update information is missing from the payload. (7 ms)
√ …
> #3222 - Provide Ministry the ability to edit Basic BCeID Profile Info (e2e tests)

- sources/packages/web/src/services/http/EducationProgramApi.ts
- sources/packages/web/src/types/contracts/DataTableContract.ts
- sources/packages/web/src/views/aest/institution/Programs.vue
- Converted Prime Vue Table to Vuetify Data Table.
**Added the loader while the data table loads:**
----------------------------------------------------------------------------------------------------------------------------------
**Data table with data:**
----------------------------------------------------------------------------------------------------------------------------------
**Data table without any records:**
> #2741 - Ministry Filter: Search Programs & Offerings [Data Table Conversion to Vuetify]

- sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json
- Modified `maxMoneyValue` in Form.io definition "partnerinformationandincomeappeal.json" to fix the backend error due to failure in Form.io dryRun validation in my previous while submitting an appeal.
- Unchecked "table view"
- Checked "Calculate on server"
Screenshot of backend error due to Form.io definition
Screenshot of successful backend log with the current change
> #3620 - Change Request - Partner Current Year Income (financial information) option (Quick Fix)

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/_tests_/cas-supplier-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-evaluation-result-processor/cas-active-supplier-and-site-found-processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-evaluation-result-processor/cas-active-supplier-found-processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-evaluation-result-processor/cas-active-supplier-not-found-processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-evaluation-result-processor/cas-evaluation-result-processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-evaluation-result-processor/cas-pre-validations-processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-supplier.service.ts
- sources/packages/backend/apps/queue-consumers/test/helpers/mock-utils/cas-service.mock.ts
- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.getSupplierInfoFromCAS.spec.ts
- sources/packages/backend/libs/integrations/src/cas/cas-cached-auth-details.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- sources/packages/backend/libs/integrations/src/cas/index.ts
- sources/packages/backend/libs/integrations/src/cas/models/cas-service.model.ts
As agreed in the previous PR, the CAS authentication is now encapsulated inside the CAS API service and the auth token no longer needs to be passed to every method.
The current CAS token expiration is set to 1 hour and the token will be considered "about to expire" one minute before it.
> #3260 - CAS Integration 3A - Create new Supplier and Site - Refactor CAS authentication

- sources/packages/backend/apps/db-migrations/src/migrations/1729785100207-UpdateCASSupplierIntegrationScheduler.ts
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Rollback-update-cas-supplier-integration.sql
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Update-cas-supplier-integration.sql
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/_tests_/cas-supplier-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/cas-supplier-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/utilities/log-utils.ts
- sources/packages/backend/libs/integrations/src/cas/cas-formatters.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- sources/packages/backend/libs/utilities/src/_tests_/unit/string-utils.translateToASCII.spec.ts
- sources/packages/backend/libs/utilities/src/address-utils.ts
- sources/packages/backend/libs/utilities/src/string-utils.ts
- Changed the to allow throwing an error when some error is present in the process summary error attending the below AC.
```
If some error is present throw in the scheduler to allow it to be retried.
```
- Added the below E2E to test the above change.
- Should throw an error for the first student and process the second one when the CAS API call failed for the first student but worked for the second one.
- Adjusted the scheduler to be executed during weekdays only attending the below AC (`0 20 * * 1-5`).
```
Schedule these to go once a day at noon during weekdays for now.
```
- `COUNTRY_CANADA` was defined as "canada" when it is defined as "Canada" is all form.io definitions leading to an incorrect logic.
- SFTP issue while providing the file content as a string instead of a Buffer as …
> #3260 - CAS Integration 3A - Create new Supplier and Site - Retry on Error and Scheduler Time

- sources/packages/web/src/components/common/AssessmentAwardDetails.vue
- sources/packages/web/src/components/common/AwardTable.vue
- sources/packages/web/src/components/common/students/applicationDetails/AssessmentAward.vue
- sources/packages/web/src/composables/useFormatters.ts
- sources/packages/web/src/constants/award-constants.ts
- Revised "Summary" to "Funding summary"
- Revised "To view your entire assessment....." to "To view your Notice of Assessment, click on view assessment".
- Format all values: $##,###.00
- Updated the following grant names, reorder based on the list below, apply changes to both estimated and final award.
- CSGP
- Revised "CSGP" to "CSG-PD"
- Updated tooltip: "Canada Student Grant for Students with Disabilities"
- CSPT
- Revised "CSPT" to "CSG-PT"
- Updated tooltip: "Canada Student Grant for Part-time Students"
- CSGD
- Revised "CSGD" to "CSG-PTDEP"
- Updated tooltip: "Canada Student Grant for Students with Dependants"
- BCAG
- Revised "BCAG" to "BCAG-PT"
- Updated tooltip: "B.C. Access Grant for Part-time Studies"
- CSLP
- Revise: "CSLP" to "CSL-PT"
- Updated tooltip: "Canada Student Loan …
> #3697 - View Assessment Updates

- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-supplier.service.ts
- sources/packages/backend/apps/queue-consumers/test/helpers/mock-utils/cas-service.mock.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- sources/packages/backend/libs/utilities/src/parallel-processing-utils.ts
- Adjusted supplier's processes to happen in parallel.
- Reduced the amount of allowed parallel processes to 2 to 4. Previously it was using the "os cores" as the default value which could potentially be up to 32 while running on Openshift.
> #3260 - CAS Integration 3A - Create new Supplier and Site - Process in Parallel

- sources/packages/backend/apps/db-migrations/src/migrations/1729880822018-SINValidationsGenderSentLengthIncrease.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1729880822018-SinValidationsGenderSentIncreaseLength.ts
- sources/packages/backend/apps/db-migrations/src/sql/SINValidations/Alter-column-gender-sent.sql
- sources/packages/backend/apps/db-migrations/src/sql/SINValidations/Rollback-alter-column-gender-sent.sql
Altered sims.sin_validations.gender_sent to be VARCHAR(50).
Tested with a pending SIN Validation:
After running sin-validation-process-integration:
Revert:
> #3833 - SIN Validation - Gender Field Limit

- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas-test.utils.ts
- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.createSupplierAndSite.spec.ts
- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.getSupplierInfoFromCAS.spec.ts
- sources/packages/backend/libs/integrations/src/cas/cas-formatters.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- sources/packages/backend/libs/integrations/src/constants/error-code.constants.ts
- Fixed the order that first and last names were provided to the formatter.
- Added the HTTP bad request logs for better troubleshooting while the final error handling ticket is pending.
> #3260 - CAS Integration 3A - Create new Supplier and Site - Name Fix And Error Log Improvement

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sims-to-sfas-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/index.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sims-to-sfas.processing.service.ts
- sources/packages/backend/libs/test-utils/src/data-source/e2e-data-source.ts
- sources/packages/backend/libs/test-utils/src/factories/student.ts
- sources/packages/backend/libs/test-utils/src/utils/date-utils.ts
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- To mock the current date(`new Date()`) returned, a new library [mockdate](https://www.npmjs.com/package/mockdate) has been added.
> #3738 - E2E Tests SIMS to SFAS

- sources/packages/backend/libs/services/src/clamav/services/clamav.service.ts
The error was possible to be reproducible in the local development machine using 17Kb files. Any file larger than 16Kb causes the error, which means that the default chunk size allocated for the stream buffer was exceeded.
The readable streams have two reading modes: [flowing and paused](https://nodejs.org/api/stream.html#two-reading-modes).
The connection to `clamav` server was open but was not receiving data for certain files, which led to the timeout. When the `passthroughStream.resume();` was added it resulted in the data being send immediately.
The `passthroughStream.readableFlowing` was defined as null, which means the below ([source](https://nodejs.org/api/stream.html#three-states))
- readable.readableFlowing === null
- readable.readableFlowing === false
- readable.readableFlowing …
> #3825 - Virus Scanning - Not functioning PROD

- sources/packages/web/src/views/institution/OfferingsUpload.vue
In Vuetify newer versions there's a [change on how VFileInput  deals with the model value](https://vuetifyjs.com/en/api/v-file-input/#props-model-value):
- If `multiple` prop is undefined or false, VFileInput will return a `File`. If true, it returns a `File[]`.
Instead of destructuring a file from an array, the model file can be used as the blob required.
> #3840 - Hotfix: Bulk uploads: Unexpected error while uploading the file displays when "Validate" or "Create now" are selected for valid bulk upload

- sources/packages/backend/apps/queue-consumers/src/constants/error-code.constants.ts
- sources/packages/backend/apps/queue-consumers/src/processors/virus-scan/_tests_/virus-scan.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/virus-scan/virus-scan.processor.ts
- sources/packages/backend/apps/queue-consumers/src/services/student-file/student-file.service.ts
- sources/packages/backend/libs/test-utils/src/mocks/object-storage-service-mock.ts
When starting a socket to send a file content to `clamav` using the passthrough and no content is sent, the connection stays open for an indefinite amount of time (over 5 minutes).
Changed queue-consumers to throw an error and remove the job, **same behavior when the file is not found**.
_We can have a separate ticket to apply validation for the file upload to avoid accepting empty files, but I considered it outside this hotfix issue._
ClamAV debug log when a empty file is send for scanning.
```
2024-10-31 08:32:55 node-clam: Initially testing socket/tcp connection to clamscan server.
2024-10-31 08:32:55 node-clam: Attempting to establish socket/TCP connection for "_ping"
2024-10-31 08:32:55 node-clam: using remote server: 172.18.0.6:3310
2024-10-31 08:32:55 node-clam: Established …
```
> #3825 - Virus Scanning - Empty File Check

- sims.code-workspace
- sources/packages/backend/apps/api/src/route-controllers/education-program/education-program.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/models/pagination.dto.ts
- sources/packages/backend/apps/api/src/services/education-program/constants.ts
- sources/packages/backend/apps/api/src/services/education-program/education-program.service.ts
- sources/packages/backend/apps/api/src/utilities/datatable-config.ts
- sources/packages/backend/apps/api/src/utilities/datatable-database-mapping-utils.ts
- sources/packages/web/src/components/generic/StatusChipProgram.vue
- sources/packages/web/src/constants/index.ts
- sources/packages/web/src/constants/program-constants.ts
- sources/packages/web/src/helpers/helpers/uri.ts
- sources/packages/web/src/types/contracts/DataTableContract.ts
- sources/packages/web/src/views/aest/institution/Programs.vue
- Added Location Search and Program Status Search for the institution programs in the UI. Each of the searches act as an `&&` operation.
- Added sorting for the Location Name and the Program Status columns.
-  Updated the `api` to include the `location` and the program status in the pagination for the search and updated the `sql` query fetching the result.
**Location Search and Program Status Search added:**
-----------------------------------------------------------------------------------------
**Location Search with Program Search Empty and Program Statuses: Pending and Inactive selected:**
------------------------------------------------------------------------------------------
**Both Location and Program Search with Program Statuses: Pending and Approved selected** …
> #2741 - Ministry Filter Search Programs and Offerings [Location and Program Status Search]

- sources/packages/backend/apps/api/src/app.exception.filter.ts
- sources/packages/backend/apps/api/src/main.ts
- sources/packages/backend/libs/integrations/src/cra-integration/cra-income-verification.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/fed-restriction-integration/fed-restriction.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-response.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/sin-validation/sin-validation.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/student-loan-balances/student-loan-balances.processing.service.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece-response.processing.service.ts
- sources/packages/backend/libs/integrations/src/services/ssh/sftp-integration-base.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.processing.service.ts
- sources/packages/backend/libs/utilities/src/logger/logger.service.ts
- Increase the log level at the `SFTPIntegrationBase` without disrupting the consumer's methods and try to limit the amount of refactoring.
- Deploy to PROD in the next possible release to allow troubleshooting of current intermittent issues while archiving files. 
- Adapted the `LoggerService.error` to receive a friendly error and log the error itself, keeping it compatible with the existing methods.
- Added log messages to all base SFTP operations in the `SFTPIntegrationBase`. The errors are reshown keeping the current behavior for current method consumers.
- Adjusted the API `mais.ts` that was using the log context.
- Adjusted the global error handler to generate only one log entry instead of three.
- Even though the `SFTPIntegrationBase` method is now generating more logs, the archive …
> #3889 - Increase Logging for SFTP and file handling

- sources/packages/backend/libs/integrations/src/esdc-integration/sin-validation/sin-validation.processing.service.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.processing.service.ts
Fix issues from the previous PR for better logging. The main log from the SFTP base would still work but ensuring the logs are added to the Job in some way makes it easier for troubleshooting.
The goal is to have all the methods following similar archive catch handling doing something closet to each other.
See the example below of a sample that will display errors and `causes`.
> #3889 - Increase Logging for SFTP and file handling - (Catch fix)

- sources/packages/backend/libs/integrations/src/services/ssh/sftp-integration-base.ts
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- Upgrade the [ssh2-sftp-client to version 11.0.0](https://www.npmjs.com/package/ssh2-sftp-client).
- Minor changes for the logging.
> #3889 - Increase Logging for SFTP and file handling - SSH Lib Upgrade

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/_tests_/cas-supplier-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-evaluation-result-processor/cas-active-supplier-found-processor.ts
- sources/packages/backend/apps/queue-consumers/test/helpers/mock-utils/cas-response.factory.ts
- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.createSiteForExistingSupplier.spec.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- sources/packages/backend/libs/integrations/src/cas/models/cas-service.model.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-supplier.ts
- If a Get Supplier Response is Successful and returns Active Supplier and NO active Sites, **Create New Site**
- If a Get Supplier Response is Successful and returns Active Supplier and ONE OR MANY active Site, Compare the Response AddressLine1 and Postal Code to SIMS address
- The address match logic was already added during the implementation of [#3260](https://github.com/bcgov/SIMS/issues/3260). 
- Created the new API `createExistingSupplierSite` call on CAS service.
- Fields to include: 
- SupplierNumber, 
- AddressLine1: Use first addressline from SIMS. Truncate if ours is longer than supported. Convert or omit special characters (like is done with other integrations). 
- City: Use as-is, 
- Province: Use abbreviated versions AB,BC,MB,NB,NL,NS,NT,NU,ON,PE,QC,YT, 
- Country, 
- …
> #3729 - CAS Integration 3B - Create New Site (Supplier found, Multiple Sites / No matching address)

- sources/packages/backend/apps/api/src/services/education-program/education-program.service.ts
As a part of this PR, the query to retrieve the list of programs was updated to ensure that the sort order of the retrieved list of programs has the correct order where the inactive programs comprise the programs that have `isActive = false` or the ones that have the `effectiveEndDate <= CURRENT_DATE`
> #2741 - Ministry Filter Search Programs and Offerings [Fix Expired Programs Sort Issue]

- sources/packages/backend/apps/api/src/auth/roles.enum.ts
- sources/packages/backend/apps/api/src/constants/error-code.constants.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/_tests_/e2e/application-restriction-bypass.aest.controller.bypassRestriction.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/_tests_/e2e/application-restriction-bypass.aest.controller.getApplicationRestrictionBypass.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/_tests_/e2e/application-restriction-bypass.aest.controller.getAvailableRestricitionsToBypass.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/_tests_/e2e/application-restriction-bypass.aest.controller.removeBypassRestriction.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/application-restriction-bypass.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/models/application-restriction-bypass.dto.ts
- sources/packages/backend/apps/api/src/services/application-restriction-bypass/application-restriction-bypass.models.ts
- sources/packages/backend/apps/api/src/services/application-restriction-bypass/application-restriction-bypass.service.ts
- sources/packages/backend/apps/api/src/services/index.ts
- sources/packages/backend/libs/sims-db/src/entities/student-restriction.model.ts
- sources/packages/backend/libs/test-utils/src/factories/application-restriction-bypass.ts
- sources/packages/backend/libs/test-utils/src/factories/student-restriction.ts
- sources/packages/backend/libs/test-utils/src/models/common.model.ts
- Created the api endpoints:
- GET aest/application-restriction-bypass/:id
- GET aest/application-restriction-bypass/application/:applicationId/options-list
- POST aest/application-restriction-bypass
- PATCH aest/application-restriction-bypass/:id
- Added new role "aest-bypass-student-restriction" only for business administrators;
- Added e2e tests:
- ApplicationRestrictionBypassAESTController(e2e)-bypassRestriction
√ Should be able to create a bypass when there is not an active bypass for the same student.                                                                                                                         
√ Should throw an HTTP error while creating a bypass when there is an active bypass for the same active student restriction. …
> #3691 - UX/UI for Ignore Restriction - Bypass Add/Remove - API part

- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/application-restriction-bypass.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application-restriction-bypass/models/application-restriction-bypass.dto.ts
Fix for the circular dependency error caused by anonymous TypeScript type.
> #3691 - Fix for the cyclic dependency

- sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt.processing.service.ts
- Updated expected file name for disbursement receipt file to `${this.esdcConfig.environmentCode}EDU\\.PBC\\.DIS.[0-9]{8}\\.[0-9]{3}`
Screenshot of the Bull Dashboard completed task with the disbursement schedule records not found
Screenshot of the Bull Dashboard completed task with the disbursement schedule records found
Screenshot of email received after successfully processing the disbursement receipt file
> #3920 - Update Expected Name for Disbursement File

- sources/packages/backend/apps/api/src/route-controllers/program-info-request/models/program-info-request.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/program-info-request/program-info-request.institutions.controller.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/forms/src/form-definitions/programinformationrequest.json
Issue: When a program is selected in a student application but study period is not selected and submitted for PIR review, the Institution PIR page was displaying the `program name` in the `program description` section.
> #3789 - Fix program description on Institution PIR Page

- sources/packages/web/src/components/common/restriction/ViewRestriction.vue
- Removed the check-role-permission decorator to allow ministry users without designated roles to close the modal as per AC
- The 'Close' button is not disabled for all users. Users without restriction edit access should be able to view it, not edit it and then close the modal without refreshing.
Screenshot
> #3943 - Bug - restriction view when access limited 

- sources/packages/backend/libs/services/src/queue/queue.module.ts
During the prior investigation was detected that when all the schedulers try to execute redis operations at the same time it fails after a certain amount of concurrent connections.
The possible solutions being investigated are:
1. Allow the connection sharing as mentioned here https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#reusing-redis-connections
2. Control the service initialization to prevent multiple concurrent connections.
This is PR an attempt to test the first options.
> #3667 - Reuse Redis Connections

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-scheduler.ts
- sources/packages/backend/libs/services/src/queue/queue.module.ts
- sources/packages/backend/libs/services/src/queue/queue.service.ts
Implementing the easy/fast (and stable) approach to resolve the queue initialization issues.
During the previous approach, sharing the ioredis connections (change being reverted in this PR) worked but there was also a possible false-positive memory leak warning. Further investigation will be needed if we change this approach in the feature but for now, keeping the existing approach.
The current solution extends the current  "specific queue-based" lock to an "all queues-based" lock.
The initialization is still pretty fast (around 1 second) and even if we double the number of schedulers in the future it still will be good enough (the code is executed once during queue-consumers initialization).
_Notes_: The logs before mentioned the queue-name every time and now it has changed to only the …
> #3667 - Bull Scheduler - Added Global Bootstrap Synchronization

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sfas-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/sims-db/src/transformers/numeric.transformer.ts
**Bug:**  0 is removed from the Exceptional costs field and the warning banner as shown below shows up. Likewise, for the other 3 cost fields.
**Fix:** `numericTransformer` on receiving the value of 0 from the database was returning it as `null` rather than the numeric value `0`. Updated the code to fix it and return `0` instead of `null`. 
https://github.com/user-attachments/assets/c8831e66-1dbe-45a6-8a46-61f2357a6b8f
> #3693 - [Bug] 0 is removed from the Exceptional costs field 

- sources/packages/backend/apps/db-migrations/src/migrations/1732672366956-UpdateDisbursementsWithoutValidSupplierReport.ts
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Create-disbursements-without-valid-supplier-report.sql
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-update-disbursements-without-valid-supplier-report.sql
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Update-disbursements-without-valid-supplier-report.sql
Fixed joins to sin_validations and cas_suppliers:
From: 
```
INNER JOIN sims.sin_validations sin_validations ON students.id = sin_validations.student_id
INNER JOIN sims.cas_suppliers cas_suppliers ON cas_suppliers.student_id = students.id
```
To:
```
INNER JOIN sims.sin_validations sin_validations ON students.sin_validation_id = sin_validations.id
INNER JOIN sims.cas_suppliers cas_suppliers ON students.cas_supplier_id = cas_suppliers.id
```
-Migration revert:
> #3763 - Ministry Reports - Disbursements Without Supplier (CAS) - Query fix

- sources/packages/backend/apps/api/src/services/cas-supplier/cas-supplier.service.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1732666324256-AddStudentProfileSnapshotToCASSupplier.ts
- sources/packages/backend/apps/db-migrations/src/sql/CASSuppliers/Add-student-profile-snapshot-column.sql
- sources/packages/backend/apps/db-migrations/src/sql/CASSuppliers/Rollback-add-student-profile-snapshot-column.sql
- sources/packages/backend/libs/sims-db/src/entities/cas-supplier.model.ts
> #3768 - CAS Supplier Maintenance Updates Part 1

- devops/openshift/queue-consumers-deploy.yml
- devops/openshift/sysdig-team.yml
- sources/packages/backend/apps/queue-consumers/src/controllers/index.ts
- sources/packages/backend/apps/queue-consumers/src/controllers/metrics/metrics.controller.ts
- sources/packages/backend/apps/queue-consumers/src/queue-consumers.module.ts
- sources/packages/backend/apps/queue-consumers/src/queues-bootstrap.module.ts
- sources/packages/backend/apps/queue-consumers/src/queues-metrics.module.module.ts
- sources/packages/backend/apps/queue-consumers/src/services/index.ts
- sources/packages/backend/apps/queue-consumers/src/services/metrics/metrics.models.ts
- sources/packages/backend/apps/queue-consumers/src/services/metrics/metrics.service.ts
- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- Enabled `/metrics` endpoint on `queue-consumers` to expose Prometheus metrics following [BC Gov docs](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/app-monitoring/user-defined-monitoring/).
- Added [prom-client](https://github.com/siimon/prom-client) also following the BC Gov docs mentioned above and the one that seems largely adopted.
- Created a [Gauge metric](https://prometheus.io/docs/concepts/metric_types/#gauge) to capture the most recent summary of every active queue allowing to add to the metrics a summary of `active`, `completed`, `failed`, `delayed`, and 'waiting' jobs. This represents the same status observed in the Bull Board. The garage metrics rely on Redis queries and will always get the most updated values from Redis.
- Created a …
> #3666 - Queue Monitoring - Enable Prometheus Metrics

- sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/cancel-application-assessment.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/start-application-assessment.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/assessment/cancel-application-assessment.processor.ts
- sources/packages/backend/apps/queue-consumers/src/processors/assessment/start-application-assessment.processor.ts
- sources/packages/backend/apps/queue-consumers/src/processors/index.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-queue.ts
- sources/packages/backend/apps/queue-consumers/src/utilities/log-utils.ts
- sources/packages/backend/libs/services/src/workflow/workflow-client.service.ts
- sources/packages/backend/libs/test-utils/src/mocks/zeebe-client-mock.ts
- sources/packages/backend/libs/utilities/src/logger/logger.service.ts
This PR is a proposal to unify the queue behavior. It contains changes for start and cancel assessments regular queues and the idea is to expand it to all schedulers.
The below image shows these points to be shared and forced for all the queues, using the CAS scheduler as an example.
1 - Return type;
2 - Provide a `processSummary`;
3 - try/catch and default start message.
4 - Error check on `processSummary` to force the jobs to fail.
5 - Error handling on `catch`.
6 - Final log activities during `finally`.
_Note:_ The above will also ensure the E2E tests follow a closer approach.
Sample log for a queue using the new `BaseQueue<T>` class.
The idea is to have the BaseScheduler extend the BaseQueue which will force a change in every single scheduler (which would be the idea). To avoid the …
> #3666 - Queue Monitoring - Default Queue Error Handling

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/application/process-archive-application.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/atbc-respone-integration/atbc-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/cas-supplier-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cra-integration/cra-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cra-integration/cra-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/application-changes-report-integration/application-changes-report-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/disbursement-receipts-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-full-time-feedback-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-part-time-feedback-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-process-integration-base.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/federal-restrictions-integration/federal-restrictions-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-full-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-full-time-process-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-part-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-part-time-process-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/sin-validation-integration/sin-validation-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/sin-validation-integration/sin-validation-process-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/student-loan-balances/student-loan-balances-part-time-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ece-request/ece-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ece-response/ece-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ier12-integration/ier12-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/notification/process-notifications.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/sfas-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/sims-to-sfas-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/student-application-notifications/student-application-notifications.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-enqueuer.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-queue-retry.scheduler.ts
- sources/packages/backend/libs/services/src/queue/queue.service.ts
As per the conversation on the [Teams chat](https://teams.microsoft.com/l/message/19:c91c9c0acf5f44dcab6789f870ddf47e@thread.tacv2/1733175923577?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=454b1d3b-af0f-4b44-b891-f4320c85d290&parentMessageId=1733175923577&teamName=External%3A%20AEST-SIMS&channelName=DEVS&createdTime=1733175923577), adjusted the queues to use the out-of-box cleanup configuration.
- Configuration reference: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#keepjobs-options
- For simplicity, not changing DB settings in this PR, just adapting the existing one to allow the removal of the methods. Currently, only schedulers were executing the cleanup, with this change, all the queues will have the completed tasks removed as per the existing DB setting.
> #3666 - Queue Monitoring - Adjusted Queues Cleanup Period

- sources/packages/backend/apps/api/src/services/student/student.service.ts
- Querying the id is necessary for TypeOrm to bring multiple numbers for the `applications` array. Otherwise, it brings only one application in the array in the `student` object.
> #3981 - Model SDPR API - Query fix

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.submitApplication.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/parsers/full-time-e-cert-record-parser.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts
- sources/packages/backend/libs/services/src/sfas/sfas-application.service.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
- sources/packages/backend/libs/test-utils/src/factories/sfas-application.ts
> #4041 - Ignore Cancelled Legacy Applications on SIMS Validations and Calculations

- sims.code-workspace
- sources/packages/backend/apps/api/src/route-controllers/restriction/_tests_/e2e/restriction.students.controller.getStudentRestrictions.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/restriction/restriction.students.controller.ts
- sources/packages/backend/apps/api/src/services/restriction/student-restriction.service.ts
- sources/packages/backend/apps/test-db-seeding/src/clean-db/clean-db.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/restriction/basic-seeding/create-restrictions.model.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/restriction/basic-seeding/create-restrictions.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/restriction/index.ts
- sources/packages/backend/apps/test-db-seeding/src/main.ts
- sources/packages/backend/apps/test-db-seeding/src/test-db-seeding.module.ts
- sources/packages/backend/libs/services/src/constants/restriction.constants.ts
- sources/packages/backend/libs/test-utils/src/factories/restriction.ts
- sources/packages/backend/libs/test-utils/src/index.ts
- sources/packages/backend/libs/test-utils/src/models/common.model.ts
- sources/packages/backend/package.json
- Prevent API from retuning 'No effect' notifications since they are not supposed to be notified to the student.
- Consolidated `LGCY_*` restrictions into a single `LGCY` restriction code to be returned to the student. The error code returned will be the highest one present in the list of the `LGCY_*` being returned.
- Create few `LGCY_*` in the DB seed to allow the E2E to use them.
- Fixed the `db:seed:test:clean` that was not removing the `create_history_entry` function leading to an error when the DB was populated again.
- Close Nestjs app (`app.close()`) to avoid the `db:seed:test:clean` and `db:seed:test` to be hanging and waiting.
```sql
INSERT INTO
sims.sfas_restriction_maps (legacy_code, code, is_legacy_only)
VALUES
('TD', 'LGCY_TD', TRUE),
('B5', 'LGCY_B5', TRUE),
('B5A', …
```
> #4013 - Legacy Restriction Mapping - Student Changes

- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
> #4052 - Fix the legacy program year totals for program year limits

- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
Trim function was called after the split, it should have been called before it.
> #3258 - Bug in the Error creation of CAS Supplier

- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.createSiteForExistingSupplier.spec.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
- sources/packages/web/src/views/aest/student/CASSupplierInformation.vue
CAS supplier errors enhancement and Unit Test
> #3258 - CAS supplier errors enhancement and Unit Test

- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.createSiteForExistingSupplier.spec.ts
- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.createSupplierAndSite.spec.ts
- sources/packages/backend/libs/integrations/src/cas/cas-formatters.ts
- Added `replace(/[^A-Z0-9\-\s]/g, "")` to `formatAddress()` to remove everything that is not A-Z (capital letters), hyphens or whitespace;
- Added invalid characters to unit test.
> #3983 - CAS Addressline1 Update - Restrict to Alpha Numeric

- sources/packages/backend/workflow/src/workflow-definitions/parttime-configure-disbursement.bpmn
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
Removed the code setting the first disbursement back for today.
> #4082 -  2 Disbursement PT Schedules - Correct First Disbursement Date

- sources/packages/backend/apps/api/src/services/cas-supplier/cas-supplier.service.ts
- sources/packages/backend/apps/api/src/services/student/student.service.ts
The create student action happening when Ministry user trying to approve a student. The SIN validation table is not inserted. This causes the search to fail as it uses the below query to fetch.
This is a bug created during the cas supplier pending verification logic centralization that happened in the #3258 ticket.
> #4087 - Search Student Bug

- sources/packages/backend/workflow/src/workflow-definitions/parttime-configure-disbursement.bpmn
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
- sources/packages/backend/workflow/test/2025-2026/parttime-assessment/disbursements/parttime-assessment-disbursements.e2e-spec.ts
- Hotfix 2.1.2 merge to main.
- Fix E2E for the new program year.
> #270 - Merge Hotfix V2.1.2 to main

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sfas-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sims-to-sfas-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/models/sfas-integration.dto.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/sfas-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/sims-to-sfas-integration.scheduler.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.processing.service.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sims-to-sfas.processing.service.ts
- Refactored SFAS-related schedulers, SFAS to SIMS and vice-versa.
- Adjusted E2E tests.
- Replaced `SFASProcessingResult` with the `processSummary`. This refactor is not expected to be done for every scheduler.
> #4076 - Queue Monitoring - Schedulers Refactor (SFAS Integration)

- sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/cancel-application-assessment.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/start-application-assessment.processor.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-queue.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/_tests_/cas-supplier-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/sin-validation-integration/_tests_/sin-validation-process-response-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/sin-validation-integration/sin-validation-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/sin-validation-integration/sin-validation-process-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/student-loan-balances/_tests_/student-loan-balances-part-time-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/student-loan-balances/student-loan-balances-part-time-integration.scheduler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/sin-validation/sin-validation.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/student-loan-balances/student-loan-balances.processing.service.ts
- Refactored SIN validation-related schedulers and student loan balance import.
- Adjusted E2E tests.
> #4076 - Queue Monitoring - Schedulers Refactor (SIN validation and loan balance)

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/disbursement-receipts-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/disbursement-receipts-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/federal-restrictions-integration/federal-restrictions-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/sims-to-sfas-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/test/helpers/mock-utils/job-mock-utils.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/fed-restriction-integration/fed-restriction.processing.service.ts
- Refactored schedulers `disbursement-receipts-file-integration` and `federal-restrictions-integration`.
- Adjusted existing E2Es.
- As agreed in previous PRs
- moving the audit user to the service instead of the processor.
- removing the friendly start/end logs from the processor since the `BaseQueue` is already logging similar start/end logs.
To allow the below check to happen the method `containLogMessages` was changed to check if the string "contains" a value instead of "endsWith" it. The `endsWith` was used to have a more precise check and remove the log initial information (e.g. context and date). Using the "contains" will still give enough assertion precision and allow inspecting errors currently serialized to a JSON.
```ts
// Act/Assert
await …
```
> #4076 - Queue Monitoring - Schedulers Refactor (Fed Restrictions and Receipts)

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/base-queue.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-full-time-process-response-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-part-time-process-response-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-full-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-full-time-process-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-part-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/msfaa-part-time-process-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/test/helpers/mock-utils/job-mock-utils.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-request.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-response.processing.service.ts
- Refactored MSFAA-related schedulers and adjusted E2E tests.
- full-time-msfaa-integration
- part-time-msfaa-process-integration
- part-time-msfaa-process-response-integration
- full-time-msfaa-process-response-integration
- Additional Refactor
- As agreed in the previous PR, added extra logs to the `BaseQueue` start and end.
> #4079 - Queue Monitoring - Schedulers Refactor - (MSFAA)

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-feedback-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-feedback-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-full-time-feedback-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-full-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-part-time-feedback-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-part-time-process-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-process-integration-base.scheduler.ts
Refactored the below schedulers.
- ecert-full-time-feedback
- ecert-full-time-process
- ecert-part-time-feedback
- ecert-part-time-process
> #4076 - Queue Monitoring - Schedulers Refactor (e-Cert and e-Cert Feedback)

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/atbc-respone-integration/_tests_/atbc-response-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/atbc-respone-integration/atbc-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/application-changes-report-integration/_tests_/application-changes-report-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/application-changes-report-integration/application-changes-report-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/notification/process-notifications.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/student-application-notifications/_tests_/student-application-notifications.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/student-application-notifications/student-application-notifications.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/_tests_/assessment-workflow-enqueuer.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/_tests_/assessment-workflow-queue-retry.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-enqueuer.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/workflow/assessment-workflow-queue-retry.scheduler.ts
- sources/packages/backend/libs/integrations/src/atbc-integration/atbc-integration.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/application-changes-report/application-changes-report.processing.service.ts
Refactored the below schedulers and associated E2E tests.
- assessment-workflow-enqueuer
- assessment-workflow-queue-retry
- application-changes-report-integration
- process-notifications
- student-application-notifications
- atbc
> #4079 - Queue Monitoring - Schedulers Refactor (Part 6)

- sources/packages/forms/Dockerfile
This PR is a quick fix to allow Form IO upgrade to be successfully installed on the server.
- Removed fixed versions for Linux packages in Dockerfile for building Form IO on servers
> #4132 - Update Form IO (Quick Fix)

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.submitApplication.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/disbursement/_tests_/e2e/disbursement.controller.associateMSFAA.e2e-spec.ts
- sources/packages/backend/libs/services/src/sfas/sfas-application.service.ts
- sources/packages/backend/libs/services/src/sfas/sfas-part-time-application.service.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
- sources/packages/backend/libs/test-utils/src/factories/sfas-part-time-application.ts
- Changed logic to: 
- Not consider part-time SFAS cancelled applications for program year totals; 
- Not consider part-time application date overlap and; 
- Ignore full-time and part-time applications in the MSFAA number process.
- Added E2E tests;
> #4133 - SFAS to SIMS Bridge - PT App Cancellation Date & MSFAA (FT/PT) Change - Part 3

- sources/packages/backend/apps/db-migrations/src/migrations/1735584931753-UpdateDisbursementReportsBCGrants.ts
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Rollback-update-disbursements-report-bc-grants.sql
- sources/packages/backend/apps/db-migrations/src/sql/Reports/Update-disbursements-report-bc-grants.sql
Report changed to show the values of BC Grant.
Migration revert Screenshot
Sample query to run and check in the DB
> (select
to_char(dr.disburse_date, 'YYYY-MM-DD') as "Date of Disbursement",
dr.student_sin as "SIN",
app.application_number as "Application Number",
ds.document_number as "Certificate Number",
drv.grant_type as "Funding Code",
drv.grant_amount as "Disbursement Amount"
from
sims.disbursement_receipts dr
inner join sims.disbursement_receipt_values drv on drv.disbursement_receipt_id = dr.id
inner join sims.disbursement_schedules ds on ds.id = dr.disbursement_schedule_id
inner join sims.student_assessments sa on sa.id = ds.student_assessment_id
inner join sims.applications app on app.id = sa.application_id
inner join sims.education_programs_offerings epo on epo.id = …
> #3946-Update BC Grants displayed

- sources/packages/web/src/components/common/sin/AddNewSIN.vue
The optional checkbox to `Skip the validations` returns `undefined` (When not touched) and `null` (on form reset) which is considered as bad request as the API is expecting a boolean value for `skipValidations`.
> #3596 - Bug on ministry add new SIN to student

- sources/packages/forms/src/form-definitions/noticeofassessment.json
- sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
- Set `"refreshOnChange": true` to display eligible amount.
- Removed "Submit application" button for pages before the last page.
> #4132 - Update Form IO (Fix Eligible Amount)

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/full-time-e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/part-time-e-cert-file-handler.ts
-  Ensured that the sequence numbers in PT and FT eCert file header is incremented as a lifetime value.
- Started the next PROD sequence number at **7 for PT eCerts** and **FT  eCerts are left as is (set to start at 1).** For this, added the following SQL to the Release 2.2 notes:
```sql
INSERT INTO sims.sequence_controls
(sequence_name, sequence_number)
VALUES ('ECERT_PT_SENT_FILE', 6), ('ECERT_FT_SENT_FILE', 0);
```
**Screenshots:**
---------------------------------------------
> #4202 - Increment Sequence Header PT ECert

- devops/Makefile
- devops/openshift/web-deploy.yml
- [Redhat Guide](https://developers.redhat.com/learning/learn:openshift:replace-deprecated-deploymentconfigs-deployments/resource/resources:convert-deploymentconfig-deployment?mc_cid=1a844df827&mc_eid=f049851a15)
- [Kubernetes rollout status command](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status/#:~:text=Show%20the%20status%20of%20the,continue%20watching%20the%20latest%20revision.)
> #3685 - Convert SIMS Web to deployment object

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/full-time-e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/part-time-e-cert-file-handler.ts
**As a part of this PR, release v2.2.0 is merged to v2.3.0**
> #274 - Merge release v2.2.0 to v2.3.0

- sources/packages/backend/libs/services/src/sfas/sfas-individual.service.ts
**Issue:** When a student creates a profile in SIMS and they have PPD = true in a matching `sfas_individuals` record, their `students.disability_status` status is `Not requested`.
**Fix:** The query retrieving the `sfas_individual` for a matching SIMS record was not returning the individual's `ppdStatus` and the `ppdStatusDate`. Added it to fix the issue.
**Fix Screenshot:**
---------------------------------------------------------------------------------------------------------
> #4223 - Student Bridge Match - PPD Status Not Importing

- .github/workflows/env-setup-sysdig-teams.yml
- devops/Makefile
- devops/openshift/sysdig-team.yml
This ticket is to add missing team members to the sysdig as agreed during the development of the ticket #3666.
_Please note the ticket is not associated with the PR because it is closed and does not seem worth opening or creating a ticket only for this task._
The current way to update and apply the changes was manual and demanded manual editing of the file to be applied to each license plate. The intention of this PR is to make it simple.
- Converted sysdig team to a template to allow adding a parameter.
- Create a make command to execute the template in the current two license plates.
Technical documentation about Sysdig team setup: https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/app-monitoring/sysdig-monitor-setup-team/?utm_source=digital&utm_medium=web&ut …
> #3666 - Queue Monitoring - Sysdig Team Update

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-full-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/_tests_/ecert-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-integration.module.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-calculation-process.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-notification/blocked-disbursement/ministry-blocked-disbursement-notification.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-notification/blocked-disbursement/student-blocked-disbursement-notification.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-notification/e-cert-notification.service.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-notification/e-cert-notification.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-notification/index.ts
- Created a base class for e-Cert notifications (`ECertNotification`) and segregated the logic to generate blocked notifications into `MinistryBlockedDisbursementNotification` and `StudentBlockedDisbursementNotification`.
- Existing logic was moved into the new files.
- Code for the method `shouldCreateNotification` for the Students was moved and no changes were done for this PR, unless critical no comments will be addressed.
- `ECertNotification` can be used for any other e-Cert notification as required, not only blocked disbursement.
_Please note that the student data required to generate the notification is now retrieved twice in the event that the disbursement is blocked and the Ministry should be notified for the first time. The benefit of having the separation between the logic for …
> #3054 - Email notification for blocked disbursement to ministry only once

- sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json
- sources/packages/forms/src/form-definitions/studentadditionaltransportationappeal.json
- sources/packages/forms/src/form-definitions/studentdependantsappeal.json
- sources/packages/forms/src/form-definitions/studentdisabilityappeal.json
- sources/packages/forms/src/form-definitions/studentfinancialinformationappeal.json
- Added `programYear` as a persistent value for all the appeals forms.
- Added `programYear` to the "Appeals - Student Disability Information" to ensure all the forms share the same program year hidden field that can be potentially used to adjust the forms to different program years.
_Note: we got the confirmation from the business (in the ticket comments) that there is no need to apply a fix to production data at this moment._
> #3984 - BUG: Ministry - Change Request Form submitted by Student not displaying Year

- devops/Makefile
- devops/openshift/forms-deploy.yml
- devops/scripts/fetchOldTags.sh
> #3685 - Convert FormIO to deployment and update fetch old tags script

- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-calculation/e-cert-calculation-process.ts
The blocked notifications logs were using the parent log instead of the child log some hierarchy was added now as below. This was an existing issue and it was causing multiple logs from multiple children to be appended to the same hierarchy.
```
INFO: Executing e-Cert calculations for all eligible disbursements.'
INFO: Retrieving eligible disbursements(s).'
INFO: Found 1 eligible disbursement(s) for 1 student(s).'
--INFO: Log details'
--INFO: Processing application number 5906924436, disbursement id 41 scheduled for 2025-01-16.'
----INFO: Log details'
----INFO: Executing e-Cert calculation steps.'
----INFO: Executing step 1 out of 9.'
----INFO: Executing full-time disbursement validations.'
----INFO: Disbursement estimated awards do not contain any amount to be disbursed.'
----INFO: There …
```
> #3054 - Email notification for blocked disbursement to ministry only once - Change log hierarchy

- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-decisions.dmn
- sources/packages/backend/workflow/test/2022-2023/parttime-assessment/eligibility/parttime-assessment-eligibility-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/parttime-assessment/eligibility/parttime-assessment-eligibility-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/eligibility/parttime-assessment-eligibility-CSPT.e2e-spec.ts
- sources/packages/backend/workflow/test/2025-2026/parttime-assessment/eligibility/parttime-assessment-eligibility-CSPT.e2e-spec.ts
> #4262 - Fix part-time family size variables DMN

- sources/packages/backend/apps/api/src/route-controllers/application-exception/_tests_/e2e/application-exception.aest.getPendingApplicationExceptions.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-exception/application-exception.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/application-exception/models/application-exception.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/models/pagination.dto.ts
- sources/packages/backend/apps/api/src/services/application-exception/application-exception.service.ts
- sources/packages/web/src/services/http/dto/ApplicationException.dto.ts
- sources/packages/web/src/views/aest/student/StudentApplicationExceptions.vue
- Revised title and subtitle;
- Expanded "Name" column into "Given names" and "Last name";
> #3315 - Content: Ministry: Student Requests Exceptions

- sources/packages/backend/apps/api/src/route-controllers/student-account-applications/models/student-account-application.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/student-account-applications/student-account-application.aest.controller.ts
- sources/packages/backend/apps/api/src/services/student-account-applications/student-account-applications.models.ts
- sources/packages/backend/apps/api/src/services/student-account-applications/student-account-applications.service.ts
- sources/packages/web/src/services/http/dto/StudentAccountApplication.dto.ts
- sources/packages/web/src/views/aest/student/StudentAccountApplications.vue
- Revised "Requests accounts" to "Pending account requests"
- Revised "Make a determination....." to "Basic BCeID account requests that require ministry review."
- Added search input box
- Revised "Name" to "Given name"
- Added "Last name"
- Added "Date of birth"
- Organized order to align with mock up
Screenshot of the updated page
> #3313 - Content: Ministry: Accounts

- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- sources/packages/forms/src/form-definitions/studentadditionaltransportationappeal.json
- Made the additional transportation exception document uploader field mandatory field for all options for the following areas:
- Application
- Change Request
- Made the BC residency exception document uploader field mandatory field for all options for the following areas:
- Application
Screenshot for the BC residency file uploader
Screenshot for the additional transportation file uploader
> #4023 - Additional transportation and bc residency uploaders is mandatory

- sources/packages/web/src/components/generic/ModalDialogBase.vue
- sources/packages/web/src/views/student/AppStudent.vue
1) Added a hamburger menu to allow for the top bar navigation when the screen size is reduced.
2) The modal dialogs throughout the application have been updated to use the `useDisplay` composable.
**Video representing the demo for the navigation drawer and the menu:**
https://github.com/user-attachments/assets/1c6d4f86-e4f3-402a-bcb6-067e275300e3
**Video representing the demo for the modal dialogs:**
https://github.com/user-attachments/assets/aa777d6c-6756-497f-a7cb-d55eef380838
> #3900 - Small screen responsiveness: Top Menu Nav Hamburger

- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- sources/packages/forms/src/form-definitions/studentadditionaltransportationappeal.json
- sources/packages/web/src/components/generic/ModalDialogBase.vue
- sources/packages/web/src/views/student/AppStudent.vue
> #276 - Main merged to v2.4.0

- sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts
- sources/packages/web/src/components/aest/students/assessment/History.vue
- Added the TIME (HH:MM 24hr) to the Assessment date in the history view.
- Ensured that the table is always ordered by submitted date descending.
- Confirmed that the changes apply to the Ministry view, Student view and the Institution view.
**Institution View:**
-------------------------------------------
**Student View:**
-------------------------------------------
**Ministry View:**
> #3067 - Assessment History: Update to show most recent assessment

- sources/packages/backend/apps/db-migrations/src/migrations/1738021154711-InsertStudentNotificationSecondDisbursementReminder.ts
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Insert-student-notification-second-disbursement-reminder.sql
- sources/packages/backend/apps/db-migrations/src/sql/NotificationMessages/Rollback-insert-student-notification-second-disbursement-reminder.sql
- sources/packages/backend/libs/sims-db/src/entities/notification.model.ts
As the first part of the story PR, this PR has the following change:
- Added DB migration for inserting the record "Student application notification for overdue second disbursement still pending." to the table `notificationMessages`
Screenshot of the added record to the `notificationMessages` table
> #3594 - Email to Student - 2nd Disbursement has passed, still pending (Part 1)

- sources/packages/backend/apps/db-migrations/src/migrations/1738006674395-AddQueueCASInvoicesBatchesCreation.ts
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Add-cas-invoices-batches-creation.sql
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Rollback-add-cas-invoices-batches-creation.sql
- sources/packages/backend/apps/queue-consumers/Dockerfile.dev
- sources/packages/backend/apps/queue-consumers/src/processors/index.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/_tests_/cas-invoices-batches-creation.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/cas-invoices-batches-creation.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/queue-consumers.module.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-invoice-batch/cas-invoice-batch.service.ts
- sources/packages/backend/apps/queue-consumers/src/services/index.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/aest/basic-seeding/create-cas-distribution-accounts.models.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/aest/basic-seeding/create-cas-distribution-accounts.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/aest/index.ts
- sources/packages/backend/apps/test-db-seeding/src/main.ts
- sources/packages/backend/apps/test-db-seeding/src/test-db-seeding.module.ts
- sources/packages/backend/libs/services/src/sequence-control/sequence-control.service.ts
- sources/packages/backend/libs/test-utils/src/data-source/e2e-data-source.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-distribution-account.ts
- sources/packages/backend/libs/test-utils/src/index.ts
- sources/packages/backend/libs/utilities/src/queue.constant.ts
- sources/packages/backend/package.json
- Created the new scheduler default setup including DB migrations.
- Added information in the wiki with the agreed time with the business.
- Created only the first E2E to allow some testing. Adding further E2E is planned but it will also demand adding more factories hence this was a point to stop for now.
- Created DB seeding for the new CAS distribution accounts to allow easy execution assertions on expected distribution accounts. It may be shared with API when API tests are created.
- _Note:_ DB seeding was never enabled for queue-consumers and few files were modified to allow it following the same already in place for the API.
- Minor refactors were executed in the DB seeding to allow the system user to be retrieved and the default logger to be used instead of `console`.
- The …
> #3254 - CAS AP Invoice - Invoices and Batches - Scheduler

- devops/helm/redis-cluster/templates/metrics-prometheus.yaml
- devops/helm/redis-cluster/templates/metrics-svc.yaml
- devops/helm/redis-cluster/templates/prometheusrule.yaml
- devops/helm/redis-cluster/values-0c27fb-dev.yaml
- devops/helm/redis-cluster/values-0c27fb-prod.yaml
- devops/helm/redis-cluster/values-0c27fb-test.yaml
- devops/helm/redis-cluster/values-a6ef19-dev.yaml
- devops/helm/redis-cluster/values-a6ef19-prod.yaml
- devops/helm/redis-cluster/values-a6ef19-test.yaml
- devops/helm/redis-cluster/values.yaml
Enable Metrics to check alerts in sysdig.
Currently only dev namespaces enabled, to test the metrics.
Ignore the below files, as they are copied from bitnami to enable metrics
> #4253 - Upgrade Redis - metrics

- sources/packages/backend/apps/api/src/route-controllers/cas-invoice-batch/_tests_/e2e/cas-invoice-batch.aest.controller.getCASInvoiceBatchReport.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/cas-invoice-batch/_tests_/e2e/cas-invoice-batch.aest.controller.getInvoiceBatches.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/_tests_/cas-invoices-batches-creation.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cas-integration/cas-invoices-batches-creation.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/services/cas-invoice-batch/cas-invoice-batch.service.ts
- sources/packages/backend/libs/services/src/constants/error-code.constants.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-invoice-batch.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-invoice-detail.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-invoice.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-supplier.ts
- sources/packages/backend/libs/test-utils/src/factories/disbursement-receipt.ts
- sources/packages/backend/libs/test-utils/src/index.ts
- sources/packages/backend/package.json
Created new E2E tests for the new endpoints and extended scheduler E2E tests previously added (only one).
- getCASInvoiceBatchReport
- Should generate an invoice batch report with part-time and full-time invoices when the batch exists.
- Should throw a HttpStatus Not Found (404) when the requested invoice batch does not exist.
- Should throw a HttpStatus Forbidden (403) error when an unauthorized Ministry user tries to get the invoice batch report.
- getInvoiceBatches
- Should be able to get invoice batches for the first page in a paginated result with a limit of two per page in descending order when there are three invoice batches available.
- Should be able to get only pending invoice batches when the filter for status is applied.
- Should throw a HttpStatus Bad Request (400) error when …
> #3254 - CAS AP Invoice - Invoices and Batches - E2E Tests

- sources/packages/backend/apps/api/src/route-controllers/institution-user/_tests_/e2e/institution-user.institutions.controller.createInstitutionUserWithAuth.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/institution-user/_tests_/e2e/institution-user.institutions.controller.updateInstitutionUserWithAuth.e2e-spec.ts
- sources/packages/backend/apps/api/src/testHelpers/auth/bceid-helpers.ts
- sources/packages/backend/apps/api/src/testHelpers/auth/index.ts
- sources/packages/backend/libs/test-utils/src/data-source/e2e-data-source.ts
As the second part of this story, this PR has the following changes:
- Added E2E tests for the following endpoint methods:
- createInstitutionUserWithAuth
- updateInstitutionUserWithAuth
- Added method `mockBCeIDAccountDetails` to mock the response from method `bceIDService.getAccountDetails` to assist the endpoint method `createInstitutionUserWithAuth`.
Screenshots of E2E tests
> #4014 - Institution Read-Only User Type PART 2 (UI) (Part 2)

- sources/packages/forms/src/form-definitions/programinformationrequest.json
- sources/packages/web/src/services/http/dto/ProgramInfoRequest.dto.ts
- sources/packages/web/src/views/institution/locations/offerings/OfferingEdit.vue
- sources/packages/web/src/views/institution/locations/program-info-request/LocationEditProgramInfoRequest.vue
This PR removes the two buttons related to program and offering executions for read-only users:
- Removed button "+ Create program" on the PIR page.
- Removed dropdown button "Edit offering" on the offering edit page.
Screenshots
> #4014 - Institution Read-Only User Type PART 2 (UI) (Part 3)

- sources/packages/web/src/types/formio.ts
- sources/packages/web/src/views/student/StudentFileUploader.vue
> #4235 - Student File Upload - Reset after submit

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.submitApplication.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student-account-applications/_test_/e2e/student-account-application.aest.controller.approveStudentAccountApplication.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/_tests_/e2e/student-scholastic-standings.aest.controller.getScholasticStandingSummary.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/_tests_/e2e/student-scholastic-standings.institutions.controller.getScholasticStandingSummary.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/_tests_/e2e/student-scholastic-standings.students.controller.getScholasticStandingSummary.e2e-spec.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/backend/apps/api/src/services/student/student.service.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sfas-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/sfas-integration/sfas-integration.processing.service.ts
- sources/packages/backend/libs/services/src/sfas/sfas-application.service.ts
- sources/packages/backend/libs/services/src/sfas/sfas-individual.service.ts
- sources/packages/backend/libs/services/src/sfas/sfas-part-time-application.service.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
- sources/packages/backend/libs/src-sql/sfas-individuals/Bulk-update-students-foreign-key.sql
- Updated the SQL script [Bulk-update-students-foreign-key.sql](https://github.com/bcgov/SIMS/blob/32674e65bdb026d42967835c0aa20114ae17fb55/sources/packages/backend/libs/src-sql/sfas-individuals/Bulk-update-students-foreign-key.sql) to avoid updating the student ID on the sfas_individuals table if already populated.
- Checked the below areas (and other possible features) to ensure the student ID from sfas_individuals table will be used instead of the 3 matching fields.
- Overawards
- Application Overlaps
- Program year totals (workers)
- Adapted existing E2E tests.
> #3249 - Bridge Matching - Re-matching and persisting the match

- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2024-2025.bpmn
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/models/assessment.model.ts
- Updated the name of the calculation in the <=2 or 3+ paths from `federalAwardCSGDAmount` to `federalAwardMaxCSGDAmount`
--------------------------------------------------------------------------------------------------------------
- Updated the `federalAwardNetCSGDAmount` calculation to take the minimum value of remaining need, max calculated, and PY award limit less previously awarded value.
--------------------------------------------------------------------------------------------------------------
- Fixed the e2e tests
> #4397 - Fix CSGD (CSG - PTDEP) [PT 24/25]

- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.aest.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentNOA.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.getAssessmentNOA.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts
- sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts
- sources/packages/web/src/components/common/AssessmentAwardDetails.vue
- sources/packages/web/src/components/common/StatusInfoEnrolment.vue
- Added the date COE was actioned beside Enrolment confirmed/declined in the screenshot below:
- Format: "Enrolment confirmed on DATE"
- Ensured the date is available for the Ministry, Student, and Institution.
- Used column `coe_updated_at`.
- Append "on DATE" to the current "status label".
- Adjusted E2E tests to ensure the API sends the date.
Screenshot
> #4291 - Date COE Confirmed on Funding Summary

- sources/packages/web/package-lock.json
- sources/packages/web/package.json
> #4343 - Updates to KeyCloak - start after Feb25

- sources/packages/web/src/components/aest/students/ApplicationHeaderTitle.vue
- sources/packages/web/src/components/aest/students/assessment/ManualReassessment.vue
- sources/packages/web/src/components/aest/students/bypassedRestrictions/HistoryBypassedRestrictions.vue
- sources/packages/web/src/components/common/NoticeOfAssessmentFormView.vue
- sources/packages/web/src/components/common/applicationTracker/ApplicationProgressBar.vue
- sources/packages/web/src/components/common/students/StudentApplications.vue
- sources/packages/web/src/components/common/students/assessment/History.vue
- sources/packages/web/src/components/common/students/assessment/Request.vue
- sources/packages/web/src/components/layouts/aest/AESTApplicationSideBar.vue
- sources/packages/web/src/views/aest/StudentApplicationView.vue
- sources/packages/web/src/views/aest/student/applicationDetails/ApplicationRestrictionsManagement.vue
- sources/packages/web/src/views/aest/student/applicationDetails/ApplicationStatusTracker.vue
- sources/packages/web/src/views/aest/student/applicationDetails/AssessmentAward.vue
- sources/packages/web/src/views/aest/student/applicationDetails/AssessmentsSummary.vue
- sources/packages/web/src/views/aest/student/applicationDetails/NoticeOfAssessment.vue
- sources/packages/web/src/views/institution/student/InstitutionStudentApplicationView.vue
- sources/packages/web/src/views/institution/student/applicationDetails/ApplicationExceptions.vue
- sources/packages/web/src/views/institution/student/applicationDetails/AssessmentAward.vue
- sources/packages/web/src/views/institution/student/applicationDetails/InstitutionAssessmentsSummary.vue
- sources/packages/web/src/views/institution/student/applicationDetails/NoticeOfAssessment.vue
- sources/packages/web/src/views/institution/student/applicationDetails/StudentAppealRequest.vue
Reverting changes related to the route with the parent application ID instead of the application ID itself, due to complexities moving forward with the changes that affected more areas than what was foreseen by the Team.
> #4247 - Revert route changes and parent application (Vue only)

- sims.code-workspace
- sources/packages/backend/apps/api/src/route-controllers/confirmation-of-enrollment/_tests_/e2e/confirmation-of-enrollment.institutions.getCOESummary.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/confirmation-of-enrollment/confirmation-of-enrollment.institutions.controller.ts
- sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts
- sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule.models.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ece-request/_tests_/ece-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt-integration.module.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece.processing.service.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.service.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/confirmation-of-enrollment.service.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/models/confirmation-of-enrollment.models.ts
> #2380 - Updated the criteria to get disbursements for ECE request

- sources/packages/backend/apps/api/src/auth/roles.enum.ts
- sources/packages/backend/apps/api/src/constants/error-code.constants.ts
- sources/packages/backend/apps/api/src/route-controllers/cas-invoice-batch/_tests_/e2e/cas-invoice-batch.aest.controller.updateCASInvoiceBatch.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/cas-invoice-batch/cas-invoice-batch.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/cas-invoice-batch/models/cas-invoice-batch.dto.ts
- sources/packages/backend/apps/api/src/services/cas-invoice-batch/cas-invoice-batch.service.ts
- sources/packages/web/src/services/CASInvoiceBatchService.ts
- sources/packages/web/src/services/http/CASInvoiceBatchApi.ts
- sources/packages/web/src/services/http/dto/CASInvoiceBatch.dto.ts
- sources/packages/web/src/types/contracts/aest/roles.ts
- sources/packages/web/src/views/aest/CASInvoices.vue
- Created API to approve/reject batch and API validations
- Updated the column `approval_status`, `approval_status_updated_on` and `approval_status_updated_by` for table `cas_invoice_batch` once a record is approved or rejected.
- Created new role for ministry `aest-cas-expense-authority` on Keycloak DEV.
- Created E2E tests for the endpoint.
Screenshot of the table with two records viewed from ministry user without role `cas-expense-authority`
Screenshot of the table with two records viewed from ministry user with role `cas-expense-authority`
Screenshot when a CAS invoice batch is approved
Screenshot when a CAS invoice batch is rejected
Screenshot of the E2E tests
Create ministry role `aest-cas-expense-authority` on Keycloak TEST and PROD for the current release.
> #4352 - CAS - Status on Approve / Reject Batch Action

- sources/packages/backend/apps/db-migrations/src/migrations/1741646122852-AddCASInvoiceStatusUpdatedByColumn.ts
- sources/packages/backend/apps/db-migrations/src/sql/CASInvoices/Add-cas-invoice-status-updated-by-column.sql
- sources/packages/backend/apps/db-migrations/src/sql/CASInvoices/Rollback-add-cas-invoice-status-updated-by-column.sql
- sources/packages/backend/apps/queue-consumers/src/services/cas-invoice-batch/cas-invoice-batch.service.ts
- sources/packages/backend/libs/sims-db/src/entities/cas-invoice.model.ts
- sources/packages/backend/libs/test-utils/src/factories/cas-invoice.ts
- Added the migration for the `CASInvoiceStatusUpdatedBy` column.
**Rollback Screenshot:**
> #4390 - CAS Manual Intervention: Add `CASInvoiceStatusUpdatedBy` Column

- sources/packages/backend/apps/api/src/app.aest.module.ts
- sources/packages/backend/apps/api/src/route-controllers/cas-invoice/cas-invoice.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/cas-invoice/models/cas-invoice.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/index.ts
- sources/packages/backend/apps/api/src/route-controllers/models/pagination.dto.ts
- sources/packages/backend/apps/api/src/services/cas-invoice/cas-invoice.service.ts
- sources/packages/backend/apps/api/src/services/index.ts
- sources/packages/backend/apps/api/src/utilities/datatable-config.ts
- Created a new controller named `cas-invoice` with the two below endpoints:
1) Create new endpoint to get list of manual intervention invoices from `cas-invoices` table, with lazy pagination enabled.
2) Created new endpoint to update the status of the `cas-invoices`.
> #4390 - CAS Manual Intervention (API)

- sims.code-workspace
- sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ece-request/_tests_/ece-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece-files/ece-file-detail.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece.integration.service.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/ece.processing.service.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ece-integration/models/ece-integration.model.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/disbursement-schedule.service.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/confirmation-of-enrollment.service.ts
- sources/packages/backend/libs/utilities/src/integration-utils.ts
> #4427 - Update ECE Request fields

- sources/packages/forms/src/form-definitions/noticeofassessment.json
- sources/packages/web/src/constants/award-constants.ts
- Removed disbursement 2 column for an assessment with only one disbursement;
- Reordered awards;
- Removed CSGT and BCSG from award breakdown;
- Removed CSGT from funding summary;
1 disbursement only:
2 disbursements:
Funding summary:
> #3961 - NOA Layout: FT offering that will only have one disbursement includes "Disbursement 2" column

- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-workflowWrapUp.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/workflow-wrap-up-factory.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/assessment.dto.ts
- sources/packages/backend/apps/workers/src/services/student-assessment/student-assessment.service.ts
- sources/packages/backend/workflow/src/workflow-definitions/assessment-gateway.bpmn
- sources/packages/backend/workflow/test/2022-2023/assessment-gateway/assessment-gateway.change-request.e2e-spec.ts
- sources/packages/backend/workflow/test/2023-2024/assessment-gateway/assessment-gateway.change-request.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/assessment-gateway/assessment-gateway.change-request.e2e-spec.ts
- sources/packages/backend/workflow/test/2025-2026/assessment-gateway/assessment-gateway.change-request.e2e-spec.ts
- sources/packages/backend/workflow/test/test-utils/constants/workflow-variables-constants.ts
- Created a variation for the existing worker "workflow-wrap-up" to allow its usage before the "end workflow" for the `assessment-gateway` "Applications In Progress" lane, as shown in items 1 to 3 in the below image (image 4 is working as before).
- The worker is backward compatible with the existing workflow, which means that once deployed, workflows executing the previous version where the new header is not provided will be able to finish its process as before. The absence of the header makes it works as before.
- _Note:_ fixed an issue when a `job.complete()` was returned from inside a transaction block with the intention of finishing the worker task but was actually finishing only the transaction block, leaving the rest of the worker processing to still be executed.
The workflow task …
> #4354 - Change Request Revamp - 1st effort - Warping up workflow during "in-progress" application

- sources/packages/forms/src/form-definitions/noticeofassessment.json
-  "Dependents" on this page should be spelled with "e".
> #3961 - NOA Layout: Dependents spelling with e

- sources/packages/backend/workflow/src/workflow-definitions/load-assessment-consolidated-data.bpmn
- sources/packages/backend/workflow/test/models/assessment.model.ts
- sources/packages/backend/workflow/test/test-utils/factories/assessment-consolidated-data.ts
- sources/packages/forms/src/form-definitions/supportinguserspartner2022-2023.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2024-2025.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2025-2026.json
- Modified the following form.io API keys for partner data as requested
- hasEmploymentInsuranceBenefits
- hasFedralProvincialPDReceipt
- hasTotalIncomeAssistance
- Modified the following Camunda variables for partner data as requested
- partner1HasEmploymentInsuranceBenefits
- partner1HasFedralProvincialPDReceipt
- partner1HasTotalIncomeAssistance
Screenshot of the Camunda variables
> #4402 - Student and Partner FT: Modify FT Partner Financial Information Section (Quick Fix)

- sources/packages/backend/apps/queue-consumers/src/processors/assessment/_tests_/cancel-application-assessment.processor.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-verifyAssessmentCalculationOrder.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/assessment/_tests_/e2e/assessment.controller-workflowWrapUp.e2e-spec.ts
- sources/packages/backend/libs/services/src/students-assessments/assessment-sequential-processing.service.ts
Currently there is an issue with sequential assessment processing and PY totals in production, when an application has all it's current assessment disbursement(s) have `Declined` COE.
Issue Description: As explained above, the sequential assessment processing logic considers only the current assessment of any application to see if the given application must be considered with the sequential applications 
FOR 
both `Calculation of PY totals from past applications` and `Consider the impacted applications to re-assess` 
WHEN 
the application has all it's current assessment disbursement(s) have `Declined` COE.
**_Update to Sequential Applications Logic(In addition to the existing ones):_** 
- Applications that have at-least one disbursement which are in following `disbursementScheduleStatus` …
> #4510 - Sequential assessment and PY totals bug fix

- sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- sources/packages/forms/src/form-definitions/studentadditionaltransportationappeal.json
- sources/packages/forms/src/form-definitions/studentdependantsappeal.json
- sources/packages/forms/src/form-definitions/studentfinancialinformationappeal.json
- sources/packages/forms/src/form-definitions/uploadstudentdocuments.json
- sources/packages/forms/src/form-definitions/uploadstudentdocumentsaest.json
- Set max number of documents to 25. Added a hidden component in each form to have it server calculated;
- All fileUploaders should be required to have at least 1 file;
- Changed some fileUploaders to allow multiple files (they allowed only one file to be uploaded);
- Removed "optional" of some labels;
- Kept same custom validation to all fileUploaders so it's easy to change it all occurrences across the forms:
```json
"validate": {
"required": true,
"customMessage": "You must upload at least one file, and the total number of uploaded files cannot exceed {{data.maxUploadedFiles}}.",
"custom": "const files = data[instance.key] || []; valid = files.length > data.maxUploadedFiles ? false : true;"
}
```
> #4459 - Set max documents for application uploaders to 25

- sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- sources/packages/forms/src/form-definitions/studentadditionaltransportationappeal.json
- sources/packages/forms/src/form-definitions/studentdependantsappeal.json
- sources/packages/forms/src/form-definitions/studentfinancialinformationappeal.json
- sources/packages/forms/src/form-definitions/uploadstudentdocuments.json
- sources/packages/forms/src/form-definitions/uploadstudentdocumentsaest.json
- Set max number of documents to 25. Added a hidden component in each form to have it server calculated;
- All fileUploaders should be required to have at least 1 file;
- Changed some fileUploaders to allow multiple files (they allowed only one file to be uploaded);
- Removed "optional" of some labels;
- Kept same custom validation to all fileUploaders so it's easy to change it all occurrences across the forms:
```json
"validate": {
"required": true,
"customMessage": "You must upload at least one file, and the total number of uploaded files cannot exceed {{data.maxUploadedFiles}}.",
"custom": "const files = data[instance.key] || []; valid = files.length > data.maxUploadedFiles ? false : true;"
}
```
> #4459 - Set max documents for application uploaders to 25 (#4537) cherry pick

- sources/packages/backend/workflow/src/workflow-definitions/load-assessment-consolidated-data.bpmn
- sources/packages/backend/workflow/test/models/assessment.model.ts
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- Changed the section name to "Financial exceptional expenses".
- Changed the text under the section title to "If you have had exceptional expenses that created financial hardship that affected your ability to start or continue your studies these expenses may be considered as part of your assessment."
- Removed the current free entry field that exists entirely.
- Created a new numerical field with the following content.
- Label: "Please enter the combined exceptional expense amount rounded to the nearest dollar."
- Validation checks up to 6 digits also there can be no negative values. Decimal places is 0.
- API key: `exceptionalExpenseAmount`.
- Changed the content to texts "Documents Provided" in the AC.
- Ensured that the currency field and the file uploader field are mandatory.
- Added …
> #4405 - Exceptional expense exception question - FT Only

- sources/packages/backend/apps/api/src/route-controllers/student-appeal/_tests_/e2e/student-appeal.aest.controller.approveStudentAppealRequests.e2e-spec.ts
- sources/packages/backend/apps/api/src/services/student-appeal/student-appeal.service.ts
- Root cause: When the student appeal is retrieved from the database along with the relations, the offering object was not returned and hence  the reference of `offering.id` resulted in error.
- Solution: Added a join with offerings in the SQL.
> #4549 - Bugfix on approving the student appeal

- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- Removed the `calculateValue` logic for the component "Capacity in which you will be attending this program:". This logic is not be needed anymore since the value for the component is passed to the form from the Vue.
> #4489 - Formio Changes: Split FT/PT form Updates Fix

- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.institutions.controller.createOffering.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.institutions.controller.updateProgramOffering.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1743799586745-OfferingAddOnlineInstructionColumns.ts
- sources/packages/backend/apps/db-migrations/src/sql/EducationProgramsOfferings/Add-online-instruction-columns.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationProgramsOfferings/Rollback-add-online-instruction-columns.sql
- sources/packages/backend/libs/sims-db/src/entities/education-program-offering.model.ts
- sources/packages/web/src/components/common/OfferingForm.vue
- sources/packages/web/src/components/common/OfferingFormSubmit.vue
- sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts
- sources/packages/web/src/views/institution/locations/offerings/OfferingCreate.vue
- Form.io definition changes
- Offering validation model changes
- E2E changes/adjustments
> #4511 - DB Migration and populate institution type on API response

- sources/packages/web/src/components/common/StudentApplication.vue
**Bug:** When the institution location is selected in the dropdown for the student application, the program component does not refresh properly and still holds the previous (stale) data in the dropdown along with the new data for the newly selected location.
**Fix:** To fix the above issue, I have added the below code snippet to force remove the stale data from both the programs and offerings dropdown before loading the fresh data.
**Code modification:** `formioUtils.setComponentValue(form, PROGRAMS_DROPDOWN_KEY, "");`
> #4489 - Formio Changes: Split FT/PT [Bug Fix]

- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.institutions.controller.createOffering.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.institutions.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/custom-validators/program-allows-offering-wil.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-import-csv.service.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering-validation.models.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/backend/apps/api/src/services/institution-location/institution-location.service.ts
- sources/packages/backend/apps/api/src/utilities/class-validation/custom-validators/allow-if.ts
- sources/packages/backend/apps/api/src/utilities/class-validation/custom-validators/is-number-greater-than.ts
- sources/packages/backend/apps/api/src/utilities/class-validation/index.ts
- sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts
- sources/packages/forms/src/form-definitions/educationprogramoffering.json
- sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts
- sources/packages/web/src/views/institution/locations/offerings/OfferingCreate.vue
- E2E Tests will be part of upcoming PR.
> #4511 - Offering data collection - API Validation and Form Inputs

- sources/packages/web/src/views/institution/OfferingsUpload.vue
- sources/packages/web/src/views/institution/WithdrawalUpload.vue
**Bug:** The file upload for bulk offering upload and withdrawal upload were not working properly i.e. there was a validation error incorrectly being shown for these two scenarios wrt. `<v-file-input />` component.
**Fix:** The file validation rule was modified to make the fix. 
1) **Bulk Offering Upload File Fix:**
--------------------------------------------------------------------------------------------------------------------------------------------
2) **Withdrawal Upload File Fix:**
> #4545 - Institution Bulk offering upload: Flagging error for CSV formatted file

- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/sfaa2025-26.json
- Removed the below shown FAED warning banner in read-only view for student, institution and ministry for both part-time and full-time applications.
**Removed the following mentioned banner for read-only view:**
**Non-readonly Mode:**
--------------------------------------------------------------------------------------------------------------------------------------------
**Institution View (readonly):**
--------------------------------------------------------------------------------------------------------------------------------------------
**Ministry View (readonly):**
--------------------------------------------------------------------------------------------------------------------------------------------
**Student View (readonly):**
> #4452 - Read-only application view: Remove FAED warning banner

- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.institutions.controller.createOffering.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/_tests_/e2e/education-program-offering.institutions.controller.updateProgramOffering.e2e-spec.ts
- sources/packages/backend/apps/test-db-seeding/src/db-seeding/institution/basic-seeding/create-institutions-and-authentication-users.model.ts
- sources/packages/forms/src/form-definitions/educationprogramoffering.json
> #4511 - Offering data collection - E2E Tests and Form content duplication fix

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.controller.getApplicationDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.institutions.controller.getApplicationDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/web/src/services/http/dto/Application.dto.ts
- sources/packages/web/src/views/aest/StudentApplicationView.vue
- sources/packages/web/src/views/institution/student/InstitutionStudentApplicationView.vue
**Bug:** The `api` was not correctly returning the offering intensity value related to the application for the institution and the ministry and the `web` was not passing this value to the formio for display.
**Bug Screenshot:**
**Institution View:**
--------------------------------------------------------------------------------------------------------------------------------------------
**Ministry View:**
--------------------------------------------------------------------------------------------------------------------------------------------
**Student View: (previously working as expected)**
> #4489 - Formio Changes: Split FT/PT within PY [Bug Fix]

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.getCompletedApplicationDetails.e2e-spec.ts
Added API tests for the student endpoint that retrieve the tracker card information.
ApplicationStudentsController(e2e)-getCompletedApplicationDetails
√ Should get application with change request details when there is an in-progress change request pending Ministry approval.
√ Should get application with change request details including waiting student income and waiting partner data when there is an in-progress change request with a partner associated.
√ Should get application with change request details including with a received student income, parent 1 waiting income, parent 2 waiting data when there is an in-progress change request with parents associated.
_Note:_ Found an existing issue when there are two parents, and the income records are not fully provided yet for both parents. If …
> #4431 - Student View change request revamp - Tracker Card API E2E tests

- sources/packages/backend/apps/workers/src/controllers/cra-integration/cra-integration.controller.ts
- sources/packages/backend/apps/workers/src/services/cra-income-verification/cra-income-verification.service.ts
- sources/packages/backend/apps/workers/src/services/student-assessment/student-assessment.service.ts
When an application has a supporting user and the supporting user has successful income verification, 
then the student reported income `studentDataCRAReportedIncome` is set  with partner's CRA Reported income value
by the worker job `loadAssessmentConsolidatedData` [loadAssessmentConsolidatedData](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts#L149)
This is because following logic receives both student and supporting user income verifications after filter BECAUSE the SQL query does not return the supporting user id.
The bug has been introduced since we removed TypeOrm `RelationId` property and referenced the relational object in a way that wasn't working so left join was added to fix the issue and used the …
> #4619 - Hotfix - Student reported income fix

- sources/packages/backend/apps/api/src/app.module.ts
- sources/packages/backend/apps/api/src/dynamic-form-configuration.module.ts
- sources/packages/backend/apps/api/src/main.ts
- sources/packages/backend/apps/api/src/services/dynamic-form-configuration/dynamic-form-configuration.service.ts
- sources/packages/backend/apps/api/src/services/index.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1745432641611-CreateDynamicFormConfigurationsTable.ts
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Create-dynamic-form-configurations-table.sql
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Insert-dynamic-form-configurations-2021-2022.sql
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Insert-dynamic-form-configurations-2022-2023.sql
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Insert-dynamic-form-configurations-2023-2024.sql
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Insert-dynamic-form-configurations-2024-2025.sql
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Insert-dynamic-form-configurations-2025-2026.sql
- sources/packages/backend/apps/db-migrations/src/sql/DynamicFormConfigurations/Rollback-create-dynamic-form-configurations-table.sql
- sources/packages/backend/libs/sims-db/src/constant.ts
- sources/packages/backend/libs/sims-db/src/data-source.ts
- sources/packages/backend/libs/sims-db/src/entities/dynamic-form-configuration.model.ts
- sources/packages/backend/libs/sims-db/src/entities/dynamic-form-type.ts
- sources/packages/backend/libs/sims-db/src/entities/index.ts
> #4520 - Formio split part-1

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.controller.getApplicationOverallDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.getCompletedApplicationDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/supporting-user/models/supporting-user.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.aest.controller.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/web/src/components/layouts/aest/AESTApplicationSideBar.vue
- sources/packages/web/src/composables/useApplication.ts
- sources/packages/web/src/services/SupportingUserService.ts
- sources/packages/web/src/services/http/SupportingUserApi.ts
- sources/packages/web/src/services/http/dto/Application.dto.ts
- sources/packages/web/src/services/http/dto/SupportingUser.dto.ts
- sources/packages/web/src/types/contracts/Common.ts
- Change the API that retrieves the application's overall information to also get the supporting users' information, which allowed the old API method to be removed as planned in the previous efforts.
- Kept the logic to decide which application version is an "in-progress change request" in the API, which means that the API is responsible for returning a change request in an explicit way (DTO property `inProgressChangeRequest`).
- Considered all applications as a version of itself, which means current, change request, and past versions share the same output DTO.
- As a side effect of having the supporting users associated with change requests, every version now can easily display supporting users in the UI (it is just not enabled yet because it is not part of the ACs).
- Added the below …
> #4616 - Ministry View Change Request Revamp (Application view menu)

- .github/workflows/prune-images.yml
- fixes default environment for prune GH action, as previous PR only updated the default environment in the manually executed workflow.
> #4648 - Updates default environment for GH Prune Action

- .github/workflows/release-build-all.yml
- adds concurrency lock to GitHub Build All function. This should resolve build errors when PRs are merged within close proximity to one another.
> #4653 - Add concurrency to build all

- sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts
- sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/COESummaryData.vue
**Expected Behaviour**
If 10 items per page and there are 10 students for COE they should be displayed on one page
If 12 students, 10 should be listed on one page and 2 students on the other
All students who are required to have COE are displayed - the institution user does not need to search for them
Issue is using 2 query in https://github.com/typeorm/typeorm/issues/320
*Note:
code to use .skip() instead of .offset() and .take() instead of .limit()
> #4501 - BUG: COE Query Impacting Count and Record Visibility 

- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.aest.controller.getStudentProfile.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/models/student.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.controller.service.ts
- sources/packages/backend/apps/api/src/services/student/student.service.ts
- sources/packages/backend/libs/sims-db/src/entities/student.model.ts
- sources/packages/backend/libs/test-utils/src/factories/sfas-individuals.ts
- sources/packages/web/src/components/common/students/StudentProfile.vue
- sources/packages/web/src/composables/useFormatters.ts
- sources/packages/web/src/services/http/dto/Student.dto.ts
- sources/packages/web/src/types/contracts/StudentContract.ts
- Exposed the legacy profile data in the student API for Ministry users only
- Included information to allow the user to know if the student has multiple legacy profiles, as the most recent AC added.
- Add E2Es for the endpoint to cover students with and without a legacy profile associated.
Add an action to the banner to allow the Ministry user to execute the search that will display a list of options to be selected.
> #4328 - Student Profile - Bridge/Legacy Matching Management -  Display Existing Match if exists

- sources/packages/backend/apps/api/src/route-controllers/application-offering-change-request/_tests_/e2e/application-offering-change-request.institutions.controller.createApplicationOfferingChangeRequest.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.students.controller.submitApplication.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/sfas-integration/_tests_/sims-to-sfas-integration.scheduler.e2e-spec.ts
- sources/packages/forms/src/form-definitions/sfaa2022-23.json
- sources/packages/forms/src/form-definitions/sfaa2023-24.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/web/src/components/common/StudentApplication.vue
- sources/packages/web/src/components/generic/formio.vue
- sources/packages/web/src/types/contracts/student/ApplicationContract.ts
- sources/packages/web/src/views/aest/StudentApplicationView.vue
- sources/packages/web/src/views/institution/student/InstitutionStudentApplicationView.vue
- sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
> #4520 -  FormIO split final part - cleanup and backward compatibility

- sources/packages/backend/apps/api/src/auth/roles.enum.ts
- sources/packages/backend/apps/api/src/route-controllers/student/models/student.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/student/student.controller.service.ts
- sources/packages/backend/libs/services/src/sfas/sfas-individual.service.ts
- sources/packages/web/src/components/aest/students/modals/StudentProfileLegacyMatchesModal.vue
- sources/packages/web/src/components/common/students/StudentProfile.vue
- sources/packages/web/src/components/common/students/StudentProfileLegacyMatches.vue
- sources/packages/web/src/services/StudentService.ts
- sources/packages/web/src/services/http/StudentApi.ts
- sources/packages/web/src/services/http/dto/Student.dto.ts
- sources/packages/web/src/types/contracts/DataTableContract.ts
- sources/packages/web/src/types/contracts/aest/roles.ts
- sources/packages/web/src/views/aest/student/Profile.vue
- Created a new role to allow the Ministry to link the student to the legacy profile: `student-link-legacy-profile`.
- New endpoints created to get the possible matches and also create the association (E2Es to be added in the next PR).
- Create the 'StudentProfileLegacyMatchesModal.vue' to simplify the student profile page.
- DataTable configured to display all records (` :items-per-page="-1"`) and hide the footer.
> #4328 - Student Profile - Bridge/Legacy Matching Management - Student Link

- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.aest.controller.associateLegacyStudent.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student/_tests_/e2e/student.aest.controller.getStudentLegacyMatches.e2e-spec.ts
- sources/packages/backend/libs/test-utils/src/factories/sfas-restriction.ts
- sources/packages/backend/libs/test-utils/src/index.ts
```
StudentAESTController(e2e)-getStudentProfile
√ Should get the student profile when the student exists and no legacy profile is associated.
√ Should get the student profile when the student exists and one legacy profile is associated.
√ Should get the student profile when the student exists and multiple legacy profiles are associated.
√ Should throw a NotFoundException when the student was not found.
```
```
StudentAESTController(e2e)-associateLegacyStudent
√ Should associate a student to a legacy profile, create a note, and set restriction as processed false when the student is not associated yet to a legacy profile and a legacy profile is a potential match.
√ Should throw an UnprocessableEntityException when the legacy profile to be associated with the student is not a valid …
```
> #4328 - Student Profile - Bridge/Legacy Matching Management - E2E Tests

- sources/packages/backend/apps/api/src/app.module.ts
- sources/packages/web/nginx/default.conf.dev.template
- sources/packages/web/nginx/default.conf.template
- sources/packages/web/src/components/generic/formio.vue
- sources/packages/web/src/composables/useFormioUtils.ts
- sources/packages/web/src/views/aest/FormioEditor.vue
- Removes the cached form.io definition to allow immediate visualization of saved changes.
- Fix for the content submission of a large payload due to a controller change in the previous PR.
- Add missing links to the content security policy that were preventing some components in the editor not to being displayed.
Added the form path to the auto-complete list, as shown below, to allow differentiation between forms with the same title.
> #4490 - FormIO - Enable Editor in Test & PR Process - Fixes and Improvements

- .github/workflows/release-deploy-all.yml
Proposed solution to have the GitHub ref provided from both workflow entries: `workflow_dispatch` and `workflow_call`.
When `workflow_call` is executed, it will be provided by the parent workflow.
When `workflow_dispatch` is executed, it will use the `github.ref_name` as the default value.
_Note:_
1 - The env variable is enough to execute the jobs, but it is not accessible from the reusable workflows `with` context for `deployCamundaDefinitions` and `deployFormioDefinitions`.
2 - Reference for the ternary operation used to set the ENV variable: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example
> #4690 - Update Deploy-All to use tag Git Reference - Build-ref Fallback

- .github/workflows/release-deploy-all.yml
Removing event condition. Apparently, the `github.event_name` will never assume the value of `workflow_call`. Its value will be propagated from the calling workflow event.
> #4690 - Update Deploy-All to use tag gitreference

- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2024-2025.bpmn
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSGD.e2e-spec.ts
- sources/packages/backend/workflow/test/2024-2025/parttime-assessment/eligibility/parttime-assessment-eligibility-CSGD.e2e-spec.ts
Hotfix changes to CSGD (CSG-PTDEP)
- `awardEligibilityCSGD` to include dependants <=11 or 12+ on taxes instead of total eligible dependants
- workflows based on the CSGD eligible dependants (above) instead of total eligible:
- E2E tests for eligibility copied from the 2025-26 changes, which means `parttime-assessment-eligibility-CSGD.e2e-spec.ts` for both year are the same since the logic is now the same.
- E2E tests for amount verification were adapted to ensure the eligibility was `true` to check the amounts.
> #4707 - Change to CSGD eligibility and 2 workflows for calculation

- devops/helm/crunchy-postgres/templates/PostgresCluster.yaml
- adds configuration for detecting Crunchy availability in openshift, removing dependency on crunchy operator.
> #4727 - Add OpenShift Spec to Crunchy-PostGres configuration

- sources/packages/backend/apps/api/src/route-controllers/application-change-request/_tests_/e2e/application-change-request.aest.assessApplicationChangeRequest.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application-change-request/_tests_/e2e/application-change-request.aest.controller.assessApplicationChangeRequest.e2e-spec.ts
- sources/packages/backend/apps/api/src/services/application-change-request/application-change-request.service.ts
- sources/packages/web/src/components/aest/students/modals/AssessApplicationChangeRequestModal.vue
- sources/packages/web/src/views/aest/StudentApplicationView.vue
- Minor fix while saving the change request to persist the change date (as pointed out in the previous PR).
- Modal refactor using the most recent practices to control modal processing, loading, and possible errors.
ApplicationChangeRequestAESTController(e2e)-assessApplicationChangeRequest
√ Should approve a change request and copy the offering and appeal when the application change request is waiting for approval.
√ Should approve a change request and copy the offering, and no appeals when the application change request is waiting for approval, and no appeals are present.
√ Should be able to decline a change request and create a student note when the application change request is waiting for approval.
√ Should throw a BadRequestException when the application change request approval has …
> #4617 - Ministry View Change Request Revamp (approval and denial) - E2E tests

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-full-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-helper.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-part-time-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/msfaa-integration/_tests_/msfaa-process-integration.scheduler.models.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa-request.processing.service.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/msfaa-integration/msfaa.integration.service.ts
Note:  Please coordinate with the business to set the life-time sequence number as a part of release instructions for the Full-time and Part-time sequence groups.
Full time: 
Part Time: 
Full time: 
Part time:
> #4438 - MSFAA Sequence Group update

- sources/packages/web/src/components/common/ProgramDetails.vue
- The common component has a condition to disable the `Deactivate` button based on the institution user data from institution store. This condition results in a runtime error when the component is loaded from a ministry user view because of the absence of Institution store and so the institution user data. 
- Validation of institution user data is applied conditionally when the user type is `Institution` skipping the same for a ministry view. 
Note: We generally avoid using the auth client type based logic in the components `AuthService.shared.authClientType === ClientIdType.Institution`. But this component being very old and already using similar condition in other places, the auth client type is used here as quick solution.
> #4445 - Program deactivate action bug fix

- sources/packages/backend/workflow/src/workflow-definitions/parttime-assessment-2025-2026.bpmn
- sources/packages/backend/workflow/test/2025-2026/parttime-assessment/awards-amounts/parttime-assessment-awards-amount-CSLP.e2e-spec.ts
- sources/packages/backend/workflow/test/2025-2026/parttime-assessment/costs/parttime-assessment-costs-program-related-costs.e2e-spec.ts
- sources/packages/backend/workflow/test/models/assessment.model.ts
Books and supplies was not showing in the assessed costs table because `calculatedDataProgramRelatedCosts` was calculating to null (showing not eligible in the NOA).
This was due to `programYearTotalPartTimeBooksAndSuppliesCost` not being checked for being null.
- Added null check and moved all program year totals to the front of the assessment flow:
**parttime-assessment-2025-2026-awards-amount-CSLP.** 
> Should determine CSLP award for an assessment which involves loan and grants when the student does not have any loan balance and has remaining need for loan.
> Should determine CSLP award for an assessment which involves loan and grants when the student have loan balance and has remaining need for loan.
Updated Expected Remaining Need +3000 to account for books and supplies max cost …
> #4748 - 25/26 PY PT: Books and Supplies not displayed in assessed costs table

- sources/packages/forms/src/form-definitions/partnerinformationandincomeappeal.json
- sources/packages/forms/src/form-definitions/reportscholasticstandingchange.json
- sources/packages/forms/src/form-definitions/sfaa2024-25.json
- sources/packages/forms/src/form-definitions/supportingusersparent2024-2025.json
- sources/packages/web/src/types/formio/custom-components/inputs/number-currency.ts
- Converts all currency inputs to use new "number-currency" custom component, which includes validation for negative numbers, delimiter, and no decimals.
- This PR includes the following files: 
- partner information income appeal 
- report scholastic standing change
- sfaa2024-25
- supporting users parent 2024-25
- includes fix to icon for number-currency component
> #4652 - PR 1: Convert currency inputs to number-currency

- sources/packages/backend/workflow/test/2025-2026/fulltime-assessment/costs/fulltime-assessment-costs-child-care-cost.e2e-spec.ts
Net new tests in the /costs/ folder for FT
Child care cost tests:
- single + 1 dep + declared childcare costs under maximum (total is student declared)
- single + 3 deps + declared childcare costs over maximum (total is max allowable)
- married + 1 dep + partner full time student >12 weeks (total reduced)
- married + 1 dep + partner full time student < 12 weeks (no reduction to total)
> #4752 - FT Assessment tests - child care costs

- sources/packages/forms/src/form-definitions/sfaa2025-26-pt.json
- sources/packages/forms/src/form-definitions/studentfinancialinformationappeal.json
- sources/packages/forms/src/form-definitions/supportingusersparent2025-2026.json
- Updates currency inputs for the following forms: 
- SFAA PT 25/26
- Student Financial Income Appeal - used max.MoneyValue for validation
- Supporting users 25/26 
Note: One more PR for SFAA FT25/26 is required to convert currency to number, but waiting to avoid conflict on any other tickets in backlog.
> #4652 - Part 2: Update Currency Inputs 

- sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- Final PR to update all currency inputs in FT25/26 to new number/currency input with proper validation
> #4652 - Part 3: Update Currency to Number Input on SFAA FT 25/26 

- sources/packages/backend/apps/db-migrations/src/migrations/1748893791404-AddDisbursementScheduleStatusRejected.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1748915343561-AddDisbursementScheduleStatusAuditCols.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1748978283307-UpdateDisbursementScheduleStatusRejected.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1748982079368-AddOverawardOriginTypeAwardDeductedRejected.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1748994454302-AddECertCancellationResponseIntegration.ts
- sources/packages/backend/apps/db-migrations/src/sql/DisbursementSchedules/Add-disbursement-schedule-status-audit-cols.sql
- sources/packages/backend/apps/db-migrations/src/sql/DisbursementSchedules/Rollback-add-disbursement-schedule-status-audit-cols.sql
- sources/packages/backend/apps/db-migrations/src/sql/DisbursementSchedules/Rollback-update-disbursement-schedule-status-rejected.sql
- sources/packages/backend/apps/db-migrations/src/sql/DisbursementSchedules/Update-disbursement-schedule-status-rejected.sql
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Add-ecert-cancellation-response-integration.sql
- sources/packages/backend/apps/db-migrations/src/sql/Queue/Rollback-add-ecert-cancellation-response-integration.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Add-disbursement-schedule-status-rejected.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Add-overaward-origin-type-award-deducted-rejected.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-add-disbursement-schedule-status-rejected.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-add-overaward-origin-type-award-deducted-rejected.sql
- sources/packages/backend/apps/queue-consumers/src/processors/index.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/esdc-integration/ecert-integration/ecert-cancellation-response-integration.scheduler.ts
- sources/packages/backend/apps/queue-consumers/src/queue-consumers.module.ts
- sources/packages/backend/libs/integrations/src/esdc-integration/e-cert-integration/e-cert-file-handler.ts
- sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/persist-calculations-step.ts
- sources/packages/backend/libs/services/src/confirmation-of-enrollment/confirmation-of-enrollment.service.ts
- sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule-shared.service.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-overaward-origin.type.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-schedule-status.type.ts
- sources/packages/backend/libs/sims-db/src/entities/disbursement-schedule.model.ts
- sources/packages/backend/libs/utilities/src/queue.constant.ts
- sources/packages/web/src/types/contracts/Overaward.ts
- sources/packages/web/src/types/contracts/institution/ConfirmationOfEnrollment.ts
> #4476 - E-cert cancellation db migrations

- sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/_tests_/e2e/student-scholastic-standings.institutions.controller.saveScholasticStanding.e2e-spec.ts
- sources/packages/backend/libs/test-utils/src/factories/education-program-offering.ts
**StudentScholasticStandingsInstitutionsController(e2e)-saveScholasticStanding.**
√ Should not create new scholastic standing 'Student did not complete program' for a part-time application when number of unsuccessful completion weeks is greater than the total number of offering weeks.
√ Should create new scholastic standing 'Student did not complete program' for a part-time application when number of unsuccessful completion weeks is less than the total number of offering weeks.
**Screenshot of passing tests:**
> #4711 - Revise FT application: Unsuccessful Completion Week Count (e2e tests)

- sources/packages/backend/workflow/src/workflow-definitions/load-assessment-consolidated-data.bpmn
- sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2025-2026.json
> #4414 - Interface Policy Questions 

- sources/packages/web/src/components/common/students/applicationDetails/ApplicationExceptionsApproval.vue
- sources/packages/web/src/views/aest/StudentApplicationView.vue
- sources/packages/web/src/views/aest/student/applicationDetails/ApplicationExceptionsApproval.vue
- sources/packages/web/src/views/aest/student/applicationDetails/StudentAppealRequestsApproval.vue
*Acceptance Criteria:*
*Demo*
1.
> #4415 - Ministry: Add student information header to additional pages

- sims.code-workspace
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cra-integration/_tests_/cra-process-integration.scheduler.e2e-spec.ts
- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/cra-integration/_tests_/parsers/cra-request-record-parser.ts
- sources/packages/backend/libs/integrations/src/services/cra-income-verification/cra-income-verification.service.ts
- sources/packages/backend/libs/test-utils/src/factories/supporting-user.ts
- Updated the CRA request query to skip supporting users without a SIN associated with it.
- Create E2E tests for the scheduler.
- Should create one CRA file request with two income verification records when there are pending requests for a student and a parent and both have a SIN.
- Should create one CRA file request with one income verification when there are pending requests for a student and a parent and only the student has a SIN.
_Note:_ The `CRARequestRecordParser` was created to follow the same idea from the existing `FullTimeCertRecordParser` and `PartTimeCertRecordParser`.
> #4740 - Parent update first effort - CRA Request Scheduler Changes

- sources/packages/backend/apps/workers/src/controllers/supporting-user/_test_/e2e/create-identifiable-supporting-user.ts
- sources/packages/backend/apps/workers/src/controllers/supporting-user/_test_/e2e/supporting-user.controller.createIdentifiableSupportingUsers.e2e-spec.ts
- sources/packages/backend/apps/workers/src/controllers/supporting-user/supporting-user.dto.ts
- sources/packages/backend/libs/test-utils/src/factories/supporting-user.ts
Created E2E tests for the new worker `createIdentifiableSupportingUsers`.
- Should create one parent supporting user and save the associated full name when one parent's information is added to the student application.
- Should create the second parent supporting user and save the associated full name when the two parents' information is added to the student application.
- Should not create a parent when the parent was already created.
- Should throw an error when the full name is expected but it is not present in the application's dynamic data.
- Should throw an error when the application does not exist.
> #4740 - Parent update first effort - New Worker E2E Tests

- sources/packages/backend/apps/queue-consumers/src/processors/schedulers/institution-integration/ier12-integration/_tests_/e2e/utils/string-utils.ts
- sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12.processing.service.ts
> #4664 - PSI Integration Changes - Filename and Folders - Part 3

- sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule-shared.service.ts
- During overaward reversal, while `addedBy` was populated, `addedDate` is not assigned and fixed the same in PR.
> #4476 - Add overaward added date

- sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- sources/packages/forms/src/form-definitions/sfaa2025-26-pt.json
- This PR adds confirmation banner to 2025/26 Full-time and Part-time applications for the following exceptions. Students cannot proceed to subsequent questions without checking the confirmation message. 
- Also includes minor fix to ensure that when student answers "None of the above" for "Modified Independent" question, they will still need to answer "Parent" questions.
> #4853 - Adds confirmation banners to FT and PT exceptions

- devops/helm/crunchy-postgres/Chart.yaml
- devops/helm/crunchy-postgres/values-0c27fb-dev.yaml
- devops/helm/crunchy-postgres/values-0c27fb-prod.yaml
- devops/helm/crunchy-postgres/values-0c27fb-test.yaml
- devops/helm/crunchy-postgres/values-a6ef19-test.yaml
As a part of this PR, the storage for the persistent volumes for the database backups and the high availability clusters in the configuration files have been updated to match the existing storage values from the cluster for all the environments.
Courtesy: Fix provided by @andrewsignori-aot
> #4833 - Postgres PV storage configuration update in all environments

- sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.supporting-users.controller.ts
- sources/packages/backend/apps/api/src/services/supporting-user/constants.ts
- sources/packages/backend/apps/api/src/services/supporting-user/supporting-user.service.ts
- sources/packages/backend/apps/api/src/utilities/system-configurations-constants.ts
- sources/packages/web/src/types/contracts/supporting-user/SupportingUserContracts.ts
- sources/packages/web/src/views/supporting-user/SupportingInformation.vue
- Made the workflow notification for supporting user data submission conditional and remove DB Lock.
- Ensured the completion message is sent only after the database update is successfully verified to prevent race conditions.
> #4818 - Parent Declare - Supporting User Portal Update

- sources/packages/backend/package-lock.json
- sources/packages/backend/package.json
- Updated `@camunda8/sdk` from `8.6.13` to `8.7.18`.
- E2E tests are passing
- Submitted an application with a parent and produced the NOA.
> #3059 - Software Package Updates (Camunda SDK)

- sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- sources/packages/forms/src/form-definitions/supportinguserspartner2025-2026.json
> #4849 - Update Living Situation Questions 

- sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.controller.getApplicationOverallDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/application/application.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/application/models/application.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/supporting-user/supporting-user.aest.controller.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
- sources/packages/backend/apps/api/src/services/supporting-user/supporting-user.service.ts
- sources/packages/web/src/components/layouts/aest/AESTApplicationSideBar.vue
- sources/packages/web/src/services/http/dto/Application.dto.ts
- sources/packages/web/src/views/aest/SupportingUser.vue
**AC**
- Update the application side menu to display the parent’s full name instead of "Parent 1/Parent 2" in all states (active, change request, history). If the name is longer than 36 characters, truncate it. If the name is missing, default to "Parent 1/Parent 2".
- Add a new subtitle for parent declarations in the application history section: "Student Declared" and "Parent Declared".
> #4820 - Parent Declare - Application History Menu - Part 1

- sources/packages/backend/apps/workers/src/controllers/supporting-user/_test_/e2e/supporting-user.controller.createIdentifiableSupportingUsers.e2e-spec.ts
- sources/packages/backend/libs/services/src/notifications/notification/notification-actions.service.ts
- sources/packages/backend/libs/sims-db/src/entities/notification.model.ts
**SupportingUserController(e2e)-createIdentifiableSupportingUsers**
**√** Should create supporting user for the first provided parent and save the associated full name when one parent's information is added to the student application and create a student notification for parent declaration uired by parent.
**√** Should create supporting user for the second provided parent and save the associated full name when the two parent's information is added to the student application and create a student notification for parent declaran required by student.
> #4823 - Parent declare: email notification (e2e tests)

- devops/openshift/forms-deploy.yml
- sources/forms-docker-compose.yml
- Updated the MongoDB local version to use the same version as recently updated on OpenShift.
- Named the MondoDB volume to force it to be recreated, making it easier to locate and making it easier to have the local upgraded.
- To update its local environment, a developer needs to execute the `make forms` and redeploy the form.io definitions.
Added the visual connector between the MongoDB and Form.io server to prevent the MongoDB from being "alone" while displaying the topology.
> #3059 - Software Package Updates (local mongo update)

- .github/dependabot.yml
Update the configuration for the dependabot PRs creation.
The PRs are still grouped per directory, but also grouped as agreed:
- major versions - individuals
- minor versions - grouped
- security patch security - grouped
_Note:_ kept Nestjs as a separate group for now.
It seems that there is a possible feature called [multi-ecosystem-groups](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-multi-ecosystem-updates) that can be explored later to group the PRs for the individual apps, but it seems new and it was causing validation issues in the file.
> #3059 - Software Package Updates (dependabot config update)

- sources/packages/backend/apps/api/src/route-controllers/student-appeal/_tests_/e2e/student-appeal.students.controller.submitStudentAppeal.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/student-appeal/student-appeal.students.controller.ts
- sources/packages/backend/apps/api/src/services/application/application.service.ts
> #4743 - Validate offering intensity for appeal in API

- sources/packages/backend/apps/api/src/route-controllers/education-program/_tests_/e2e/education-program.institutions.controller.createEducationProgram.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/education-program.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program/models/education-program.dto.ts
- sources/packages/backend/apps/api/src/services/education-program/education-program.service.models.ts
- sources/packages/backend/apps/api/src/services/education-program/education-program.service.ts
- sources/packages/backend/apps/api/src/testHelpers/fake-entities/education-program-fake.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1753136296375-AddCredentialTypesAviationColumn.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1753144314059-UpdateIsAviationProgramToNo.ts
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Add-credential-types-aviation-column.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Rollback-add-credential-types-aviation-column.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Rollback-update-is-aviation-program-to-no.sql
- sources/packages/backend/apps/db-migrations/src/sql/EducationPrograms/Update-is-aviation-program-to-no.sql
- sources/packages/backend/libs/sims-db/src/entities/education-program.model.ts
- sources/packages/backend/libs/test-utils/src/factories/education-program.ts
- sources/packages/forms/src/form-definitions/educationprogram.json
- sources/packages/web/src/services/http/dto/EducationProgram.dto.ts
- Added migrations for the following:
1. Added the new `Credential Types Aviation` column
2. Updated the `isAviationProgram` to `no` where `null` for existing records
- Updated the `api` and `web` code logic to save, update and retrieve the values in edit and read-only mode from this newly created column `Credential Types Aviation` to be displayed to the UI
**Read-only mode institutions program:**
--------------------------------------------------------------------------------------------------------------------------------------------
**Migrations Rollback:**
--------------------------------------------------------------------------------------------------------------------------------------------
> #4571 - Aviation Change Program Questions - Part 2

- sources/packages/backend/libs/sims-db/src/entities/education-program.model.ts
- sources/packages/forms/src/form-definitions/educationprogram.json
- sources/packages/web/src/types/contracts/EducationProgram.ts
**As a part of this PR, the following bug was fixed:**
- Removed the "None of the above" option for the aviation credential types question
> #4571 - Aviation Change: Program Questions (Bug Fix)

- .github/workflows/clamav.yml
- .github/workflows/crunchy-db.yml
- .github/workflows/env-setup-build-forms-server.yml
- .github/workflows/env-setup-deploy-forms-server.yml
- .github/workflows/env-setup-deploy-mongo.yml
- .github/workflows/env-setup-deploy-secrets.yml
- .github/workflows/env-setup-redis-cluster-recovery.yml
- .github/workflows/env-setup-sysdig-teams.yml
- .github/workflows/prune-images.yml
- .github/workflows/redis-cluster.yml
- .github/workflows/release-build-all.yml
- .github/workflows/release-create-branch.yml
- .github/workflows/release-deploy-all.yml
- .github/workflows/release-deploy-camunda-definitions.yml
- .github/workflows/release-deploy-db-migrations-repl.yml
- .github/workflows/release-deploy-formio-definitions.yml
- .github/workflows/repo-checks-tests.yml
- Explicitly added the `read` permission for almost all workflows.
- Workflows invoking another workflow require the `actions: read` permission.
- Repo tests required additional permissions.
> #4665 - Workflow Permissions

- sources/packages/web/src/constants/system-constants.ts
- sources/packages/web/src/types/ApplicationToken.ts
- sources/packages/web/src/views/student/StudentProfileCreate.vue
Update keycloak to accept new fields from BCSC logins (BCSC in DEV/TEST are currently configured to send these fields)
Dev Done ✅
**Pending**:
Test/Staging
Prod
> #4471 - BCSC - Enable using the address from BCSC in SIMS profile

- sources/packages/backend/apps/api/src/services/student-file/student-file.service.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1754086479996-AddStudentFileHash.ts
- sources/packages/backend/apps/db-migrations/src/sql/StudentFiles/Add-file-hash-column.sql
- sources/packages/backend/apps/db-migrations/src/sql/StudentFiles/Rollback-add-file-hash-column.sql
- sources/packages/backend/libs/integrations/src/object-storage/object-storage.service.ts
- sources/packages/backend/libs/sims-db/src/entities/student-file.model.ts
- sources/packages/backend/libs/test-utils/src/factories/student-file-uploads.ts
Saving the file hash for student-uploaded files to allow future comparison of exception files.
> #4941 - Approved exception does not repeat - Save File Hash

- sources/packages/web/src/components/common/StudentApplication.vue
- sources/packages/web/src/components/generic/formio.vue
- sources/packages/web/src/constants/system-constants.ts
But by doing this way, there is a visual re-rendering which is now hidden by forcefully using a timeout.
> #4731 -  Formio-loader bug fix

- sources/packages/backend/apps/db-migrations/src/sql/ApplicationExceptionRequests/Add-hash-and-other-columns.sql
- sources/packages/backend/apps/db-migrations/src/sql/ApplicationExceptionRequests/Rollback-add-hash-and-other-columns.sql
- sources/packages/backend/libs/sims-db/src/entities/application-exception-requests.model.ts
- Adjusting the previously DB migration to remove the `exception_index` column.
- Removed the already existing unique constraint that prevents an exception name from being repeated, which must happen now that multiple exceptions with the same name will be saved for dependents and parents.
- Removed the recently added constraint, as discussed with @dheepak-aot, there is not a great benefit and it may cause an issue depending on how the descriptions are defined.
> #4941 - Approved exception does not repeat - DB Migrations Fixes

- sources/packages/backend/workflow/src/workflow-definitions/fulltime-assessment-2025-2026.bpmn
- sources/packages/backend/workflow/test/2025-2026/fulltime-assessment/contribution/fulltime-assessment-spouse-contribution.e2e-spec.ts
- sources/packages/backend/workflow/test/2025-2026/fulltime-assessment/contribution/fulltime-assessment-student-contribution.e2e-spec.ts
- sources/packages/backend/workflow/test/models/assessment.model.ts
- Max contribution weeks for federal student contribution made into it's own variable
- Provincial and Federal Assessed Need have a minimum of 0 (to prevent them from being negative).
- BCSL Remaining 2 fixed to "Net" top up
- Eligible dependants for CSG-FTDEP (CSGD) are <12 years old or 12+ on disability (childcare dependants). Updated eligibility and calculation dependant count to reflect this group.
- Single Independant | $40k/16 week | No targeted resources
- Single Independant | $40k/16 week | $1000 targeted
- Single Independant | $40k/50 week | No targeted resources
- Single Independant | $20k/16 week | No targeted resources
- Single Independant | Exempt (Indigenous)
- Single Independant | Exempt (PD/PPD)
- Single Independant | Exempt (Former Youth In Care)
- Single Independant | …
> #5023 - FT Assessment Updates: CSG-FTDEP eligibility, negative need, BCSL

- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/education-program-offering/models/education-program-offering.dto.ts
- sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts
- sources/packages/web/src/services/http/dto/EducationProgramOffering.dto.ts
- sources/packages/web/src/types/contracts/DataTableContract.ts
- sources/packages/web/src/views/aest/institution/OfferingChangeRequests.vue
The PR adds a Program Name column to the Pending offering change requests queue, populating it from the database for new forms.
- It renames the "Study Period name" column to "Offering Name" and capitalizes the "Date Submitted" field.
- Sorting functionality is enabled for Institution Name, Location Name, Program Name, and Offering Name.
**Demo**
> #4562 - Ministry: show Program Name in Offering Change Request

- sources/packages/backend/libs/utilities/src/_tests_/unit/string-utils.translateToASCII.spec.ts
- sources/packages/backend/libs/utilities/src/string-utils.ts
As a part of this PR, the following was added:
- Adapted the method `convertToASCII` to allow only printable characters from 0 to 127 (excluding newline and carriage return characters).
- Added a unit test to test it.
> #4886 - Convert to ASCII

- sources/packages/backend/libs/integrations/src/cas/_tests_/unit/cas.service.getSupplierInfoFromCAS.spec.ts
- sources/packages/backend/libs/integrations/src/cas/cas.service.ts
**As a part of this PR, the URL in the `getSupplierInfoFromCAS` is encoded to ensure a valid URL is formed for the CAS api call.**
> #4886 - Converting to ASCII [Encode URL]

- sources/packages/web/src/components/aest/students/bypassedRestrictions/HistoryBypassedRestrictions.vue
**Bug Fix**
- Moved `WatchEffect` code block to end.
- but the reason is, reloadBypassedRestrictionsHistory  is not accessible from watch effect as it is defined after watch effect.
- When Ministry User adds bypass, Ministry user can go back and see the history of Bypass at any time.
**Error**
**Demo**
> #5049 - BUG: History of Bypassed restrictions

- sources/packages/forms/src/form-definitions/sfaa2025-26-ft.json
- Fixes bug where uploader is not displayed for parent residency exception question on FT25/26 form
- Uploader is displayed when list of situations for parent residency exception is shown.
> #5111 - Fixes display of uploader 

- sources/packages/backend/apps/api/src/app.external.module.ts
- sources/packages/backend/apps/api/src/auth/auth.module.ts
- sources/packages/backend/apps/api/src/services/student/student.service.ts
- sources/packages/backend/libs/services/src/restriction/model/restriction.model.ts
- sources/packages/backend/libs/services/src/restriction/student-restriction-shared.service.ts
Implements automatic addition of HOLD restrictions when partial matches are detected during student account creation. This ensures that students with potential data conflicts are prevented from completing applications until the matches are resolved manually.
- 2 partial data (Last name, DOB)
1. Restriction Added.
2.Notes Added
> #5059 - When a partial match exists add hold restriction

- sources/packages/backend/libs/services/src/disbursement-schedule/disbursement-schedule-shared.service.ts
During the process of creating disbursement schedules(which happens in workers), besides saving the value amount for each award, we subtract the award value which was already sent for that particular award for the same application to eventually derive the effective amount. 
In a particular scenario where, an application has 2 disbursements where one of the disbursement is Sent and other disbursement is pending with 2nd disbursement amount different than first disbursement for the same award, and then the application gets re-assessed, then the issue that **_this particular award gets amount subtracted with value which was never sent_**.
Assessment 1 - Original Assessment
| Disbursement Schedule No | Disbursement status | Award Code | Award Value | Amount Subtracted | …
> #5124 - Student debit subtraction bug

- sources/packages/backend/apps/api/src/app.aest.module.ts
- sources/packages/backend/apps/api/src/auth/roles.enum.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.aest.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.institutions.controller.getAssessmentNOA.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.getAssessmentAwardDetails.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/_tests_/e2e/assessment.students.controller.getAssessmentNOA.e2e-spec.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts
- sources/packages/backend/apps/api/src/route-controllers/assessment/models/assessment.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/disbursement-schedule/disbursement-schedule.aest.controller.ts
- sources/packages/backend/apps/api/src/route-controllers/disbursement-schedule/models/disbursement-schedule.dto.ts
- sources/packages/backend/apps/api/src/route-controllers/index.ts
- sources/packages/backend/apps/api/src/services/disbursement-schedule/disbursement-schedule-service.ts
- sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts
- sources/packages/backend/libs/test-utils/src/factories/disbursement-schedule.ts
- sources/packages/web/src/components/common/AssessmentAwardDetails.vue
- sources/packages/web/src/components/common/CancelDisbursementSchedule.vue
- sources/packages/web/src/components/common/ConfirmEnrolment.vue
- sources/packages/web/src/components/common/StatusInfoDisbursementCancellation.vue
- sources/packages/web/src/components/common/modals/UserNoteConfirmModal.vue
- sources/packages/web/src/components/common/students/applicationDetails/AssessmentAward.vue
- sources/packages/web/src/composables/useModalDialog.ts
- sources/packages/web/src/services/DisbursementScheduleService.ts
- sources/packages/web/src/services/http/ApiClient.ts
- sources/packages/web/src/services/http/DisbursementScheduleApi.ts
- sources/packages/web/src/services/http/dto/Assessment.dto.ts
- sources/packages/web/src/services/http/dto/DisbursementSchedule.dto.ts
- sources/packages/web/src/services/http/dto/index.ts
- sources/packages/web/src/types/contracts/aest/roles.ts
- sources/packages/web/src/views/aest/student/applicationDetails/AssessmentAward.vue
- Created new role `student-cancel-disbursement-schedule`.
- Created new API endpoint for disbursement schedules (placeholder for upcoming PR).
- Included in the assessment summary API payload the below new values:
-  `disbursementReceipt[n]Received`: indicates if a receipt was received. _Note:_ full-time final awards are retrieved when a receipt is received, and part-time are displayed upon e-Cert creation. This new variable indicates when a receipt was received, not when a final award was returned.
- `disbursementReceipt[n]HasAwards`: added to indicate when an award is present in the payload. Previously, only awards were present in this payload, and they were dynamically created. Adding the boolean makes it easier to identify when awards are present, avoiding inspecting the object …
> #4378 - Ecert Cancellation - UI & Ministry Access (2/2)

- sources/packages/web/src/composables/useFormioUtils.ts
- sources/packages/web/src/types/formio/formio.ts
- sources/packages/web/src/views/aest/StudentApplicationView.vue
Prevent highlighting on a container with no visible elements.
> #5160 - BUG: 2.15: PT Exceptions NR: Container inconsistent red edit section highlighting

- sources/packages/backend/apps/api/src/route-controllers/restriction/_tests_/e2e/restriction.aest.controller.deleteStudentProvincialRestriction.e2e-spec.ts
- sources/packages/backend/apps/api/src/services/application-restriction-bypass/application-restriction-bypass.service.ts
- sources/packages/backend/libs/test-utils/src/factories/student-restriction.ts
- Should delete a provincial student restriction and resolve active bypasses when the deleted restriction is associated with some active bypasses.
- Should throw a NotFoundException when trying to delete a provincial restriction, but it is a federal restriction.
- Should throw an UnprocessableEntityException when trying to delete a provincial restriction that is already deleted.
- Should throw a BadRequestException when an invalid payload is received.
> #4873 - Ministry: ability to delete restrictions - E2E Tests

- .github/dependabot.yml
- sources/packages/web/package-lock.json
- sources/packages/web/package.json
- Fixed banners that were not displayed correctly after the `@fortawesome/fontawesome-free` upgrade.
- Grouped form. io-related packages for dependabot PRs.
- Added monitoring of upgrades for Docker versions.
- Added a "commit-message" that should be the prefix for the PR titles, trying to make it clear where they are. We can remove it later if it does not achieve the goal.
> #4964 - Upgrade Packages - Layout fix and dependabot updates

- sources/packages/backend/apps/db-migrations/src/migrations/1759531941797-CreateApplicationExceptionRequestStatus.ts
- sources/packages/backend/apps/db-migrations/src/migrations/1759532829028-ApplicationExceptionRequestsAddStatusCol.ts
- sources/packages/backend/apps/db-migrations/src/sql/ApplicationExceptionRequests/Add-col-exception-request-status.sql
- sources/packages/backend/apps/db-migrations/src/sql/ApplicationExceptionRequests/Rollback-add-col-exception-request-status.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Create-application-exception-request-status.sql
- sources/packages/backend/apps/db-migrations/src/sql/Types/Rollback-create-application-exception-request-status.sql
- sources/packages/backend/apps/workers/src/controllers/application/_tests_/e2e/application.controller-verifyUniqueApplicationExceptions.e2e-spec.ts
- sources/packages/backend/apps/workers/src/services/application-exception/application-exception.service.ts
- sources/packages/backend/libs/sims-db/src/entities/application-exception-request-status.type.ts
- sources/packages/backend/libs/sims-db/src/entities/application-exception-requests.model.ts
- sources/packages/backend/libs/sims-db/src/entities/index.ts
- sources/packages/backend/libs/test-utils/src/factories/application-exception-request.ts
> #5166 - Individual exception approval - DB migration and worker updates
